Repository 18F/identity-idp, pull requests merged in 2018-04, with the labels that each got.

#2074 Upgrade Ruby from 2.3.5 to 2.3.7
  .circleci/config.yml
  Gemfile
  Gemfile.lock
Labels: area - security, status - ready for review

#2075 Update gems with bummr
  Gemfile.lock
Labels: status - ready for review

#2077 Make Ahoy visit duration match session timeout
  config/initializers/ahoy.rb
Labels: status - ready for review

#2081 Pin Rubocop version and sync local and code climate lint configuration
  .reek
  .rubocop.yml
  Gemfile
  Gemfile.lock
  config/initializers/devise.rb
Labels: status - ready for review

#2083 LG-166 Use proper rotation path suffix in SAML metadata
  app/controllers/saml_idp_controller.rb
  spec/features/saml/saml_spec.rb
Labels: status - ready for review

#2089 Remove vendor session id from idv session and proofing flow
  app/jobs/idv/phone_job.rb
  app/jobs/idv/profile_job.rb
  app/jobs/idv/proofer_job.rb
  app/services/idv/profile_step.rb
  app/services/idv/session.rb
  app/services/idv/submit_idv_job.rb
  app/services/idv/vendor_result.rb
  spec/jobs/idv/phone_job_spec.rb
  spec/jobs/idv/profile_job_spec.rb
  spec/services/idv/submit_idv_job_spec.rb
  spec/services/idv/vendor_result_spec.rb
  spec/services/vendor_validator_result_storage_spec.rb
Labels: status - work in progress

#2086 Add the uuid for a x509 subject to the users table
  app/models/user.rb
  db/migrate/20180409193120_add_x509_dn_uuid_to_users_table.rb
  db/schema.rb
  spec/factories/users.rb
  spec/models/user_spec.rb
Labels: status - ready for review

#2054 Break trailing comma cop into hash and array cop
  .codeclimate.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/services/encrypted_attribute.rb
Labels: status - ready for review

#2076 LG-163 Turn on agency based UUIDs
  config/application.yml.example
Labels: status - ready for review

#2091 LG-170 Log user out when deleting account
  app/controllers/users/delete_controller.rb
Labels: status - ready for review

#2090 Break account creation spec into 2 specs
  spec/features/idv/account_creation_spec.rb
  spec/features/idv/sp_handoff_spec.rb
  spec/features/idv/sp_requested_attributes_spec.rb
  spec/support/idv_examples/account_creation.rb
  spec/support/idv_examples/sp_handoff.rb
  spec/support/idv_examples/sp_requested_attributes.rb
Labels: status - ready for review

#2095 Break phone input tests into their own spec
  spec/features/idv/phone_input_spec.rb
  spec/features/idv/phone_spec.rb
  spec/support/features/idv_step_helper.rb
Labels: status - ready for review

#2094 Use shared examples to test cancelation behavior
  spec/features/idv/cancel_idv_step_spec.rb
  spec/features/idv/flow_spec.rb
  spec/features/idv/phone_input_spec.rb
  spec/support/features/idv_helper.rb
  spec/support/features/idv_step_helper.rb
  spec/support/features/javascript_driver_helper.rb
  spec/support/idv_examples/cancel_at_idv_step.rb
Labels: status - ready for review

#2061 LG-141 Allow use of auth app without phone
  app/controllers/users/totp_setup_controller.rb
  app/models/user.rb
  app/services/analytics.rb
  app/views/users/shared/_otp_delivery_preference_selection.html.slim
  config/locales/links/en.yml
  config/locales/links/es.yml
  config/locales/links/fr.yml
  spec/controllers/users/totp_setup_controller_spec.rb
  spec/features/users/sign_up_spec.rb
  spec/support/features/session_helper.rb
  spec/support/shared_examples/account_creation.rb
Labels: status - ready for review

#2097 Test failed and timed out jobs in shared examples
  spec/features/idv/failed_job_spec.rb
  spec/rails_helper.rb
  spec/support/features/step_tags_helper.rb
  spec/support/idv_examples/failed_idv_job.rb
  spec/support/idv_examples/max_attempts.rb
Labels: status - ready for review

#2098 Davemcorwin dev server config
  Makefile
  Procfile_dev
Labels: status - ready for review

#2103 Create a phone step spec
  spec/features/idv/cancel_idv_step_spec.rb
  spec/features/idv/failed_job_spec.rb
  spec/features/idv/max_attempts_spec.rb
  spec/features/idv/steps/phone_step_spec.rb
  spec/support/idv_examples/fail_to_verify.rb
  spec/support/idv_examples/failed_idv_job.rb
Labels: status - ready for review

#2104 Add address and OTP delivery method step specs
  spec/features/idv/cancel_idv_step_spec.rb
  spec/features/idv/phone_spec.rb
  spec/features/idv/steps/address_step_spec.rb
  spec/features/idv/steps/phone_otp_delivery_selection_step_spec.rb
  spec/support/idv_examples/fail_to_verify.rb
Labels: status - ready for review

#2101 Use shared examples to test failure to verify
  spec/features/idv/fail_to_verify_spec.rb
  spec/features/idv/flow_spec.rb
  spec/features/idv/phone_spec.rb
Labels: status - ready for review

#2108 Replace Poltergeist/PhantomJS with Headless Chrome
  .circleci/config.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  config/database.yml
  knapsack_rspec_report.json
  spec/features/accessibility/idv_pages_spec.rb
  spec/features/idv/flow_spec.rb
  spec/features/idv/interrupted_session_spec.rb
  spec/features/saml/loa1_sso_spec.rb
  spec/features/two_factor_authentication/sign_in_spec.rb
  spec/features/users/regenerate_personal_key_spec.rb
  spec/features/users/sign_in_spec.rb
  spec/features/users/user_edit_spec.rb
  spec/features/users/user_profile_spec.rb
  spec/features/visitors/i18n_spec.rb
  spec/features/visitors/set_password_spec.rb
  spec/support/capybara.rb
  spec/support/features/idv_helper.rb
  spec/support/idv_examples/cancel_at_idv_step.rb
Labels: status - ready for review

#2100 Update webpacker from 3.2.2 to 3.4.3
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  bin/webpack
  bin/webpack-dev-server
  package.json
  spec/features/idv/flow_spec.rb
  yarn.lock
Labels: status - ready for review

#2107 Add tests for USPS idv steps
  spec/features/idv/steps/usps_otp_verification_step_spec.rb
  spec/features/idv/steps/usps_step_spec.rb
  spec/features/idv/usps_verification_spec.rb
  spec/support/features/idv_step_helper.rb
  spec/support/idv_examples/usps_otp_verification_step.rb
  spec/support/idv_examples/usps_verification_selection.rb
Labels: status - ready for review

#2111 Upgrade Ahoy from 1.6.1 to 2.0.2
  .reek
  Gemfile
  Gemfile.lock
  config/initializers/ahoy.rb
Labels: status - ready for review

#2112 Add phone otp verification step spec
  spec/features/idv/cancel_idv_step_spec.rb
  spec/features/idv/steps/phone_otp_verification_step_spec.rb
Labels: status - ready for review

#2114 LG-208 Create user Event when password is changed
  app/controllers/users/passwords_controller.rb
  spec/controllers/users/passwords_controller_spec.rb
Labels: status - ready for review

#2102 Create a profile and verify step spec
  spec/features/idv/cancel_idv_step_spec.rb
  spec/features/idv/fail_to_verify_spec.rb
  spec/features/idv/failed_job_spec.rb
  spec/features/idv/max_attempts_spec.rb
  spec/features/idv/steps/profile_step_spec.rb
  spec/features/idv/steps/verify_step_spec.rb
Labels: status - ready for review

#2115 Update gems with bummr
  Gemfile.lock
  spec/controllers/users/two_factor_authentication_controller_spec.rb
  spec/features/users/sign_up_spec.rb
  spec/services/twilio_service_spec.rb
  spec/support/fake_twilio_error_response.rb
Labels: status - ready for review

#2113 Remove duplicate or obselete idv specs
  spec/features/idv/account_creation_spec.rb
  spec/features/idv/flow_spec.rb
  spec/features/idv/phone_spec.rb
  spec/features/idv/previous_address_spec.rb
  spec/features/idv/state_id_data_spec.rb
  spec/features/idv/steps/phone_step_spec.rb
  spec/support/idv_examples/otp_delivery_method.rb
  spec/support/idv_examples/usps_verification_selection.rb
Labels: status - ready for review

#2116 Decouple Proofer gem from IdP
  .reek
  app/controllers/verify/phone_controller.rb
  app/controllers/verify/sessions_controller.rb
  app/jobs/idv/phone_job.rb
  app/jobs/idv/profile_job.rb
  app/jobs/idv/proofer_job.rb
  app/services/idv/agent.rb
  app/services/idv/profile_maker.rb
  app/services/idv/session.rb
  app/services/idv/submit_idv_job.rb
  app/services/idv/vendor_result.rb
  spec/controllers/verify/confirmations_controller_spec.rb
  spec/controllers/verify/phone_controller_spec.rb
  spec/controllers/verify/sessions_controller_spec.rb
  spec/features/idv/state_id_data_spec.rb
  spec/jobs/idv/phone_job_spec.rb
  spec/jobs/idv/profile_job_spec.rb
  spec/jobs/idv/proofer_job_spec.rb
  spec/rails_helper.rb
  spec/services/idv/agent_spec.rb
  spec/services/idv/phone_step_spec.rb
  spec/services/idv/profile_maker_spec.rb
  spec/services/idv/profile_step_spec.rb
  spec/services/idv/submit_idv_job_spec.rb
  spec/services/idv/vendor_result_spec.rb
  spec/services/vendor_validator_result_storage_spec.rb
  spec/support/controller_helper.rb
  spec/support/idv/proofer_job_helper.rb
  spec/support/idv_examples/failed_idv_job.rb
Labels: status - ready for review

#2123 Remove temporary mailer
  app/mailers/user_mailer.rb
  app/views/user_mailer/reset_password.html.slim
Labels: status - ready for review
