Repository 18F/identity-idp, pull requests merged in 2018-09, with the labels that each got.

#2450 Refactor AccountReset::DeleteAccountController
  app/controllers/account_reset/delete_account_controller.rb
  app/models/account_reset_request.rb
  app/models/anonymous_user.rb
  app/services/account_reset/delete_account.rb
  app/services/account_reset/validate_granted_token.rb
  app/validators/account_reset/granted_token_validator.rb
  app/views/account_reset/confirm_delete_account/show.html.slim
  app/views/account_reset/delete_account/show.html.slim
  config/locales/devise/en.yml
  config/locales/devise/es.yml
  config/locales/devise/fr.yml
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
  spec/controllers/account_reset/delete_account_controller_spec.rb
  spec/features/account_reset/delete_account_spec.rb
  spec/models/account_reset_request_spec.rb
  spec/views/account_reset/confirm_delete_account/show.html.slim_spec.rb
Labels: status - ready for review

#2479 Allow full exception logs for users without phone
  app/views/exception_notifier/_session.text.erb
Labels: status - ready for review

#2481 Remove unused personal_key method
  app/models/concerns/user_access_key_overrides.rb
  spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb
  spec/features/two_factor_authentication/sign_in_via_personal_key_spec.rb
  spec/forms/personal_key_form_spec.rb
  spec/models/profile_spec.rb
Labels: status - ready for review

#2374 Drop personal key columns
  db/migrate/20180724154947_drop_personal_key_columns_from_user.rb
  db/schema.rb
Labels: status - do not merge, status - ready for review

#2430 LG-528 Use IdV specific phone otp confirmation
  app/controllers/concerns/idv/phone_otp_rate_limitable.rb
  app/controllers/concerns/idv/phone_otp_sendable.rb
  app/controllers/idv/otp_delivery_method_controller.rb
  app/controllers/idv/otp_verification_controller.rb
  app/controllers/idv/resend_otp_controller.rb
  app/controllers/idv/review_controller.rb
  app/forms/idv/phone_confirmation_otp_verification_form.rb
  app/presenters/idv/otp_verification_presenter.rb
  app/services/analytics.rb
  app/services/idv/generate_phone_confirmation_otp.rb
  app/services/idv/send_phone_confirmation_otp.rb
  app/services/idv/session.rb
  app/views/idv/otp_verification/show.html.slim
  config/routes.rb
  spec/controllers/idv/otp_delivery_method_controller_spec.rb
  spec/controllers/idv/otp_verification_controller_spec.rb
  spec/controllers/idv/resend_otp_controller_spec.rb
  spec/controllers/idv/review_controller_spec.rb
  spec/features/idv/phone_otp_rate_limiting_spec.rb
  spec/features/idv/steps/phone_otp_delivery_selection_step_spec.rb
  spec/features/idv/steps/phone_otp_verification_step_spec.rb
  spec/features/idv/steps/phone_step_spec.rb
  spec/features/idv/usps_disabled_spec.rb
  spec/features/two_factor_authentication/remember_device_spec.rb
  spec/forms/idv/phone_confirmation_otp_verification_form_spec.rb
  spec/services/idv/send_phone_confirmation_otp_spec.rb
Labels: status - ready for review

#2482 LG-640 Add Railroad Retirement Board Branding
  app/decorators/service_provider_session_decorator.rb
Labels: status - ready for review

#2483 Set up a TOTP user for local development
  app/controllers/two_factor_authentication/totp_verification_controller.rb
  app/views/two_factor_authentication/totp_verification/show.html.slim
  lib/tasks/dev.rake
  spec/factories/users.rb
  spec/lib/tasks/dev_rake_spec.rb
Labels: status - ready for review

#2489 Prune IdV branches from MFA otp verification logic
  app/controllers/concerns/phone_confirmation.rb
  app/controllers/concerns/remember_device_concern.rb
  app/controllers/concerns/two_factor_authenticatable.rb
  app/controllers/concerns/user_session_context.rb
  app/controllers/concerns/verify_profile_concern.rb
  app/controllers/idv/sessions_controller.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/controllers/saml_idp_controller.rb
  app/controllers/two_factor_authentication/otp_verification_controller.rb
  app/presenters/two_factor_auth_code/phone_delivery_presenter.rb
  app/services/otp_delivery_preference_updater.rb
  spec/controllers/concerns/user_session_context_spec.rb
  spec/controllers/idv/confirmations_controller_spec.rb
  spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
  spec/features/idv/steps/usps_step_spec.rb
  spec/presenters/two_factor_auth_code/phone_delivery_presenter_spec.rb
  spec/services/otp_delivery_preference_updater_spec.rb
  spec/views/two_factor_authentication/otp_verification/show.html.slim_spec.rb
Labels: status - ready for review

#2490 LG-601 Allow a user to add a new webauthn configuration
  .reek
  Gemfile
  Gemfile.lock
  app/controllers/users/webauthn_setup_controller.rb
  app/forms/webauthn_setup_form.rb
  app/javascript/packs/webauthn-setup.js
  app/services/analytics.rb
  app/services/marketing_site.rb
  app/view_models/account_show.rb
  app/views/accounts/actions/_add_webauthn.html.slim
  app/views/accounts/show.html.slim
  app/views/users/webauthn_setup/new.html.slim
  config/application.yml.example
  config/locales/account/en.yml
  config/locales/account/es.yml
  config/locales/account/fr.yml
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
  config/locales/headings/en.yml
  config/locales/headings/es.yml
  config/locales/headings/fr.yml
  config/locales/links/en.yml
  config/locales/links/es.yml
  config/locales/links/fr.yml
  config/locales/notices/en.yml
  config/locales/notices/es.yml
  config/locales/notices/fr.yml
  config/routes.rb
  lib/feature_management.rb
  spec/controllers/users/webauthn_setup_controller_spec.rb
  spec/features/users/webauthn_management_spec.rb
  spec/forms/webauthn_setup_form_spec.rb
  spec/lib/feature_management_spec.rb
  spec/support/features/webauthn_helper.rb
Labels: status - ready for review

#2488 LG-644 Ensure rack-timeout is properly configured
  config/application.rb
  config/application.yml.example
  config/initializers/figaro.rb
Labels: status - ready for review

#2487 LG-646 Add CBP I-94 SP
  config/agencies.yml
  config/service_providers.yml
  spec/services/agency_seeder_spec.rb
  spec/services/link_agency_identities_spec.rb
Labels: status - ready for review

#2478 [LG-501] Only write to phone configuration table
  app/controllers/users/two_factor_authentication_controller.rb
  app/models/concerns/user_encrypted_attribute_overrides.rb
  app/models/user.rb
  app/services/pii/cacher.rb
  app/services/populate_phone_configurations_table.rb
  app/services/update_user.rb
  lib/tasks/create_test_accounts.rb
  lib/tasks/dev.rake
  lib/tasks/migrate_phone_configurations.rake
  spec/controllers/account_recovery_setup_controller_spec.rb
  spec/controllers/idv/phone_controller_spec.rb
  spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
  spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb
  spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb
  spec/controllers/users/phones_controller_spec.rb
  spec/controllers/users/piv_cac_authentication_setup_controller_spec.rb
  spec/controllers/users/totp_setup_controller_spec.rb
  spec/controllers/users/two_factor_authentication_controller_spec.rb
  spec/factories/phone_configurations.rb
  spec/factories/users.rb
  spec/features/accessibility/user_pages_spec.rb
  spec/features/sign_in/two_factor_options_spec.rb
  spec/features/two_factor_authentication/change_factor_spec.rb
  spec/features/two_factor_authentication/sign_in_spec.rb
  spec/features/users/piv_cac_management_spec.rb
  spec/features/users/sign_in_spec.rb
  spec/features/visitors/phone_confirmation_spec.rb
  spec/forms/idv/phone_form_spec.rb
  spec/forms/user_phone_form_spec.rb
  spec/lib/tasks/rotate_rake_spec.rb
  spec/models/phone_configuration_spec.rb
  spec/models/user_spec.rb
  spec/requests/edit_user_spec.rb
  spec/requests/openid_connect_authorize_spec.rb
  spec/services/account_reset/cancel_spec.rb
  spec/services/key_rotator/attribute_encryption_spec.rb
  spec/services/pii/cacher_spec.rb
  spec/services/populate_phone_configurations_table_spec.rb
  spec/services/remember_device_cookie_spec.rb
  spec/services/update_user_spec.rb
  spec/support/features/session_helper.rb
  spec/support/shared_examples/sign_in.rb
  spec/support/shared_examples_for_phone_validation.rb
Labels: status - ready for review

#2495 LG-652 Add HUD to the service providers in production
  app/assets/images/sp-logos/hud.png
  certs/sp/hud_prod.crt
  config/agencies.yml
  config/service_providers.yml
Labels: status - ready for review

#2453 LG-572 Visual design tweaks on /verify/session
  app/views/idv/sessions/new.html.slim
  config/locales/links/en.yml
  config/locales/links/es.yml
  config/locales/links/fr.yml
Labels: status - ready for review

#2491 LG-643 Add timeout to Twilio API calls
  app/errors/twilio_errors.rb
  app/services/twilio_service.rb
  config/application.yml.example
  config/initializers/figaro.rb
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
  spec/services/twilio_service_spec.rb
  spec/support/fake_sms.rb
  spec/support/fake_voice_call.rb
Labels: status - ready for review

#2493 Update gems with bummr
  .reek
  Gemfile.lock
  app/controllers/users/sessions_controller.rb
  app/views/devise/mailer/confirmation_instructions.html.slim
  app/views/devise/mailer/reset_password_instructions.html.slim
  app/views/user_mailer/account_reset_granted.html.slim
  app/views/user_mailer/signup_with_your_email.html.slim
  spec/factories/authorizations.rb
  spec/factories/events.rb
  spec/factories/identities.rb
  spec/factories/otp_presenter.rb
  spec/factories/profiles.rb
  spec/factories/service_providers.rb
  spec/factories/users.rb
  spec/factories/usps_confirmation_codes.rb
Labels: status - ready for review

#2497 Revert changes to `find_with_email `
  app/controllers/users/sessions_controller.rb
  app/models/concerns/user_encrypted_attribute_overrides.rb
Labels: status - ready for review

#2499 Update Reek from 4.8.1 to 5.0.2
  .reek.yml
  Gemfile.lock
Labels: status - ready for review

#2494 LG-598 LG-600 List/delete webauthn configurations for a user
  app/assets/stylesheets/components/_btn.scss
  app/controllers/users/webauthn_setup_controller.rb
  app/models/user.rb
  app/models/webauthn_configuration.rb
  app/services/analytics.rb
  app/view_models/account_show.rb
  app/views/accounts/_webauthn.html.slim
  app/views/accounts/actions/_add_webauthn.html.slim
  app/views/accounts/show.html.slim
  app/views/users/webauthn_setup/new.html.slim
  config/locales/account/en.yml
  config/locales/account/es.yml
  config/locales/account/fr.yml
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
  config/locales/notices/en.yml
  config/locales/notices/es.yml
  config/locales/notices/fr.yml
  config/routes.rb
  spec/controllers/users/webauthn_setup_controller_spec.rb
  spec/features/users/webauthn_management_spec.rb
Labels: status - ready for review

#2498 Revert removal of #2351 (redirect uri validation)
  .reek
  app/controllers/concerns/secure_headers_concern.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/decorators/service_provider_session_decorator.rb
  app/forms/openid_connect_authorize_form.rb
  app/forms/openid_connect_logout_form.rb
  app/services/openid_connect_redirector.rb
  app/validators/redirect_uri_validator.rb
  config/service_providers.yml
  spec/controllers/openid_connect/logout_controller_spec.rb
  spec/features/openid_connect/openid_connect_spec.rb
  spec/features/openid_connect/redirect_uri_validation_spec.rb
  spec/features/saml/redirect_uri_validation_spec.rb
  spec/forms/openid_connect_authorize_form_spec.rb
  spec/forms/openid_connect_logout_form_spec.rb
  spec/services/openid_connect_redirector_spec.rb
Labels: status - ready for review

#2485 LG-610 Don't show recovery code before IdV flow
  .reek
  app/controllers/concerns/two_factor_authenticatable.rb
  app/controllers/users/totp_setup_controller.rb
  app/decorators/user_decorator.rb
  app/policies/personal_key_for_new_user_policy.rb
  spec/decorators/user_decorator_spec.rb
  spec/features/idv/account_creation_spec.rb
  spec/policies/personal_key_for_new_user_policy_spec.rb
  spec/support/features/session_helper.rb
  spec/support/shared_examples/account_creation.rb
Labels: status - ready for review

#2500 Add Guardfile for faster local testing
  Gemfile.lock
  Guardfile
  README.md
Labels: status - ready for review

#2507 LG-654 Redact entire SSN from /account page
  app/views/accounts/_pii.html.slim
Labels: status - ready for review

#2501 LG-599 LG-603 Allow webauthn at account creation. Allow webauthn for 2FA.
  .reek
  .reek.yml
  .rubocop.yml
  app/controllers/two_factor_authentication/options_controller.rb
  app/controllers/two_factor_authentication/webauthn_verification_controller.rb
  app/controllers/users/two_factor_authentication_controller.rb
  app/controllers/users/two_factor_authentication_setup_controller.rb
  app/controllers/users/webauthn_setup_controller.rb
  app/forms/two_factor_login_options_form.rb
  app/forms/two_factor_options_form.rb
  app/forms/webauthn_verification_form.rb
  app/javascript/packs/webauthn-authenticate.js
  app/models/user.rb
  app/policies/webauthn_login_option_policy.rb
  app/presenters/two_factor_auth_code/webauthn_authentication_presenter.rb
  app/presenters/two_factor_login_options_presenter.rb
  app/presenters/two_factor_options_presenter.rb
  app/views/two_factor_authentication/webauthn_verification/show.html.slim
  config/locales/devise/en.yml
  config/locales/devise/es.yml
  config/locales/devise/fr.yml
  config/locales/instructions/en.yml
  config/locales/instructions/es.yml
  config/locales/instructions/fr.yml
  config/locales/titles/en.yml
  config/locales/titles/es.yml
  config/locales/titles/fr.yml
  config/locales/two_factor_authentication/en.yml
  config/locales/two_factor_authentication/es.yml
  config/locales/two_factor_authentication/fr.yml
  config/routes.rb
  spec/controllers/two_factor_authentication/options_controller_spec.rb
  spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb
  spec/controllers/users/two_factor_authentication_controller_spec.rb
  spec/controllers/users/two_factor_authentication_setup_controller_spec.rb
  spec/controllers/users/webauthn_setup_controller_spec.rb
  spec/forms/webauthn_verification_form_spec.rb
  spec/policies/webauthn_login_option_policy_spec.rb
  spec/presenters/two_factor_auth_code/webauthn_authentication_presenter_spec.rb
  spec/support/features/webauth_verification_helper.rb
Labels: status - ready for review

#2506 LG-609 Change language on phone / address confirmation page
  app/views/idv/phone/new.html.slim
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
Labels: status - ready for review

#2503 [LG-587] Add email address table
  app/models/concerns/email_address_callback.rb
  app/models/email_address.rb
  app/models/user.rb
  config/environments/test.rb
  db/migrate/20180906181420_create_email_address_table.rb
  db/schema.rb
  spec/factories/email_addresses.rb
  spec/models/email_address_spec.rb
  spec/models/user_spec.rb
Labels: status - ready for review

#2512 Update webauthn setup to match master branch
  .reek.yml
  app/controllers/users/webauthn_setup_controller.rb
  config/locales/account/fr.yml
  config/locales/devise/fr.yml
  config/locales/errors/fr.yml
  config/locales/forms/fr.yml
  config/locales/headings/fr.yml
  config/locales/instructions/fr.yml
  config/locales/links/fr.yml
  config/locales/notices/fr.yml
  config/locales/titles/fr.yml
  config/locales/two_factor_authentication/fr.yml
  spec/features/idv/account_creation_spec.rb
  spec/features/users/webauthn_management_spec.rb
  spec/support/features/webauthn_helper.rb
  spec/support/shared_examples/account_creation.rb
Labels: status - ready for review

#2470 LG-625 Cancel flow modification
  app/views/idv/cancellations/destroy.html.slim
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
  config/locales/links/en.yml
  config/locales/links/es.yml
  config/locales/links/fr.yml
  spec/support/idv_examples/cancel_at_idv_step.rb
Labels: status - ready for review

#2516 [LG-588] Rake task populating email addresses
  app/services/populate_email_addresses_table.rb
  lib/tasks/migrate_email_addresses.rake
  spec/services/populate_email_addresses_table_spec.rb
Labels: status - ready for review

#2519 Fix PIV/CAC and Webauthn errors when disabled
  app/controllers/two_factor_authentication/options_controller.rb
  app/presenters/two_factor_options_presenter.rb
  spec/controllers/two_factor_authentication/options_controller_spec.rb
Labels: status - ready for review

#2517 LG-442 Remove unused sidekiq and worker code
  .reek
  .reek.yml
  Gemfile
  Gemfile.lock
  Procfile
  Procfile_dev
  app/controllers/health/health_controller.rb
  app/controllers/health/workers_controller.rb
  app/services/admin_constraint.rb
  app/views/exception_notifier/_data.text.erb
  config/application.yml.example
  config/initializers/exception_notification.rb
  config/initializers/sidekiq.rb
  config/routes.rb
  config/sidekiq.yml
  docker-compose.yml
  lib/encrypted_sidekiq_redis.rb
  lib/no_retry_jobs.rb
  lib/production_database_configuration.rb
  lib/queue_config.rb
  lib/sidekiq_logger_formatter.rb
  lib/worker_health_checker.rb
  spec/controllers/health/health_controller_spec.rb
  spec/controllers/health/workers_controller_spec.rb
  spec/lib/encrypted_sidekiq_redis_spec.rb
  spec/lib/no_retry_jobs_spec.rb
  spec/lib/production_database_configuration_spec.rb
  spec/lib/queue_config_spec.rb
  spec/lib/sidekiq_logging_formatter_spec.rb
  spec/lib/worker_health_checker_spec.rb
  spec/rails_helper.rb
  spec/requests/constrained_route_spec.rb
Labels: status - ready for review

#2511 LG-627 Don't automatically select SMS during IdV
  app/controllers/idv/otp_delivery_method_controller.rb
  app/views/idv/otp_delivery_method/new.html.slim
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
  spec/controllers/idv/otp_delivery_method_controller_spec.rb
  spec/features/idv/steps/phone_otp_delivery_selection_step_spec.rb
  spec/support/features/idv_helper.rb
Labels: status - ready for review

#2518 LG-558 Make jurisdiction step non-re-entrant
  app/controllers/idv/jurisdiction_controller.rb
  app/controllers/idv/sessions_controller.rb
  app/services/idv/session.rb
  spec/controllers/idv/jurisdiction_controller_spec.rb
  spec/features/idv/steps/jurisdiction_step_spec.rb
  spec/support/idv_examples/max_attempts.rb
Labels: status - ready for review

#2527 Add trailing period to a french idv translation
  config/locales/idv/fr.yml
Labels: status - ready for review

#2513 LG-669 Retry once when Twilio request times out
  .codeclimate.yml
  .reek.yml
  app/services/twilio_service.rb
  spec/services/twilio_service_spec.rb
  spec/support/fake_sms.rb
  spec/support/fake_voice_call.rb
Labels: status - ready for review

#2526 LG-650 Report IdV vendor timeouts to the user
  Gemfile
  Gemfile.lock
  app/services/idv/agent.rb
  app/services/idv/phone_step.rb
  app/services/idv/profile_step.rb
  lib/proofer_mocks/address_mock.rb
  lib/proofer_mocks/resolution_mock.rb
  spec/controllers/idv/phone_controller_spec.rb
  spec/controllers/idv/sessions_controller_spec.rb
  spec/services/idv/agent_spec.rb
  spec/services/idv/phone_step_spec.rb
  spec/services/idv/profile_step_spec.rb
  spec/support/idv_examples/failed_idv_job.rb
Labels: status - ready for review

#2532 Update capybara-screenshot to point to rubygems
  Gemfile
  Gemfile.lock
  app/views/account_reset/confirm_delete_account/show.html.slim
  app/views/shared/_personal_key.html.slim
  config/locales/account_reset/en.yml
  config/locales/account_reset/es.yml
  config/locales/account_reset/fr.yml
  config/locales/errors/en.yml
  config/locales/two_factor_authentication/en.yml
  config/locales/two_factor_authentication/es.yml
  config/locales/two_factor_authentication/fr.yml
  config/locales/users/en.yml
  config/locales/users/es.yml
  config/locales/users/fr.yml
  spec/features/users/regenerate_personal_key_spec.rb
  spec/support/shared_examples_for_personal_keys.rb
Labels: status - ready for review

#2531 LG-684 Rescue Faraday::ConnectionFailed errors
  app/services/twilio_service.rb
  spec/services/twilio_service_spec.rb
Labels: status - ready for review

#2533 LG-624 Add HOMES.mil logo and help text in INT
  app/assets/images/sp-logos/homes_mil.png
  app/decorators/service_provider_session_decorator.rb
  config/locales/service_providers/en.yml
  config/locales/service_providers/es.yml
  config/locales/service_providers/fr.yml
Labels: status - ready for review

#2534 LG-651 Allow newrelic_rpm to be updated
  Gemfile.lock
  spec/services/encryption/password_verifier_spec.rb
  spec/services/encryption/user_access_key_spec.rb
Labels: status - ready for review

#2525 LG-677 Add confirm screen on account reset cancel
  app/controllers/account_reset/cancel_controller.rb
  app/services/account_reset/cancel.rb
  app/services/account_reset/validate_cancel_token.rb
  app/validators/account_reset/cancel_token_validator.rb
  app/views/account_reset/cancel/show.html.slim
  config/locales/account_reset/en.yml
  config/locales/account_reset/es.yml
  config/locales/account_reset/fr.yml
  config/routes.rb
  spec/controllers/account_reset/cancel_controller_spec.rb
  spec/features/account_reset/cancel_request_spec.rb
  spec/views/account_reset/cancel/show.html.slim_spec.rb
Labels: status - ready for review

#2538 Get link right for adding a phone
  app/views/accounts/_phone.html.slim
  spec/views/accounts/show.html.slim_spec.rb
Labels: status - ready for review

#2530 LG-637 Set max length of state id number to 25
  app/assets/javascripts/i18n-strings.js.erb
  app/javascript/app/form-validation.js
  app/validators/idv/form_state_id_validator.rb
  app/views/idv/sessions/new.html.slim
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
  spec/features/idv/state_id_data_spec.rb
  spec/forms/idv/profile_form_spec.rb
Labels: status - ready for review

#2537 LG-553 LOA3: Cancel verification doesn't remove pending status
  app/controllers/idv/phone_controller.rb
  app/models/profile.rb
  spec/controllers/idv/phone_controller_spec.rb
Labels: status - ready for review

#2539 Add TTP exact matching logout redirect uri
  config/service_providers.yml
Labels: status - ready for review

#2542 LG-694 Add vermont to list of supported states
  app/validators/idv/form_jurisdiction_validator.rb
Labels: status - ready for review

#2543 LG-666 Refactor AccountResetService
  app/controllers/account_reset/send_notifications_controller.rb
  app/services/account_reset/grant_request.rb
  app/services/account_reset/grant_requests_and_send_emails.rb
  app/services/account_reset_service.rb
  lib/tasks/account_reset.rake
  spec/controllers/account_reset/delete_account_controller_spec.rb
  spec/controllers/account_reset/send_notifications_controller_spec.rb
  spec/features/account_reset/cancel_request_spec.rb
  spec/features/account_reset/delete_account_spec.rb
  spec/services/account_reset/grant_request_spec.rb
  spec/services/account_reset/grant_requests_and_send_emails_spec.rb
  spec/support/account_reset_helper.rb
Labels: status - ready for review

#2535 LG507: Remove PIV/CAC feature flag
  app/controllers/test/piv_cac_authentication_test_subject_controller.rb
  app/models/piv_cac_configuration.rb
  app/policies/two_factor_authentication/piv_cac_policy.rb
  app/services/piv_cac_service.rb
  config/application.yml.example
  config/routes.rb
  lib/feature_management.rb
  spec/controllers/test/piv_cac_authentication_test_subject_controller_spec.rb
  spec/controllers/two_factor_authentication/options_controller_spec.rb
  spec/features/users/piv_cac_management_spec.rb
  spec/features/users/sign_up_spec.rb
  spec/lib/feature_management_spec.rb
  spec/policies/two_factor_authentication/piv_cac_policy_spec.rb
  spec/services/piv_cac_service_spec.rb
  spec/support/features/session_helper.rb
Labels: status - ready for review

#2545 Pad list items in account management screen
  app/assets/stylesheets/components/_list.scss
  app/views/accounts/_phone.html.slim
  app/views/accounts/_webauthn.html.slim
Labels: status - ready for review

#2544 LG-695 Enable Webauthn when there is no SP
  app/controllers/accounts_controller.rb
  app/controllers/two_factor_authentication/webauthn_verification_controller.rb
  app/controllers/users/two_factor_authentication_controller.rb
  app/policies/two_factor_authentication/webauthn_policy.rb
  app/presenters/two_factor_options_presenter.rb
  app/view_models/account_show.rb
  app/views/accounts/show.html.slim
  config/locales/errors/en.yml
  spec/policies/webauthn_login_option_policy_spec.rb
  spec/support/shared_examples/account_creation.rb
Labels: status - ready for review

#2546 Add support for proofing SC, MO, and RI
  app/validators/idv/form_jurisdiction_validator.rb
  lib/proofer_mocks/state_id_mock.rb
Labels: status - ready for review, status - required for release

#2540 LG-543 Retry failed Twilio Verify requests
  .codeclimate.yml
  app/errors/twilio_errors.rb
  app/services/phone_verification.rb
  spec/services/phone_verification_spec.rb
  spec/support/fake_adapter.rb
Labels: status - ready for review, status - required for release

#2529 LG-615 Update personal key page design and language
  app/assets/images/personal-key/lock-check.svg
  app/assets/images/personal-key/pkey-block.svg
  app/assets/images/personal-key/shield.svg
  app/assets/images/personal-key/warning.svg
  app/assets/stylesheets/components/_personal-key.scss
  app/controllers/users/personal_keys_controller.rb
  app/views/partials/personal_key/_key.slim
  app/views/shared/_personal_key.html.slim
  config/locales/headings/en.yml
  config/locales/headings/es.yml
  config/locales/headings/fr.yml
  config/locales/instructions/en.yml
  config/locales/instructions/es.yml
  config/locales/instructions/fr.yml
  config/locales/notices/en.yml
  config/locales/notices/es.yml
  config/locales/notices/fr.yml
  config/locales/users/en.yml
  config/locales/users/es.yml
  config/locales/users/fr.yml
  spec/controllers/users/personal_keys_controller_spec.rb
  spec/features/saml/loa1_sso_spec.rb
  spec/features/users/regenerate_personal_key_spec.rb
  spec/support/shared_examples/account_creation.rb
  spec/support/shared_examples_for_personal_keys.rb
  spec/views/sign_up/personal_keys/show.html.slim_spec.rb
Labels: status - ready for review, status - required for release

#2547 Enable webauthn in prod
  config/application.yml.example
Labels: status - ready for review, status - required for release

#2556 LG-670 Handle SES timeouts gracefully
  app/controllers/users/reset_passwords_controller.rb
  app/forms/password_reset_email_form.rb
  app/forms/reset_password_form.rb
  app/forms/update_user_password_form.rb
  app/models/nonexistent_user.rb
  app/services/analytics.rb
  app/services/email_notifier.rb
  lib/aws/ses.rb
  spec/controllers/users/reset_passwords_controller_spec.rb
  spec/forms/password_reset_email_form_spec.rb
  spec/forms/reset_password_form_spec.rb
  spec/forms/update_user_password_form_spec.rb
  spec/lib/aws/ses_spec.rb
  spec/services/email_notifier_spec.rb
  spec/support/shared_examples/password_strength.rb
Labels: status - ready for review

#2559 Fix docauth selfie CSS
  app/views/idv/doc_auth/self_image.html.slim
Labels: status - ready for review

#2548 LG-671 Don't raise if TOTP secret not in session
  app/controllers/users/totp_setup_controller.rb
  app/forms/totp_setup_form.rb
  spec/controllers/users/totp_setup_controller_spec.rb
  spec/forms/totp_setup_form_spec.rb
Labels: status - ready for review

#2552 LG-702 Add redirect uris for Forest Service SP
  config/service_providers.yml
Labels: status - ready for review

#2562 Move timeout translation under notices namespace
  app/controllers/users/sessions_controller.rb
  config/locales/notices/en.yml
  config/locales/notices/es.yml
  config/locales/notices/fr.yml
  spec/controllers/users/sessions_controller_spec.rb
Labels: status - ready for review

#2564 LG-711 Stop asking for webauthn attestation and catch errors
  app/forms/webauthn_setup_form.rb
  app/javascript/packs/webauthn-setup.js
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
  spec/forms/webauthn_setup_form_spec.rb
Labels: status - ready for review
