Repository 18F/identity-idp, pull requests merged in 2018-10, with the labels that each got.

#2563 LG-667 Don't create stray ServiceProvideRequests
  app/controllers/concerns/fully_authenticatable.rb
  app/controllers/concerns/saml_idp_auth_concern.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/decorators/openid_connect_authorize_decorator.rb
  app/forms/openid_connect_authorize_form.rb
  app/models/federated_protocols/oidc.rb
  app/models/federated_protocols/saml.rb
  app/services/service_provider_request_handler.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/decorators/openid_connect_authorize_decorator_spec.rb
  spec/features/account_creation/multiple_browsers_spec.rb
  spec/features/openid_connect/openid_connect_spec.rb
  spec/features/saml/loa1_sso_spec.rb
  spec/features/users/sign_in_spec.rb
  spec/support/shared_examples/account_creation.rb
Labels: status - ready for review

#2567 LG-672 Fix flickering OIDC spec
  spec/forms/openid_connect_token_form_spec.rb
Labels: status - ready for review

#2560 LG-691 Increase minimum password length to 12
  app/controllers/users/passwords_controller.rb
  config/initializers/devise.rb
  spec/controllers/sign_up/passwords_controller_spec.rb
  spec/controllers/users/reset_passwords_controller_spec.rb
  spec/features/visitors/password_recovery_spec.rb
  spec/features/visitors/set_password_spec.rb
  spec/forms/password_form_spec.rb
  spec/forms/reset_password_form_spec.rb
  spec/support/shared_examples/password_strength.rb
Labels: status - ready for review

#2570 [LG-589] read email from email_address table
  app/controllers/account_reset/request_controller.rb
  app/controllers/concerns/two_factor_authenticatable.rb
  app/controllers/concerns/unconfirmed_user_concern.rb
  app/controllers/sign_up/registrations_controller.rb
  app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
  app/controllers/users/passwords_controller.rb
  app/controllers/users/reset_passwords_controller.rb
  app/decorators/user_decorator.rb
  app/forms/register_user_email_form.rb
  app/forms/update_user_email_form.rb
  app/mailers/user_mailer.rb
  app/models/anonymous_user.rb
  app/models/concerns/user_encrypted_attribute_overrides.rb
  app/models/email_address.rb
  app/models/identity.rb
  app/models/service_provider.rb
  app/presenters/openid_connect_user_info_presenter.rb
  app/services/account_reset/cancel.rb
  app/services/account_reset/delete_account.rb
  app/services/key_rotator/hmac_fingerprinter.rb
  app/services/pii/cacher.rb
  app/services/reset_user_password.rb
  app/validators/form_email_validator.rb
  app/validators/form_password_validator.rb
  app/views/accounts/show.html.slim
  lib/tasks/rotate.rake
  spec/controllers/users/reset_passwords_controller_spec.rb
  spec/factories/users.rb
  spec/forms/register_user_email_form_spec.rb
  spec/forms/update_user_email_form_spec.rb
  spec/forms/update_user_password_form_spec.rb
  spec/lib/tasks/rotate_rake_spec.rb
  spec/models/service_provider_spec.rb
  spec/view_models/account_show_spec.rb
Labels: status - ready for review

#2572 Support State Department PIVs
  config/application.yml.example
Labels: status - ready for review, status - required for release

#2576 Only show webauthn option at most once
  app/presenters/two_factor_login_options_presenter.rb
  spec/presenters/two_factor_login_options_presenter_spec.rb
Labels: status - ready for review

#2579 Merge verify password partial with template
  app/views/shared/_user_verify_password.html.slim
  app/views/users/verify_password/new.html.slim
Labels: status - ready for review

#2580 LG-730 Add the Homes.mil Service Provider to production
  certs/sp/homes_mil_prod.crt
  config/service_providers.yml
Labels: status - ready for review, status - required for release

#2575 LG-659 Update FIDO Design flow
  app/assets/stylesheets/components/_util.scss
  app/assets/stylesheets/variables/_colors.scss
  app/controllers/users/webauthn_setup_controller.rb
  app/javascript/packs/webauthn-setup.js
  app/views/accounts/_webauthn.html.slim
  app/views/two_factor_authentication/webauthn_verification/show.html.slim
  app/views/users/two_factor_authentication_setup/index.html.slim
  app/views/users/webauthn_setup/new.html.slim
  app/views/users/webauthn_setup/success.html.slim
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
  config/locales/headings/en.yml
  config/locales/headings/es.yml
  config/locales/headings/fr.yml
  config/locales/notices/en.yml
  config/locales/notices/es.yml
  config/locales/notices/fr.yml
  config/locales/two_factor_authentication/en.yml
  config/locales/two_factor_authentication/es.yml
  config/locales/two_factor_authentication/fr.yml
  config/routes.rb
  spec/controllers/users/webauthn_setup_controller_spec.rb
  spec/features/users/webauthn_management_spec.rb
  spec/support/features/webauthn_helper.rb
Labels: status - ready for review, status - required for release

#2583 LG-696 Add webauthn algorithms
  app/javascript/packs/webauthn-setup.js
Labels: status - ready for review

#2577 Translate remaining untranslated strings
  config/initializers/i18n_english_fallback.rb
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
  config/locales/headings/es.yml
  config/locales/headings/fr.yml
  config/locales/help_text/es.yml
  config/locales/help_text/fr.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
  config/locales/instructions/es.yml
  config/locales/instructions/fr.yml
  config/locales/time/es.yml
  config/locales/time/fr.yml
  config/locales/titles/es.yml
  config/locales/titles/fr.yml
  config/locales/two_factor_authentication/es.yml
  config/locales/two_factor_authentication/fr.yml
  config/locales/user_mailer/es.yml
  config/locales/user_mailer/fr.yml
  spec/config/initializers/i18n_english_fallback.rb
  spec/i18n_spec.rb
Labels: status - ready for review

#2573 Fix multiple MFA configurations login options bug
  .reek.yml
  app/decorators/mfa_context.rb
  app/models/concerns/webauthn_configurations_extension.rb
  app/presenters/two_factor_authentication/phone_selection_presenter.rb
  app/presenters/two_factor_login_options_presenter.rb
  spec/decorators/mfa_context_spec.rb
  spec/features/sign_in/two_factor_options_spec.rb
  spec/presenters/two_factor_authentication/sms_selection_presenter_spec.rb
  spec/presenters/two_factor_authentication/voice_selection_presenter_spec.rb
Labels: status - ready for review, status - required for release

#2574 LG-721 Track account age and enabled MFA methods
  .reek.yml
  app/decorators/mfa_context.rb
  app/models/anonymous_user.rb
  app/models/auth_app_configuration.rb
  app/models/phone_configuration.rb
  app/models/piv_cac_configuration.rb
  app/models/webauthn_configuration.rb
  app/services/account_reset/delete_account.rb
  spec/controllers/account_reset/delete_account_controller_spec.rb
  spec/decorators/mfa_context_spec.rb
  spec/support/account_reset_helper.rb
Labels: status - ready for review, status - required for release

#2585 LG-709 LG-710 LG-731 Enable webauthn for all users
  app/controllers/accounts_controller.rb
  app/controllers/two_factor_authentication/webauthn_verification_controller.rb
  app/controllers/users/two_factor_authentication_controller.rb
  app/policies/two_factor_authentication/webauthn_policy.rb
  app/presenters/two_factor_options_presenter.rb
  app/view_models/account_show.rb
  app/views/accounts/show.html.slim
  app/views/users/webauthn_setup/new.html.slim
  spec/features/users/webauthn_management_spec.rb
  spec/policies/webauthn_login_option_policy_spec.rb
  spec/support/features/webauthn_helper.rb
  spec/support/shared_examples/account_creation.rb
Labels: status - ready for review

#2596 Add full email_fingerprint index
  db/migrate/20181011152323_add_email_fingerprint_index.rb
  db/schema.rb
Labels: status - ready for review, status - required for release

#2597 Deploy RC 68.1 to int
  db/migrate/20181011152323_add_email_fingerprint_index.rb
  db/schema.rb
Labels: status - promotion

#2599 Deploy RC 68.1 to staging
  db/migrate/20181011152323_add_email_fingerprint_index.rb
  db/schema.rb
Labels: status - promotion

#2600 Deploy RC 68.1 to prod
  db/migrate/20181011152323_add_email_fingerprint_index.rb
  db/schema.rb
Labels: status - promotion

#2604 LG-741 LG-739 Fix Webauthn enter key after nickname
  app/javascript/packs/webauthn-setup.js
  app/views/users/webauthn_setup/new.html.slim
Labels: status - ready for review

#2584 LG-693 LG-715 Don't allow adding same FIDO key. Detect webauthn support.
  app/controllers/users/webauthn_setup_controller.rb
  app/forms/webauthn_visit_form.rb
  app/javascript/packs/webauthn-setup.js
  app/views/users/webauthn_setup/new.html.slim
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
  spec/controllers/users/webauthn_setup_controller_spec.rb
  spec/forms/webauthn_visit_form_spec.rb
Labels: status - ready for review

#2603 LG-717 Don't ban disposable email domain names
  config/valid_email.yml
Labels: status - ready for review

#2608 LG-761 Fix reset password
  app/controllers/users/reset_passwords_controller.rb
  app/views/layouts/base.html.slim
  spec/controllers/users/reset_passwords_controller_spec.rb
Labels: status - ready for review

#2541 LG-683 Allow IdV restart on USPS confirmation
  app/controllers/concerns/idv_session.rb
  app/controllers/idv/come_back_later_controller.rb
  app/controllers/idv/phone_controller.rb
  app/controllers/idv/sessions_controller.rb
  app/controllers/idv/usps_controller.rb
  app/controllers/users/verify_account_controller.rb
  app/services/analytics.rb
  app/services/idv/cancel_verification_attempt.rb
  app/views/idv/usps/index.html.slim
  app/views/users/verify_account/index.html.slim
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
  spec/controllers/idv/come_back_later_controller_spec.rb
  spec/controllers/idv/phone_controller_spec.rb
  spec/controllers/idv/sessions_controller_spec.rb
  spec/controllers/idv/usps_controller_spec.rb
  spec/features/idv/clearing_and_restarting_spec.rb
  spec/features/idv/steps/phone_step_spec.rb
  spec/features/idv/steps/usps_step_spec.rb
  spec/services/idv/cancel_verification_attempt_spec.rb
  spec/support/controller_helper.rb
  spec/support/idv_examples/clearing_and_restarting.rb
Labels: status - ready for review

#2594 LG-466 Remove unnecessary code from UserPhoneForm
  app/controllers/users/phones_controller.rb
  app/forms/user_phone_form.rb
  spec/forms/user_phone_form_spec.rb
Labels: status - ready for review

#2607 LG-359 Don't penalize users for IdV vendor errors
  app/services/idv/phone_step.rb
  app/services/idv/profile_step.rb
  spec/services/idv/phone_step_spec.rb
  spec/services/idv/profile_step_spec.rb
Labels: status - ready for review

#2558 Change cancel link on usps to recognize pending user
  app/controllers/idv/usps_controller.rb
  app/decorators/usps_decorator.rb
  app/presenters/idv/usps_presenter.rb
  app/views/idv/usps/index.html.slim
  spec/features/idv/steps/usps_step_spec.rb
  spec/presenters/idv/usps_presenter_spec.rb
  spec/views/idv/usps/index.html.slim_spec.rb
Labels: status - ready for review

#2605 Add remember_device_revoked_at to user
  app/forms/user_phone_form.rb
  app/services/remember_device_revoked_at_migrator.rb
  db/migrate/20181015153200_add_remember_device_revoked_at_to_user.rb
  db/schema.rb
  lib/tasks/migrate_remember_me_revoked_at.rake
  spec/forms/user_phone_form_spec.rb
  spec/services/remember_device_revoked_at_migrator_spec.rb
Labels: status - ready for review

#2610 LG-759 Add personal key phishing warning
  app/assets/images/personal-key/email.svg
  app/assets/stylesheets/components/_background.scss
  app/views/shared/_personal_key.html.slim
  config/locales/instructions/en.yml
  config/locales/instructions/es.yml
  config/locales/instructions/fr.yml
Labels: status - ready for review

#2614 LG-769 Notify exception trackers about IdV errors
  app/services/idv/agent.rb
  spec/services/idv/agent_spec.rb
Labels: status - ready for review

#2615 Remove period from end of "Send me another letter"
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
Labels: status - ready for review

#2578 [LG-424] disable phone by deleting
  app/assets/stylesheets/components/_btn.scss
  app/controllers/concerns/two_factor_authenticatable.rb
  app/controllers/users/phones_controller.rb
  app/controllers/users/reset_passwords_controller.rb
  app/forms/two_factor_authentication/phone_deletion_form.rb
  app/models/auth_app_configuration.rb
  app/models/personal_key_configuration.rb
  app/models/phone_configuration.rb
  app/models/piv_cac_configuration.rb
  app/models/webauthn_configuration.rb
  app/presenters/two_factor_login_options_presenter.rb
  app/services/analytics.rb
  app/validators/multiple_mfa_options_validator.rb
  app/validators/owned_by_user_validator.rb
  app/view_models/account_show.rb
  app/views/accounts/_phone.html.slim
  app/views/accounts/actions/_manage_action_button.html.slim
  app/views/users/phones/edit.html.slim
  app/views/users/shared/_otp_delivery_preference_selection.html.slim
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
  config/locales/headings/en.yml
  config/locales/headings/es.yml
  config/locales/headings/fr.yml
  config/locales/links/en.yml
  config/locales/links/es.yml
  config/locales/links/fr.yml
  config/locales/two_factor_authentication/en.yml
  config/locales/two_factor_authentication/es.yml
  config/locales/two_factor_authentication/fr.yml
  config/routes.rb
  spec/controllers/users/phones_controller_spec.rb
  spec/features/users/user_edit_spec.rb
  spec/forms/two_factor_authentication/phone_deletion_form_spec.rb
  spec/models/webauthn_configuration_spec.rb
Labels: status - ready for review

#2619 LG-771 Add OPM Secure Portal SP to Production
  app/assets/images/sp-logos/opm.png
  certs/sp/opm_prod.crt
  config/service_providers.yml
Labels: status - ready for review, status - required for release

#2622 Namespace platform authenticator params in analytics controller
  app/controllers/analytics_controller.rb
  app/javascript/app/platform-authenticator.js
  app/services/analytics.rb
  spec/controllers/analytics_controller_spec.rb
  spec/requests/edit_user_spec.rb
  spec/requests/frontend_analytics_spec.rb
  spec/support/request_helper.rb
Labels: status - ready for review

#2629 Guard against nil email in password validator
  app/controllers/users/reset_passwords_controller.rb
  app/forms/reset_password_form.rb
  app/validators/form_password_validator.rb
  spec/controllers/users/reset_passwords_controller_spec.rb
  spec/forms/reset_password_form_spec.rb
Labels: status - ready for review

#2606 LG-735 Use remember_me_revoked_at to revoke remember device
  app/services/remember_device_cookie.rb
  spec/services/remember_device_cookie_spec.rb
Labels: status - ready for review

#2638 Add IAL and AAL columns to SP
  db/migrate/20181029203754_add_aal_and_ial_to_service_provider.rb
  db/schema.rb
Labels: status - ready for review
