Repository 18F/identity-idp, pull requests merged in 2018-07, with the labels that each got.

#2279 Prioritize piv/cac during signin if configured
  app/controllers/users/two_factor_authentication_controller.rb
  spec/features/two_factor_authentication/sign_in_spec.rb
Labels: status - ready for review

#2280 LG-340 Use Twilio Verify for international SMS
  .reek
  app/controllers/users/two_factor_authentication_controller.rb
  app/errors/twilio_errors.rb
  app/jobs/sms_otp_sender_job.rb
  app/services/phone_verification.rb
  config/application.yml.example
  spec/controllers/users/two_factor_authentication_controller_spec.rb
  spec/features/two_factor_authentication/change_factor_spec.rb
  spec/features/two_factor_authentication/sign_in_spec.rb
  spec/features/visitors/phone_confirmation_spec.rb
  spec/jobs/sms_otp_sender_job_spec.rb
  spec/services/phone_verification_spec.rb
  spec/services/twilio_service_spec.rb
  spec/support/fake_adapter.rb
Labels: status - ready for review

#2203 LG-290 Move attribute encryption away from KMS
  app/services/encryption/encryptors/attribute_encryptor.rb
  app/services/encryption/encryptors/deprecated_attribute_encryptor.rb
  app/services/encryption/kms_client.rb
  config/application.yml.example
  spec/services/encrypted_attribute_spec.rb
  spec/services/encryption/encryptors/attribute_encryptor_spec.rb
  spec/services/encryption/encryptors/deprecated_attribute_encryptor_spec.rb
  spec/services/encryption/kms_client_spec.rb
  spec/services/pii/cacher_spec.rb
  spec/support/key_rotation_helper.rb
Labels: status - ready for review

#2276 LG-312 Add SMS opt-out
  .reek
  app/controllers/sms_controller.rb
  app/forms/sms_form.rb
  app/jobs/sms_account_reset_notifier_job.rb
  app/jobs/sms_otp_sender_job.rb
  app/jobs/sms_reply_sender_job.rb
  app/jobs/voice_otp_sender_job.rb
  app/services/analytics.rb
  app/services/twilio_service.rb
  app/services/twilio_service/sms/request.rb
  app/services/twilio_service/sms/response.rb
  config/application.yml.example
  config/initializers/new_relic_tracers.rb
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
  config/locales/sms/en.yml
  config/locales/sms/es.yml
  config/locales/sms/fr.yml
  config/routes.rb
  lib/user_flow_exporter.rb
  spec/controllers/account_reset/request_controller_spec.rb
  spec/forms/sms_form_spec.rb
  spec/jobs/sms_account_reset_notifier_job_spec.rb
  spec/jobs/sms_otp_sender_job_spec.rb
  spec/jobs/voice_otp_sender_job_spec.rb
  spec/requests/sms_spec.rb
  spec/services/account_reset_service_spec.rb
  spec/services/twilio_service/sms/request_spec.rb
  spec/services/twilio_service/sms/response_spec.rb
  spec/services/twilio_service_spec.rb
  spec/support/features/session_helper.rb
Labels: status - do not merge

#2284 Define locale argument for VoiceOtpSenderJob
  .reek
  app/jobs/voice_otp_sender_job.rb
  spec/features/two_factor_authentication/sign_in_spec.rb
Labels: status - ready for review

#2289 LG-438 Remove csrf protection on account reset delayed notifications endpoint
  app/controllers/account_reset/send_notifications_controller.rb
Labels: status - ready for review

#2295 Remove TODOs from codebase
  .codeclimate.yml
  app/controllers/concerns/user_session_context.rb
  app/forms/openid_connect_token_form.rb
  app/javascript/packs/personal-key-page-controller.js
  app/services/piv_cac_service.rb
  config/application.yml.example
  spec/features/flows/sp_authentication_flows_spec.rb
  spec/features/two_factor_authentication/sign_in_spec.rb
  spec/lib/worker_health_checker_spec.rb
Labels: status - ready for review

#2292 Allow Code Climate to analyze the spec folder
  .codeclimate.yml
  spec/controllers/account_reset/cancel_controller_spec.rb
  spec/controllers/account_reset/delete_account_controller_spec.rb
  spec/controllers/account_reset/report_fraud_controller_spec.rb
  spec/controllers/account_reset/request_controller_spec.rb
  spec/jobs/sms_account_reset_notifier_job_spec.rb
  spec/mailers/user_mailer_spec.rb
  spec/models/account_reset_request_spec.rb
  spec/services/account_reset_service_spec.rb
  spec/views/account_reset/confirm_delete_account/show.html.slim_spec.rb
  spec/views/account_reset/delete_account/show.html.slim_spec.rb
  spec/views/account_reset/request/show.html.slim_spec.rb
Labels: status - ready for review

#2294 Fix attribute_encryption_key_queue in example yml
  config/application.yml.example
Labels: status - ready for review

#2306 LG-447 Fix typo on account reset page
  config/locales/account_reset/en.yml
Labels: status - ready for review

#2309 LG-451 Remove duplicate SMS sent with account reset delayed notification
  app/services/account_reset_service.rb
Labels: status - ready for review

#2307 LG-408 Remove USPS mail batch hours config
  config/application.yml.example
Labels: status - ready for review

#2314 LG-436 Update gems to verify addresses with LN
  Gemfile
  Gemfile.lock
  lib/proofer_mocks/address_mock.rb
  lib/proofer_mocks/resolution_mock.rb
  lib/proofer_mocks/state_id_mock.rb
  spec/controllers/idv/confirmations_controller_spec.rb
  spec/controllers/idv/review_controller_spec.rb
  spec/controllers/idv/usps_controller_spec.rb
  spec/services/idv/agent_spec.rb
Labels: status - ready for review

#2311 LG-289 Drop old encrypted password columns
  db/migrate/20180709141748_drop_encrypted_password_column_from_user.rb
  db/schema.rb
Labels: status - ready for review

#2319 LG-462 Add tsp.move.mil service provider
  config/service_providers.yml
Labels: status - ready for review

#2323 Add NGA and EOP as agencies which allow piv/cac
  config/application.yml.example
Labels: status - ready for review

#2321 LG-268 Serve assets from Cloudfront CDN
  config/environments/production.rb
  config/initializers/secure_headers.rb
Labels: status - ready for review

#2322 LG-464 Update attribute encryption rake task to log errors and continue
  lib/tasks/rotate.rake
  spec/lib/tasks/rotate_rake_spec.rb
Labels: status - ready for review

#2320 LG-449 - Cancelling account deletion should notify both factors
  .reek
  app/controllers/account_reset/cancel_controller.rb
  app/controllers/account_reset/delete_account_controller.rb
  app/controllers/account_reset/request_controller.rb
  app/jobs/sms_account_reset_cancellation_notifier_job.rb
  app/mailers/user_mailer.rb
  app/services/account_reset_service.rb
  app/views/user_mailer/account_reset_cancel.html.slim
  config/locales/devise/en.yml
  config/locales/devise/es.yml
  config/locales/devise/fr.yml
  config/locales/jobs/en.yml
  config/locales/jobs/es.yml
  config/locales/jobs/fr.yml
  config/locales/user_mailer/en.yml
  config/locales/user_mailer/es.yml
  config/locales/user_mailer/fr.yml
  spec/controllers/account_reset/cancel_controller_spec.rb
  spec/controllers/account_reset/delete_account_controller_spec.rb
  spec/jobs/sms_account_reset_cancellation_notifier_job_spec.rb
  spec/services/account_reset_service_spec.rb
Labels: status - ready for review

#2327 LG-482 Add a new redirect uri to DOT portal SP
  config/service_providers.yml
Labels: status - ready for review

#2329 Ignore the old password columns on the user model
  app/models/user.rb
  db/migrate/20180709141748_drop_encrypted_password_column_from_user.rb
  db/schema.rb
Labels: status - ready for review

#2313 Stop reading old recovery code columns
  .reek
  app/controllers/concerns/two_factor_authenticatable.rb
  app/controllers/idv/sessions_controller.rb
  app/controllers/sign_up/personal_keys_controller.rb
  app/decorators/user_decorator.rb
  app/models/concerns/user_access_key_overrides.rb
  app/models/user.rb
  app/services/encryption/password_verifier.rb
  app/services/personal_key_generator.rb
  spec/factories/users.rb
  spec/features/two_factor_authentication/sign_in_spec.rb
  spec/features/users/regenerate_personal_key_spec.rb
  spec/forms/password_reset_email_form_spec.rb
  spec/services/encryption/password_verifier_spec.rb
  spec/services/personal_key_generator_spec.rb
  spec/support/shared_examples_for_personal_keys.rb
Labels: status - ready for review

#2336 Revert "Stop reading personal key columns (#2313)"
  .reek
  app/controllers/concerns/two_factor_authenticatable.rb
  app/controllers/idv/sessions_controller.rb
  app/controllers/sign_up/personal_keys_controller.rb
  app/decorators/user_decorator.rb
  app/models/concerns/user_access_key_overrides.rb
  app/models/user.rb
  app/services/encryption/password_verifier.rb
  app/services/personal_key_generator.rb
  spec/factories/users.rb
  spec/features/two_factor_authentication/sign_in_spec.rb
  spec/features/users/regenerate_personal_key_spec.rb
  spec/forms/password_reset_email_form_spec.rb
  spec/services/encryption/password_verifier_spec.rb
  spec/services/personal_key_generator_spec.rb
  spec/support/shared_examples_for_personal_keys.rb
Labels: status - ready for review

#2332 LG-403 Create an AWS lambda function to upload USPS verification to GPO
  app/controllers/usps_upload_controller.rb
  spec/controllers/usps_upload_controller_spec.rb
Labels: status - ready for review

#2339 LG-492 Add Forest Service ePermits to the production service providers
  certs/sp/usfs_prod.crt
  config/agencies.yml
  config/service_providers.yml
Labels: status - ready for review

#2326 LG 469 USPS Confirmation Url and SP name
  app/services/usps_exporter.rb
  spec/services/usps_exporter_spec.rb
Labels: status - ready for review

#2337 Fix personal key 2fa selection
  .reek
  app/controllers/concerns/two_factor_authenticatable.rb
  app/controllers/idv/sessions_controller.rb
  app/controllers/sign_up/personal_keys_controller.rb
  app/decorators/user_decorator.rb
  app/models/concerns/user_access_key_overrides.rb
  app/models/user.rb
  app/policies/personal_key_login_option_policy.rb
  app/services/encryption/password_verifier.rb
  app/services/personal_key_generator.rb
  spec/factories/users.rb
  spec/features/two_factor_authentication/sign_in_spec.rb
  spec/features/users/regenerate_personal_key_spec.rb
  spec/forms/password_reset_email_form_spec.rb
  spec/services/encryption/password_verifier_spec.rb
  spec/services/personal_key_generator_spec.rb
  spec/support/shared_examples_for_personal_keys.rb
Labels: status - ready for review

#2348 Deploy RC 61.1 to int
  app/services/openid_connect_redirector.rb
  spec/services/openid_connect_redirector_spec.rb
Labels: status - promotion

#2349 Deploy RC 61.1 to staging
  app/services/openid_connect_redirector.rb
  spec/services/openid_connect_redirector_spec.rb
Labels: status - promotion

#2350 Deploy RC 61.1 to stages/prod
  app/services/openid_connect_redirector.rb
  spec/services/openid_connect_redirector_spec.rb
Labels: status - promotion

#2346 Fix 500 errors on bad personal key and invalid otp_delivery_preference in path. Add specs.
  app/controllers/two_factor_authentication/personal_key_verification_controller.rb
  config/routes.rb
  spec/features/two_factor_authentication/remember_device_spec.rb
  spec/features/two_factor_authentication/sign_in_spec.rb
  spec/features/users/sign_in_spec.rb
Labels: status - ready for review

#2352 Ignore saml_*.txt files generated by tests
  .gitignore
  saml_20180619025351.txt
  saml_20180620023548.txt
Labels: status - ready for review

#2331 LG-484 Display a message to the user when an account reset link is expired
  app/controllers/account_reset/delete_account_controller.rb
  app/models/account_reset_request.rb
  app/presenters/two_factor_login_options_presenter.rb
  config/locales/devise/en.yml
  config/locales/devise/es.yml
  config/locales/devise/fr.yml
  config/locales/user_mailer/en.yml
  config/locales/user_mailer/es.yml
  config/locales/user_mailer/fr.yml
  spec/controllers/account_reset/delete_account_controller_spec.rb
  spec/models/account_reset_request_spec.rb
  spec/presenters/two_factor_login_options_presenter_spec.rb
Labels: status - ready for review

#2341 LG 363 LOA3 cancellation
  app/assets/stylesheets/components/_list.scss
  app/assets/stylesheets/components/all.scss
  app/controllers/idv/cancellations_controller.rb
  app/controllers/idv/sessions_controller.rb
  app/controllers/idv_controller.rb
  app/presenters/idv/cancellation_confirmation_presenter.rb
  app/presenters/idv/cancellation_presenter.rb
  app/services/analytics.rb
  app/views/idv/cancellations/destroy.html.slim
  app/views/idv/cancellations/new.html.slim
  app/views/idv/jurisdiction/new.html.slim
  app/views/idv/otp_delivery_method/new.html.slim
  app/views/idv/phone/new.html.slim
  app/views/idv/review/new.html.slim
  app/views/idv/sessions/new.html.slim
  app/views/idv/sessions/success.html.slim
  app/views/idv/usps/index.html.slim
  app/views/shared/_cancel.html.slim
  app/views/shared/_failure.html.slim
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
  config/locales/headings/en.yml
  config/locales/headings/es.yml
  config/locales/headings/fr.yml
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
  config/locales/links/en.yml
  config/locales/links/es.yml
  config/locales/links/fr.yml
  config/routes.rb
  saml_20180717020714.txt
  spec/controllers/idv/cancellations_controller_spec.rb
  spec/controllers/idv/sessions_controller_spec.rb
  spec/controllers/idv_controller_spec.rb
  spec/features/idv/steps/phone_otp_delivery_selection_step_spec.rb
  spec/features/idv/steps/phone_otp_verification_step_spec.rb
  spec/features/idv/steps/phone_step_spec.rb
  spec/features/idv/steps/profile_step_spec.rb
  spec/features/idv/steps/review_step_spec.rb
  spec/features/idv/steps/usps_step_spec.rb
  spec/features/saml/loa3_sso_spec.rb
  spec/presenters/idv/cancellation_presenter_spec.rb
  spec/support/features/idv_helper.rb
  spec/support/features/idv_step_helper.rb
  spec/support/idv_examples/cancel_at_idv_step.rb
Labels: status - ready for review

#2360 LG-455 User can't create account because their email is "invalid"
  config/valid_email.yml
Labels: status - ready for review

#2366 Cleanup idv cancel path formation
  app/presenters/idv/cancellation_presenter.rb
Labels: status - ready for review

#2355 LG-491 Don't truncate scrypt digest in pii encryption
  app/services/encryption/encryptors/pii_encryptor.rb
  spec/services/encryption/encryptors/pii_encryptor_spec.rb
Labels: status - ready for review

#2354 LG-490 Verify password hashes without digesting salts
  app/services/encryption/encryptors/deprecated_attribute_encryptor.rb
  app/services/encryption/encryptors/session_encryptor.rb
  app/services/encryption/user_access_key.rb
  spec/services/encryption/password_verifier_spec.rb
  spec/services/encryption/user_access_key_spec.rb
Labels: status - ready for review

#2367 Read 2L-KMS encrypted sessions
  app/services/encryption/encryptors/deprecated_session_encryptor.rb
  app/services/encryption/encryptors/session_encryptor.rb
  spec/services/encryption/encryptors/deprecated_session_encryptor.rb
  spec/services/encryption/encryptors/session_encryptor_spec.rb
Labels: status - ready for review

#2353 LG-489 Adjust scrypt cost
  config/application.yml.example
Labels: status - ready for review

#2310 LG-429 Create an AWS lambda function for delayed notifications with account reset
  .rubocop.yml
  lib/lambdas/account_reset_lambda.rb
  spec/lib/lambdas/account_reset_lambda_spec.rb
Labels: status - ready for review

#2370 LG 503 usps upload wo file
  .reek
  app/controllers/usps_upload_controller.rb
  app/services/usps_confirmation_exporter.rb
  app/services/usps_confirmation_uploader.rb
  app/services/usps_uploader.rb
  spec/controllers/usps_upload_controller_spec.rb
  spec/services/usps_confirmation_exporter_spec.rb
  spec/services/usps_confirmation_uploader_spec.rb
  spec/services/usps_exporter_spec.rb
  spec/services/usps_uploader_spec.rb
Labels: status - ready for review

#2335 Drop password columns
  db/migrate/20180709141748_drop_encrypted_password_column_from_user.rb
  db/schema.rb
Labels: status - do not merge, status - ready for review

#2358 LG-483 Update USAJOBS / TTP instructions on create account
  app/decorators/service_provider_session_decorator.rb
  app/decorators/session_decorator.rb
  app/views/shared/_sp_alert.html.slim
  config/locales/service_providers/en.yml
  config/locales/service_providers/es.yml
  config/locales/service_providers/fr.yml
Labels: status - ready for review

#2376 LG-475 Add Connected Applications to Account Management
  app/assets/images/connected_apps.png
  app/decorators/identity_decorator.rb
  app/decorators/user_decorator.rb
  app/view_models/account_show.rb
  app/views/accounts/_connected_app.html.slim
  app/views/accounts/show.html.slim
  config/locales/account/en.yml
  config/locales/account/es.yml
  config/locales/account/fr.yml
  config/locales/headings/en.yml
  config/locales/headings/es.yml
  config/locales/headings/fr.yml
  spec/features/account_connected_apps_spec.rb
  spec/views/accounts/show.html.slim_spec.rb
Labels: status - ready for review

#2379 LG-17 Production Error: ERROR: duplicate key (email)
  app/controllers/sign_up/email_confirmations_controller.rb
  spec/controllers/sign_up/email_confirmations_controller_spec.rb
Labels: status - ready for review

#2378 Add logstash.conf.example and update README
  README.md
  logstash.conf.example
Labels: status - ready for review

#2315 Update PR template and contribution guidelines
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: status - ready for review

#2359 LG-399 Fix confusing placeholder phone number
  app/assets/stylesheets/components/_form.scss
  app/javascript/app/phone-validation.js
  app/views/users/phone_setup/index.html.slim
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
Labels: status - ready for review

#2342 LG-450 Use different text in SMS for login vs verify phone number
  .reek
  app/controllers/users/two_factor_authentication_controller.rb
  app/jobs/sms_otp_sender_job.rb
  config/i18n-tasks.yml
  config/locales/jobs/en.yml
  config/locales/jobs/es.yml
  config/locales/jobs/fr.yml
  spec/controllers/users/two_factor_authentication_controller_spec.rb
  spec/features/two_factor_authentication/change_factor_spec.rb
  spec/features/two_factor_authentication/sign_in_spec.rb
  spec/features/visitors/phone_confirmation_spec.rb
  spec/jobs/sms_otp_sender_job_spec.rb
  spec/services/twilio_service_spec.rb
Labels: status - ready for review

#2340 LG-433 Add script to email compromised users
  app/mailers/user_mailer.rb
  app/services/reset_user_password.rb
  app/services/reset_user_password_and_send_email.rb
  app/views/user_mailer/please_reset_password.html.slim
  bin/reset_user_password
  config/locales/user_mailer/en.yml
  config/locales/user_mailer/es.yml
  config/locales/user_mailer/fr.yml
  spec/mailers/user_mailer_spec.rb
  spec/services/reset_user_password_and_send_email_spec.rb
  spec/support/shared_contexts/rake.rb
Labels: status - ready for review

#2351 Refactor SP redirect URI validation
  .reek
  app/controllers/concerns/secure_headers_concern.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/decorators/service_provider_session_decorator.rb
  app/forms/openid_connect_authorize_form.rb
  app/forms/openid_connect_logout_form.rb
  app/services/openid_connect_redirector.rb
  app/validators/redirect_uri_validator.rb
  config/service_providers.yml
  spec/controllers/openid_connect/logout_controller_spec.rb
  spec/features/openid_connect/openid_connect_spec.rb
  spec/features/openid_connect/redirect_uri_validation_spec.rb
  spec/features/saml/redirect_uri_validation_spec.rb
  spec/forms/openid_connect_authorize_form_spec.rb
  spec/forms/openid_connect_logout_form_spec.rb
  spec/services/openid_connect_redirector_spec.rb
Labels: status - ready for review

#2386 Upload a `file` to GPO via sftp instead of streaming
  app/services/usps_confirmation_uploader.rb
  config/application.yml.example
  spec/services/usps_confirmation_uploader_spec.rb
Labels: status - ready for review

#2361 [LG-498] Add phone configurations table
  app/models/concerns/encryptable_attribute.rb
  app/models/phone_configuration.rb
  app/models/user.rb
  app/services/key_rotator/attribute_encryption.rb
  app/services/update_user.rb
  db/migrate/20180720152009_create_phone_configurations_table.rb
  db/schema.rb
  lib/tasks/create_test_accounts.rb
  lib/tasks/dev.rake
  lib/tasks/rotate.rake
  spec/controllers/account_reset/cancel_controller_spec.rb
  spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
  spec/controllers/users/phones_controller_spec.rb
  spec/factories/phone_configurations.rb
  spec/factories/users.rb
  spec/features/two_factor_authentication/change_factor_spec.rb
  spec/features/two_factor_authentication/sign_in_spec.rb
  spec/features/users/piv_cac_management_spec.rb
  spec/features/visitors/phone_confirmation_spec.rb
  spec/forms/user_phone_form_spec.rb
  spec/lib/tasks/rotate_rake_spec.rb
  spec/models/phone_configuration_spec.rb
  spec/models/user_spec.rb
  spec/services/update_user_spec.rb
Labels: status - ready for review

#2394 LG-523 Update release script to remove workers and rename recycle script
  bin/release
Labels: status - ready for review

#2387 LG-504 Create a health checker for account reset notifications
  app/controllers/health/health_controller.rb
  app/services/account_reset_health_checker.rb
  spec/controllers/health/health_controller_spec.rb
  spec/services/account_reset_health_checker_spec.rb
Labels: status - ready for review
