Repository 18F/identity-idp, pull requests merged in 2018-11, with the labels that each got.

#2639 LG-766 Require MFA after 12 hours for IAL2 and AAL2
  .rubocop.yml
  app/controllers/concerns/remember_device_concern.rb
  app/controllers/concerns/two_factor_authenticatable.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/controllers/saml_idp_controller.rb
  app/controllers/two_factor_authentication/personal_key_verification_controller.rb
  app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
  app/controllers/two_factor_authentication/webauthn_verification_controller.rb
  app/decorators/service_provider_session_decorator.rb
  app/decorators/session_decorator.rb
  app/services/remember_device_cookie.rb
  app/views/two_factor_authentication/otp_verification/show.html.slim
  config/application.yml.example
  config/initializers/figaro.rb
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
  spec/controllers/saml_idp_controller_spec.rb
  spec/decorators/service_provider_session_decorator_spec.rb
  spec/decorators/session_decorator_spec.rb
  spec/features/two_factor_authentication/remember_device_sp_expiration_spec.rb
  spec/features/two_factor_authentication/remember_device_spec.rb
  spec/services/remember_device_cookie_spec.rb
  spec/support/controller_helper.rb
  spec/support/shared_examples/remember_device.rb
Labels: status - ready for review

#2634 LG-768 Create event for personal key as 2FA
  app/controllers/two_factor_authentication/personal_key_verification_controller.rb
  app/models/event.rb
  config/locales/event_types/en.yml
  config/locales/event_types/es.yml
  config/locales/event_types/fr.yml
  spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb
  spec/features/users/sign_in_spec.rb
  yarn.lock
Labels: status - ready for review

#2624 LG-763 Fix SAML NameFormat to comply with the SAML 2.0 standard
  app/services/attribute_asserter.rb
  spec/controllers/saml_idp_controller_spec.rb
Labels: status - ready for review

#2635 LG-748 Create events for webauthn key management
  app/controllers/users/webauthn_setup_controller.rb
  app/forms/webauthn_setup_form.rb
  app/models/event.rb
  config/locales/event_types/en.yml
  config/locales/event_types/es.yml
  config/locales/event_types/fr.yml
  spec/controllers/users/webauthn_setup_controller_spec.rb
  spec/features/users/webauthn_management_spec.rb
  spec/forms/webauthn_setup_form_spec.rb
Labels: status - ready for review

#2633 LG-668 Capture use of remember me feature
  app/controllers/users/sessions_controller.rb
  spec/controllers/users/sessions_controller_spec.rb
Labels: status - ready for review

#2617 LG-726 Confirm before removing security key
  app/controllers/users/webauthn_setup_controller.rb
  app/views/accounts/_webauthn.html.slim
  app/views/users/webauthn_setup/delete.html.slim
  config/locales/account/en.yml
  config/locales/account/es.yml
  config/locales/account/fr.yml
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
  config/locales/instructions/en.yml
  config/locales/instructions/es.yml
  config/locales/instructions/fr.yml
  config/locales/notices/en.yml
  config/locales/notices/es.yml
  config/locales/notices/fr.yml
  config/locales/two_factor_authentication/en.yml
  config/locales/two_factor_authentication/es.yml
  config/locales/two_factor_authentication/fr.yml
  config/routes.rb
  spec/features/users/webauthn_management_spec.rb
Labels: status - ready for review

#2630 LG-767 Alert a user on personal key sign in
  app/forms/personal_key_form.rb
  app/jobs/sms_personal_key_sign_in_notifier_job.rb
  app/mailers/user_mailer.rb
  app/views/user_mailer/personal_key_sign_in.html.slim
  config/locales/jobs/en.yml
  config/locales/jobs/es.yml
  config/locales/jobs/fr.yml
  config/locales/user_mailer/en.yml
  config/locales/user_mailer/es.yml
  config/locales/user_mailer/fr.yml
  spec/features/two_factor_authentication/sign_in_via_personal_key_spec.rb
  spec/features/users/sign_in_spec.rb
  spec/forms/personal_key_form_spec.rb
  spec/jobs/sms_account_reset_notifier_job_spec.rb
  spec/jobs/sms_personal_key_sign_in_notifier_job_spec.rb
  spec/mailers/user_mailer_spec.rb
  spec/support/shared_examples/sign_in.rb
Labels: status - required for release

#2644 Stub twilio when testing personal key as mfa
  spec/features/users/password_recovery_via_recovery_code_spec.rb
Labels: status - ready for review, status - required for release

#2642 LG-775 Do not present FIDO auth option if browser does not support FIDO
  app/javascript/packs/webauthn-setup.js
  app/javascript/packs/webauthn-unhide.js
  app/presenters/two_factor_authentication/selection_presenter.rb
  app/presenters/two_factor_authentication/webauthn_selection_presenter.rb
  app/views/two_factor_authentication/options/index.html.slim
  spec/presenters/two_factor_authentication/webauthn_selection_presenter_spec.rb
Labels: status - ready for review

#2648 LG-746 Return 400 error for invalid String params
  app/controllers/application_controller.rb
  app/controllers/sign_up/email_resend_controller.rb
  lib/core_extensions/string/permit.rb
  spec/requests/invalid_sign_in_params_spec.rb
  spec/requests/params_is_string_instead_of_hash_spec.rb
Labels: status - ready for review

#2651 Fix redirect when not presenting FIDO
  app/javascript/packs/webauthn-authenticate.js
  app/javascript/packs/webauthn-setup.js
Labels: status - ready for review

#2649 LG-793 Add user event when removing phone number
  app/controllers/users/phones_controller.rb
  app/models/event.rb
  config/locales/event_types/en.yml
  config/locales/event_types/es.yml
  config/locales/event_types/fr.yml
  spec/features/users/user_edit_spec.rb
Labels: status - ready for review

#2647 LG-732 Add security key SVG to setup page
  app/assets/images/security-key.svg
  app/views/users/webauthn_setup/new.html.slim
Labels: status - ready for review

#2653 Update gems with bummr
  Gemfile.lock
  spec/services/phone_verification_spec.rb
Labels: status - ready for review

#2657 LG-742 Create password screen allows less than 12 characters
  app/javascript/packs/pw-strength.js
Labels: status - ready for review

#2654 LG-795 Display timestamps in the local timezone
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/decorators/event_decorator.rb
  app/decorators/identity_decorator.rb
  app/javascript/app/local-time.js
  app/javascript/packs/application.js
  app/presenters/utc_time_presenter.rb
  app/views/accounts/_connected_app.html.slim
  app/views/accounts/_event_item.html.slim
  app/views/accounts/_identity_item.html.slim
  config/i18n-tasks.yml
  config/locales/account/en.yml
  config/locales/account/es.yml
  config/locales/account/fr.yml
  spec/features/account_connected_apps_spec.rb
  spec/presenters/utc_time_presenter_spec.rb
Labels: status - ready for review

#2652 LG-583 Update account reset final delete screen design
  app/views/account_reset/delete_account/show.html.slim
  config/locales/account_reset/en.yml
  config/locales/account_reset/es.yml
  config/locales/account_reset/fr.yml
  spec/features/account_reset/delete_account_spec.rb
  spec/views/account_reset/delete_account/show.html.slim_spec.rb
Labels: status - ready for review

#2660 LG-785 Alert users when personal key is regenerated
  app/controllers/users/personal_keys_controller.rb
  app/jobs/sms_personal_key_regeneration_notifier_job.rb
  app/mailers/user_mailer.rb
  app/views/user_mailer/personal_key_regenerated.html.slim
  config/locales/jobs/en.yml
  config/locales/jobs/es.yml
  config/locales/jobs/fr.yml
  config/locales/user_mailer/en.yml
  config/locales/user_mailer/es.yml
  config/locales/user_mailer/fr.yml
  spec/features/users/regenerate_personal_key_spec.rb
  spec/jobs/sms_personal_key_regeneration_notifier_job_spec.rb
  spec/mailers/user_mailer_spec.rb
Labels: status - ready for review

#2665 Update Account Reset Cancel analytics
  app/services/account_reset/validate_cancel_token.rb
  spec/controllers/account_reset/cancel_controller_spec.rb
Labels: status - ready for review

#2670 LG-792 Upgrade to ruby v2.5.3
  .circleci/config.yml
  Gemfile
  Gemfile.lock
Labels: status - ready for review

#2669 LG-833 Don't let user's remove last 2fa method
  .rubocop.yml
  app/controllers/users/piv_cac_authentication_setup_controller.rb
  app/controllers/users/totp_setup_controller.rb
  app/view_models/account_show.rb
  spec/controllers/users/piv_cac_authentication_setup_controller_spec.rb
  spec/controllers/users/totp_setup_controller_spec.rb
  spec/features/users/piv_cac_management_spec.rb
  spec/features/users/totp_management_spec.rb
  spec/view_models/account_show_spec.rb
Labels: status - ready for review

#2623 Remove deprecated frontend analytics API
  app/controllers/analytics_controller.rb
  spec/requests/frontend_analytics_spec.rb
Labels: status - ready for review

#2674 Don't fail setup script if geo_data folder exists
  bin/setup
Labels: status - ready for review

#2677 Upgrade to node v10
  package.json
Labels: status - ready for review

#2679 Fix geolite copy issue in setup script
  bin/setup
Labels: status - ready for review
