Repository 18F/identity-idp, pull requests merged in 2018-08, with the labels that each got.

#2395 Hardcode session encryption cost for migration
  app/services/encryption/encryptors/deprecated_session_encryptor.rb
Labels: status - ready for review

#2398 LG-525 Fix IDV for users without phones
  app/controllers/two_factor_authentication/otp_verification_controller.rb
  spec/features/idv/steps/phone_step_spec.rb
Labels: status - ready for review

#2373 Write 2L KMS encrypted sessions
  app/services/encryption/encryptors/session_encryptor.rb
  spec/services/encryption/encryptors/session_encryptor_spec.rb
Labels: status - do not merge, status - ready for review

#2372 LG-490 Use 32 byte salts for passwords
  app/services/encryption/password_verifier.rb
  spec/services/encryption/password_verifier_spec.rb
Labels: status - do not merge, status - ready for review

#2400 Revert "Merge pull request #2351 from 18F/mb-refactor-redirect-uri-va…
  .reek
  app/controllers/concerns/secure_headers_concern.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/decorators/service_provider_session_decorator.rb
  app/forms/openid_connect_authorize_form.rb
  app/forms/openid_connect_logout_form.rb
  app/services/openid_connect_redirector.rb
  app/validators/redirect_uri_validator.rb
  config/service_providers.yml
  spec/controllers/openid_connect/logout_controller_spec.rb
  spec/features/openid_connect/openid_connect_spec.rb
  spec/features/openid_connect/redirect_uri_validation_spec.rb
  spec/features/saml/redirect_uri_validation_spec.rb
  spec/forms/openid_connect_authorize_form_spec.rb
  spec/forms/openid_connect_logout_form_spec.rb
  spec/services/openid_connect_redirector_spec.rb
Labels: status - ready for review

#2401 Deploy RC 63.1 to int
  .reek
  app/controllers/concerns/secure_headers_concern.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/controllers/two_factor_authentication/otp_verification_controller.rb
  app/decorators/service_provider_session_decorator.rb
  app/forms/openid_connect_authorize_form.rb
  app/forms/openid_connect_logout_form.rb
  app/services/openid_connect_redirector.rb
  app/validators/redirect_uri_validator.rb
  config/service_providers.yml
  spec/controllers/openid_connect/logout_controller_spec.rb
  spec/features/idv/steps/phone_step_spec.rb
  spec/features/openid_connect/openid_connect_spec.rb
  spec/features/openid_connect/redirect_uri_validation_spec.rb
  spec/features/saml/redirect_uri_validation_spec.rb
  spec/forms/openid_connect_authorize_form_spec.rb
  spec/forms/openid_connect_logout_form_spec.rb
  spec/services/openid_connect_redirector_spec.rb
Labels: status - promotion

#2402 Deploy RC 63.1 to staging
  .reek
  app/controllers/concerns/secure_headers_concern.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/controllers/two_factor_authentication/otp_verification_controller.rb
  app/decorators/service_provider_session_decorator.rb
  app/forms/openid_connect_authorize_form.rb
  app/forms/openid_connect_logout_form.rb
  app/services/openid_connect_redirector.rb
  app/validators/redirect_uri_validator.rb
  config/service_providers.yml
  spec/controllers/openid_connect/logout_controller_spec.rb
  spec/features/idv/steps/phone_step_spec.rb
  spec/features/openid_connect/openid_connect_spec.rb
  spec/features/openid_connect/redirect_uri_validation_spec.rb
  spec/features/saml/redirect_uri_validation_spec.rb
  spec/forms/openid_connect_authorize_form_spec.rb
  spec/forms/openid_connect_logout_form_spec.rb
  spec/services/openid_connect_redirector_spec.rb
Labels: status - promotion

#2407 Allow exception logs to capture nil user
  app/views/exception_notifier/_session.text.erb
Labels: status - ready for review

#2408 Deploy RC 63.3 to int
  app/services/encryption/encryptors/session_encryptor.rb
  spec/services/encryption/encryptors/session_encryptor_spec.rb
Labels: status - promotion

#2412 Remove unused code that inflated our session size
  app/controllers/openid_connect/authorization_controller.rb
Labels: status - ready for review

#2390 LG-519 Fix: session timeout prevents return to SP and loses SP branding
  app/controllers/users/sessions_controller.rb
  spec/features/saml/loa1_sso_spec.rb
Labels: status - ready for review

#2416 LG-533 Add a New Redirect URI for the DOE - Fossil Energy SP
  config/service_providers.yml
Labels: status - ready for review

#2235 LG-352 Create new CloudHSM key sharing script to grant IDP access to generated keys
  .reek
  .rubocop.yml
  lib/cloudhsm/cloudhsm_key_generator.rb
  lib/cloudhsm/cloudhsm_key_sharer.rb
  lib/tasks/cloudhsm.rake
  spec/lib/cloudhsm/cloudhsm_key_generator_spec.rb
  spec/lib/cloudhsm/cloudhsm_key_sharer_spec.rb
Labels: status - ready for review

#2385 LG-454 Refactor AccountReset::CancelController
  app/controllers/account_reset/cancel_controller.rb
  app/services/account_reset/cancel.rb
  app/services/account_reset_service.rb
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
  config/routes.rb
  spec/controllers/account_reset/cancel_controller_spec.rb
  spec/features/account_reset/cancel_request_spec.rb
  spec/services/account_reset/cancel_spec.rb
  spec/services/account_reset_service_spec.rb
  spec/support/account_reset_helper.rb
Labels: status - ready for review

#2421 LG-542 Don't allow LOA3 users to request delete account
  app/controllers/account_reset/request_controller.rb
  app/presenters/two_factor_login_options_presenter.rb
  app/services/account_reset_service.rb
  app/views/two_factor_authentication/options/index.html.slim
  spec/features/account_reset/delete_account_spec.rb
Labels: status - ready for review

#2424 Deploy RC 64 to int
  .github/PULL_REQUEST_TEMPLATE.md
  .reek
  .rubocop.yml
  Gemfile.lock
  app/controllers/account_reset/cancel_controller.rb
  app/controllers/account_reset/request_controller.rb
  app/controllers/health/health_controller.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/controllers/users/sessions_controller.rb
  app/decorators/identity_decorator.rb
  app/models/null_service_provider.rb
  app/presenters/two_factor_login_options_presenter.rb
  app/services/account_reset/cancel.rb
  app/services/account_reset_health_checker.rb
  app/services/account_reset_service.rb
  app/services/populate_phone_configurations_table.rb
  app/views/exception_notifier/_session.text.erb
  app/views/two_factor_authentication/options/index.html.slim
  bin/release
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
  config/routes.rb
  config/service_providers.yml
  db/migrate/20180728122856_add_failure_to_proof_url_to_service_provider.rb
  db/schema.rb
  lib/cloudhsm/cloudhsm_key_generator.rb
  lib/cloudhsm/cloudhsm_key_sharer.rb
  lib/tasks/cloudhsm.rake
  lib/tasks/migrate_phone_configurations.rake
  spec/controllers/account_reset/cancel_controller_spec.rb
  spec/controllers/health/health_controller_spec.rb
  spec/decorators/identity_decorator_spec.rb
  spec/features/account_reset/cancel_request_spec.rb
  spec/features/account_reset/delete_account_spec.rb
  spec/features/saml/loa1_sso_spec.rb
  spec/lib/cloudhsm/cloudhsm_key_generator_spec.rb
  spec/lib/cloudhsm/cloudhsm_key_sharer_spec.rb
  spec/models/null_service_provider_spec.rb
  spec/services/account_reset/cancel_spec.rb
  spec/services/account_reset_health_checker_spec.rb
  spec/services/account_reset_service_spec.rb
  spec/services/populate_phone_configurations_table_spec.rb
  spec/support/account_reset_helper.rb
Labels: status - promotion

#2369 Tear down code for phone profile verification
  app/controllers/concerns/idv_session.rb
  app/controllers/concerns/verify_profile_concern.rb
  app/controllers/idv/come_back_later_controller.rb
  app/controllers/idv/usps_controller.rb
  app/controllers/users/verify_profile_phone_controller.rb
  app/decorators/user_decorator.rb
  app/models/profile.rb
  app/services/idv/profile_maker.rb
  app/services/idv/session.rb
  app/view_models/account_show.rb
  app/views/accounts/_pending_profile_phone.html.slim
  config/locales/account/en.yml
  config/locales/account/es.yml
  config/locales/account/fr.yml
  config/routes.rb
  spec/controllers/idv/come_back_later_controller_spec.rb
  spec/controllers/idv/confirmations_controller_spec.rb
  spec/controllers/idv/usps_controller_spec.rb
  spec/controllers/users/sessions_controller_spec.rb
  spec/controllers/users/verify_account_controller_spec.rb
  spec/controllers/users/verify_profile_phone_controller_spec.rb
  spec/decorators/user_decorator_spec.rb
  spec/features/idv/steps/review_step_spec.rb
  spec/features/idv/steps/usps_step_spec.rb
  spec/features/users/verify_profile_spec.rb
  spec/services/idv/profile_maker_spec.rb
  spec/support/idv_examples/usps_otp_verification_step.rb
  spec/view_models/account_show_spec.rb
Labels: status - ready for review

#2338 Ignore old personal key columns
  app/models/user.rb
Labels: status - ready for review

#2428 Deploy RC 64 to staging
  .github/PULL_REQUEST_TEMPLATE.md
  .reek
  .rubocop.yml
  Gemfile.lock
  app/controllers/account_reset/cancel_controller.rb
  app/controllers/account_reset/request_controller.rb
  app/controllers/health/health_controller.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/controllers/users/sessions_controller.rb
  app/decorators/identity_decorator.rb
  app/models/null_service_provider.rb
  app/presenters/two_factor_login_options_presenter.rb
  app/services/account_reset/cancel.rb
  app/services/account_reset_health_checker.rb
  app/services/account_reset_service.rb
  app/services/populate_phone_configurations_table.rb
  app/views/exception_notifier/_session.text.erb
  app/views/two_factor_authentication/options/index.html.slim
  bin/release
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
  config/routes.rb
  config/service_providers.yml
  db/migrate/20180728122856_add_failure_to_proof_url_to_service_provider.rb
  db/schema.rb
  lib/cloudhsm/cloudhsm_key_generator.rb
  lib/cloudhsm/cloudhsm_key_sharer.rb
  lib/tasks/cloudhsm.rake
  lib/tasks/migrate_phone_configurations.rake
  spec/controllers/account_reset/cancel_controller_spec.rb
  spec/controllers/health/health_controller_spec.rb
  spec/decorators/identity_decorator_spec.rb
  spec/features/account_reset/cancel_request_spec.rb
  spec/features/account_reset/delete_account_spec.rb
  spec/features/saml/loa1_sso_spec.rb
  spec/lib/cloudhsm/cloudhsm_key_generator_spec.rb
  spec/lib/cloudhsm/cloudhsm_key_sharer_spec.rb
  spec/models/null_service_provider_spec.rb
  spec/services/account_reset/cancel_spec.rb
  spec/services/account_reset_health_checker_spec.rb
  spec/services/account_reset_service_spec.rb
  spec/services/populate_phone_configurations_table_spec.rb
  spec/support/account_reset_helper.rb
Labels: status - promotion

#2431 Track additional IdV analytics
  app/controllers/idv/cancellations_controller.rb
  app/controllers/idv/come_back_later_controller.rb
  app/controllers/idv/sessions_controller.rb
  app/controllers/users_controller.rb
  app/services/analytics.rb
  app/services/parse_controller_from_referer.rb
  spec/controllers/idv/cancellations_controller_spec.rb
  spec/controllers/idv/come_back_later_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/services/parse_controller_from_referer_spec.rb
Labels: status - ready for review

#2426 LG-554 Fix already authenticated users redirecting to account page
  app/controllers/application_controller.rb
  app/controllers/concerns/two_factor_authenticatable.rb
  spec/features/two_factor_authentication/multiple_tabs_spec.rb
  spec/support/shared_examples/sign_in.rb
Labels: status - ready for review

#2429 [LG-487] piv/cac available based on email domain
  app/models/user.rb
  app/policies/piv_cac_login_option_policy.rb
  config/application.yml.example
  spec/policies/piv_cac_login_option_policy_spec.rb
Labels: status - ready for review

#2435 LG-562 Add a new redirect_uri for logout with the CBP ROAM SP
  config/service_providers.yml
Labels: status - ready for review

#2423 LG-544 Prevent calling unsupported countries
  app/helpers/form_helper.rb
  app/javascript/app/phone-internationalization.js
  app/services/phone_number_capabilities.rb
  app/views/users/phone_setup/index.html.slim
  app/views/users/phones/edit.html.slim
  spec/features/sign_in/two_factor_options_spec.rb
  spec/features/users/sign_in_spec.rb
  spec/features/users/verify_profile_spec.rb
  spec/services/phone_number_capabilities_spec.rb
Labels: status - ready for review

#2439 Deploy RC 64 to prod
  .github/PULL_REQUEST_TEMPLATE.md
  .reek
  .rubocop.yml
  Gemfile.lock
  app/controllers/account_reset/cancel_controller.rb
  app/controllers/account_reset/request_controller.rb
  app/controllers/health/health_controller.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/controllers/users/sessions_controller.rb
  app/decorators/identity_decorator.rb
  app/models/null_service_provider.rb
  app/presenters/two_factor_login_options_presenter.rb
  app/services/account_reset/cancel.rb
  app/services/account_reset_health_checker.rb
  app/services/account_reset_service.rb
  app/services/populate_phone_configurations_table.rb
  app/views/exception_notifier/_session.text.erb
  app/views/two_factor_authentication/options/index.html.slim
  bin/release
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
  config/routes.rb
  config/service_providers.yml
  db/migrate/20180728122856_add_failure_to_proof_url_to_service_provider.rb
  db/schema.rb
  lib/cloudhsm/cloudhsm_key_generator.rb
  lib/cloudhsm/cloudhsm_key_sharer.rb
  lib/tasks/cloudhsm.rake
  lib/tasks/migrate_phone_configurations.rake
  spec/controllers/account_reset/cancel_controller_spec.rb
  spec/controllers/health/health_controller_spec.rb
  spec/decorators/identity_decorator_spec.rb
  spec/features/account_reset/cancel_request_spec.rb
  spec/features/account_reset/delete_account_spec.rb
  spec/features/saml/loa1_sso_spec.rb
  spec/lib/cloudhsm/cloudhsm_key_generator_spec.rb
  spec/lib/cloudhsm/cloudhsm_key_sharer_spec.rb
  spec/models/null_service_provider_spec.rb
  spec/services/account_reset/cancel_spec.rb
  spec/services/account_reset_health_checker_spec.rb
  spec/services/account_reset_service_spec.rb
  spec/services/populate_phone_configurations_table_spec.rb
  spec/support/account_reset_helper.rb
Labels: status - promotion

#2438 LG-559 Allow sign in via remember me after idling
  app/controllers/users/sessions_controller.rb
  spec/controllers/users/sessions_controller_spec.rb
  spec/features/two_factor_authentication/remember_device_spec.rb
  spec/support/shared_examples/remember_device.rb
Labels: status - ready for review

#2380 [LG-423] Redirect piv/cac errors to cleanup url
  app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
  app/controllers/users/piv_cac_authentication_setup_controller.rb
  app/presenters/piv_cac_authentication_setup_error_presenter.rb
  app/views/users/piv_cac_authentication_setup/error.html.slim
  spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb
  spec/controllers/users/piv_cac_authentication_setup_controller_spec.rb
  spec/features/users/piv_cac_management_spec.rb
  spec/presenters/piv_cac_authentication_setup_error_presenter_spec.rb
Labels: status - ready for review

#2440 Add separate OtpDeliveryMethodForm for IdV
  app/controllers/idv/otp_delivery_method_controller.rb
  app/forms/idv/otp_delivery_method_form.rb
  app/forms/idv/phone_form.rb
  app/presenters/idv/otp_delivery_method_presenter.rb
  app/services/analytics.rb
  app/views/idv/otp_delivery_method/new.html.slim
  spec/controllers/idv/otp_delivery_method_controller_spec.rb
  spec/controllers/idv/phone_controller_spec.rb
  spec/forms/idv/otp_delivery_method_form_spec.rb
  spec/presenters/idv/otp_delivery_method_presenter_spec.rb
Labels: status - ready for review

#2258 [LG-256] Add spinner when presenting piv/cac cert
  app/assets/stylesheets/components/_spinner.scss
  app/assets/stylesheets/components/_util.scss
  app/assets/stylesheets/components/all.scss
  app/views/shared/_spinner.html.slim
  app/views/two_factor_authentication/piv_cac_verification/show.html.slim
  app/views/users/piv_cac_authentication_setup/new.html.slim
  config/i18n-tasks.yml
  config/locales/devise/en.yml
  config/locales/devise/es.yml
  config/locales/devise/fr.yml
Labels: status - ready for review

#2446 LG-582 Add a logout redirect uri for the Trusted Traveler Program SP
  config/service_providers.yml
Labels: status - ready for review

#2448 Fix a flickering spec in the OTP rate limiter
  spec/services/otp_rate_limiter_spec.rb
Labels: status - ready for review

#2443 [LG-487] Email based Suggesting scoped by agency
  app/models/identity.rb
  app/policies/piv_cac_login_option_policy.rb
  app/services/piv_cac_service.rb
  spec/models/identity_spec.rb
  spec/policies/piv_cac_login_option_policy_spec.rb
  spec/services/piv_cac_service_spec.rb
Labels: status - ready for review

#2449 Copy phone info to new table sans crypto
  app/services/populate_phone_configurations_table.rb
  spec/services/populate_phone_configurations_table_spec.rb
Labels: status - ready for review

#2447 LG-550 Remove proofer initializer
  .reek
  app/services/idv/proofer.rb
  config/initializers/idv_proofer.rb
  config/initializers/proofer.rb
  spec/services/idv/proofer_spec.rb
Labels: status - ready for review

#2441 [LG-500] Read phone configuration from table
  .gitignore
  app/controllers/concerns/account_recoverable.rb
  app/controllers/concerns/authorizable.rb
  app/controllers/concerns/phone_confirmation.rb
  app/controllers/concerns/two_factor_authenticatable.rb
  app/controllers/idv/confirmations_controller.rb
  app/controllers/two_factor_authentication/otp_verification_controller.rb
  app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
  app/controllers/users/phone_setup_controller.rb
  app/controllers/users/phones_controller.rb
  app/controllers/users/piv_cac_authentication_setup_controller.rb
  app/controllers/users/two_factor_authentication_controller.rb
  app/decorators/user_decorator.rb
  app/forms/idv/phone_form.rb
  app/forms/two_factor_options_form.rb
  app/forms/user_phone_form.rb
  app/models/user.rb
  app/policies/sms_login_option_policy.rb
  app/policies/voice_login_option_policy.rb
  app/services/account_reset/cancel.rb
  app/services/account_reset/create_request.rb
  app/services/otp_delivery_preference_updater.rb
  app/services/remember_device_cookie.rb
  app/views/accounts/show.html.slim
  app/views/exception_notifier/_session.text.erb
  config/environments/test.rb
  spec/controllers/idv/confirmations_controller_spec.rb
  spec/controllers/idv/phone_controller_spec.rb
  spec/controllers/idv/review_controller_spec.rb
  spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
  spec/controllers/users/two_factor_authentication_controller_spec.rb
  spec/factories/users.rb
  spec/features/idv/steps/phone_step_spec.rb
  spec/features/two_factor_authentication/change_factor_spec.rb
  spec/features/two_factor_authentication/sign_in_spec.rb
  spec/features/visitors/phone_confirmation_spec.rb
  spec/forms/idv/phone_form_spec.rb
  spec/forms/user_phone_form_spec.rb
  spec/services/account_reset/cancel_spec.rb
  spec/services/otp_rate_limiter_spec.rb
  spec/services/remember_device_cookie_spec.rb
  spec/support/features/idv_step_helper.rb
  spec/support/features/session_helper.rb
  spec/support/shared_examples_for_phone_validation.rb
  spec/support/sp_auth_helper.rb
  spec/views/two_factor_authentication/totp_verification/show.html.slim_spec.rb
Labels: status - ready for review

#2455 [LG-487] Scope piv/cac push by SP/email
  app/models/service_provider.rb
  app/presenters/two_factor_options_presenter.rb
  config/application.yml.example
  spec/models/service_provider_spec.rb
Labels: status - ready for review

#2465 Int: Fix Idv::Proofer vendor initialization
  app/services/idv/proofer.rb
Labels: status - promotion

#2464 Staging: Fix Idv::Proofer vendor initialization
  app/services/idv/proofer.rb
Labels: status - promotion

#2461 LG-597 Create WebAuthn Configurations Table
  app/models/user.rb
  app/models/webauthn_configuration.rb
  db/migrate/20180827225542_create_webauthn_configurations_table.rb
  db/schema.rb
  spec/models/user_spec.rb
Labels: status - ready for review

#2469 Remove dup webauthn_configurations index creation
  db/migrate/20180827225542_create_webauthn_configurations_table.rb
Labels: status - ready for review

#2474 Deploy RC 65 patch 2 to Int
  app/decorators/service_provider_session_decorator.rb
  app/models/anonymous_user.rb
  app/policies/sms_login_option_policy.rb
  app/views/idv/shared/_failure_to_proof_url.html.slim
  app/views/idv/shared/verification_failure.html.slim
  app/views/shared/_failure.html.slim
  app/views/shared/_failure_url.html.slim
  spec/controllers/account_reset/confirm_request_controller_spec.rb
  spec/decorators/service_provider_session_decorator_spec.rb
Labels: status - promotion

#2477 Catch no method error in formatted phone
  app/forms/user_phone_form.rb
  app/models/phone_configuration.rb
  spec/forms/user_phone_form_spec.rb
Labels: status - ready for review
