Repository 18F/identity-idp, pull requests merged in 2018-05, with the labels that each got.

#2120 LG-209 Delete ahoy_visit cookie after sign out
  app/controllers/application_controller.rb
  app/controllers/openid_connect/authorization_controller.rb
  spec/controllers/application_controller_spec.rb
  spec/controllers/openid_connect/authorization_controller_spec.rb
Labels: status - ready for review

#2127 LG-228 Make migrations safer and more resilient
  Gemfile
  Gemfile.lock
  config/application.yml.example
  config/database.yml
  config/initializers/figaro.rb
  config/initializers/safe_migrations.rb
  deploy/migrate
  lib/deploy/migration_statement_timeout.rb
  spec/spec_helper.rb
Labels: status - ready for review

#2132 Fix flaky `remember_device_spec.rb` example
  spec/support/shared_examples/remember_device.rb
Labels: status - ready for review

#2134 LG-203 Make MFA event properties consistent
  app/controllers/two_factor_authentication/otp_verification_controller.rb
  app/controllers/two_factor_authentication/personal_key_verification_controller.rb
  spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
  spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb
Labels: status - ready for review

#2138 LG-232 Localize password changed event text
  config/locales/event_types/en.yml
  config/locales/event_types/es.yml
  config/locales/event_types/fr.yml
Labels: status - ready for review

#2140 LG-234 Update link to auth app help page
  app/services/marketing_site.rb
  app/views/users/totp_setup/new.html.slim
  spec/services/marketing_site_spec.rb
Labels: status - ready for review

#2130 LG-214 Update `remember device` translations
  README.md
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
Labels: status - ready for review

#2143 LG-238 Use XHR transport mechanism for GA
  app/views/shared/google_analytics/_page_tracking.html.erb
  config/initializers/secure_headers.rb
Labels: status - ready for review

#2145 LG-237 Add Secret Service PIX SP to Production
  app/assets/images/sp-logos/usss_pix.png
  certs/sp/usss_prod.crt
  config/agencies.yml
  config/service_providers.yml
Labels: status - ready for review

#2128 [LG-187] (Dis)associate PIV/CAC with user account
  .rubocop.yml
  app/controllers/test/piv_cac_authentication_test_subject_controller.rb
  app/controllers/users/piv_cac_authentication_setup_controller.rb
  app/decorators/user_decorator.rb
  app/forms/user_piv_cac_setup_form.rb
  app/models/event.rb
  app/models/user.rb
  app/presenters/piv_cac_authentication_setup_presenter.rb
  app/services/analytics.rb
  app/services/piv_cac_service.rb
  app/view_models/account_show.rb
  app/views/accounts/actions/_disable_piv_cac.html.slim
  app/views/accounts/actions/_enable_piv_cac.html.slim
  app/views/accounts/show.html.slim
  app/views/test/piv_cac_authentication_test_subject/new.html.slim
  app/views/users/piv_cac_authentication_setup/error.html.slim
  app/views/users/piv_cac_authentication_setup/new.html.slim
  config/application.yml.example
  config/i18n-tasks.yml
  config/locales/account/en.yml
  config/locales/account/es.yml
  config/locales/account/fr.yml
  config/locales/event_types/en.yml
  config/locales/event_types/es.yml
  config/locales/event_types/fr.yml
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
  config/locales/headings/en.yml
  config/locales/headings/es.yml
  config/locales/headings/fr.yml
  config/locales/notices/en.yml
  config/locales/notices/es.yml
  config/locales/notices/fr.yml
  config/locales/titles/en.yml
  config/locales/titles/es.yml
  config/locales/titles/fr.yml
  config/routes.rb
  lib/feature_management.rb
  spec/controllers/test/piv_cac_authentication_test_subject_controller_spec.rb
  spec/controllers/users/piv_cac_authentication_setup_controller_spec.rb
  spec/forms/user_piv_cac_setup_form_spec.rb
  spec/lib/feature_management_spec.rb
  spec/models/user_spec.rb
  spec/presenters/piv_cac_authentication_setup_presenter_spec.rb
  spec/services/piv_cac_service_spec.rb
Labels: status - ready for review

#2136 LG-229 Add reCAPTCHA to account creation and password reset screens
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/components/_recaptcha.scss
  app/assets/stylesheets/components/all.scss
  app/controllers/concerns/recaptcha_concern.rb
  app/controllers/sign_up/registrations_controller.rb
  app/controllers/users/reset_passwords_controller.rb
  app/forms/password_reset_email_form.rb
  app/forms/register_user_email_form.rb
  app/services/ab_test.rb
  app/views/devise/passwords/new.html.slim
  app/views/shared/_recaptcha.html.slim
  app/views/sign_up/registrations/new.html.slim
  config/application.yml.example
  config/initializers/recaptcha.rb
  config/initializers/secure_headers.rb
  lib/feature_management.rb
  spec/controllers/sign_up/registrations_controller_spec.rb
  spec/controllers/users/reset_passwords_controller_spec.rb
  spec/forms/password_reset_email_form_spec.rb
  spec/forms/register_user_email_form_spec.rb
  spec/lib/feature_management_spec.rb
  spec/services/ab_test_spec.rb
  spec/views/devise/passwords/new.html.slim_spec.rb
  spec/views/sign_up/registrations/new.html.slim_spec.rb
Labels: status - do not merge, status - ready for review

#2150 Update Aamva gem dependency
  Gemfile
  Gemfile.lock
Labels: status - ready for review

#1648 Require raise-if-root gem to stop running as root.
  Gemfile
  Gemfile.lock
Labels: status - ready for review

#2156 Fix scope of present_with method
  spec/presenters/two_factor_auth_code/generic_delivery_presenter_spec.rb
  spec/presenters/two_factor_auth_code/piv_cac_authentication_presenter_spec.rb
Labels: status - ready for review

#2155 LG-246 Create attribute encryptor
  app/models/concerns/encryptable_attribute.rb
  app/services/encrypted_attribute.rb
  app/services/encryption/encryptors/attribute_encryptor.rb
  app/services/encryption/encryptors/user_access_key_encryptor.rb
  app/services/key_rotator/attribute_encryption.rb
  config/application.yml.example
  spec/controllers/users/sessions_controller_spec.rb
  spec/services/encrypted_attribute_spec.rb
  spec/services/encryption/encryptors/attribute_encryptor_spec.rb
  spec/services/encryption/encryptors/user_access_key_encryptor_spec.rb
  spec/services/pii/cacher_spec.rb
  spec/support/key_rotation_helper.rb
Labels: status - ready for review

#2151 LG-243 Disallow indexing of certain pages
  app/views/layouts/application.html.slim
  bin/copy_robots_file
  config/application.yml.example
  config/initializers/figaro.rb
  deploy/build-post-config
  lib/feature_management.rb
  public/ban-robots.txt
  public/robots.txt
  spec/controllers/sign_up/passwords_controller_spec.rb
  spec/controllers/users/reset_passwords_controller_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/lib/feature_management_spec.rb
Labels: status - ready for review

#2158 Make tests compatible with zeus
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: status - ready for review

#2161 Update initialization of Idv::Proofer@vendors
  .reek
  app/services/idv/agent.rb
  app/services/idv/proofer.rb
  app/services/idv/vendor_result.rb
  config/initializers/proofer.rb
  spec/services/idv/agent_spec.rb
Labels: status - ready for review

#2164 LG-246 Add session encryptor
  app/services/encryption/encryptors/session_encryptor.rb
  app/services/session_encryptor.rb
  app/services/usps_confirmation_entry.rb
  spec/services/encryption/encryptors/session_encryptor_spec.rb
  spec/services/session_encryptor_spec.rb
Labels: status - ready for review

#2165 LG-273 Sanitize Ahoy headers and cookies
  config/initializers/ahoy.rb
  lib/rack_request_parser.rb
  lib/utf8_cleaner.rb
  lib/utf8_sanitizer.rb
  spec/config/initializers/ahoy_spec.rb
  spec/requests/invalid_encoding_spec.rb
Labels: status - ready for review

#2166 LG-246 Remove password encryptor
  app/services/pii/password_encryptor.rb
  spec/services/pii/nist_encryption_spec.rb
  spec/services/pii/password_encryptor_spec.rb
Labels: status - ready for review

#2152 Lg 248 state id screen
  app/assets/images/state-id-none@3x.png
  app/controllers/idv/jurisdiction_controller.rb
  app/controllers/idv/sessions_controller.rb
  app/controllers/idv_controller.rb
  app/forms/idv/jurisdiction_form.rb
  app/helpers/form_helper.rb
  app/services/analytics.rb
  app/validators/idv/form_jurisdiction_validator.rb
  app/validators/idv/form_state_id_validator.rb
  app/view_models/idv/sessions_new.rb
  app/views/idv/index.html.slim
  app/views/idv/jurisdiction/new.html.slim
  app/views/idv/jurisdiction/show.html.slim
  app/views/idv/sessions/new.html.slim
  app/views/shared/_cancel.html.slim
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
  config/routes.rb
  spec/controllers/idv/jurisdiction_controller_spec.rb
  spec/features/flows/sp_authentication_flows_spec.rb
  spec/features/idv/steps/jurisdiction_step_spec.rb
  spec/features/idv/steps/verify_step_spec.rb
  spec/features/saml/loa3_sso_spec.rb
  spec/features/users/password_recovery_via_recovery_code_spec.rb
  spec/features/users/user_profile_spec.rb
  spec/forms/idv/jurisdiction_form_spec.rb
  spec/presenters/two_factor_auth_code/phone_delivery_presenter_spec.rb
  spec/support/features/idv_helper.rb
  spec/support/features/idv_step_helper.rb
  spec/support/idv_examples/cancel_at_idv_step.rb
  spec/support/idv_examples/max_attempts.rb
  spec/support/idv_examples/sp_handoff.rb
  spec/support/idv_examples/sp_requested_attributes.rb
  spec/support/sp_auth_helper.rb
Labels: status - ready for review

#2167 LG-274 Remove ascii vendor_params
  app/services/idv/session.rb
  spec/controllers/idv/review_controller_spec.rb
Labels: status - ready for review

#2168 LG-275 Remove unused financial idv params
  app/services/idv/proofer.rb
  spec/features/flows/sp_authentication_flows_spec.rb
  spec/views/idv/review/new.html.slim_spec.rb
Labels: status - ready for review

#2080 Add script to automate release management
  bin/release
Labels: status - ready for review

#2173 Update gems with bummr
  Gemfile.lock
  package.json
  yarn.lock
Labels: status - ready for review

#2172 Add proofing info to analytics
  app/services/idv/profile_step.rb
  spec/controllers/idv/sessions_controller_spec.rb
  spec/services/idv/profile_step_spec.rb
Labels: status - ready for review

#2178 Update proofer and aamva gems
  Gemfile
  Gemfile.lock
  app/services/idv/proofer.rb
  config/initializers/proofer.rb
  spec/services/idv/proofer_spec.rb
Labels: status - ready for review

#2180 Add a column for password digest w/o length req
  db/migrate/20180518153201_add_password_digest_to_user.rb
  db/schema.rb
Labels: status - ready for review

#2179 Populate state with prior value after idv failure
  app/helpers/form_helper.rb
  app/views/idv/jurisdiction/show.html.slim
  app/views/idv/sessions/new.html.slim
  spec/features/idv/steps/jurisdiction_step_spec.rb
  spec/features/idv/steps/profile_step_spec.rb
  spec/support/features/idv_helper.rb
Labels: status - ready for review

#2185 Rename password_digest encrypted_password_digest
  db/migrate/20180521155700_change_password_digest_to_encrypted_password_digest.rb
  db/schema.rb
Labels: status - ready for review

#2171 Don't check worker health if we have no workers.
  app/controllers/health/health_controller.rb
  app/services/multi_health_checker.rb
  spec/controllers/health/health_controller_spec.rb
Labels: status - ready for review

#2176 Update rspec-rails and xmlenc
  Gemfile
  Gemfile.lock
Labels: status - ready for review

#2187 Move strong_migrations out of development group
  Gemfile
Labels: status - ready for review

#2188 Only try to return a link to piv/cac if enabled
  app/presenters/two_factor_auth_code/generic_delivery_presenter.rb
  spec/presenters/two_factor_auth_code/generic_delivery_presenter_spec.rb
Labels: status - ready for review, type - bug

#2191 LG-285 Implement 2L-KMS (hotdog encryption)
  app/services/encryption/encryptors/pii_encryptor.rb
  app/services/pii/cipher.rb
  spec/controllers/users/sessions_controller_spec.rb
  spec/services/encryption/encryptors/pii_encryptor_spec.rb
Labels: status - ready for review

#2192 LG-286 Write encryption inputs to `encrypted_password_digest
  .reek
  app/models/concerns/user_access_key_overrides.rb
  spec/models/user_spec.rb
Labels: status - ready for review

#2193 LG-302 update jurisdiction screen
  app/assets/stylesheets/components/_jurisdiction.scss
  app/assets/stylesheets/components/all.scss
  app/views/idv/jurisdiction/new.html.slim
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
Labels: status - ready for review

#2194 LG-306 Update to match current designs
  app/helpers/application_helper.rb
  config/locales/links/en.yml
  config/locales/links/es.yml
  config/locales/links/fr.yml
  spec/features/flows/sp_authentication_flows_spec.rb
  spec/support/idv_examples/cancel_at_idv_step.rb
Labels: status - ready for review

#2199 Upgrade file encryptor to work with gpg2
  app/services/file_encryptor.rb
Labels: status - ready for review

#2198 LG-249 Add LexisNexis gem
  Gemfile
  Gemfile.lock
  app/services/idv/proofer.rb
  config/application.yml.example
  spec/services/idv/proofer_spec.rb
Labels: status - ready for review

#2197 [LG 240] piv/cac is only for certain agencies
  app/decorators/user_decorator.rb
  app/models/identity.rb
  app/models/user.rb
  app/services/piv_cac_service.rb
  app/views/accounts/show.html.slim
  config/application.yml.example
  spec/features/users/piv_cac_management_spec.rb
  spec/models/identity_spec.rb
  spec/models/user_spec.rb
Labels: status - ready for review

#2200 LG 303 add idv verified screen
  app/assets/images/state-id-confirm@3x.png
  app/controllers/idv/sessions_controller.rb
  app/views/idv/sessions/success.html.slim
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
  config/routes.rb
  spec/controllers/idv/sessions_controller_spec.rb
  spec/features/accessibility/idv_pages_spec.rb
  spec/features/idv/previous_address_spec.rb
  spec/features/idv/state_id_data_spec.rb
  spec/features/idv/steps/profile_step_spec.rb
  spec/features/saml/loa3_sso_spec.rb
  spec/features/two_factor_authentication/remember_device_spec.rb
  spec/support/features/idv_helper.rb
  spec/support/features/idv_step_helper.rb
  spec/support/idv_examples/fail_to_verify.rb
  spec/support/idv_examples/max_attempts.rb
  spec/support/sp_auth_helper.rb
Labels: status - ready for review

#2205 LG-305 Updated screen per design
  app/views/idv/phone/new.html.slim
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
Labels: status - ready for review

#2207 Add proofer information to result and analytics
  app/services/idv/phone_step.rb
  lib/proofer_mocks/address_mock.rb
  spec/controllers/idv/phone_controller_spec.rb
  spec/services/idv/phone_step_spec.rb
Labels: status - ready for review

#2148 [LG-190] share certificate subject with SPs
  .reek
  .rubocop.yml
  app/controllers/concerns/piv_cac_concern.rb
  app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
  app/controllers/users/piv_cac_authentication_setup_controller.rb
  app/models/identity.rb
  app/presenters/openid_connect_user_info_presenter.rb
  app/services/openid_connect_attribute_scoper.rb
  app/services/reactivate_account_session.rb
  app/services/x509/attribute.rb
  app/services/x509/attributes.rb
  app/services/x509/session_store.rb
  spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb
  spec/controllers/users/piv_cac_authentication_setup_controller_spec.rb
  spec/presenters/openid_connect_user_info_presenter_spec.rb
  spec/services/x509/attribute_spec.rb
  spec/services/x509/attributes_spec.rb
  spec/services/x509/session_store_spec.rb
Labels: status - ready for review

#2206 LG 304 idv phone confirmation screen
  app/controllers/idv/address_controller.rb
  app/controllers/idv/review_controller.rb
  app/forms/idv/address_delivery_method_form.rb
  app/services/analytics.rb
  app/views/idv/address/index.html.slim
  app/views/idv/sessions/success.html.slim
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
  config/routes.rb
  spec/controllers/idv/address_controller_spec.rb
  spec/controllers/idv/review_controller_spec.rb
  spec/features/accessibility/idv_pages_spec.rb
  spec/features/flows/sp_authentication_flows_spec.rb
  spec/features/idv/steps/address_step_spec.rb
  spec/features/idv/steps/phone_step_spec.rb
  spec/features/idv/steps/profile_step_spec.rb
  spec/features/saml/loa3_sso_spec.rb
  spec/features/two_factor_authentication/remember_device_spec.rb
  spec/forms/idv/address_delivery_method_form_spec.rb
  spec/support/features/idv_helper.rb
  spec/support/features/idv_step_helper.rb
  spec/support/idv_examples/fail_to_verify.rb
  spec/support/idv_examples/max_attempts.rb
  spec/support/sp_auth_helper.rb
Labels: status - ready for review
