Repository 18F/identity-idp, pull requests merged in 2019-07, with the labels that each got.

#3059 LG-1470, 1472, 1473 Log user uuid with OIDC token call
  app/forms/openid_connect_token_form.rb
  spec/controllers/openid_connect/token_controller_spec.rb
  spec/forms/openid_connect_token_form_spec.rb
Labels: status - ready for review

#3054 Do not show TOTP success message if it is the first MFA method
  app/controllers/users/totp_setup_controller.rb
  spec/controllers/users/totp_setup_controller_spec.rb
  spec/features/totp/setup_success_message_spec.rb
Labels: status - ready for review

#3058 Update node modules and gems
  Gemfile.lock
  yarn.lock
Labels: status - ready for review

#3060 Fix French translation for "Email addresses"
  config/locales/account/fr.yml
Labels: status - ready for review

#3046 Adds NLRB my account sp configuration
  app/assets/images/sp-logos/nlrb.png
  certs/sp/nlrb_prod.crt
  config/agencies.yml
  config/service_providers.yml
Labels: status - ready for review, type - config

#3063 LG-1498 Fix OIDC prompt=login automatic sign out after sign in
  app/controllers/application_controller.rb
  app/controllers/concerns/secure_headers_concern.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/controllers/sign_up/completions_controller.rb
Labels: status - ready for review

#3064 LG-1499 Update email address column after delete
  app/forms/delete_user_email_form.rb
  db/schema.rb
  spec/features/multiple_emails/email_management_spec.rb
Labels: status - ready for review

#3061 LG-1424 Allow user to disavow new phone event
  app/controllers/concerns/two_factor_authenticatable.rb
  app/mailers/user_mailer.rb
  app/models/event.rb
  app/views/user_mailer/phone_added.html.slim
  config/locales/event_types/en.yml
  config/locales/event_types/es.yml
  config/locales/event_types/fr.yml
  config/locales/user_mailer/en.yml
  config/locales/user_mailer/es.yml
  config/locales/user_mailer/fr.yml
  spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
  spec/features/event_disavowal_spec.rb
  spec/features/two_factor_authentication/change_factor_spec.rb
  spec/features/users/add_phone_spec.rb
  spec/mailers/user_mailer_spec.rb
Labels: status - ready for review

#3071 Adds eCBP SP configuration
  config/service_providers.yml
Labels: status - ready for review, type - config

#3073 LG-1418 Remove visual remnants when you can no longer add emails
  app/views/accounts/_emails.html.slim
Labels: status - ready for review

#3076 Adds BETA SAM service provider config
  certs/sp/beta_sam_prod.crt
  config/service_providers.yml
Labels: status - ready for review, type - config

#3072 start of sprint has moved to tuesdays
  lib/github_metrics/sprint.rb
Labels: status - ready for review

#3070 LG-1192 Clearer account deletion emails
  app/mailers/user_mailer.rb
  app/views/layouts/user_mailer.html.slim
  app/views/user_mailer/account_reset_request.html.slim
  config/locales/user_mailer/en.yml
  config/locales/user_mailer/es.yml
  config/locales/user_mailer/fr.yml
  spec/mailers/user_mailer_spec.rb
Labels: status - ready for review

#3075 LG-1383 Send emails for error conditions in add email
  app/mailers/user_mailer.rb
  app/services/send_add_email_confirmation.rb
  app/views/user_mailer/add_email_associated_with_another_account.html.slim
  config/locales/user_mailer/en.yml
  config/locales/user_mailer/es.yml
  config/locales/user_mailer/fr.yml
  spec/features/multiple_emails/add_email_spec.rb
Labels: status - ready for review

#3044 LG-1330 generate backup codes on post
  app/controllers/saml_idp_controller.rb
  app/controllers/two_factor_authentication/backup_code_verification_controller.rb
  app/controllers/users/backup_code_setup_controller.rb
  app/controllers/users/two_factor_authentication_controller.rb
  app/policies/two_factor_authentication/backup_code_policy.rb
  app/presenters/backup_code_create_presenter.rb
  app/presenters/backup_code_depleted_presenter.rb
  app/presenters/two_factor_options_presenter.rb
  app/services/first_mfa_enabled_for_user.rb
  app/view_models/account_show.rb
  app/views/accounts/_backup_codes.html.erb
  app/views/accounts/actions/_generate_backup_codes.html.erb
  app/views/accounts/show.html.erb
  app/views/users/backup_code_setup/create.html.slim
  app/views/users/backup_code_setup/depleted.html.erb
  app/views/users/backup_code_setup/edit.html.slim
  app/views/users/backup_code_setup/index.html.erb
  config/application.yml.default
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
  config/routes.rb
  lib/feature_management.rb
  spec/features/account/backup_codes_spec.rb
  spec/features/backup_mfa/bypass_backup_mfa_spec.rb
  spec/features/remember_device/revocation_spec.rb
  spec/features/two_factor_authentication/backup_code_sign_up_spec.rb
  spec/lib/feature_management_spec.rb
  spec/policies/backup_code_policy_spec.rb
  spec/presenters/backup_code_create_presenter_spec.rb
  spec/presenters/backup_code_depleted_presenter_spec.rb
  spec/presenters/two_factor_options_presenter_spec.rb
  spec/support/features/session_helper.rb
  spec/support/shared_examples/remember_device.rb
Labels: needs code review, status - ready for review

#3083 Upgrade rubocop to 0.72.0
  .codeclimate.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/helpers/session_timeout_warning_helper.rb
  app/services/idv/acuant/assure_id.rb
  app/services/remember_device_cookie.rb
  config/initializers/rack_attack.rb
  config/initializers/secure_headers.rb
  lib/tasks/dev.rake
  spec/controllers/concerns/idv_step_concern_spec.rb
  spec/controllers/idv/otp_delivery_method_controller_spec.rb
  spec/controllers/idv/resend_otp_controller_spec.rb
  spec/controllers/openid_connect/authorization_controller_spec.rb
  spec/features/idv/doc_auth/send_link_step_spec.rb
  spec/support/features/doc_auth_helper.rb
Labels: status - ready for review

#3081 Move logic to send password reset email off of the user model
  app/mailers/custom_devise_mailer.rb
  app/mailers/user_mailer.rb
  app/models/user.rb
  app/services/request_password_reset.rb
  app/views/devise/mailer/reset_password_instructions.html.slim
  app/views/user_mailer/please_reset_password.html.slim
  app/views/user_mailer/reset_password_instructions.html.slim
  config/initializers/devise.rb
  config/initializers/new_relic_tracers.rb
  config/locales/devise/en.yml
  config/locales/devise/es.yml
  config/locales/devise/fr.yml
  config/locales/mailer/en.yml
  config/locales/mailer/es.yml
  config/locales/mailer/fr.yml
  config/locales/user_mailer/en.yml
  config/locales/user_mailer/es.yml
  config/locales/user_mailer/fr.yml
  config/routes.rb
  spec/controllers/users/reset_passwords_controller_spec.rb
  spec/features/multiple_emails/reset_password_spec.rb
  spec/features/visitors/password_recovery_spec.rb
  spec/services/request_password_reset_spec.rb
Labels: status - ready for review

#3056 LG-1461 When the user's jurisdiction is not supported the back button should take the user to select a new one
  app/controllers/idv/jurisdiction_controller.rb
  spec/features/idv/state_id_data_spec.rb
  spec/features/idv/steps/jurisdiction_step_spec.rb
Labels: status - ready for review

#3086 LG-1331 Add algorithms to webauthn
  app/javascript/app/webauthn.js
  config/initializers/webauthn.rb
  spec/javascripts/app/webauthn_spec.js
Labels: status - ready for review

#3084 LG-1419 Improve add email message when email associated w/another account
  config/locales/devise/en.yml
  config/locales/devise/es.yml
  config/locales/devise/fr.yml
Labels: status - ready for review

#3085 LG-1445 Messaging for users about to delete an email
  app/views/users/emails/confirm_delete.html.slim
  config/locales/email_addresses/en.yml
  config/locales/email_addresses/es.yml
  config/locales/email_addresses/fr.yml
Labels: status - ready for review

#3087 Fix rubocop incovation in Makefile
  Makefile
Labels: status - ready for review

#3088 Remove the pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: status - ready for review

#3074 LG-422 Prevent create account using passwords from known breaches
  app/services/binary_search_sorted_hash_file.rb
  app/services/pwned_passwords/lookup_password.rb
  app/validators/form_password_validator.rb
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
  spec/features/visitors/set_password_spec.rb
  spec/fixtures/pwned_passwords.txt
  spec/services/pwned_passwords/lookup_password_spec.rb
Labels: status - ready for review

#3092 LG-1269 removed english from fr.yml, LG-1484 changed confusing terminology with authentication methods & LG-1493 changed FAKE to TEST or DEMO on non-production sites
  config/locales/account_reset/en.yml
  config/locales/errors/fr.yml
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
  config/locales/instructions/en.yml
  config/locales/recover/en.yml
  config/locales/shared/en.yml
  config/locales/shared/es.yml
  config/locales/shared/fr.yml
  config/locales/two_factor_authentication/en.yml
  spec/views/layouts/application.html.slim_spec.rb
Labels: status - ready for review

#3079 prevent modification of request_id
  app/forms/register_user_email_form.rb
  config/locales/sign_up/en.yml
  config/locales/sign_up/es.yml
  config/locales/sign_up/fr.yml
  spec/factories/service_provider_requests.rb
  spec/forms/register_user_email_form_spec.rb
Labels: status - ready for review

#3069 LG-1458 Fix logic to show sign up completed page
  app/controllers/application_controller.rb
  app/controllers/concerns/verify_sp_attributes_concern.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/controllers/saml_idp_controller.rb
  app/controllers/sign_up/completions_controller.rb
  app/controllers/sign_up/personal_keys_controller.rb
  app/views/sign_up/completions/_show_identities.html.slim
  spec/controllers/sign_up/completions_controller_spec.rb
Labels: status - ready for review

#3093 Add tests for the add email confirmation token validator
  app/services/add_email_confirm_token_validator.rb
  spec/services/add_email_confirm_token_validator_spec.rb
Labels: status - ready for review

#3089 Remove old code that enabled changing email addresses
  app/controllers/concerns/unconfirmed_user_concern.rb
  app/controllers/sign_up/email_confirmations_controller.rb
  app/controllers/sign_up/passwords_controller.rb
  app/mailers/user_mailer.rb
  app/services/email_confirmation_token_validator.rb
  app/views/user_mailer/email_changed.html.slim
  config/initializers/devise.rb
  config/locales/mailer/en.yml
  config/locales/mailer/es.yml
  config/locales/mailer/fr.yml
  config/locales/user_mailer/en.yml
  config/locales/user_mailer/es.yml
  config/locales/user_mailer/fr.yml
  spec/controllers/sign_up/email_confirmations_controller_spec.rb
  spec/controllers/sign_up/passwords_controller_spec.rb
  spec/mailers/user_mailer_spec.rb
  spec/services/email_confirmation_token_validator_spec.rb
  spec/views/layouts/user_mailer.html.slim_spec.rb
Labels: status - ready for review

#3095 Add a method tracer to the hash file search
  config/initializers/new_relic_tracers.rb
Labels: status - ready for review

#3097 LG-1412 Explain invalid token on add email confirmation
  app/controllers/users/email_confirmations_controller.rb
  spec/features/multiple_emails/add_email_spec.rb
Labels: status - ready for review

#3096 LG-1549 Phone setup enter OTP cancel behavior
  app/views/two_factor_authentication/otp_verification/show.html.slim
  spec/features/two_factor_authentication/sign_in_spec.rb
  spec/views/two_factor_authentication/otp_verification/show.html.slim_spec.rb
Labels: status - ready for review

#3099 LG-1536 Add step indicator to "Check your email" screen
  app/views/sign_up/emails/show.html.slim
Labels: status - ready for review

#3098 LG-1553 Remove regenerate backup codes for user
  app/views/users/backup_code_setup/create.html.slim
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
Labels: status - ready for review

#3101 Trace encryptor methods
  config/initializers/new_relic_tracers.rb
  spec/services/encryption/encryptors/pii_encryptor_spec.rb
Labels: status - ready for review

#3102 Update gems and npm packages
  .babelrc
  Gemfile.lock
  app/javascript/app/webauthn.js
  app/javascript/packs/intl-tel-input.js
  babel.config.js
  package.json
  spec/javascripts/app/utils/events_spec.js
  yarn.lock
Labels: status - ready for review

#3100 LG-1550 Conditionally ask account reset users for personal key
  app/views/account_reset/request/show.html.slim
  config/locales/account_reset/en.yml
  config/locales/account_reset/es.yml
  config/locales/account_reset/fr.yml
  spec/views/account_reset/request/show.html.slim_spec.rb
Labels: status - ready for review

#3105 LG-720 Update copy on confirmation email
  config/locales/user_mailer/en.yml
  config/locales/user_mailer/es.yml
  config/locales/user_mailer/fr.yml
Labels: status - ready for review

#3103 LG-1549 converted the slim into an erb
  app/presenters/idv/otp_verification_presenter.rb
  app/presenters/two_factor_auth_code/phone_delivery_presenter.rb
  app/views/two_factor_authentication/otp_verification/show.html.erb
  app/views/two_factor_authentication/otp_verification/show.html.slim
  config/locales/instructions/en.yml
  config/locales/instructions/es.yml
  config/locales/instructions/fr.yml
  spec/features/backup_mfa/otp_delivery_selection_spec.rb
  spec/features/users/default_phone_selection_spec.rb
  spec/presenters/two_factor_auth_code/phone_delivery_presenter_spec.rb
  spec/views/two_factor_authentication/otp_verification/show.html.slim_spec.rb
Labels: status - ready for review

#3104 LG-1201 fixed english wording and added translations for accuant throttling message
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
Labels: status - ready for review

#3082 LG-1421 Standardize success confirmation during 2FA setup
  app/controllers/application_controller.rb
  app/controllers/concerns/two_factor_authenticatable.rb
  app/controllers/two_factor_authentication/personal_key_verification_controller.rb
  app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
  app/controllers/users/piv_cac_authentication_setup_controller.rb
  app/controllers/users/totp_setup_controller.rb
  app/controllers/users/two_factor_authentication_setup_controller.rb
  app/controllers/users/webauthn_setup_controller.rb
  app/policies/personal_key_for_new_user_policy.rb
  app/presenters/two_factor_options_presenter.rb
  app/views/users/two_factor_authentication_setup/index.html.erb
  app/views/users/two_factor_authentication_setup/success.html.erb
  app/views/users/webauthn_setup/success.html.slim
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
  config/locales/headings/en.yml
  config/locales/headings/es.yml
  config/locales/headings/fr.yml
  config/locales/titles/en.yml
  config/locales/titles/es.yml
  config/locales/titles/fr.yml
  config/routes.rb
  spec/controllers/users/totp_setup_controller_spec.rb
  spec/features/backup_mfa/bypass_backup_mfa_spec.rb
  spec/features/backup_mfa/no_duplicate_phone_numbers_spec.rb
  spec/features/backup_mfa/otp_delivery_selection_spec.rb
  spec/features/backup_mfa/second_phone_spec.rb
  spec/features/backup_mfa/sign_up_spec.rb
  spec/features/mfa_enrollability_spec.rb
  spec/features/phone/confirmation_spec.rb
  spec/features/phone/rate_limitting_spec.rb
  spec/features/remember_device/phone_spec.rb
  spec/features/remember_device/sp_expiration_spec.rb
  spec/features/remember_device/totp_spec.rb
  spec/features/remember_device/webauthn_spec.rb
  spec/features/totp/setup_success_message_spec.rb
  spec/features/two_factor_authentication/backup_code_sign_up_spec.rb
  spec/features/users/sign_up_spec.rb
  spec/features/users/sign_up_success_screen_spec.rb
  spec/features/webauthn/management_spec.rb
  spec/features/webauthn/sign_up_spec.rb
  spec/policies/personal_key_for_new_user_policy_spec.rb
  spec/support/features/session_helper.rb
  spec/support/shared_examples/account_creation.rb
  spec/support/shared_examples/phone/otp_confirmation.rb
  spec/support/shared_examples/sign_in.rb
  spec/support/shared_examples/webauthn_setup.rb
  spec/support/sp_auth_helper.rb
Labels: status - ready for review

#3108 LG-1486 Add timeout for post to google analytics on backend
  app/services/google_analytics_measurement.rb
  config/application.yml.default
  spec/services/google_analytics_measurement_spec.rb
Labels: status - ready for review

#3107 Use the AddEmailConfirmTokenValidator to validate that an email has not been confirmed yet
  app/controllers/users/email_confirmations_controller.rb
  app/services/add_email_confirm_token_validator.rb
  spec/services/add_email_confirm_token_validator_spec.rb
Labels: status - ready for review

#2815 [LG-919] Allow authentication with a PIV/CAC
  app/controllers/concerns/ial2_profile_concern.rb
  app/controllers/concerns/piv_cac_concern.rb
  app/controllers/concerns/two_factor_authenticatable.rb
  app/controllers/concerns/two_factor_authenticatable_methods.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/controllers/password_capture_controller.rb
  app/controllers/test/piv_cac_authentication_test_subject_controller.rb
  app/controllers/users/piv_cac_login_controller.rb
  app/controllers/users/sessions_controller.rb
  app/forms/concerns/piv_cac_form_helpers.rb
  app/forms/user_piv_cac_login_form.rb
  app/forms/user_piv_cac_setup_form.rb
  app/forms/user_piv_cac_verification_form.rb
  app/presenters/piv_cac_authentication_login_presenter.rb
  app/services/analytics.rb
  app/view_models/account_show.rb
  app/views/accounts/_pii_locked.html.slim
  app/views/devise/sessions/new.html.slim
  app/views/password_capture/new.html.slim
  app/views/users/piv_cac_login/error.html.slim
  app/views/users/piv_cac_login/new.html.slim
  config/application.yml.default
  config/i18n-tasks.yml
  config/locales/account/en.yml
  config/locales/account/es.yml
  config/locales/account/fr.yml
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
  config/locales/headings/en.yml
  config/locales/headings/es.yml
  config/locales/headings/fr.yml
  config/locales/titles/en.yml
  config/locales/titles/es.yml
  config/locales/titles/fr.yml
  config/routes.rb
  lib/feature_management.rb
  spec/controllers/accounts_controller_spec.rb
  spec/controllers/openid_connect/authorization_controller_spec.rb
  spec/features/sign_in/two_factor_options_spec.rb
  spec/features/users/sign_in_spec.rb
  spec/support/features/session_helper.rb
  spec/support/shared_examples/sign_in.rb
  spec/views/devise/sessions/new.html.slim_spec.rb
Labels: status - ready for review

#3113 Add ability to show deprecation warnings when using email attributes
  app/models/concerns/deprecated_user_attributes.rb
  app/models/user.rb
  config/application.yml.default
Labels: status - ready for review

#3109 Use email address table to confirm email during sign up
  app/controllers/concerns/unconfirmed_user_concern.rb
  app/controllers/users/email_confirmations_controller.rb
  app/services/add_email_confirm_token_validator.rb
  app/services/email_confirmation_token_validator.rb
  app/services/send_sign_up_email_confirmation.rb
  app/views/sign_up/emails/show.html.slim
  app/views/users/emails/verify.html.slim
  spec/controllers/sign_up/email_confirmations_controller_spec.rb
  spec/decorators/user_decorator_spec.rb
  spec/factories/email_addresses.rb
  spec/factories/users.rb
  spec/services/add_email_confirm_token_validator_spec.rb
  spec/services/email_confirmation_token_validator_spec.rb
  spec/services/send_sign_up_email_confirmation_spec.rb
Labels: status - ready for review

#3114 Update sign in with piv cac copy
  app/views/devise/sessions/new.html.slim
Labels: status - ready for review

#3116 Remove pwned password feature flag and configs
  .circleci/config.yml
  .gitignore
  app/services/pwned_passwords/lookup_password.rb
  app/validators/form_password_validator.rb
  bin/setup
  pwned_passwords/pwned_passwords.txt.sample
  spec/features/visitors/set_password_spec.rb
  spec/services/pwned_passwords/lookup_password_spec.rb
Labels: status - ready for review

#3119 Fix pwned passwords path
  lib/deploy/activate.rb
Labels: status - ready for review

#3120 Fix pwned password s3 path
  lib/deploy/activate.rb
Labels: status - ready for review

#3122 LG-1639 Fix copy for account creation email
  config/locales/user_mailer/en.yml
  config/locales/user_mailer/es.yml
  config/locales/user_mailer/fr.yml
Labels: status - ready for review

#3111 Remove RegiserUserEmailForm from views that deal with resending email
  app/controllers/sign_up/email_resend_controller.rb
  app/controllers/sign_up/emails_controller.rb
  app/controllers/users/emails_controller.rb
  app/forms/register_user_email_form.rb
  app/forms/resend_email_confirmation_form.rb
  app/models/email_address.rb
  app/views/sign_up/email_resend/new.html.slim
  app/views/sign_up/emails/show.html.slim
  spec/forms/resend_email_confirmation_form_spec.rb
  spec/models/email_address_spec.rb
  spec/views/sign_up/emails/show.html.slim_spec.rb
Labels: status - ready for review

#3123 Fix flickering push notification spec
  spec/features/account_reset/delete_account_spec.rb
  spec/features/users/user_profile_spec.rb
  spec/services/push_notification/account_delete_spec.rb
  spec/support/features/push_notifications_helper.rb
Labels: status - ready for review

#3121 LG-1551 OMB Fitara stats on sign ups
  app/controllers/concerns/two_factor_authenticatable_methods.rb
  app/controllers/sign_up/email_confirmations_controller.rb
  app/controllers/sign_up/passwords_controller.rb
  app/controllers/sign_up/registrations_controller.rb
  app/controllers/users/backup_code_setup_controller.rb
  app/controllers/users/piv_cac_authentication_setup_controller.rb
  app/controllers/users/totp_setup_controller.rb
  app/controllers/users/webauthn_setup_controller.rb
  app/models/registration_log.rb
  app/models/user.rb
  app/services/funnel/registration/add_mfa.rb
  app/services/funnel/registration/add_password.rb
  app/services/funnel/registration/confirm_email.rb
  app/services/funnel/registration/create.rb
  app/services/funnel/registration/range_registered_count.rb
  app/services/funnel/registration/range_submitted_count.rb
  app/services/funnel/registration/total_registered_count.rb
  app/services/funnel/registration/total_submitted_count.rb
  app/services/reports/omb_fitara_report.rb
  config/initializers/job_configurations.rb
  db/migrate/20190720132736_create_registration_logs.rb
  db/schema.rb
  spec/config/initializers/job_configurations.rb
  spec/features/reports/omb_fitara_report_spec.rb
  spec/features/visitors/sign_up_with_email_spec.rb
  spec/services/funnel/registration/add_mfa_spec.rb
  spec/services/funnel/registration/add_password_spec.rb
  spec/services/funnel/registration/confirm_email_spec.rb
  spec/services/funnel/registration/range_registered_count_spec.rb
  spec/services/funnel/registration/range_submitted_count_spec.rb
  spec/services/funnel/registration/total_registered_count_spec.rb
  spec/services/funnel/registration/total_submitted_count_spec.rb
  spec/support/features/session_helper.rb
Labels: status - ready for review

#3125 LG-1637 Start supporting the JOIN keyword for inbound SMS responses
  app/services/twilio_service/sms/response.rb
  spec/services/twilio_service/sms/response_spec.rb
Labels: status - ready for review

#3126 LG-1638 Change the text for the HELP and STOP messages
  config/locales/sms/en.yml
  config/locales/sms/es.yml
  config/locales/sms/fr.yml
Labels: status - ready for review

#3118 LG-1537 Redesign check your email screen
  app/assets/stylesheets/components/_icon.scss
  app/controllers/users/webauthn_setup_controller.rb
  app/view_models/forgot_password_show.rb
  app/views/account_reset/confirm_request/show.html.erb
  app/views/account_reset/confirm_request/show.html.slim
  app/views/forgot_password/show.html.erb
  app/views/forgot_password/show.html.slim
  app/views/idv/usps/index.html.erb
  app/views/idv/usps/index.html.slim
  app/views/sign_up/emails/show.html.erb
  app/views/sign_up/emails/show.html.slim
  app/views/users/emails/verify.html.erb
  app/views/users/emails/verify.html.slim
  config/brakeman.ignore
  config/initializers/devise.rb
  config/locales/account_reset/en.yml
  config/locales/account_reset/es.yml
  config/locales/account_reset/fr.yml
  spec/controllers/sign_up/email_confirmations_controller_spec.rb
  spec/controllers/sign_up/passwords_controller_spec.rb
  spec/features/account_reset/delete_account_spec.rb
  spec/features/webauthn/sign_up_spec.rb
  spec/services/email_confirmation_token_validator_spec.rb
  spec/views/account_reset/confirm_request/show.html.erb_spec.rb
  spec/views/forgot_password/show.html.slim_erb.rb
  spec/views/idv/usps/index.html.slim_erb.rb
  spec/views/sign_up/emails/show.html.erb_spec.rb
Labels: status - ready for review

#3127 LG-1614 Add new titles for MFA setup option menus
  app/presenters/two_factor_options_presenter.rb
  app/views/users/two_factor_authentication_setup/index.html.erb
  config/i18n-tasks.yml
  config/locales/two_factor_authentication/en.yml
  config/locales/two_factor_authentication/es.yml
  config/locales/two_factor_authentication/fr.yml
Labels: status - ready for review

#3128 Cleanup rubocop violations
  app/controllers/two_factor_authentication/personal_key_verification_controller.rb
  app/models/concerns/deprecated_user_attributes.rb
  app/validators/form_password_validator.rb
  config/initializers/webauthn.rb
  spec/controllers/sign_up/passwords_controller_spec.rb
  spec/features/backup_mfa/sign_up_spec.rb
  spec/support/shared_examples/sign_in.rb
Labels: status - ready for review

#3131 Fix OMB Fitara report background job
  config/initializers/job_configurations.rb
  spec/config/initializers/job_configurations.rb
Labels: status - ready for review

#3129 Remove the phone setup presenter
  app/controllers/users/phone_setup_controller.rb
  app/controllers/users/phones_controller.rb
  app/presenters/phone_setup_presenter.rb
  app/views/users/phone_setup/index.html.erb
  app/views/users/shared/_phone_form.html.erb
  spec/controllers/users/phone_setup_controller_spec.rb
  spec/views/phone_setup/index.html.slim_spec.rb
  spec/views/users/phones/edit.html.slim_spec.rb
Labels: status - ready for review

#3130 LG-1633 Add fee disclosure to phone setup and add phone
  app/views/users/phone_setup/index.html.erb
  app/views/users/phones/add.html.erb
  config/locales/two_factor_authentication/en.yml
  config/locales/two_factor_authentication/es.yml
  config/locales/two_factor_authentication/fr.yml
Labels: status - ready for review

#3132 Make the email attribute in the factories transient
  spec/controllers/account_reset/recover_controller_spec.rb
  spec/controllers/account_reset/request_controller_spec.rb
  spec/factories/users.rb
  spec/features/multiple_emails/email_management_spec.rb
  spec/forms/delete_user_email_form_spec.rb
  spec/forms/reset_password_form_spec.rb
  spec/forms/update_user_password_form_spec.rb
  spec/mailers/user_mailer_spec.rb
  spec/models/user_spec.rb
  spec/presenters/openid_connect_user_info_presenter_spec.rb
  spec/services/id_token_builder_spec.rb
  spec/services/request_password_reset_spec.rb
  spec/support/shared_examples/password_strength.rb
  spec/views/accounts/show.html.erb_spec.rb
Labels: status - ready for review

#3133 Drop uniqueness constraint on user email fingerprint
  db/migrate/20190725211433_drop_email_fingerprint_index.rb
  db/schema.rb
Labels: status - ready for review

#3134 LG-1193 Improve error copy on SMS error pages
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
Labels: status - ready for review

#3137 Adds Touchpoints SP configuration
  certs/sp/touchpoints_prod.crt
  config/service_providers.yml
Labels: status - ready for review, type - config

#3138 LG-1653 New setup flow for backup codes
  app/controllers/application_controller.rb
  app/controllers/concerns/two_factor_authenticatable_methods.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/controllers/two_factor_authentication/otp_verification_controller.rb
  app/controllers/two_factor_authentication/personal_key_verification_controller.rb
  app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
  app/controllers/users/piv_cac_authentication_setup_controller.rb
  app/controllers/users/totp_setup_controller.rb
  app/controllers/users/two_factor_authentication_setup_controller.rb
  app/controllers/users_controller.rb
  app/models/backup_code_configuration.rb
  app/policies/mfa_policy.rb
  app/presenters/two_factor_authentication/backup_code_selection_presenter.rb
  app/presenters/two_factor_options_presenter.rb
  app/views/shared/_cancel_or_back_to_options.html.erb
  config/locales/two_factor_authentication/en.yml
  config/locales/two_factor_authentication/es.yml
  config/locales/two_factor_authentication/fr.yml
  spec/features/mfa_enrollability_spec.rb
  spec/features/two_factor_authentication/backup_code_sign_up_spec.rb
Labels: status - ready for review

#3136 LG-1622 Fix backup codes copy button output on IE
  app/views/users/backup_code_setup/create.html.slim
Labels: status - ready for review

#3135 LG-1621 Fix Backup codes download on IE
  app/controllers/users/backup_code_setup_controller.rb
  spec/controllers/users/backup_code_setup_controller_spec.rb
Labels: status - ready for review

#3139 LG-1652 Redesign backup codes warning page
  app/views/users/backup_code_setup/index.html.erb
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
  spec/features/two_factor_authentication/sign_in_spec.rb
Labels: status - ready for review

#3140 LG-1615 Redesign backup codes screen
  app/assets/stylesheets/components/_icon.scss
  app/views/users/backup_code_setup/create.html.slim
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
  spec/features/remember_device/revocation_spec.rb
  spec/features/two_factor_authentication/backup_code_sign_up_spec.rb
Labels: status - ready for review

#3144 Fix remember browser for first MFA
  app/controllers/concerns/remember_device_concern.rb
  app/controllers/users/backup_code_setup_controller.rb
  app/controllers/users/piv_cac_authentication_setup_controller.rb
  app/controllers/users/totp_setup_controller.rb
  app/controllers/users/webauthn_setup_controller.rb
  app/forms/two_factor_authentication/phone_deletion_form.rb
  app/forms/user_phone_form.rb
  app/forms/user_piv_cac_setup_form.rb
  spec/features/remember_device/totp_spec.rb
  spec/features/remember_device/webauthn_spec.rb
Labels: status - ready for review

#3146 LG-1661 Fix copy on sign in selection list with backup codes
  app/presenters/two_factor_authentication/backup_code_selection_presenter.rb
  config/locales/two_factor_authentication/en.yml
  config/locales/two_factor_authentication/es.yml
  config/locales/two_factor_authentication/fr.yml
  spec/features/two_factor_authentication/backup_code_sign_up_spec.rb
Labels: status - ready for review

#3149 LG-1422: add a logout redirect to the oidc-sinatra sample sp
  config/service_providers.yml
Labels: status - ready for review

#3124 LG-1410: validate service providers via the identity-validations gem
  Gemfile
  Gemfile.lock
  app/models/null_service_provider.rb
  app/models/service_provider.rb
  app/services/service_provider_seeder.rb
  certs/sp/saml_test_invalid_sp.crt
  config/service_providers.yml
  spec/features/saml/saml_spec.rb
  spec/models/identity_spec.rb
  spec/models/null_service_provider_spec.rb
  spec/models/service_provider_spec.rb
  spec/services/service_provider_updater_spec.rb
  spec/services/usps_confirmation_exporter_spec.rb
Labels: status - ready for review

#3150 LG-1558 Add password strength meter to password error screen
  app/controllers/sign_up/passwords_controller.rb
Labels: status - ready for review

#3152 Update copy for sign in with PIV/CAC
  config/locales/account/en.yml
  config/locales/account/es.yml
  config/locales/account/fr.yml
Labels: status - ready for review

#3151 Add a feature flag to disable USPS upload in an environment
  app/services/usps_confirmation_uploader.rb
  config/application.yml.default
  lib/feature_management.rb
  spec/services/usps_confirmation_uploader_spec.rb
Labels: status - ready for review

#3143 LG-1646 CAC Proofing Flow
  app/controllers/idv/cac_controller.rb
  app/services/analytics.rb
  app/services/idv/flows/cac_flow.rb
  app/services/idv/steps/cac/enter_info_step.rb
  app/services/idv/steps/cac/present_cac_step.rb
  app/services/idv/steps/cac/success_step.rb
  app/services/idv/steps/cac/verify_step.rb
  app/services/idv/steps/cac/welcome_step.rb
  app/views/idv/cac/_start_over_or_cancel.html.slim
  app/views/idv/cac/enter_info.html.erb
  app/views/idv/cac/present_cac.html.erb
  app/views/idv/cac/success.html.slim
  app/views/idv/cac/verify.html.slim
  app/views/idv/cac/welcome.html.slim
  config/locales/cac_proofing/en.yml
  config/locales/cac_proofing/es.yml
  config/locales/cac_proofing/fr.yml
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
  config/routes.rb
  spec/features/idv/cac/enter_info_step_spec.rb
  spec/features/idv/cac/present_cac_step_spec.rb
  spec/features/idv/cac/success_step_spec.rb
  spec/features/idv/cac/verify_step_spec.rb
  spec/features/idv/cac/welcome_step_spec.rb
  spec/support/features/cac_proofing_helper.rb
Labels: status - ready for review
