Repository 18F/identity-idp, pull requests merged in 2019-02, with the labels that each got.

#2730 Enable configuration for multiple SAML endpoints
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  app/controllers/concerns/saml_idp_auth_concern.rb
  app/controllers/saml_idp_controller.rb
  app/services/saml_cert_rotation_manager.rb
  app/services/saml_endpoint.rb
  bin/setup
  certs/samlcloudhsm.crt.example
  config/application.yml.example
  config/initializers/figaro.rb
  config/initializers/saml_idp.rb
  config/routes.rb
  lib/saml_idp_encryption_configurator.rb
  spec/features/openid_connect/openid_connect_spec.rb
  spec/features/saml/idp_initiated_slo_spec.rb
  spec/features/saml/multiple_endpoints_spec.rb
  spec/features/saml/saml_spec.rb
  spec/lib/cloudhsm_jwt_spec.rb
  spec/lib/saml_idp_encryption_configurator_spec.rb
  spec/services/saml_endpoint_manager.rb
  spec/support/cloudhsm_mocks.rb
Labels: status - ready for review

#2732 Remove one-off rake tasks
  app/services/link_agency_identities.rb
  app/services/populate_email_addresses_table.rb
  app/services/remember_device_revoked_at_migrator.rb
  bin/link_agency_identities
  lib/tasks/agency_based_uuids.rake
  lib/tasks/migrate_email_addresses.rake
  lib/tasks/migrate_remember_me_revoked_at.rake
  lib/tasks/readonly_database_user.rake
  spec/services/link_agency_identities_spec.rb
  spec/services/populate_email_addresses_table_spec.rb
  spec/services/remember_device_revoked_at_migrator_spec.rb
Labels: status - ready for review

#2720 LG-794 Audit devices, IP addresses Users are Authenticating With
  Gemfile
  Gemfile.lock
  app/controllers/accounts_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/two_factor_authenticatable.rb
  app/controllers/events_controller.rb
  app/controllers/users/backup_code_setup_controller.rb
  app/controllers/users/personal_keys_controller.rb
  app/controllers/users/piv_cac_authentication_setup_controller.rb
  app/controllers/users/sessions_controller.rb
  app/decorators/device_decorator.rb
  app/decorators/event_decorator.rb
  app/decorators/user_decorator.rb
  app/models/device.rb
  app/models/event.rb
  app/models/user.rb
  app/presenters/login_presenter.rb
  app/services/analytics.rb
  app/services/device_tracking/create_device.rb
  app/services/device_tracking/device_name.rb
  app/services/device_tracking/list_device_events.rb
  app/services/device_tracking/list_devices.rb
  app/services/device_tracking/lookup_device_for_user.rb
  app/services/device_tracking/update_device.rb
  app/view_models/account_show.rb
  app/views/accounts/_current_sign_in.html.slim
  app/views/accounts/_device_item.html.slim
  app/views/accounts/_event_item.html.slim
  app/views/accounts/_last_sign_in.html.slim
  app/views/accounts/events/show.html.slim
  app/views/accounts/show.html.slim
  config/locales/account/en.yml
  config/locales/account/es.yml
  config/locales/account/fr.yml
  config/locales/event_types/en.yml
  config/locales/event_types/es.yml
  config/locales/event_types/fr.yml
  config/locales/headings/en.yml
  config/locales/headings/es.yml
  config/locales/headings/fr.yml
  config/routes.rb
  db/migrate/20190111231134_create_devices.rb
  db/schema.rb
  spec/controllers/application_controller_spec.rb
  spec/controllers/users/personal_keys_controller_spec.rb
  spec/controllers/users/webauthn_setup_controller_spec.rb
  spec/factories/devices.rb
  spec/features/account/device_spec.rb
  spec/features/device_tracking_spec.rb
  spec/models/device_spec.rb
  spec/presenters/idv/usps_presenter_spec.rb
  spec/services/device_tracking/create_device_spec.rb
  spec/services/device_tracking/device_name_spec.rb
  spec/services/device_tracking/list_device_events_spec.rb
  spec/services/device_tracking/list_devices_spec.rb
  spec/services/device_tracking/lookup_device_for_user_spec.rb
  spec/services/device_tracking/update_device_spec.rb
  spec/services/idv/usps_mail_spec.rb
  spec/views/accounts/show.html.slim_spec.rb
Labels: status - ready for review

#2737 Fix copy/paste issue with cert in setup scrpit
  bin/setup
Labels: status - ready for review

#2738 Use factories in device tracking tests
  app/models/event.rb
  spec/factories/devices.rb
  spec/factories/events.rb
  spec/features/account/device_spec.rb
  spec/features/device_tracking_spec.rb
  spec/presenters/idv/usps_presenter_spec.rb
  spec/services/device_tracking/list_device_events_spec.rb
  spec/services/device_tracking/list_devices_spec.rb
  spec/services/device_tracking/lookup_device_for_user_spec.rb
Labels: status - ready for review

#2736 Use CloudHSM helpers in OIDC specs
  spec/features/openid_connect/openid_connect_spec.rb
  spec/lib/cloudhsm_jwt_spec.rb
  spec/support/cloudhsm_mocks.rb
Labels: status - ready for review

#2739 Update gems and npm packages
  Gemfile.lock
  yarn.lock
Labels: status - ready for review

#2740 Use upstream session store
  Gemfile
  Gemfile.lock
Labels: status - ready for review

#2742 LG-947 New DOT LMS service provider to production
  certs/sp/dot_lms_prod.crt
  config/service_providers.yml
Labels: status - ready for review, status - required for release

#2744 Give readonly db user access to schemas after migration
  deploy/migrate
  lib/tasks/db_grant_readonly_access.rake
Labels: status - ready for review

#2748 Remove enabled_identity_verification feature flag
  config/application.yml.example
  config/initializers/figaro.rb
  config/routes.rb
  lib/feature_management.rb
  spec/lib/feature_management_spec.rb
  spec/routing/id_verification_routing_spec.rb
  spec/routing/usps_verification_routing.rb
Labels: status - ready for review

#2753 Remove webauthn_enabled feature flag
  app/models/webauthn_configuration.rb
  app/policies/two_factor_authentication/webauthn_policy.rb
  config/application.yml.example
  config/routes.rb
  lib/feature_management.rb
  spec/controllers/two_factor_authentication/options_controller_spec.rb
  spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb
  spec/lib/feature_management_spec.rb
  spec/models/webauthn_configuration_spec.rb
Labels: status - ready for review

#2752 Remove password metrics model
  app/controllers/sign_up/passwords_controller.rb
  app/forms/reset_password_form.rb
  app/forms/update_user_password_form.rb
  app/models/password_metric.rb
  app/services/password_metrics_incrementer.rb
  spec/controllers/sign_up/passwords_controller_spec.rb
  spec/controllers/users/reset_passwords_controller_spec.rb
  spec/forms/update_user_password_form_spec.rb
  spec/models/password_metric_spec.rb
  spec/services/password_metrics_incrementer_spec.rb
Labels: status - ready for review

#2724 [LG-872] Present confirmed phones when proofing
  app/assets/stylesheets/components/_form.scss
  app/controllers/idv/phone_controller.rb
  app/forms/idv/phone_form.rb
  app/javascript/app/form-validation.js
  app/javascript/app/radio-btn.js
  app/services/idv/phone_step.rb
  app/views/idv/phone/new.html.slim
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
  spec/features/idv/steps/phone_step_spec.rb
  spec/forms/idv/phone_form_spec.rb
Labels: status - ready for review

#2756 Fix doc auth unauthenticated 500 errors
  app/controllers/idv/doc_auth_controller.rb
  spec/controllers/idv/doc_auth_controller_spec.rb
Labels: status - ready for review

#2751 Remove platform_authenticator_analytics_enabled flag
  app/views/layouts/base.html.slim
  app/views/shared/_platform_authenticator.slim
  config/application.yml.example
  lib/feature_management.rb
  spec/features/saml/loa1_sso_spec.rb
  spec/features/two_factor_authentication/sign_in_spec.rb
  spec/features/users/password_recovery_via_recovery_code_spec.rb
  spec/features/users/sign_in_spec.rb
  spec/lib/feature_management_spec.rb
Labels: status - ready for review

#2755 Enable acuant simulator in local development
  config/application.yml.example
Labels: status - ready for review

#2747 Remove account_reset_enabled? feature flag
  app/controllers/account_reset/cancel_controller.rb
  app/controllers/account_reset/delete_account_controller.rb
  app/controllers/account_reset/request_controller.rb
  app/presenters/two_factor_auth_code/phone_delivery_presenter.rb
  config/application.yml.example
  lib/feature_management.rb
  spec/controllers/account_reset/cancel_controller_spec.rb
  spec/controllers/account_reset/delete_account_controller_spec.rb
  spec/controllers/account_reset/request_controller_spec.rb
  spec/lib/feature_management_spec.rb
Labels: status - ready for review

#2734 Add encryption context to KMS calls
  app/models/profile.rb
  app/services/encryption/contextless_kms_client.rb
  app/services/encryption/encryptors/pii_encryptor.rb
  app/services/encryption/encryptors/session_encryptor.rb
  app/services/encryption/kms_client.rb
  app/services/encryption/user_access_key.rb
  app/services/pii/attributes.rb
  config/application.yml.example
  config/initializers/new_relic_tracers.rb
  lib/feature_management.rb
  lib/tasks/add_context_to_pii_bundles.rake
  spec/models/profile_spec.rb
  spec/services/encryption/contextless_kms_client_spec.rb
  spec/services/encryption/encryptors/pii_encryptor_spec.rb
  spec/services/encryption/encryptors/session_encryptor_spec.rb
  spec/services/encryption/kms_client_spec.rb
  spec/services/pii/attributes_spec.rb
Labels: status - ready for review

#2735 Use 2L-KMS method to encrypt passwords
  app/models/concerns/user_access_key_overrides.rb
  app/services/encryption/password_verifier.rb
  app/services/encryption/uak_password_verifier.rb
  config/application.yml.example
  lib/feature_management.rb
  spec/features/legacy_passwords_spec.rb
  spec/services/encryption/password_verifier_spec.rb
  spec/services/encryption/uak_password_verifier_spec.rb
  spec/services/pii/nist_encryption_spec.rb
Labels: status - ready for review

#2746 Remove encryption examples from docs
  docs/encryption-examples.md
Labels: status - ready for review

#2762 Remove rubocop file exclusions
  .rubocop.yml
  app/controllers/application_controller.rb
  app/controllers/concerns/saml_idp_auth_concern.rb
  app/controllers/concerns/two_factor_authenticatable.rb
  app/controllers/users/sessions_controller.rb
  app/controllers/users/two_factor_authentication_controller.rb
  app/decorators/service_provider_session_decorator.rb
  app/decorators/user_decorator.rb
  app/forms/openid_connect_token_form.rb
  app/services/analytics.rb
  app/services/idv/session.rb
  app/view_models/account_show.rb
  config/initializers/active_job_logger_patch.rb
  config/initializers/secure_headers.rb
  lib/cloudhsm/cloudhsm_key_generator.rb
  lib/i18n_override.rb
  lib/lambdas/account_reset_lambda.rb
  spec/support/saml_response_doc.rb
Labels: status - ready for review

#2761 Regenerate the knapsack report
  knapsack_rspec_report.json
Labels: status - ready for review

#2766 Remove stale password digest rotation
  app/models/concerns/user_access_key_overrides.rb
  spec/features/idv/uak_password_spec.rb
  spec/features/legacy_passwords_spec.rb
Labels: status - ready for review

#2765 Adds BETA Sam.gov logo
  app/assets/images/sp-logos/beta-sam.png
Labels: status - ready for review

#2764 LG-881 Use physical mail address for proofing
  app/controllers/idv/address_controller.rb
  app/forms/idv/address_form.rb
  app/forms/idv/ssn_format_form.rb
  app/services/analytics.rb
  app/services/flow/base_step.rb
  app/services/idv/actions/redo_ssn_action.rb
  app/services/idv/flows/doc_auth_flow.rb
  app/services/idv/steps/doc_failed_step.rb
  app/services/idv/steps/ssn_step.rb
  app/services/idv/steps/verify_step.rb
  app/validators/idv/form_address_validator.rb
  app/validators/idv/form_ssn_format_validator.rb
  app/views/idv/address/new.html.slim
  app/views/idv/doc_auth/doc_failed.html.slim
  app/views/idv/doc_auth/verify.html.slim
  config/locales/doc_auth/en.yml
  config/locales/doc_auth/es.yml
  config/locales/doc_auth/fr.yml
  config/routes.rb
  spec/features/idv/doc_auth/address_step_spec.rb
  spec/features/idv/doc_auth/doc_failed_step_spec.rb
  spec/features/idv/doc_auth/doc_success_step_spec.rb
  spec/features/idv/doc_auth/ssn_step_spec.rb
  spec/features/idv/doc_auth/verify_step_spec.rb
  spec/forms/idv/ssn_format_form_spec.rb
  spec/support/features/doc_auth_helper.rb
Labels: status - ready for review

#2767 Remove code that selects inline or async AJ adapter
  config/application.rb
  config/application.yml.example
  lib/queue_config.rb
  lib/random_tools.rb
  spec/lib/queue_config_spec.rb
  spec/lib/random_tools_spec.rb
Labels: status - ready for review

#2770 Coerce the device id param into an integer
  app/controllers/events_controller.rb
Labels: status - ready for review

#2773 Render a 404 when a device is not found
  app/controllers/events_controller.rb
  spec/features/device_tracking_spec.rb
Labels: status - ready for review

#2774 Remove custom render call on events/show
  app/controllers/events_controller.rb
  app/views/events/show.html.slim
Labels: status - ready for review

#2771 Deploy RC 77.1 to staging
  app/controllers/events_controller.rb
  app/views/events/show.html.slim
  spec/features/device_tracking_spec.rb
Labels: status - promotion

#2772 Deploy RC 77.1 to prod
  app/controllers/events_controller.rb
  app/views/events/show.html.slim
  spec/features/device_tracking_spec.rb
Labels: status - ready for review

#2759 Fix issue where PIV/CAC redirects to the account page
  app/controllers/test/piv_cac_authentication_test_subject_controller.rb
  app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
  app/decorators/mfa_context.rb
  app/models/anonymous_user.rb
  app/policies/mfa_policy.rb
  spec/decorators/mfa_context_spec.rb
  spec/factories/backup_code_configurations.rb
  spec/features/users/sign_in_spec.rb
  spec/support/shared_examples/sign_in.rb
Labels: status - ready for review

#2763 Remove code that overrides i18n behavior
  Gemfile
  Gemfile.lock
  app/javascript/packs/i18n-mode.js
  app/views/layouts/base.html.slim
  app/views/shared/_i18n_mode.html.slim
  config/application.yml.example
  config/initializers/i18n_mode.rb
  config/initializers/saml_idp.rb
  lib/feature_management.rb
  lib/i18n_converter.rb
  lib/i18n_override.rb
  scripts/i18n-csv-to-yml
  scripts/i18n-md-to-xml
  scripts/i18n-xml-to-md
  scripts/i18n-xml-to-yml
  scripts/i18n-yml-to-xml
  spec/lib/feature_management_spec.rb
  spec/lib/i18n_converter_spec.rb
  spec/lib/i18n_override_spec.rb
  spec/views/layouts/application.html.slim_spec.rb
Labels: status - ready for review

#2768 Remove the AWS SES region pool
  config/application.yml.example
  lib/aws/ses.rb
  spec/lib/aws/ses_spec.rb
Labels: status - ready for review

#2757 LG-479 Add a rake tast to reset user passwords
  app/mailers/user_mailer.rb
  app/services/reset_password_and_notify_user.rb
  app/views/user_mailer/please_reset_password.html.slim
  config/locales/user_mailer/en.yml
  config/locales/user_mailer/es.yml
  config/locales/user_mailer/fr.yml
  lib/tasks/reset_user_passwords.rake
  spec/mailers/user_mailer_spec.rb
  spec/services/reset_password_and_notify_user_spec.rb
Labels: status - ready for review

#2778 Upgrade gems and npm packages
  Gemfile.lock
  yarn.lock
Labels: status - ready for review

#2776 Change SSN error in IdV flow
  app/controllers/idv/sessions_controller.rb
  app/presenters/idv/ssn_failure_presenter.rb
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
  spec/controllers/idv/sessions_controller_spec.rb
  spec/features/idv/steps/profile_step_spec.rb
  spec/presenters/idv/ssn_failure_presenter_spec.rb
Labels: status - ready for review

#2777 Cleanup 404 rendering around events controller
  app/controllers/events_controller.rb
  config/routes.rb
Labels: status - ready for review

#2780 New USAID DIS service provider to production
  certs/sp/usaid_prod.crt
  config/agencies.yml
  config/service_providers.yml
Labels: status - ready for review, status - required for release

#2775 LG-882 Invalid physical mail address
  app/controllers/concerns/verify_profile_concern.rb
  app/controllers/idv/doc_auth_controller.rb
  app/controllers/idv/usps_controller.rb
  app/decorators/user_decorator.rb
  app/presenters/idv/usps_presenter.rb
  app/services/analytics.rb
  app/services/flow/base_flow.rb
  app/services/flow/base_step.rb
  app/services/flow/flow_state_machine.rb
  app/services/idv/flows/doc_auth_flow.rb
  app/services/idv/steps/doc_auth_base_step.rb
  app/services/idv/steps/doc_failed_step.rb
  app/services/idv/steps/verify_step.rb
  app/view_models/account_show.rb
  app/views/accounts/_pending_profile_bounced_usps.html.slim
  app/views/idv/doc_auth/doc_failed.html.slim
  app/views/idv/usps/_address_on_file.html.slim
  app/views/idv/usps/_new_address.html.slim
  app/views/idv/usps/index.html.slim
  app/views/user_mailer/undeliverable_address.slim
  config/locales/account/en.yml
  config/locales/account/es.yml
  config/locales/account/fr.yml
  config/locales/doc_auth/en.yml
  config/locales/doc_auth/es.yml
  config/locales/doc_auth/fr.yml
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
  config/locales/user_mailer/en.yml
  config/locales/user_mailer/es.yml
  config/locales/user_mailer/fr.yml
  config/routes.rb
  spec/features/idv/doc_auth/doc_failed_step_spec.rb
  spec/features/idv/doc_auth/verify_step_spec.rb
  spec/features/saml/loa3_sso_spec.rb
  spec/support/controller_helper.rb
  spec/support/features/doc_auth_helper.rb
  spec/views/idv/usps/index.html.slim_spec.rb
Labels: status - ready for review, status - required for release

#2784 New DOL Apprenticeship.gov service provider to production
  certs/sp/dol_apprentice_prod.crt
  config/service_providers.yml
Labels: status - ready for review, status - required for release

#2783 Move duplicate SSN check into profile step
  app/controllers/idv/sessions_controller.rb
  app/services/idv/duplicate_ssn_finder.rb
  app/services/idv/profile_step.rb
  app/validators/idv/form_profile_validator.rb
  spec/controllers/idv/sessions_controller_spec.rb
  spec/forms/idv/profile_form_spec.rb
  spec/services/idv/duplitcate_ssn_finder_spec.rb
  spec/services/idv/profile_step_spec.rb
Labels: status - ready for review

#2779 Remove old unused gems from the the Gemfile
  Gemfile
  Gemfile.lock
Labels: status - ready for review

#2785 Log KMS actions to a KMS log file
  app/services/encryption/contextless_kms_client.rb
  app/services/encryption/kms_client.rb
  app/services/encryption/kms_logger.rb
  spec/services/encryption/contextless_kms_client_spec.rb
  spec/services/encryption/kms_client_spec.rb
  spec/services/encryption/kms_logger_spec.rb
Labels: status - ready for review

#2788 Re-add maxminddb back to the Gemfile
  Gemfile
  Gemfile.lock
Labels: status - ready for review

#2789 Deploy RC 77.1 to staging
  Gemfile
  Gemfile.lock
Labels: status - ready for review

#2787 Add encryption contexts to session KMS events
  app/services/encryption/encryptors/session_encryptor.rb
  config/application.yml.example
  lib/feature_management.rb
  spec/services/encryption/encryptors/session_encryptor_spec.rb
Labels: status - ready for review

#2782 LG-883 Address verification letter reminders and expiration notifications
  app/controllers/expired_letters_controller.rb
  app/controllers/idv/usps_controller.rb
  app/mailers/user_mailer.rb
  app/services/analytics.rb
  app/services/send_expired_letter_notifications.rb
  app/services/undeliverable_address_notifier.rb
  app/views/user_mailer/letter_expired.html.slim
  app/views/user_mailer/letter_reminder.html.slim
  config/application.yml.example
  config/locales/user_mailer/en.yml
  config/locales/user_mailer/es.yml
  config/locales/user_mailer/fr.yml
  config/routes.rb
  db/migrate/20190225005651_add_expired_to_usps_confirmation_codes.rb
  db/schema.rb
  spec/controllers/expired_letters_controller_spec.rb
  spec/mailers/user_mailer_spec.rb
  spec/services/send_expired_letter_notifications_spec.rb
Labels: status - ready for review

#2791 Add the post logout redirect URI for the OIDC SP
  config/service_providers.yml
Labels: status - ready for review
