Repository 18F/identity-idp, pull requests merged in 2019-10, with the labels that each got.

#3311 Set twilio_verify_override_for_intl_sms false
  config/application.yml.default
Labels: status - ready for review

#3313 LG-1964 Confirming email then entering password redirects to sign in
  app/services/send_sign_up_email_confirmation.rb
  spec/features/users/sign_up_spec.rb
  spec/services/send_sign_up_email_confirmation_spec.rb
Labels: status - ready for review

#3296 Adds DOI FedTalent configuration
  app/assets/images/sp-logos/doi.svg
  certs/sp/doi_talent_prod.crt
  config/service_providers.yml
Labels: status - ready for review, type - config

#3325 fix redirect from doc auth to idv when browser back clicked
  app/services/flow/flow_state_machine.rb
  spec/features/idv/doc_auth/finished_spec.rb
  spec/support/features/doc_auth_helper.rb
Labels: status - ready for review

#3324 Update gems
  Gemfile.lock
Labels: status - ready for review

#3315 LG-1930 Log redirect to SP bounce
  app/controllers/openid_connect/authorization_controller.rb
  app/controllers/users/sp_handoff_bounced_controller.rb
  app/services/analytics.rb
  app/services/sp_handoff_bounce/add_handoff_time_to_session.rb
  app/services/sp_handoff_bounce/is_bounced.rb
  app/views/devise/sessions/bounced.html.slim
  config/application.yml.default
  config/locales/headings/en.yml
  config/locales/headings/es.yml
  config/locales/headings/fr.yml
  config/locales/instructions/en.yml
  config/locales/instructions/es.yml
  config/locales/instructions/fr.yml
  config/routes.rb
  spec/features/openid_connect/openid_connect_spec.rb
  spec/features/users/sign_in_spec.rb
  spec/support/saml_auth_helper.rb
Labels: status - ready for review

#3332 LG-2058 Fix 500 error when unauthenticated on IAL2 password screen
  app/controllers/idv/review_controller.rb
  spec/features/idv/steps/review_step_spec.rb
Labels: status - ready for review

#3331 LG-2062 Fix erroneous error counts reported in doc auth funnel
  app/services/analytics.rb
  app/services/funnel/doc_auth/register_step_from_analytics_submit_event.rb
  app/services/funnel/doc_auth/register_step_from_analytics_view_event.rb
Labels: status - ready for review

#3333 LG-2059 Fix 500 error verifying images in doc auth
  app/services/idv/steps/doc_auth_base_step.rb
  app/views/idv/doc_auth/_error_messages.html.slim
  config/locales/errors/en.yml
  spec/features/idv/doc_auth/back_image_step_spec.rb
  spec/features/idv/doc_auth/front_image_step_spec.rb
  spec/features/idv/doc_auth/link_sent_step_spec.rb
  spec/features/idv/doc_auth/mobile_back_image_step_spec.rb
  spec/features/idv/doc_auth/mobile_front_image_step_spec.rb
  spec/features/idv/doc_auth/test_credentials_spec.rb
  spec/features/idv/doc_capture/mobile_back_image_step_spec.rb
  spec/features/idv/doc_capture/mobile_front_image_step_spec.rb
  spec/features/idv/recovery/back_image_step_spec.rb
  spec/features/idv/recovery/front_image_step_spec.rb
  spec/features/idv/recovery/recover_step_spec.rb
  spec/support/features/doc_auth_helper.rb
Labels: status - ready for review

#3335 Hide doc auth error and info after new image selected
  app/javascript/packs/image-preview.js
Labels: status - ready for review

#3345 LG-2116 Add missing hybrid flow steps to doc auth funnel analytics
  app/services/funnel/doc_auth/register_step.rb
  db/migrate/20191015123431_add_hybrid_steps_to_doc_auth_logs.rb
  db/schema.rb
  spec/features/reports/doc_auth_funnel_report_spec.rb
Labels: status - ready for review

#3342 Update NGA NOME cert
  certs/sp/nome_prod.crt
  config/service_providers.yml
Labels: status - ready for review

#3346 Deploy RC 94.1 to staging
  app/services/funnel/doc_auth/register_step.rb
  certs/sp/nome_prod.crt
  config/service_providers.yml
  db/migrate/20191015123431_add_hybrid_steps_to_doc_auth_logs.rb
  db/schema.rb
  spec/features/reports/doc_auth_funnel_report_spec.rb
  spec/forms/openid_connect_authorize_form_spec.rb
  spec/services/push_notification/account_delete_spec.rb
Labels: status - promotion

#3347 Deploy RC 94.1 to produciton
  app/services/funnel/doc_auth/register_step.rb
  certs/sp/nome_prod.crt
  config/service_providers.yml
  db/migrate/20191015123431_add_hybrid_steps_to_doc_auth_logs.rb
  db/schema.rb
  spec/features/reports/doc_auth_funnel_report_spec.rb
Labels: status - promotion

#3344 LG-915 LG-1928 Fix Sign In With PIV/CAC 500 errors
  app/controllers/users/piv_cac_login_controller.rb
  app/views/test/piv_cac_authentication_test_subject/new.html.slim
  app/views/users/piv_cac_login/temporary_error.html.slim
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
  config/locales/headings/en.yml
  config/locales/headings/es.yml
  config/locales/headings/fr.yml
  config/locales/instructions/en.yml
  config/locales/instructions/es.yml
  config/locales/instructions/fr.yml
  config/locales/titles/en.yml
  config/locales/titles/es.yml
  config/locales/titles/fr.yml
  config/routes.rb
  spec/features/users/sign_in_spec.rb
  spec/support/features/session_helper.rb
Labels: status - ready for review

#3343 Add `DOL - CIO - Case Management Platform` SP
  certs/sp/dol_ocio_cmp_prod.crt
  config/service_providers.yml
Labels: status - ready for review

#3348 LG-2123 Update AAMVA gem to 3.2.4
  Gemfile
  Gemfile.lock
Labels: status - ready for review

#3323 Cleanup application.yml
  Gemfile
  Gemfile.lock
  config/application.yml.default
  config/initializers/figaro.rb
  spec/features/two_factor_authentication/sign_in_spec.rb
  spec/lib/aws/ses_spec.rb
  spec/services/encryption/encryptors/attribute_encryptor_spec.rb
  spec/support/key_rotation_helper.rb
Labels: status - do not merge, status - ready for review

#3350 LG-1957 Remove decorative image alt tags
  app/views/account_reset/recover/email_sent.html.slim
  app/views/idv/cac/success.html.slim
  app/views/idv/capture_doc/capture_complete.html.slim
  app/views/idv/come_back_later/show.html.slim
  app/views/idv/doc_auth/_back_of_state_id_image.slim
  app/views/idv/doc_auth/_front_of_state_id_image.slim
  app/views/idv/doc_auth/doc_success.html.slim
  app/views/idv/doc_auth/email_sent.html.slim
  app/views/idv/doc_auth/recover.html.slim
  app/views/idv/doc_auth/recover_fail.html.slim
  app/views/idv/in_person/bar_code.html.slim
  app/views/idv/jurisdiction/new.html.erb
  app/views/idv/sessions/success.html.slim
  app/views/layouts/user_mailer.html.slim
  app/views/shared/_failure.html.erb
  app/views/users/backup_code_setup/edit.html.slim
  app/views/users/totp_setup/new.html.slim
  app/views/users/two_factor_authentication_setup/success.html.erb
  app/views/users/webauthn_setup/delete.html.slim
  config/initializers/asset_tag_helper_patch.rb
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
  config/locales/mailer/en.yml
  config/locales/mailer/es.yml
  config/locales/mailer/fr.yml
  config/locales/users/en.yml
  config/locales/users/es.yml
  config/locales/users/fr.yml
Labels: status - ready for review

#3352 LG-915 LG-1928 PIV/CAC certificate timeout and ocsp errors
  app/controllers/users/piv_cac_login_controller.rb
  app/forms/user_piv_cac_login_form.rb
  app/forms/user_piv_cac_setup_form.rb
  config/locales/titles/en.yml
  config/locales/titles/es.yml
  config/locales/titles/fr.yml
  config/locales/two_factor_authentication/en.yml
  config/locales/two_factor_authentication/es.yml
  config/locales/two_factor_authentication/fr.yml
  spec/forms/user_piv_cac_setup_form_spec.rb
Labels: status - ready for review

#3355 LG-1821 Add a uniqueness constraint to email address
  app/controllers/users/emails_controller.rb
  db/migrate/20191022134041_add_uniqueness_constraint_to_unconfirmed_emails.rb
  db/schema.rb
  spec/features/multiple_emails/add_email_spec.rb
Labels: status - ready for review

#3356 add aria label to checkbox
  app/javascript/app/checkbox.js
Labels: status - ready for review

#3358 LG-2113 Update authentication and confirmation OTP message
  Gemfile
  Gemfile.lock
Labels: status - ready for review

#3360 LG-2117 Fix auth counts tracking to exclude ones that do not make it back to sp
  app/controllers/application_controller.rb
  app/controllers/concerns/remember_device_concern.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/controllers/saml_idp_controller.rb
  app/controllers/sign_up/completions_controller.rb
Labels: status - ready for review

#3364 LG-2054 Add link to send verification code via usps on error pages
  app/presenters/idv/max_attempts_failure_presenter.rb
  app/presenters/idv/warning_presenter.rb
  app/views/shared/_failure.html.erb
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
  spec/support/idv_examples/max_attempts.rb
Labels: status - ready for review

#3361 LG-2044 Add a PIV/CAC during sign in flow
  app/controllers/application_controller.rb
  app/controllers/sign_up/email_confirmations_controller.rb
  app/controllers/users/piv_cac_login_controller.rb
  app/controllers/users/piv_cac_setup_from_sign_in_controller.rb
  app/views/users/piv_cac_setup_from_sign_in/prompt.slim
  app/views/users/piv_cac_setup_from_sign_in/success.html.erb
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
  config/locales/headings/en.yml
  config/locales/headings/es.yml
  config/locales/headings/fr.yml
  config/locales/instructions/en.yml
  config/locales/instructions/es.yml
  config/locales/instructions/fr.yml
  config/locales/titles/en.yml
  config/locales/titles/es.yml
  config/locales/titles/fr.yml
  config/routes.rb
  spec/features/users/sign_in_spec.rb
Labels: status - ready for review

#3368 Whitelist SP redirect in CSP on piv cac setup after sign in action
  app/controllers/users/piv_cac_setup_from_sign_in_controller.rb
Labels: status - ready for review

#3366 LG-1832 Display attributes on consent screen
  app/controllers/sign_up/completions_controller.rb
  app/views/sign_up/completions/_requested_attributes.html.slim
  spec/features/saml/ial1_sso_spec.rb
  spec/support/idv_examples/sp_requested_attributes.rb
Labels: status - ready for review

#3367 LG-1451 Ensure PII is not being transmitted/shared with IAL1 SPs
  app/forms/openid_connect_authorize_form.rb
  app/services/openid_connect_attribute_scoper.rb
  app/view_models/sign_up_completions_show.rb
  config/application.yml.default
  config/locales/openid_connect/en.yml
  config/locales/openid_connect/es.yml
  config/locales/openid_connect/fr.yml
  spec/controllers/openid_connect/authorization_controller_spec.rb
  spec/forms/openid_connect_authorize_form_spec.rb
Labels: status - ready for review

#3370 LG-1832 Update consent screen to display attributes before continue button
  app/assets/images/user-signup-ial1.svg
  app/assets/images/user-signup-ial2.svg
  app/controllers/sign_up/completions_controller.rb
  app/views/sign_up/completions/_show_sp.html.slim
  config/locales/help_text/en.yml
  config/locales/help_text/es.yml
  config/locales/help_text/fr.yml
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
  config/locales/titles/en.yml
  config/locales/titles/es.yml
  config/locales/titles/fr.yml
  spec/support/idv_examples/sp_requested_attributes.rb
Labels: status - ready for review

#3371 LG-2194 Move image upload errors to top of screen
  app/views/idv/capture_doc/back_image.html.slim
  app/views/idv/capture_doc/capture_mobile_back_image.html.slim
  app/views/idv/capture_doc/front_image.html.slim
  app/views/idv/capture_doc/mobile_front_image.html.slim
  app/views/idv/doc_auth/_error_messages.html.slim
  app/views/idv/doc_auth/_notices.html.slim
  app/views/idv/doc_auth/back_image.html.slim
  app/views/idv/doc_auth/front_image.html.slim
  app/views/idv/doc_auth/mobile_back_image.html.slim
  app/views/idv/doc_auth/mobile_front_image.html.slim
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
Labels: status - ready for review

#3378 International phone number flag icon fix
  app/assets/stylesheets/components/_intl-tel-input.scss
Labels: status - ready for review
