Repository 18F/identity-idp, pull requests merged in 2019-05, with the labels that each got.

#2907 LG-938 Streamline sign in
  app/assets/images/user-access.svg
  app/assets/stylesheets/components/_btn.scss
  app/assets/stylesheets/components/_util.scss
  app/controllers/concerns/fully_authenticatable.rb
  app/controllers/sign_up/registrations_controller.rb
  app/decorators/service_provider_session_decorator.rb
  app/views/devise/sessions/_return_to_service_provider.html.slim
  app/views/devise/sessions/new.html.slim
  app/views/shared/_cancel.html.slim
  app/views/shared/_sp_alert.html.slim
  app/views/sign_up/registrations/_return_to_sp_from_start_page.html.slim
  app/views/sign_up/registrations/new.html.slim
  app/views/sign_up/registrations/show.html.slim
  config/locales/links/en.yml
  config/locales/links/es.yml
  config/locales/links/fr.yml
  config/locales/sign_up/en.yml
  config/locales/sign_up/es.yml
  config/locales/sign_up/fr.yml
  config/locales/titles/en.yml
  config/locales/titles/es.yml
  config/locales/titles/fr.yml
  config/routes.rb
  logstash.conf.example
  spec/controllers/openid_connect/authorization_controller_spec.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/controllers/sign_up/registrations_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/decorators/service_provider_session_decorator_spec.rb
  spec/features/accessibility/visitor_pages_spec.rb
  spec/features/flows/sp_authentication_flows_spec.rb
  spec/features/openid_connect/openid_connect_spec.rb
  spec/features/openid_connect/redirect_uri_validation_spec.rb
  spec/features/remember_device/session_expiration_spec.rb
  spec/features/saml/loa1/account_creation_spec.rb
  spec/features/saml/loa1_sso_spec.rb
  spec/features/saml/loa3_sso_spec.rb
  spec/features/saml/redirect_uri_validation_spec.rb
  spec/features/saml/saml_spec.rb
  spec/features/users/sign_in_spec.rb
  spec/features/visitors/navigation_spec.rb
  spec/requests/openid_connect_authorize_spec.rb
  spec/support/features/idv_step_helper.rb
  spec/support/features/session_helper.rb
  spec/support/idv_examples/failed_idv_job.rb
  spec/support/idv_examples/max_attempts.rb
  spec/support/idv_examples/sp_handoff.rb
  spec/support/idv_examples/sp_requested_attributes.rb
  spec/support/shared_examples/remember_device.rb
  spec/support/shared_examples/sign_in.rb
  spec/support/sp_auth_helper.rb
  spec/views/devise/passwords/new.html.slim_spec.rb
  spec/views/devise/sessions/new.html.slim_spec.rb
  spec/views/sign_up/registrations/destroy_confirm.html.slim_spec.rb
  spec/views/sign_up/registrations/new.html.slim_spec.rb
  spec/views/sign_up/registrations/show.html.slim_spec.rb
Labels: status - ready for review

#2921 LG-1241 LG-1242 Fix doc auth cancel then sign in restart and errors
  app/controllers/idv/cancellations_controller.rb
  spec/features/idv/doc_auth/cancel_spec.rb
Labels: status - ready for review

#2917 LG-1229 Add visual difference between front and back image screens
  app/views/idv/capture_doc/front_image.html.slim
  app/views/idv/capture_doc/mobile_front_image.html.slim
  app/views/idv/doc_auth/_front_of_state_id_image.slim
  app/views/idv/doc_auth/front_image.html.slim
  app/views/idv/doc_auth/mobile_front_image.html.slim
Labels: status - ready for review

#2922 LG-1239 Remove the webauthn success cancel link
  app/views/users/webauthn_setup/success.html.slim
Labels: status - ready for review

#2910 Add admin.move.mil to production service providers
  config/service_providers.yml
Labels: status - ready for review, type - config

#2925 LG-1240 Add general error for problems connecting to vendors in doc auth
  app/services/flow/base_step.rb
  app/services/idv/steps/back_image_step.rb
  app/services/idv/steps/capture_mobile_back_image_step.rb
  app/services/idv/steps/doc_auth_base_step.rb
  app/services/idv/steps/doc_success_step.rb
  app/services/idv/steps/front_image_step.rb
  app/services/idv/steps/mobile_back_image_step.rb
  app/services/idv/steps/mobile_front_image_step.rb
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
  spec/features/idv/doc_auth/back_image_step_spec.rb
  spec/features/idv/doc_auth/front_image_step_spec.rb
Labels: status - ready for review

#2913 Adds DOT Delphi eInvoicing configuration
  certs/sp/dot_einvoicing_prod.crt
  config/service_providers.yml
Labels: status - ready for review, type - config

#2905 Lg/ga workflow goals
  app/controllers/concerns/remember_device_concern.rb
  app/controllers/concerns/two_factor_authenticatable.rb
  app/controllers/sign_up/completions_controller.rb
  app/controllers/two_factor_authentication/backup_code_verification_controller.rb
  app/controllers/two_factor_authentication/otp_verification_controller.rb
  app/controllers/two_factor_authentication/personal_key_verification_controller.rb
  app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
  app/controllers/two_factor_authentication/totp_verification_controller.rb
  app/controllers/two_factor_authentication/webauthn_verification_controller.rb
  app/javascript/app/form-validation.js
  app/services/analytics.rb
  app/views/devise/sessions/new.html.slim
  app/views/two_factor_authentication/backup_code_verification/show.html.slim
  app/views/two_factor_authentication/otp_verification/show.html.slim
  app/views/two_factor_authentication/personal_key_verification/show.html.slim
  app/views/two_factor_authentication/piv_cac_verification/show.html.slim
  app/views/two_factor_authentication/totp_verification/show.html.slim
  app/views/two_factor_authentication/webauthn_verification/show.html.slim
  spec/controllers/sign_up/completions_controller_spec.rb
  spec/services/analytics_spec.rb
  spec/support/fake_analytics.rb
Labels: status - ready for review

#2920 Adds USGS sciencebase configuration
  app/assets/images/sp-logos/usgs.svg
  certs/sp/usgs_prod.crt
  config/agencies.yml
  config/service_providers.yml
Labels: status - do not merge, type - config

#2918 LG-1074 Add help info to docauth image capture screens
  app/services/flow/base_flow.rb
  app/services/flow/base_step.rb
  app/services/idv/steps/doc_auth_base_step.rb
  app/views/idv/capture_doc/back_image.html.slim
  app/views/idv/capture_doc/capture_mobile_back_image.html.slim
  app/views/idv/capture_doc/front_image.html.slim
  app/views/idv/capture_doc/mobile_front_image.html.slim
  app/views/idv/doc_auth/back_image.html.slim
  app/views/idv/doc_auth/front_image.html.slim
  app/views/idv/doc_auth/mobile_back_image.html.slim
  app/views/idv/doc_auth/mobile_front_image.html.slim
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
  spec/features/idv/doc_auth/back_image_step_spec.rb
  spec/features/idv/doc_auth/mobile_back_image_step_spec.rb
  spec/features/idv/recovery/back_image_step_spec.rb
  spec/support/features/doc_auth_helper.rb
Labels: status - ready for review

#2928 LG-1262 Create rake task for generating an account w/ multiple emails
  lib/tasks/dev.rake
Labels: status - ready for review

#2934 As config fmcsa help text
  app/decorators/service_provider_session_decorator.rb
  config/locales/service_providers/en.yml
  config/locales/service_providers/es.yml
  config/locales/service_providers/fr.yml
Labels: status - ready for review

#2936 Deploy RC 83.1 to staging
  app/decorators/service_provider_session_decorator.rb
  config/locales/service_providers/en.yml
  config/locales/service_providers/es.yml
  config/locales/service_providers/fr.yml
Labels: status - promotion

#2929 Add the id for email addresses to the URL for modifying the email address
  app/controllers/reauthn_required_controller.rb
  app/controllers/users/emails_controller.rb
  app/forms/update_user_email_form.rb
  app/views/accounts/_email.html.slim
  app/views/accounts/show.html.slim
  app/views/users/emails/edit.html.slim
  config/routes.rb
  spec/controllers/users/emails_controller_spec.rb
  spec/features/accessibility/user_pages_spec.rb
  spec/features/two_factor_authentication/change_factor_spec.rb
  spec/features/users/user_edit_spec.rb
  spec/features/visitors/password_recovery_spec.rb
  spec/forms/update_user_email_form_spec.rb
  spec/requests/edit_user_spec.rb
  spec/views/accounts/show.html.slim_spec.rb
  spec/views/users/emails/edit.html.slim_spec.rb
Labels: status - ready for review

#2935 LG-1276 Add test for sign-in with multiple email addresses
  spec/features/multiple_emails/sign_in_spec.rb
Labels: status - ready for review

#2939 Remove roles from users
  app/controllers/sign_up/passwords_controller.rb
  app/forms/password_reset_email_form.rb
  app/models/nonexistent_user.rb
  app/models/user.rb
  app/presenters/confirmation_email_presenter.rb
  app/services/request_password_reset.rb
  config/locales/mailer/en.yml
  config/locales/mailer/es.yml
  config/locales/mailer/fr.yml
  spec/controllers/sign_up/passwords_controller_spec.rb
  spec/controllers/users/reset_passwords_controller_spec.rb
  spec/factories/users.rb
  spec/forms/password_reset_email_form_spec.rb
  spec/models/nonexistent_user_spec.rb
  spec/services/request_password_reset_spec.rb
  spec/views/devise/mailer/confirmation_instructions.html.slim_spec.rb
Labels: status - ready for review

#2941 LG-1275 Display all email addresses on the account page
  app/views/accounts/_emails.html.slim
  app/views/accounts/show.html.slim
  config/locales/account/en.yml
  spec/features/multiple_emails/email_management_spec.rb
  spec/views/accounts/show.html.slim_spec.rb
Labels: status - ready for review

#2945 LG-1285 Prevent sign in with an unconfirmed email address
  app/models/concerns/user_encrypted_attribute_overrides.rb
  spec/factories/users.rb
  spec/features/multiple_emails/sign_in_spec.rb
Labels: status - ready for review

#2938 LG-1263 Add a trait for multiple emails to the user factory
  spec/features/multiple_emails/email_management_spec.rb
Labels: status - ready for review

#2946 Read from the email address table to determine if a user is confirmed
  app/models/user.rb
  spec/forms/reset_password_form_spec.rb
  spec/services/email_confirmation_token_validator_spec.rb
Labels: status - ready for review

#2943 LG-1266 Send the email address the user signs in with to the SP
  app/controllers/users/sessions_controller.rb
  app/decorators/email_context.rb
  app/models/identity.rb
  app/presenters/openid_connect_user_info_presenter.rb
  app/services/attribute_asserter.rb
  config/initializers/saml_idp.rb
  db/migrate/20190510202639_add_last_signed_in_at_to_email_addresses.rb
  db/schema.rb
  spec/controllers/openid_connect/user_info_controller_spec.rb
  spec/decorators/email_context_spec.rb
  spec/factories/users.rb
  spec/features/multiple_emails/sp_sign_in_spec.rb
  spec/presenters/openid_connect_user_info_presenter_spec.rb
  spec/services/attribute_asserter_spec.rb
  spec/services/id_token_builder_spec.rb
Labels: status - ready for review

#2948 Use a service class to send confirmation emails
  app/forms/register_user_email_form.rb
  app/forms/resend_email_confirmation_form.rb
  app/forms/update_user_email_form.rb
  app/mailers/custom_devise_mailer.rb
  app/mailers/user_mailer.rb
  app/models/user.rb
  app/presenters/confirmation_email_presenter.rb
  app/services/request_password_reset.rb
  app/services/send_sign_up_email_confirmation.rb
  app/views/user_mailer/account_reset_granted.html.slim
  app/views/user_mailer/confirm_email_and_reverify.html.slim
  app/views/user_mailer/email_confirmation_instructions.html.slim
  config/i18n-tasks.yml
  config/initializers/new_relic_tracers.rb
  config/locales/devise/en.yml
  config/locales/devise/es.yml
  config/locales/devise/fr.yml
  config/locales/mailer/en.yml
  config/locales/mailer/es.yml
  config/locales/mailer/fr.yml
  config/locales/user_mailer/en.yml
  config/locales/user_mailer/es.yml
  config/locales/user_mailer/fr.yml
  spec/controllers/users/emails_controller_spec.rb
  spec/features/visitors/email_confirmation_spec.rb
  spec/forms/register_user_email_form_spec.rb
  spec/forms/resend_email_confirmation_form_spec.rb
  spec/forms/update_user_email_form_spec.rb
  spec/mailers/custom_devise_mailer_spec.rb
  spec/mailers/user_mailer_spec.rb
  spec/services/request_password_reset_spec.rb
  spec/services/send_sign_up_email_confirmation_spec.rb
  spec/support/features/session_helper.rb
  spec/views/account_reset/user_mailer/email_confirmation_instructions.html.slim_spec.rb
Labels: status - ready for review

#2949 Fixed LG-1288 bug which defaults the delivery preference to the selection made for the previous phone
  app/controllers/concerns/phone_confirmation.rb
  app/controllers/users/phone_setup_controller.rb
  spec/features/backup_mfa/otp_delivery_selection_spec.rb
Labels: status - ready for review

#2951 LG-1278 alert the user they cannot use the same phone number as a backup MFA
  app/controllers/users/phone_setup_controller.rb
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
  db/schema.rb
  spec/features/backup_mfa/no_duplicate_phone_numbers_spec.rb
  spec/features/backup_mfa/otp_delivery_selection_spec.rb
Labels: status - ready for review

#2947 Added phone config default, fixed delivery preference
  app/controllers/concerns/phone_confirmation.rb
  app/controllers/concerns/two_factor_authenticatable.rb
  app/controllers/users/phones_controller.rb
  app/controllers/users/two_factor_authentication_controller.rb
  app/decorators/mfa_context.rb
  app/decorators/phone_configuration_decorator.rb
  app/forms/user_phone_form.rb
  app/models/phone_configuration.rb
  app/models/user.rb
  app/presenters/two_factor_auth_code/phone_delivery_presenter.rb
  app/services/update_user.rb
  app/views/accounts/_phone.html.slim
  app/views/two_factor_authentication/otp_verification/show.html.slim
  app/views/users/phones/add.html.slim
  app/views/users/phones/edit.html.slim
  app/views/users/shared/_otp_delivery_preference_selection.html.slim
  app/views/users/shared/_otp_make_default_number.html.slim
  config/locales/account/en.yml
  config/locales/account/es.yml
  config/locales/account/fr.yml
  config/locales/two_factor_authentication/en.yml
  config/locales/two_factor_authentication/es.yml
  config/locales/two_factor_authentication/fr.yml
  db/migrate/20190422200501_add_made_default_at_to_phone_configurations.rb
  db/migrate/20190503155016_add_made_default_at_index_to_phone_configurations.rb
  db/schema.rb
  spec/controllers/users/phone_setup_controller_spec.rb
  spec/controllers/users/phones_controller_spec.rb
  spec/controllers/users/two_factor_authentication_controller_spec.rb
  spec/decorators/phone_configuration_decorator_spec.rb
  spec/features/accessibility/user_pages_spec.rb
  spec/features/two_factor_authentication/change_factor_spec.rb
  spec/features/users/default_phone_selection_spec.rb
  spec/forms/user_phone_form_spec.rb
  spec/models/phone_configuration_spec.rb
  spec/models/user_spec.rb
  spec/services/update_user_spec.rb
Labels: status - ready for review

#2950 LG-935 Push notifications for account delete events
  app/controllers/users/delete_controller.rb
  app/models/push_account_delete.rb
  app/services/account_reset/delete_account.rb
  app/services/push_notification/account_delete.rb
  config/service_providers.yml
  db/migrate/20190506152241_creat_push_account_deletes.rb
  db/migrate/20190509144212_add_push_notification_url_to_service_provider.rb
  db/schema.rb
  spec/features/account_reset/delete_account_spec.rb
  spec/features/users/user_profile_spec.rb
  spec/models/push_account_delete_spec.rb
  spec/services/push_notification/account_delete_spec.rb
  spec/support/features/push_notifications_helper.rb
Labels: status - ready for review

#2952 LG-1279 List available backup authentication methods on registration
  app/policies/two_factor_authentication/auth_app_policy.rb
  app/policies/two_factor_authentication/backup_code_policy.rb
  app/presenters/two_factor_options_presenter.rb
  spec/features/mfa_enrollability_spec.rb
  spec/features/remember_device/totp_spec.rb
  spec/features/remember_device/webauthn_spec.rb
  spec/presenters/two_factor_options_presenter_spec.rb
  spec/support/features/session_helper.rb
Labels: status - ready for review

#2953 LG 1268 - managing an email address if adding email addresses has not been enabled
  app/views/accounts/_emails.html.slim
  lib/feature_management.rb
  spec/features/multiple_emails/email_management_spec.rb
Labels: status - ready for review

#2956 Switch up descriptions for manage email specs
  spec/features/multiple_emails/email_management_spec.rb
Labels: status - ready for review

#2958 Set statement timeout to zero before running account delete report
  lib/tasks/deleted_accounts.rake
Labels: status - ready for review

#2955 Ac/delete an email address
  app/controllers/users/emails_controller.rb
  app/decorators/email_context.rb
  app/forms/delete_user_email_form.rb
  app/models/event.rb
  app/policies/email_policy.rb
  app/presenters/confirm_delete_email_presenter.rb
  app/services/analytics.rb
  app/view_models/account_show.rb
  app/views/accounts/_emails.html.slim
  app/views/accounts/actions/_delete_action_button.html.slim
  app/views/users/emails/confirm_delete.html.slim
  config/application.yml.default
  config/locales/email_addresses/en.yml
  config/locales/email_addresses/es.yml
  config/locales/email_addresses/fr.yml
  config/locales/event_types/en.yml
  config/locales/event_types/es.yml
  config/locales/event_types/fr.yml
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
  config/locales/titles/en.yml
  config/locales/titles/es.yml
  config/locales/titles/fr.yml
  config/routes.rb
  lib/feature_management.rb
  spec/features/multiple_emails/email_management_spec.rb
  spec/forms/delete_user_email_form_spec.rb
  spec/lib/feature_management_spec.rb
  spec/presenters/confirm_delete_email_presenter_spec.rb
Labels: status - ready for review

#2940 Drop columns related to roles from the database
  app/models/user.rb
  db/migrate/20190510202920_drop_role_from_user.rb
  db/schema.rb
Labels: status - ready for review

#2919 LG-1113 Implement GPO mail job as rake task using RDS
  app/controllers/health/health_controller.rb
  app/models/job_run.rb
  app/services/job_runner/callback_executor.rb
  app/services/job_runner/health_checker.rb
  app/services/job_runner/job_configuration.rb
  app/services/job_runner/job_run_needed_resolver.rb
  app/services/job_runner/lock_referee.rb
  app/services/job_runner/runner.rb
  config/application.yml.default
  config/initializers/job_configurations.rb
  db/migrate/20190502143706_create_job_runs.rb
  db/schema.rb
  lib/tasks/job_runs.rake
  spec/controllers/health/health_controller_spec.rb
  spec/factories/job_runs.rb
  spec/models/job_run_spec.rb
  spec/services/job_runner/callback_executor_spec.rb
  spec/services/job_runner/health_checker_spec.rb
  spec/services/job_runner/job_run_needed_resolver_spec.rb
  spec/services/job_runner/lock_referee_spec.rb
  spec/services/job_runner/runner_spec.rb
Labels: status - ready for review

#2964 LG-1324 Remove the phone configuration consideration from 2fa options form
  app/forms/two_factor_options_form.rb
  spec/features/backup_mfa/otp_delivery_selection_spec.rb
Labels: status - ready for review

#2963 LG-1286 Add a generated at timestamp to backup codes
  app/view_models/account_show.rb
  app/views/accounts/_backup_codes.html.erb
  app/views/accounts/actions/_generate_backup_codes.html.erb
  app/views/accounts/actions/_generate_backup_codes.html.slim
  app/views/accounts/actions/_regenerate_backup_codes.html.erb
  app/views/accounts/actions/_regenerate_backup_codes.html.slim
  app/views/accounts/show.html.erb
  app/views/accounts/show.html.slim
  db/migrate/20190524205306_add_index_to_backup_code_configuration.rb
  db/schema.rb
  spec/features/account/backup_codes_spec.rb
  spec/view_models/account_show_spec.rb
  spec/views/accounts/show.html.erb_spec.rb
Labels: status - ready for review

#2966 LG-1332 Sign in with backup codes needs redirect to SP
  app/controllers/two_factor_authentication/backup_code_verification_controller.rb
Labels: status - ready for review

#2967 LG-1337 Fix supported webauthn protocols
  app/javascript/app/webauthn.js
  spec/javascripts/app/webauthn_spec.js
Labels: status - ready for review

#2971 LG-1329 Show backup codes download button only on desktop
  app/helpers/application_helper.rb
  app/views/users/backup_code_setup/index.html.slim
  spec/features/two_factor_authentication/backup_code_sign_up_spec.rb
Labels: status - ready for review

#2972 Mark local SAML rails SP as IAL2
  config/service_providers.yml
Labels: status - ready for review

#2975 LG-1284 Fix a bug parsing the GA cookie
  app/services/analytics.rb
  spec/services/analytics_spec.rb
Labels: status - ready for review

#2976 Fix backup_codes_configuration index
  db/migrate/20190529120309_fix_backup_code_configuration_index.rb
  db/schema.rb
Labels: status - ready for review

#2981 LG-1344 Fix account reset for users with 1 MFA (ie no personal key)
  app/controllers/account_reset/request_controller.rb
  spec/controllers/account_reset/request_controller_spec.rb
Labels: status - ready for review

#2986 Make the PR age script take draft PRs into account
  bin/fetch_github_metrics
  lib/github_metrics.rb
  lib/github_metrics/pr_age_reporter.rb
  lib/github_metrics/pull_request.rb
  lib/github_metrics/sprint.rb
Labels: status - ready for review
