Repository 18F/identity-idp, pull requests merged in 2019-03, with the labels that each got.

#2795 Sunset SAML SLO
  app/controllers/concerns/saml_idp_logout_concern.rb
  app/controllers/saml_idp_controller.rb
  app/controllers/users/sessions_controller.rb
  app/models/user.rb
  app/services/agency_identity_linker.rb
  app/services/logout_response_handler.rb
  app/services/single_logout_handler.rb
  config/routes.rb
  config/service_providers.yml
  spec/controllers/openid_connect/logout_controller_spec.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/controllers/users/sessions_controller_spec.rb
  spec/features/openid_connect/openid_connect_spec.rb
  spec/features/saml/idp_initiated_slo_spec.rb
  spec/features/saml/loa3_sso_spec.rb
  spec/features/saml/multiple_endpoints_spec.rb
  spec/features/saml/saml_logout_spec.rb
  spec/features/saml/saml_spec.rb
  spec/features/saml/sp_initiated_slo_spec.rb
  spec/forms/openid_connect_logout_form_spec.rb
  spec/models/user_spec.rb
  spec/services/agency_identity_linker_spec.rb
  spec/support/idv_examples/sp_handoff.rb
  spec/support/idv_examples/sp_requested_attributes.rb
Labels: status - ready for review

#2760 Remove scaffolding to migrate to 2L-KMS
  app/services/encryption/kms_client.rb
  app/services/encryption/password_verifier.rb
  config/application.yml.example
  lib/feature_management.rb
  lib/tasks/add_context_to_pii_bundles.rake
  spec/features/idv/uak_password_spec.rb
  spec/services/encryption/kms_client_spec.rb
  spec/services/encryption/password_verifier_spec.rb
Labels: status - do not merge, status - ready for review

#2754 Drop password metrics table
  db/migrate/20190212163140_drop_password_metrics.rb
  db/schema.rb
Labels: status - do not merge, status - ready for review

#2797 Add usdoj.gov to list of supported email domains
  config/application.yml.example
Labels: status - ready for review

#2798 Create Event objects in controller instead of forms / services
  app/controllers/idv/review_controller.rb
  app/controllers/users/piv_cac_authentication_setup_controller.rb
  app/controllers/users/reset_passwords_controller.rb
  app/controllers/users/totp_setup_controller.rb
  app/controllers/users/verify_account_controller.rb
  app/controllers/users/webauthn_setup_controller.rb
  app/forms/reset_password_form.rb
  app/forms/totp_setup_form.rb
  app/forms/user_piv_cac_setup_form.rb
  app/forms/webauthn_setup_form.rb
  app/services/create_verified_account_event.rb
  app/services/idv/profile_activator.rb
  spec/controllers/idv/review_controller_spec.rb
  spec/controllers/users/webauthn_setup_controller_spec.rb
  spec/features/users/piv_cac_management_spec.rb
  spec/features/users/totp_management_spec.rb
  spec/features/visitors/password_recovery_spec.rb
  spec/forms/reset_password_form_spec.rb
  spec/forms/totp_setup_form_spec.rb
  spec/forms/user_piv_cac_setup_form_spec.rb
  spec/services/create_account_verified_event_spec.rb
Labels: status - ready for review

#2800 Fix 500 errors on doc auth when no phone used for 2fa
  app/services/idv/steps/back_image_step.rb
  app/services/idv/steps/link_sent_step.rb
  app/services/idv/steps/mobile_back_image_step.rb
  spec/features/idv/doc_auth/back_image_step_spec.rb
  spec/features/idv/doc_auth/link_sent_step_spec.rb
  spec/features/idv/doc_auth/mobile_back_image_step_spec.rb
Labels: status - ready for review

#2802 Add missing event names
  config/locales/event_types/en.yml
  config/locales/event_types/es.yml
  config/locales/event_types/fr.yml
  config/locales/two_factor_authentication/en.yml
  spec/models/event_spec.rb
Labels: status - ready for review

#2803 Upgrade gems and npm packages
  Gemfile.lock
  yarn.lock
Labels: status - ready for review

#2801 Updates USAID prod certificate
  certs/sp/usaid_prod.crt
Labels: status - ready for review

#2723 Connect docker-compose web container to mailcatcher container
  docker-compose.yml
Labels: status - ready for review

#2808 Updates OpenID Connect ExpressJS sample app
  config/service_providers.yml
Labels: status - ready for review

#2810 Fix the OIDC token form code validation
  app/forms/openid_connect_token_form.rb
  spec/forms/openid_connect_token_form_spec.rb
Labels: status - ready for review

#2811 Use `render_not_found` helper in events controller
  app/controllers/events_controller.rb
Labels: status - ready for review

#2809 Add nasa.gov to list of email domains for piv/cac
  config/application.yml.example
Labels: status - work in progress

#2790 Tear down scaffolding for migrating to sessions w/ KMS contexts
  app/services/encryption/encryptors/session_encryptor.rb
  config/application.yml.example
  lib/feature_management.rb
  spec/services/encryption/encryptors/session_encryptor_spec.rb
Labels: status - do not merge

#2817 Stop saving in user factory traits
  spec/controllers/account_reset/request_controller_spec.rb
  spec/factories/users.rb
  spec/support/shared_examples/password_strength.rb
Labels: status - ready for review

#2816 Stop using pkey generator in user factory
  spec/controllers/account_reset/request_controller_spec.rb
  spec/controllers/mfa_confirmation_controller_spec.rb
  spec/controllers/users/reset_passwords_controller_spec.rb
  spec/controllers/users/webauthn_setup_controller_spec.rb
  spec/decorators/mfa_context_spec.rb
  spec/factories/users.rb
  spec/features/two_factor_authentication/sign_in_spec.rb
  spec/services/email_notifier_spec.rb
Labels: status - ready for review

#2818 Reduce capybara wait time
  spec/features/two_factor_authentication/sign_in_spec.rb
  spec/features/users/sign_in_spec.rb
  spec/support/capybara.rb
Labels: status - ready for review

#2820 Silence Puma in test environment
  spec/support/capybara.rb
Labels: status - ready for review

#2822 Silence output from CloudHSMKeySharer spec
  spec/lib/cloudhsm/cloudhsm_key_sharer_spec.rb
Labels: status - ready for review

#2821 Don't use knapsack when running locally
  spec/spec_helper.rb
Labels: status - ready for review

#2824 Silence zonebie
  spec/spec_helper.rb
Labels: status - ready for review

#2813 Add disavowals to events
  app/controllers/application_controller.rb
  app/controllers/event_disavowal_controller.rb
  app/controllers/users/passwords_controller.rb
  app/controllers/users/reset_passwords_controller.rb
  app/forms/event_disavowal/password_reset_from_disavowal_form.rb
  app/forms/reset_password_form.rb
  app/forms/update_user_password_form.rb
  app/mailers/user_mailer.rb
  app/services/analytics.rb
  app/services/event_disavowal/build_disavowed_event_analytics_attributes.rb
  app/services/event_disavowal/disavow_event.rb
  app/services/event_disavowal/find_disavowed_event.rb
  app/services/event_disavowal/generate_disavowal_token.rb
  app/services/event_disavowal/validate_disavowed_event.rb
  app/views/event_disavowal/new.html.slim
  app/views/user_mailer/password_changed.html.slim
  config/application.yml.example
  config/locales/event_disavowals/en.yml
  config/locales/event_disavowals/es.yml
  config/locales/event_disavowals/fr.yml
  config/locales/user_mailer/en.yml
  config/locales/user_mailer/es.yml
  config/locales/user_mailer/fr.yml
  config/routes.rb
  db/migrate/20190306143757_add_disavowal_token_fingerprint_to_events.rb
  db/schema.rb
  spec/controllers/event_disavowal_controller_spec.rb
  spec/controllers/users/passwords_controller_spec.rb
  spec/controllers/users/reset_passwords_controller_spec.rb
  spec/factories/events.rb
  spec/features/event_disavowal_spec.rb
  spec/forms/event_disavowal/password_reset_from_disavowal_form_spec.rb
  spec/forms/update_user_password_form_spec.rb
  spec/mailers/user_mailer_spec.rb
  spec/services/event_disavowal/disavow_event_spec.rb
  spec/services/event_disavowal/find_disavowed_event_spec.rb
  spec/services/event_disavowal/generate_disavowal_token_spec.rb
  spec/services/event_disavowal/validate_disavowed_event_spec.rb
Labels: status - ready for review

#2825 Disable bullet in unit tests
  config/environments/test.rb
  spec/rails_helper.rb
Labels: status - ready for review

#2827 Fix name collision in doc auth / doc capture shared examples
  spec/features/idv/doc_auth/mobile_back_image_step_spec.rb
  spec/features/idv/doc_capture/mobile_back_image_step_spec.rb
Labels: status - ready for review

#2826 Use 18f logo for service provider session decorator test
  spec/decorators/service_provider_session_decorator_spec.rb
Labels: status - ready for review

#2823 Upgrade shoulda_matchers
  Gemfile
  Gemfile.lock
Labels: status - ready for review

#2828 Upgrade gems and npm packages
  Gemfile.lock
  yarn.lock
Labels: status - ready for review

#2829 Regenerate knapsack report
  knapsack_rspec_report.json
Labels: status - ready for review

#2830 Separate alerting about new devices from service that finds a device
  app/controllers/application_controller.rb
  app/mailers/user_mailer.rb
  app/services/device_tracking/alert_user_about_new_device.rb
  app/services/device_tracking/find_or_create_device.rb
  app/services/device_tracking/manage_device.rb
  spec/factories/email_addresses.rb
  spec/features/new_device_tracking_spec.rb
  spec/mailers/user_mailer_spec.rb
  spec/rails_helper.rb
  spec/services/device_tracking/alert_user_about_new_device_spec.rb
  spec/services/device_tracking/find_or_create_device_spec.rb
  spec/services/device_tracking/manage_device_spec.rb
  spec/support/geocoder.rb
  spec/support/geocoder_stubs.rb
Labels: status - ready for review

#2831 Make create_user_event_with_disavowal return an event
  app/controllers/application_controller.rb
  app/controllers/users/passwords_controller.rb
  app/controllers/users/reset_passwords_controller.rb
  app/models/event.rb
  app/services/event_disavowal/generate_disavowal_token.rb
  spec/services/event_disavowal/generate_disavowal_token_spec.rb
Labels: status - ready for review

#2672 LG-744 Whitelist SP attributes for ability to receive LOA3 data
  app/forms/openid_connect_authorize_form.rb
  app/models/null_service_provider.rb
  app/services/saml_request_validator.rb
  config/locales/openid_connect/en.yml
  config/locales/openid_connect/es.yml
  config/locales/openid_connect/fr.yml
  config/service_providers.yml
  spec/controllers/saml_idp_controller_spec.rb
  spec/forms/openid_connect_authorize_form_spec.rb
  spec/services/saml_request_validator_spec.rb
Labels: status - ready for review

#2832 Add a service class to handle event creation
  app/controllers/application_controller.rb
  app/services/user_event_creator.rb
Labels: status - ready for review

#2804 LG-918 Initial cut of the unphishable badge logic.
  app/assets/images/alert/unphishable.svg
  app/decorators/mfa_context.rb
  app/policies/mfa_policy.rb
  app/view_models/account_show.rb
  app/views/accounts/_badges.html.slim
  app/views/accounts/_header.html.slim
  app/views/accounts/_unphishable_badge.html.slim
  app/views/accounts/_verified_account_badge.html.slim
  app/views/accounts/_verified_header.html.slim
  config/locales/headings/en.yml
  config/locales/headings/es.yml
  config/locales/headings/fr.yml
  spec/decorators/mfa_context_spec.rb
  spec/features/account/unphishable_badge_spec.rb
  spec/policies/user_mfa_policy_spec.rb
  spec/view_models/account_show_spec.rb
Labels: status - ready for review

#2819 Add backup codes option to account page
  app/view_models/account_show.rb
  app/views/accounts/actions/_generate_backup_codes.html.slim
  app/views/accounts/actions/_regenerate_backup_codes.html.slim
  app/views/accounts/show.html.slim
  config/locales/account/en.yml
  config/locales/account/es.yml
  config/locales/account/fr.yml
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
  spec/features/account/backup_codes_spec.rb
Labels: status - ready for review

#2834 LG-633 Fix back button prevents confirming personal key
  app/controllers/idv/confirmations_controller.rb
  app/controllers/idv/review_controller.rb
  spec/controllers/idv/confirmations_controller_spec.rb
  spec/controllers/idv/review_controller_spec.rb
Labels: status - ready for review

#2833 Add the ability to disavow a new device sign in
  app/mailers/user_mailer.rb
  app/services/device_tracking/alert_user_about_new_device.rb
  app/services/user_event_creator.rb
  app/views/user_mailer/new_device_sign_in.html.slim
  config/locales/user_mailer/en.yml
  config/locales/user_mailer/es.yml
  config/locales/user_mailer/fr.yml
  spec/features/event_disavowal_spec.rb
  spec/features/new_device_tracking_spec.rb
  spec/mailers/user_mailer_spec.rb
  spec/services/device_tracking/alert_user_about_new_device_spec.rb
  spec/services/user_event_creator_spec.rb
Labels: status - ready for review

#2838 Remove FindOrCreateUser service
  app/services/device_tracking/find_or_create_device.rb
  spec/services/device_tracking/find_or_create_device_spec.rb
Labels: status - ready for review

#2840 Allow users to disavow personal key sign ins
  app/controllers/two_factor_authentication/personal_key_verification_controller.rb
  app/controllers/users/passwords_controller.rb
  app/controllers/users/reset_passwords_controller.rb
  app/forms/personal_key_form.rb
  app/mailers/user_mailer.rb
  app/models/concerns/user_access_key_overrides.rb
  app/services/user_alerts/alert_user_about_new_device.rb
  app/services/user_alerts/alert_user_about_password_change.rb
  app/services/user_alerts/alert_user_about_personal_key_sign_in.rb
  app/services/user_event_creator.rb
  app/views/user_mailer/personal_key_sign_in.html.slim
  spec/factories/users.rb
  spec/features/event_disavowal_spec.rb
  spec/forms/personal_key_form_spec.rb
  spec/mailers/user_mailer_spec.rb
  spec/services/user_alerts/alert_user_about_new_device_spec.rb
  spec/services/user_alerts/alert_user_about_password_change_spec.rb
  spec/services/user_alerts/alert_user_about_personal_key_sign_in_spec.rb
  spec/services/user_event_creator_spec.rb
Labels: status - ready for review

#2841 Fix issue with twilio mocks in pkey verification controller
  spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb
Labels: status - ready for review

#2796 Remove saml.crt from the app
  .circleci/config.yml
  .gitignore
  app/services/request_key_manager.rb
  bin/setup
  certs/saml2019.crt.example
  config/application.yml.example
  config/initializers/figaro.rb
  keys/oidc.key.example
  keys/oidc.pub.example
  keys/saml2019.key.enc.example
  spec/controllers/saml_idp_controller_spec.rb
  spec/features/saml/multiple_endpoints_spec.rb
  spec/features/saml/redirect_uri_validation_spec.rb
  spec/features/saml/saml_logout_spec.rb
  spec/features/saml/saml_spec.rb
  spec/support/idv_examples/confirmation_step.rb
  spec/support/idv_examples/sp_requested_attributes.rb
  spec/support/saml_auth_helper.rb
Labels: status - do not merge

#2843 Adds HHS XMS logo to sp-logos
  app/assets/images/sp-logos/hhs-xms.png
Labels: status - ready for review

#2845 Fix a bug where EventUserCreator returned nil instead of an event
  app/services/user_event_creator.rb
  spec/services/user_event_creator_spec.rb
Labels: status - ready for review

#2846 Fix doc auth 500 error on invalid phone exception from Twilio
  app/services/idv/steps/send_link_step.rb
  spec/features/idv/doc_auth/send_link_step_spec.rb
Labels: status - ready for review

#2844 Parallelize test suite when running with make test
  Gemfile
  Gemfile.lock
  Makefile
  app/services/encryption/kms_logger.rb
  bin/setup
  config/database.yml
  spec/services/encryption/kms_logger_spec.rb
Labels: status - ready for review

#2850 Consolidate remember device specs
  spec/features/remember_device/phone_spec.rb
  spec/features/remember_device/session_expiration_spec.rb
  spec/features/remember_device/sp_expiration_spec.rb
  spec/features/remember_device/totp_spec.rb
  spec/support/shared_examples/remember_device.rb
Labels: status - ready for review

#2852 Adds NPS logo
  app/assets/images/sp-logos/nps.png
Labels: status - ready for review

#2855 Don't call first on disavowed event lookup query
  app/services/event_disavowal/find_disavowed_event.rb
Labels: status - ready for review

#2853 Clean up remember device revocations
  app/controllers/users/backup_code_setup_controller.rb
  app/controllers/users/totp_setup_controller.rb
  app/controllers/users/webauthn_setup_controller.rb
  app/services/remember_device_cookie.rb
  spec/features/remember_device/revocation_spec.rb
  spec/services/remember_device_cookie_spec.rb
  spec/support/shared_examples/remember_device.rb
Labels: status - ready for review

#2859 Add remember device to TOTP
  app/controllers/concerns/two_factor_authenticatable.rb
  app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
  app/controllers/users/totp_setup_controller.rb
  app/presenters/two_factor_auth_code/generic_delivery_presenter.rb
  app/views/two_factor_authentication/otp_verification/show.html.slim
  app/views/two_factor_authentication/totp_verification/show.html.slim
  app/views/users/totp_setup/new.html.slim
  spec/features/remember_device/totp_spec.rb
  spec/support/shared_examples/remember_device.rb
Labels: status - ready for review

#2849 Add message for doc auth recovery success
  app/services/flow/base_flow.rb
  app/services/flow/base_step.rb
  app/services/flow/flow_state_machine.rb
  app/services/idv/flows/capture_doc_flow.rb
  app/services/idv/flows/doc_auth_flow.rb
  app/services/idv/flows/recovery_flow.rb
  app/services/idv/steps/recover_doc_success_step.rb
  config/locales/doc_auth/en.yml
  config/locales/doc_auth/es.yml
  config/locales/doc_auth/fr.yml
  config/locales/recover/en.yml
  config/locales/recover/es.yml
  config/locales/recover/fr.yml
  spec/services/idv/flows/doc_auth_flow_spec.rb
Labels: status - ready for review
