Repository 18F/identity-idp, pull requests merged in 2020-04, with the labels that each got.

#3685 Switch reports to use TimeWithZone objects
  app/services/db/sp_cost/sp_cost_summary.rb
  app/services/db/sp_cost/total_sp_cost_summary.rb
  app/services/reports/base_report.rb
Labels: status - ready for review

#3692 Remove telephony_disabled config, it's not used
  README.md
  config/application.yml.default
  lib/feature_management.rb
  spec/lib/feature_management_spec.rb
Labels: status - ready for review

#3691 Allow the doc auth image steps to process a image url instead of an upload
  app/forms/idv/image_upload_form.rb
  app/services/idv/data_url_image.rb
  app/services/idv/steps/back_image_step.rb
  app/services/idv/steps/capture_mobile_back_image_step.rb
  app/services/idv/steps/doc_auth_base_step.rb
  app/services/idv/steps/front_image_step.rb
  app/services/idv/steps/mobile_back_image_step.rb
  app/services/idv/steps/mobile_front_image_step.rb
  app/views/idv/capture_doc/back_image.html.slim
  app/views/idv/capture_doc/capture_mobile_back_image.html.slim
  app/views/idv/capture_doc/front_image.html.slim
  app/views/idv/capture_doc/mobile_front_image.html.slim
  app/views/idv/doc_auth/back_image.html.slim
  app/views/idv/doc_auth/front_image.html.slim
  app/views/idv/doc_auth/mobile_back_image.html.slim
  app/views/idv/doc_auth/mobile_front_image.html.slim
  spec/features/idv/doc_auth/back_image_step_spec.rb
  spec/features/idv/doc_auth/front_image_step_spec.rb
  spec/features/idv/doc_auth/mobile_back_image_step_spec.rb
  spec/features/idv/doc_auth/mobile_front_image_step_spec.rb
  spec/features/idv/doc_capture/mobile_back_image_step_spec.rb
  spec/features/idv/doc_capture/mobile_front_image_step_spec.rb
  spec/features/idv/recovery/back_image_step_spec.rb
  spec/features/idv/recovery/front_image_step_spec.rb
  spec/forms/idv/image_upload_form_spec.rb
  spec/services/idv/data_url_image_spec.rb
  spec/support/features/doc_auth_helper.rb
  spec/support/fixtures/doc_auth_image_data_url.data
Labels: status - ready for review

#3681 LG-2836 - Mobile capture as primary flow
  app/views/idv/doc_auth/upload.html.slim
  config/locales/doc_auth/en.yml
  config/locales/doc_auth/es.yml
  config/locales/doc_auth/fr.yml
  config/locales/image_description/en.yml
  config/locales/image_description/es.yml
  config/locales/image_description/fr.yml
  spec/features/idv/recovery/upload_step_spec.rb
  spec/support/features/doc_auth_helper.rb
  spec/support/features/recovery_helper.rb
Labels: status - ready for review

#3689 LG-2861 Unique actives over period of performance report
  app/services/db/identity/sp_active_user_counts.rb
  app/services/reports/base_report.rb
  app/services/reports/sp_active_users_over_period_of_performance_report.rb
  config/initializers/job_configurations.rb
  spec/config/initializers/job_configurations.rb
  spec/services/db/identity/sp_active_user_counts_spec.rb
  spec/services/reports/sp_active_users_over_period_of_performance_report_spec.rb
Labels: status - ready for review

#3694 Explicitly remove Rack::Attack when we want to disable rate limiting
  config/application.rb
Labels: status - ready for review

#3693 Make the Acuant SDK files available relative to URLs where we will use the SDK
  app/controllers/acuant_sdk_controller.rb
  config/routes.rb
  spec/requests/acuant_sdk_spec.rb
Labels: status - ready for review

#3695 Add webpack dev server to the Procfile
  Procfile
Labels: status - ready for review

#3690 LG-2857 Add analytics tracking for no SP IAL2/link flow
  app/controllers/concerns/verify_profile_concern.rb
  app/controllers/idv_controller.rb
  app/controllers/users/sessions_controller.rb
  app/services/db/doc_auth_log/doc_auth_funnel_summary_stats.rb
  app/services/flow/flow_state_machine.rb
  app/services/funnel/doc_auth/register_campaign.rb
  db/migrate/20200405233913_add_no_sp_tracking_to_doc_auth_logs.rb
  db/schema.rb
  spec/features/users/sign_in_spec.rb
Labels: status - ready for review

#3696 Add the Acuant mobile capture to the doc auth flow
  app/controllers/idv/doc_auth_controller.rb
  app/javascript/app/acuant/document_capture.js
  app/javascript/app/acuant/domUpdateCallbacks.js
  app/javascript/packs/acuant_document_capture.js
  app/views/idv/_acuant_sdk_document_capture_form.html.erb
  app/views/idv/doc_auth/_spinner.html.erb
  app/views/idv/doc_auth/_spinner.slim
  app/views/idv/doc_auth/front_image.html.erb
  app/views/idv/doc_auth/front_image.html.slim
  app/views/layouts/base.html.slim
  config/application.yml.default
  config/initializers/secure_headers.rb
  config/locales/doc_auth/en.yml
  config/locales/doc_auth/es.yml
  config/locales/doc_auth/fr.yml
  config/locales/image_description/en.yml
  config/locales/image_description/es.yml
  config/locales/image_description/fr.yml
  package.json
  spec/controllers/idv/doc_auth_controller_spec.rb
  spec/javascripts/app/acuant/document_capture_spec.js
  yarn.lock
Labels: status - ready for review

#3703 Add the Acuant SDK document capture experience to the hybrid flow
  app/controllers/idv/capture_doc_controller.rb
  app/views/idv/capture_doc/capture_mobile_back_image.html.erb
  app/views/idv/capture_doc/capture_mobile_back_image.html.slim
  app/views/idv/capture_doc/mobile_front_image.html.erb
  app/views/idv/capture_doc/mobile_front_image.html.slim
  config/routes.rb
  spec/controllers/idv/capture_doc_controller_spec.rb
Labels: status - ready for review

#3704 Add the Acuant SDK document capture experience to the mobile front and back image steps
  app/controllers/idv/doc_auth_controller.rb
  app/views/idv/doc_auth/mobile_back_image.html.erb
  app/views/idv/doc_auth/mobile_back_image.html.slim
  app/views/idv/doc_auth/mobile_front_image.html.erb
  app/views/idv/doc_auth/mobile_front_image.html.slim
  spec/controllers/idv/doc_auth_controller_spec.rb
Labels: status - ready for review

#3706 LG-2573 Configurable NIST conformant verification flow for IAL2
  app/controllers/idv/scan_id_base_controller.rb
  app/controllers/idv/scan_id_controller.rb
  app/models/null_service_provider.rb
  config/application.yml.default
  db/migrate/20200409075651_add_liveness_checking_required_to_service_providers.rb
  db/schema.rb
  spec/controllers/idv/scan_id_controller_spec.rb
Labels: status - ready for review

#3707 Render a button so the user can retry an upload
  app/views/idv/_acuant_sdk_document_capture_form.html.erb
  app/views/idv/capture_doc/capture_mobile_back_image.html.erb
  app/views/idv/capture_doc/mobile_front_image.html.erb
  app/views/idv/doc_auth/back_image.html.erb
  app/views/idv/doc_auth/front_image.html.erb
  app/views/idv/doc_auth/mobile_back_image.html.erb
  app/views/idv/doc_auth/mobile_front_image.html.erb
  config/locales/doc_auth/en.yml
  config/locales/doc_auth/es.yml
  config/locales/doc_auth/fr.yml
Labels: status - ready for review

#3711 Prod RC 107.1
  app/services/flow/flow_state_machine.rb
  app/services/idv/steps/send_link_step.rb
  config/routes.rb
  spec/features/idv/doc_auth/send_link_step_spec.rb
Labels: status - promotion

#3715 Whitelist no sp campaigns
  app/services/funnel/doc_auth/register_campaign.rb
  config/application.yml.default
  spec/features/users/sign_in_spec.rb
Labels: status - ready for review

#3716 LG-2904 Add an Acuant escape hatch
  app/javascript/app/acuant/document_capture.js
  app/javascript/app/acuant/document_capture_dom.js
  app/javascript/app/acuant/document_capture_fallback.js
  app/javascript/packs/acuant_document_capture.js
  app/views/idv/_acuant_sdk_document_capture_form.html.erb
  config/locales/doc_auth/en.yml
  config/locales/doc_auth/es.yml
  config/locales/doc_auth/fr.yml
  spec/javascripts/app/acuant/document_capture_fallback_spec.js
  spec/javascripts/app/acuant/document_capture_spec.js
  spec/javascripts/support/acuant/document_capture_dom.js
Labels: status - ready for review

#3718 Check in yarn.lock changes
  package-lock.json
  yarn.lock
Labels: status - ready for review

#3721 Use the progress formatter when parallel tests is running
  spec/spec_helper.rb
Labels: status - ready for review

#3717 LG-2901 Don't send reset password emails to unconfirmed email addresses on confirmed users
  app/forms/password_reset_email_form.rb
  app/forms/register_user_email_form.rb
  app/models/nonexistent_user.rb
  app/services/request_password_reset.rb
  app/validators/form_add_email_validator.rb
  app/validators/form_email_validator.rb
  spec/features/multiple_emails/reset_password_spec.rb
  spec/forms/register_user_email_form_spec.rb
  spec/models/nonexistent_user_spec.rb
  spec/services/request_password_reset_spec.rb
Labels: status - ready for review

#3723 Underscore step names when determining if unsafe-eval is set in capture doc controller
  app/controllers/idv/capture_doc_controller.rb
  app/services/flow/flow_state_machine.rb
  spec/controllers/idv/capture_doc_controller_spec.rb
Labels: status - ready for review

#3728 Add unsafe-eval to the CSP for the Acuant SDK JS and WASM
  app/controllers/acuant_sdk_controller.rb
  spec/requests/acuant_sdk_spec.rb
Labels: status - ready for review

#3733 Add the Acaunt image capture canvas
  app/javascript/app/acuant/document_capture_dom.js
  app/views/idv/_acuant_sdk_document_capture_form.html.erb
  spec/javascripts/app/acuant/document_capture_spec.js
  spec/javascripts/support/acuant/document_capture_dom.js
Labels: status - ready for review

#3735 Move the link on the create account button outside the button's border
  app/assets/stylesheets/components/_btn.scss
  app/views/devise/sessions/new.html.erb
  app/views/devise/sessions/new.html.slim
  spec/views/devise/sessions/new.html.erb_spec.rb
Labels: status - ready for review

#3736 Log time as an iso8601 string, instead of as a float
  config/application.rb
Labels: status - ready for review

#3738 LG-1899 Hide impossible to confirm email address on the account page
  app/decorators/user_decorator.rb
  app/views/accounts/_emails.html.slim
  spec/decorators/user_decorator_spec.rb
  spec/features/multiple_emails/email_management_spec.rb
Labels: status - ready for review

#3737 Add the Acuant SDK to capture-doc routes with a hyphen
  config/routes.rb
Labels: status - ready for review

#3739 LG 2368 Cancel button otp
  .gitignore
  app/controllers/concerns/two_factor_authenticatable_methods.rb
  app/controllers/two_factor_authentication/otp_verification_controller.rb
  app/presenters/two_factor_auth_code/phone_delivery_presenter.rb
  spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
  spec/features/phone/add_phone_spec.rb
  spec/presenters/two_factor_auth_code/phone_delivery_presenter_spec.rb
  spec/views/two_factor_authentication/otp_verification/show.html.slim_spec.rb
Labels: needs code review

#3742 Move assets from the precompilation array to manifest.js
  app/assets/config/manifest.js
  config/initializers/assets.rb
Labels: status - ready for review

#3743 Deploy RC 108.1 to staging
  app/services/idv/steps/doc_auth_base_step.rb
Labels: status - promotion

#3744 Deploy RC 108.1 to prod
  app/services/idv/steps/doc_auth_base_step.rb
Labels: status - promotion
