Repository 18F/identity-idp, pull requests merged in 2020-09, with the labels that each got.

#4156 Register selfie step in doc auth logs
  app/services/funnel/doc_auth/register_step.rb
Labels: status - ready for review

#3981 Stop writing to mfa_device_remembered in the session
  app/controllers/concerns/remember_device_concern.rb
  app/controllers/concerns/two_factor_authenticatable_methods.rb
  app/controllers/two_factor_authentication/backup_code_verification_controller.rb
  app/controllers/two_factor_authentication/personal_key_verification_controller.rb
  app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
  app/controllers/two_factor_authentication/webauthn_verification_controller.rb
Labels: status - ready for review

#4167 LG-3362 Ignore SPs missing IAA start or end dates on billing reports
  app/services/reports/iaa_billing_report.rb
  spec/services/reports/iaa_billing_report_spec.rb
Labels: status - ready for review

#4170 LG-1567 Users can confirm an email while logged into a different account
  app/controllers/concerns/unconfirmed_user_concern.rb
  app/controllers/users/email_confirmations_controller.rb
  app/services/email_confirmation_token_validator.rb
  spec/services/email_confirmation_token_validator_spec.rb
  spec/support/shared_examples/account_creation.rb
Labels: status - ready for review

#4158 Use complete phrase for document capture errors
  config/locales/doc_auth/en.yml
  config/locales/doc_auth/es.yml
  config/locales/doc_auth/fr.yml
  spec/forms/idv/api_image_upload_form_spec.rb
Labels: status - blocked

#4177 Notify via email when resetting password from RISC (LG-3120)
  app/forms/security_event_form.rb
  app/mailers/user_mailer.rb
  app/services/marketing_site.rb
  app/services/reset_password_and_notify_user.rb
  app/services/reset_user_password.rb
  app/services/reset_user_password_and_send_email.rb
  app/views/user_mailer/please_reset_password.html.erb
  app/views/user_mailer/please_reset_password.html.slim
  bin/reset_user_password
  config/locales/user_mailer/en.yml
  config/locales/user_mailer/es.yml
  config/locales/user_mailer/fr.yml
  lib/tasks/reset_user_passwords.rake
  spec/mailers/user_mailer_spec.rb
  spec/services/reset_password_and_notify_user_spec.rb
  spec/services/reset_user_password_and_send_email_spec.rb
  spec/services/reset_user_password_spec.rb
Labels: status - ready for review

#4182 LG-3118 Fix bugs discovered while testing AAL3 flows
  app/controllers/users/webauthn_setup_controller.rb
  app/presenters/two_factor_auth_code/piv_cac_authentication_presenter.rb
  app/presenters/two_factor_auth_code/webauthn_authentication_presenter.rb
  spec/features/webauthn/sign_up_spec.rb
  spec/presenters/two_factor_auth_code/piv_cac_authentication_presenter_spec.rb
  spec/presenters/two_factor_auth_code/webauthn_authentication_presenter_spec.rb
Labels: status - ready for review

#4190 LG-3118 Update the webauthn verification headers
  config/locales/titles/en.yml
  config/locales/titles/es.yml
  config/locales/titles/fr.yml
  config/locales/two_factor_authentication/en.yml
  config/locales/two_factor_authentication/es.yml
  config/locales/two_factor_authentication/fr.yml
Labels: status - ready for review

#4189 LG-3118 Change "Sign in" to "Continue" on user authorization confirmation
  config/locales/user_authorization_confirmation/en.yml
  config/locales/user_authorization_confirmation/es.yml
  config/locales/user_authorization_confirmation/fr.yml
Labels: status - ready for review

#4202 Add maintenance window notification for Acuant (LG-3451)
  app/services/maintenance_window.rb
  app/views/devise/sessions/new.html.erb
  app/views/idv/cac/choose_method.html.erb
  app/views/idv/doc_auth/welcome.html.erb
  app/views/shared/_alert.html.erb
  app/views/shared/_maintenance_window_alert.html.erb
  config/application.yml.default
  config/locales/notices/en.yml
  config/locales/notices/es.yml
  config/locales/notices/fr.yml
  config/locales/time/en.yml
  config/locales/time/es.yml
  config/locales/time/fr.yml
  spec/features/idv/doc_auth/welcome_step_spec.rb
  spec/services/maintenance_window_spec.rb
  spec/views/devise/sessions/new.html.erb_spec.rb
  spec/views/idv/doc_auth/welcome.html.erb_spec.rb
  spec/views/shared/_alert.html.erb_spec.rb
  spec/views/shared/_maintenance_window_alert.html.erb_spec.rb
Labels: status - ready for review

#4191 Tweak PIV/CAC and WebAuthn verification controllers
  app/presenters/two_factor_auth_code/piv_cac_authentication_presenter.rb
  app/presenters/two_factor_auth_code/webauthn_authentication_presenter.rb
  app/views/two_factor_authentication/piv_cac_verification/show.html.erb
  config/locales/instructions/en.yml
  config/locales/instructions/es.yml
  config/locales/instructions/fr.yml
  spec/presenters/two_factor_auth_code/piv_cac_authentication_presenter_spec.rb
  spec/presenters/two_factor_auth_code/webauthn_authentication_presenter_spec.rb
Labels: status - ready for review

#4204 Remove redundant "Connect your key" header
  app/views/two_factor_authentication/webauthn_verification/show.html.erb
Labels: status - ready for review

#4206 Deploy RC 118.1 to Staging
  app/services/maintenance_window.rb
  app/views/devise/sessions/new.html.erb
  app/views/idv/cac/choose_method.html.erb
  app/views/idv/doc_auth/welcome.html.erb
  app/views/shared/_alert.html.erb
  app/views/shared/_maintenance_window_alert.html.erb
  config/application.yml.default
  config/locales/notices/en.yml
  config/locales/notices/es.yml
  config/locales/notices/fr.yml
  config/locales/time/en.yml
  config/locales/time/es.yml
  config/locales/time/fr.yml
  spec/features/idv/doc_auth/welcome_step_spec.rb
  spec/services/maintenance_window_spec.rb
  spec/views/devise/sessions/new.html.erb_spec.rb
  spec/views/idv/doc_auth/welcome.html.erb_spec.rb
  spec/views/shared/_alert.html.erb_spec.rb
  spec/views/shared/_maintenance_window_alert.html.erb_spec.rb
Labels: status - promotion

#4207 Deploy RC 118.1 to Prod
  app/services/maintenance_window.rb
  app/views/devise/sessions/new.html.erb
  app/views/idv/cac/choose_method.html.erb
  app/views/idv/doc_auth/welcome.html.erb
  app/views/shared/_alert.html.erb
  app/views/shared/_maintenance_window_alert.html.erb
  config/application.yml.default
  config/locales/notices/en.yml
  config/locales/notices/es.yml
  config/locales/notices/fr.yml
  config/locales/time/en.yml
  config/locales/time/es.yml
  config/locales/time/fr.yml
  spec/features/idv/doc_auth/welcome_step_spec.rb
  spec/services/maintenance_window_spec.rb
  spec/views/devise/sessions/new.html.erb_spec.rb
  spec/views/idv/doc_auth/welcome.html.erb_spec.rb
  spec/views/shared/_alert.html.erb_spec.rb
  spec/views/shared/_maintenance_window_alert.html.erb_spec.rb
Labels: status - promotion

#4230 LG-3543 Update doc captures to avoid showing the selfie in the hybrid…
  app/controllers/idv/capture_doc_controller.rb
  app/services/capture_doc/create_request.rb
  app/services/capture_doc/validate_document_capture_session.rb
  app/services/capture_doc/validate_request_token.rb
  app/services/flow/base_flow.rb
  app/services/idv/steps/send_link_step.rb
  db/migrate/20200922144112_add_liveness_enabled_fields_to_doc_captures.rb
  db/schema.rb
  spec/controllers/idv/capture_doc_controller_spec.rb
  spec/features/idv/doc_capture/mobile_back_image_step_spec.rb
  spec/services/capture_doc/create_request_spec.rb
  spec/services/capture_doc/find_user_id_spec.rb
  spec/services/capture_doc/update_acuant_token_spec.rb
  spec/support/features/doc_capture_helper.rb
Labels: status - ready for review

#4239 Ensure that structs parsed from JSON can accept new keys (LG-3574)
  app/services/encryption/password_verifier.rb
  app/services/pii/attributes.rb
  app/services/x509/attributes.rb
  spec/services/encryption/encryptors/pii_encryptor_spec.rb
  spec/services/encryption/password_verifier_spec.rb
  spec/services/encryption/uak_password_verifier_spec.rb
  spec/services/pii/attributes_spec.rb
  spec/services/x509/attributes_spec.rb
Labels: status - ready for review
