Repository 18F/identity-idp, pull requests merged in 2020-02, with the labels that each got.

#3557 Update the release checklist
  lib/release_management/deploy_checklist.md.erb
Labels: status - ready for review

#3559 Make the SP cost specs proper feature specs
  spec/features/sp_cost_tracking_spec.rb
Labels: status - ready for review

#3555 (LG-2549) Fix PIV/CAC setup page
  app/views/users/piv_cac_setup_from_sign_in/prompt.slim
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
Labels: status - ready for review

#3543 LG-2392 Add rate limit screen for doc auth image upload
  app/services/idv/steps/doc_auth_base_step.rb
  app/views/idv/session_errors/throttled.html.erb
  config/routes.rb
  spec/features/idv/doc_auth/back_image_step_spec.rb
  spec/features/idv/doc_auth/front_image_step_spec.rb
Labels: status - ready for review

#3558 Log the telephony responses
  app/controllers/users/two_factor_authentication_controller.rb
  app/services/analytics.rb
  spec/controllers/users/two_factor_authentication_controller_spec.rb
Labels: status - ready for review

#3560 Add the PIV/CAC service URL directly to the CSP in local dev
  app/controllers/concerns/piv_cac_concern.rb
Labels: status - ready for review

#3525 LG-2041: Authorization confirmation page
  .rubocop.yml
  app/controllers/application_controller.rb
  app/controllers/concerns/authorization_count_concern.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/controllers/saml_idp_controller.rb
  app/controllers/users/authorization_confirmation_controller.rb
  app/views/users/authorization_confirmation/show.html.erb
  config/initializers/rack_timeout.rb
  config/locales/user_authorization_confirmation/en.yml
  config/locales/user_authorization_confirmation/es.yml
  config/locales/user_authorization_confirmation/fr.yml
  config/routes.rb
  spec/controllers/openid_connect/authorization_controller_spec.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/features/openid_connect/authorization_confirmation_spec.rb
  spec/features/openid_connect/openid_connect_spec.rb
  spec/features/remember_device/session_expiration_spec.rb
  spec/features/saml/authorization_confirmation_spec.rb
  spec/features/saml/ial1_sso_spec.rb
  spec/support/features/session_helper.rb
  spec/support/shared_examples/account_creation.rb
  spec/support/shared_examples/sign_in.rb
Labels: status - ready for review

#3562 LG-2041: logs event on authentication confirmation
  app/controllers/users/authorization_confirmation_controller.rb
  app/services/analytics.rb
Labels: status - ready for review

#3565 Specify the redirect URI in the request to the PKI server
  app/controllers/idv/cac_controller.rb
  app/controllers/test/piv_cac_authentication_test_subject_controller.rb
  app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
  app/controllers/users/piv_cac_authentication_setup_controller.rb
  app/controllers/users/piv_cac_login_controller.rb
  app/presenters/two_factor_auth_code/piv_cac_authentication_presenter.rb
  app/services/piv_cac_service.rb
  app/views/idv/cac/present_cac.html.erb
  config/routes.rb
  spec/controllers/test/piv_cac_authentication_test_subject_controller_spec.rb
  spec/services/piv_cac_service_spec.rb
  spec/support/features/session_helper.rb
Labels: status - ready for review

#3554 LG-2025 Move ServiceProviderRequest to Redis
  app/controllers/application_controller.rb
  app/controllers/concerns/fully_authenticatable.rb
  app/controllers/sign_up/registrations_controller.rb
  app/forms/register_user_email_form.rb
  app/models/service_provider_request.rb
  app/services/service_provider_request_handler.rb
  app/services/service_provider_request_proxy.rb
  app/services/store_sp_metadata_in_session.rb
  config/application.yml.default
  config/initializers/redis.rb
  spec/controllers/openid_connect/authorization_controller_spec.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/decorators/service_provider_session_decorator_spec.rb
  spec/features/openid_connect/openid_connect_spec.rb
  spec/features/remember_device/session_expiration_spec.rb
  spec/features/saml/ial1/account_creation_spec.rb
  spec/features/saml/ial1_sso_spec.rb
  spec/features/session/timeout_spec.rb
  spec/features/users/sign_in_spec.rb
  spec/models/service_provider_request_spec.rb
  spec/requests/openid_connect_authorize_spec.rb
  spec/services/store_sp_metadata_in_session_spec.rb
  spec/support/features/session_helper.rb
  spec/support/shared_examples/account_creation.rb
  spec/support/shared_examples/sign_in.rb
  spec/view_models/sign_up_completions_show_spec.rb
  spec/views/devise/passwords/new.html.slim_spec.rb
  spec/views/devise/sessions/new.html.slim_spec.rb
  spec/views/layouts/application.html.slim_spec.rb
Labels: status - ready for review

#3553 LG-2388 Make recover fail a proper error screen
  app/services/idv/flows/recovery_flow.rb
  app/services/idv/steps/recover_fail_step.rb
  app/services/idv/steps/recover_verify_step.rb
  app/views/idv/doc_auth/recover_fail.html.slim
  app/views/idv/session_errors/recovery_failure.html.erb
  app/views/idv/session_errors/recovery_warning.html.erb
  app/views/idv/shared/_reset_your_account.html.erb
  config/locales/recover/en.yml
  config/locales/recover/es.yml
  config/locales/recover/fr.yml
  config/locales/two_factor_authentication/en.yml
  config/locales/two_factor_authentication/es.yml
  config/locales/two_factor_authentication/fr.yml
  config/routes.rb
  spec/features/idv/recovery/recover_fail_step_spec.rb
  spec/features/idv/recovery/verify_step_spec.rb
  spec/support/features/recovery_helper.rb
Labels: status - ready for review

#3567 Deploy RC 102.1 to staging
  app/controllers/idv/cac_controller.rb
  app/controllers/test/piv_cac_authentication_test_subject_controller.rb
  app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
  app/controllers/users/piv_cac_authentication_setup_controller.rb
  app/controllers/users/piv_cac_login_controller.rb
  app/presenters/two_factor_auth_code/piv_cac_authentication_presenter.rb
  app/services/piv_cac_service.rb
  app/views/idv/cac/present_cac.html.erb
  config/routes.rb
  spec/controllers/test/piv_cac_authentication_test_subject_controller_spec.rb
  spec/features/sp_cost_tracking_spec.rb
  spec/services/piv_cac_service_spec.rb
  spec/support/features/session_helper.rb
Labels: status - promotion

#3569 Redirect users who visit authentication confirmation unauthenticated
  app/controllers/users/authorization_confirmation_controller.rb
  spec/features/openid_connect/authorization_confirmation_spec.rb
  spec/features/saml/authorization_confirmation_spec.rb
Labels: status - ready for review

#3570 LG-2386: Shorten the header on the email sent screen in doc auth recovery flow
  app/views/account_reset/recover/email_sent.html.slim
  config/locales/recover/en.yml
  config/locales/recover/es.yml
  config/locales/recover/fr.yml
Labels: status - ready for review

#3564 Copy in agencies.yml from identity-idp-config repo
  .circleci/config.yml
  .gitignore
  bin/fast_setup
  bin/setup
  config/agencies.localdev.yml
  lib/deploy/activate.rb
Labels: status - ready for review

#3581 LG-2392 Add rate limit screen for doc auth image upload Part 2
  app/services/idv/steps/doc_auth_base_step.rb
  app/views/idv/session_errors/recovery_throttled.html.erb
  config/routes.rb
  spec/features/idv/recovery/back_image_step_spec.rb
Labels: status - ready for review

#3579 LG-1898: Stop truncating long emails
  app/views/accounts/_emails.html.slim
  spec/features/multiple_emails/add_email_spec.rb
Labels: status - ready for review

#3585 Docker: Increase DB statement timeout for Docker
  docker-compose.yml
Labels: status - ready for review

#3583 LG-2556: openid connect spec refactor
  spec/features/openid_connect/authorization_confirmation_spec.rb
  spec/features/openid_connect/openid_connect_spec.rb
  spec/rails_helper.rb
  spec/support/oidc_auth_helper.rb
Labels: status - ready for review

#3563 WIP : LG-2562 : Create IDP container with Docker
  .dockerignore
  .gitignore
  Dockerfile
  Makefile
  README.md
  bin/docker_setup
  bin/setup
  docker-compose.yml
  spec/support/capybara.rb
  spec/support/database_cleaner.rb
Labels: status - ready for review

#3582 LG-2025 Move service_service_provider_requests to redis part 2
  app/models/service_provider_request.rb
  app/services/service_provider_request_proxy.rb
  spec/factories/service_provider_requests.rb
  spec/forms/register_user_email_form_spec.rb
Labels: status - do not merge, status - ready for review

#3574 LG-2564 LG-2565 IALMAX for SAML and OIDC
  app/controllers/sign_up/completions_controller.rb
  app/forms/openid_connect_authorize_form.rb
  app/presenters/openid_connect_user_info_presenter.rb
  app/presenters/saml_request_presenter.rb
  app/services/id_token_builder.rb
  app/services/store_sp_metadata_in_session.rb
  app/view_models/sign_up_completions_show.rb
  app/views/sign_up/completions/_requested_attributes.html.slim
  config/application.yml.default
  lib/saml_idp_constants.rb
  spec/controllers/openid_connect/authorization_controller_spec.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/features/users/sign_in_spec.rb
  spec/services/store_sp_metadata_in_session_spec.rb
  spec/support/saml_auth_helper.rb
  spec/view_models/sign_up_completions_show_spec.rb
  spec/views/sign_up/completions/show.html.slim_spec.rb
Labels: status - ready for review

#3591 LG-2622 Fix CAC error when attempting to proof
  app/controllers/idv/cac_controller.rb
  spec/features/idv/cac/present_cac_step_spec.rb
  spec/support/features/cac_proofing_helper.rb
Labels: status - ready for review

#3590 LG-2623 Better logging for PIV/CAC errors
  app/forms/concerns/piv_cac_form_helpers.rb
  app/forms/user_piv_cac_login_form.rb
  app/forms/user_piv_cac_setup_form.rb
  app/forms/user_piv_cac_verification_form.rb
  spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb
  spec/features/users/piv_cac_management_spec.rb
  spec/forms/user_piv_cac_setup_form_spec.rb
  spec/forms/user_piv_cac_verification_form_spec.rb
Labels: status - ready for review

#3587 LG-2025 Move service_service_provider_requests to redis part 3
  db/migrate/20200210235313_drop_service_provider_requests.rb
  db/schema.rb
Labels: status - ready for review
