Repository 18F/identity-idp, pull requests merged in 2020-08, with the labels that each got.

#4001 Log acuant result code, if billable (LG-2495)
  app/services/acuant/acuant_client.rb
  app/services/acuant/responses/get_results_response.rb
  app/services/acuant/responses/liveness_response.rb
  app/services/acuant/responses/response_with_pii.rb
  app/services/acuant/result_codes.rb
  app/services/db/proofing_cost/add_user_proofing_cost.rb
  app/services/doc_auth_mock/doc_auth_mock_client.rb
  app/services/doc_auth_mock/responses/get_results_response.rb
  app/services/doc_auth_mock/result_response_builder.rb
  app/services/idv/steps/back_image_step.rb
  app/services/idv/steps/doc_auth_base_step.rb
  db/migrate/20200731213827_add_acuant_result_to_proofing_costs.rb
  db/schema.rb
  spec/features/reports/proofing_costs_report_spec.rb
  spec/services/acuant/responses/get_results_response_spec.rb
  spec/services/acuant/responses/liveness_response_spec.rb
  spec/services/acuant/result_codes_spec.rb
Labels: status - ready for review

#4018 Log face match results to events.log (LG-2495)
  app/services/acuant/acuant_client.rb
  app/services/acuant/responses/get_results_response.rb
  app/services/acuant/responses/response_with_pii.rb
  app/services/analytics.rb
  app/services/doc_auth_mock/doc_auth_mock_client.rb
  app/services/doc_auth_mock/responses/get_results_response.rb
  app/services/doc_auth_mock/result_response_builder.rb
  app/services/flow/base_flow.rb
  app/services/idv/steps/document_capture_step.rb
  app/services/idv/steps/selfie_step.rb
  spec/features/idv/doc_auth/document_capture_step_spec.rb
  spec/features/idv/doc_auth/selfie_step_spec.rb
  spec/services/acuant/responses/get_results_response_spec.rb
  spec/support/fake_analytics.rb
Labels: status - ready for review

#4014 Merge logic for dealing with AAL3 and PIV/CAC requirement
  app/controllers/application_controller.rb
  app/controllers/concerns/aal3_concern.rb
  app/controllers/concerns/mfa_setup_concern.rb
  app/controllers/concerns/two_factor_authenticatable.rb
  app/controllers/concerns/two_factor_authenticatable_methods.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/controllers/saml_idp_controller.rb
  app/controllers/two_factor_authentication/backup_code_verification_controller.rb
  app/controllers/two_factor_authentication/options_controller.rb
  app/controllers/two_factor_authentication/otp_verification_controller.rb
  app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
  app/controllers/two_factor_authentication/webauthn_verification_controller.rb
  app/controllers/users/two_factor_authentication_controller.rb
  app/controllers/users/two_factor_authentication_setup_controller.rb
  app/policies/aal3_policy.rb
  app/policies/service_provider_mfa_policy.rb
  app/presenters/two_factor_auth_code/generic_delivery_presenter.rb
  app/presenters/two_factor_auth_code/piv_cac_authentication_presenter.rb
  app/presenters/two_factor_auth_code/webauthn_authentication_presenter.rb
  app/presenters/two_factor_login_options_presenter.rb
  app/views/service_provider_mfa/new.html.erb
  spec/controllers/openid_connect/authorization_controller_spec.rb
  spec/controllers/users/two_factor_authentication_controller_spec.rb
  spec/features/openid_connect/aal3_required_spec.rb
  spec/features/saml/aal3_required_spec.rb
  spec/policies/aal3_policy_spec.rb
  spec/policies/service_provider_mfa_policy_spec.rb
  spec/presenters/two_factor_auth_code/piv_cac_authentication_presenter_spec.rb
  spec/presenters/two_factor_auth_code/webauthn_authentication_presenter_spec.rb
  spec/presenters/two_factor_login_options_presenter_spec.rb
  spec/views/two_factor_authentication/options/index.html.slim_spec.rb
Labels: status - ready for review

#4019 LG-3099: request multiple authn contexts
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/concerns/saml_idp_auth_concern.rb
  app/models/federated_protocols/saml.rb
  app/presenters/saml_request_presenter.rb
  app/services/attribute_asserter.rb
  app/services/saml_request_validator.rb
  lib/saml_idp_constants.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/presenters/saml_request_presenter_spec.rb
  spec/services/attribute_asserter_spec.rb
  spec/services/saml_request_validator_spec.rb
  spec/support/fake_saml_request.rb
  spec/support/saml_auth_helper.rb
Labels: status - ready for review

#4060 Create a generic doc auth client response
  app/services/acuant/acuant_client.rb
  app/services/acuant/request.rb
  app/services/acuant/requests/upload_image_request.rb
  app/services/acuant/response.rb
  app/services/acuant/responses/create_document_response.rb
  app/services/acuant/responses/facial_match_response.rb
  app/services/acuant/responses/get_face_image_response.rb
  app/services/acuant/responses/get_results_response.rb
  app/services/acuant/responses/liveness_response.rb
  app/services/acuant/responses/response_with_pii.rb
  app/services/acuant/responses/upload_image_response.rb
  app/services/doc_auth_client.rb
  app/services/doc_auth_client/response.rb
  app/services/doc_auth_mock/doc_auth_mock_client.rb
  app/services/doc_auth_mock/responses/create_document_response.rb
  app/services/doc_auth_mock/responses/get_results_response.rb
  app/services/doc_auth_mock/result_response_builder.rb
  app/services/flow/base_flow.rb
  app/services/idv/steps/doc_auth_base_step.rb
  spec/features/idv/doc_auth/back_image_step_spec.rb
  spec/features/idv/doc_auth/document_capture_step_spec.rb
  spec/features/idv/doc_auth/front_image_step_spec.rb
  spec/features/idv/doc_auth/mobile_back_image_step_spec.rb
  spec/features/idv/doc_auth/mobile_document_capture_step_spec.rb
  spec/features/idv/doc_auth/selfie_step_spec.rb
  spec/features/idv/doc_capture/selfie_step_spec.rb
  spec/services/acuant/acuant_client_spec.rb
  spec/services/acuant/responses/upload_image_response_spec.rb
  spec/services/doc_auth_mock/dock_auth_mock_client_spec.rb
  spec/services/doc_auth_mock/result_response_builder_spec.rb
  spec/support/features/doc_auth_helper.rb
Labels: status - ready for review

#4072 Deploy RC 116.1 to staging
  Gemfile
  Gemfile.lock
Labels: status - promotion

#4075 Deploy RC 116.1 to production
  Gemfile
  Gemfile.lock
Labels: status - promotion

#3980 Use `auth_method` to determine if remember device was used
  app/controllers/concerns/remember_device_concern.rb
Labels: status - blocked, status - do not merge

#4088 Use the stored result from the image upload API in document capture step
  app/models/document_capture_session.rb
  app/models/user.rb
  app/services/document_capture_session_result.rb
  app/services/idv/steps/doc_auth_base_step.rb
  app/services/idv/steps/document_capture_step.rb
  app/services/idv/steps/welcome_step.rb
  db/migrate/20200811144552_create_document_capture_sessions.rb
  db/schema.rb
  spec/features/idv/doc_auth/document_capture_step_spec.rb
  spec/models/document_capture_session_spec.rb
  spec/services/document_capture_session_result_spec.rb
Labels: status - ready for review

#4092 Wire doc capture session to the upload controller
  app/controllers/idv/image_uploads_controller.rb
  app/forms/idv/api_image_upload_form.rb
  app/javascript/packages/document-capture/context/upload.jsx
  app/javascript/packs/document-capture.jsx
  app/models/document_capture_session.rb
  app/views/idv/doc_auth/document_capture.html.erb
  spec/controllers/idv/image_uploads_controller_spec.rb
  spec/forms/idv/api_image_upload_form_spec.rb
  spec/javascripts/packages/document-capture/context/upload-spec.jsx
Labels: status - ready for review

#4123 LG-3295 Remove overcommit
  .overcommit.yml
  CONTRIBUTING.md
  Gemfile
  Gemfile.lock
  README.md
  bin/remove-overcommit
  bin/setup
Labels: status - ready for review

#4133 Clean up Acuant date parsing
  app/services/doc_auth/acuant/pii_from_doc.rb
  spec/services/doc_auth/acuant/pii_from_doc_spec.rb
Labels: status - ready for review

#4139 Deploy RC 117 with unsafe-eval changes to staging
  app/controllers/idv/capture_doc_controller.rb
  app/controllers/idv/doc_auth_controller.rb
Labels: status - promotion

#4146 LG-3368 Don't show duplicate Acuant error messages
  app/services/doc_auth/acuant/responses/get_results_response.rb
  spec/services/doc_auth/acuant/responses/get_results_response_spec.rb
Labels: status - ready for review

#4149 Exclude document capture from rack timeout
  config/initializers/rack_timeout.rb
Labels: status - ready for review

#4155 RISC notifications: reset password for authorization fraud (LG-3344)
  app/controllers/risc/security_events_controller.rb
  app/forms/security_event_form.rb
  app/services/reset_user_password.rb
  app/services/reset_user_password_and_send_email.rb
  spec/controllers/risc/security_events_controller_spec.rb
Labels: status - ready for review
