Repository 18F/identity-idp, pull requests merged in 2020-06, with the labels that each got.

#3803 LG-3063 Collect proofing w/CAC funnel data to calculate drop off rates
  app/controllers/idv/cac_controller.rb
  app/services/funnel/doc_auth/register_step.rb
  db/migrate/20200530185607_add_proofing_with_cac_steps_to_doc_auth_logs.rb
  db/schema.rb
  spec/features/idv/cac/present_cac_step_spec.rb
  spec/features/reports/doc_auth_funnel_report_spec.rb
Labels: status - ready for review

#3805 Deploy RC 110.4 to staging
  app/controllers/idv/cac_controller.rb
  app/services/funnel/doc_auth/register_step.rb
  db/migrate/20200530185607_add_proofing_with_cac_steps_to_doc_auth_logs.rb
  db/schema.rb
  spec/features/idv/cac/present_cac_step_spec.rb
  spec/features/reports/doc_auth_funnel_report_spec.rb
Labels: status - promotion

#3806 Deploy RC 110.4 to production
  app/controllers/idv/cac_controller.rb
  app/services/funnel/doc_auth/register_step.rb
  db/migrate/20200530185607_add_proofing_with_cac_steps_to_doc_auth_logs.rb
  db/schema.rb
  spec/features/idv/cac/present_cac_step_spec.rb
  spec/features/reports/doc_auth_funnel_report_spec.rb
Labels: status - promotion

#3809 Fix selfie checking on hybrid flow; add selfie checking to funnel
  app/services/acuant/acuant_base.rb
  app/services/idv/steps/link_sent_step.rb
  app/views/idv/capture_doc/selfie.html.erb
  db/migrate/20200601235647_add_liveness_steps_to_doc_auth_logs.rb
  db/schema.rb
  spec/controllers/idv/scan_id_acuant_controller_spec.rb
  spec/features/idv/doc_capture/selfie_step_spec.rb
  spec/features/reports/doc_auth_funnel_report_spec.rb
  spec/support/features/doc_capture_helper.rb
Labels: status - ready for review

#3807 LG-954 Retain events for users that delete their account
  app/controllers/users/delete_controller.rb
  app/models/deleted_user.rb
  app/models/device.rb
  app/models/user.rb
  app/services/account_reset/delete_account.rb
  app/services/db/deleted_user/create.rb
  db/migrate/20200601215509_create_deleted_users.rb
  db/schema.rb
  spec/features/account_reset/delete_account_spec.rb
  spec/services/db/deleted_user/create_spec.rb
Labels: status - ready for review

#3813 Deploy RC 111 to staging
  Gemfile
  Gemfile.lock
  app/controllers/account_reset/request_controller.rb
  app/controllers/two_factor_authentication/personal_key_verification_controller.rb
  app/controllers/users/delete_controller.rb
  app/controllers/users/personal_keys_controller.rb
  app/models/deleted_user.rb
  app/models/device.rb
  app/models/null_service_provider.rb
  app/models/user.rb
  app/services/account_reset/cancel.rb
  app/services/account_reset/create_request.rb
  app/services/account_reset/delete_account.rb
  app/services/acuant/acuant_base.rb
  app/services/analytics.rb
  app/services/db/deleted_user/create.rb
  app/services/idv/steps/link_sent_step.rb
  app/services/sms_responder.rb
  app/services/user_alerts/alert_user_about_personal_key_sign_in.rb
  app/views/accounts/_email.html.slim
  app/views/accounts/_webauthn.html.erb
  app/views/accounts/_webauthn.html.slim
  app/views/idv/capture_doc/selfie.html.erb
  app/views/idv/session_errors/recovery_warning.html.erb
  config/initializers/telephony.rb
  db/migrate/20200601215509_create_deleted_users.rb
  db/migrate/20200601235647_add_liveness_steps_to_doc_auth_logs.rb
  db/schema.rb
  production.Dockerfile
  spec/controllers/account_reset/cancel_controller_spec.rb
  spec/controllers/account_reset/request_controller_spec.rb
  spec/controllers/idv/scan_id_acuant_controller_spec.rb
  spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb
  spec/controllers/users/personal_keys_controller_spec.rb
  spec/features/account_reset/delete_account_spec.rb
  spec/features/idv/doc_auth/verify_step_spec.rb
  spec/features/idv/doc_capture/selfie_step_spec.rb
  spec/features/idv/recovery/verify_step_spec.rb
  spec/features/reports/doc_auth_funnel_report_spec.rb
  spec/models/null_service_provider_spec.rb
  spec/services/account_reset/cancel_spec.rb
  spec/services/account_reset/create_request_spec.rb
  spec/services/db/deleted_user/create_spec.rb
  spec/services/user_alerts/alert_user_about_personal_key_sign_in_spec.rb
  spec/support/features/doc_capture_helper.rb
Labels: status - promotion

#3780 LG-2944: account reset disavow
  app/assets/stylesheets/components/_btn.scss
  app/assets/stylesheets/email.css.scss
  app/controllers/account_reset/pending_controller.rb
  app/controllers/users/sessions_controller.rb
  app/presenters/account_reset/pending_presenter.rb
  app/services/account_reset/cancel_request_for_user.rb
  app/services/account_reset/find_pending_request_for_user.rb
  app/services/account_reset/notify_user_of_request_cancellation.rb
  app/services/analytics.rb
  app/views/account_reset/pending/cancel.html.erb
  app/views/account_reset/pending/confirm.html.erb
  app/views/account_reset/pending/show.html.erb
  config/locales/account_reset/en.yml
  config/locales/account_reset/es.yml
  config/locales/account_reset/fr.yml
  config/locales/links/en.yml
  config/locales/links/es.yml
  config/locales/links/fr.yml
  config/routes.rb
  spec/controllers/account_reset/pending_controller_spec.rb
  spec/controllers/users/sessions_controller_spec.rb
  spec/features/account_reset/pending_request_spec.rb
  spec/presenters/account_reset/pending_presenter_spec.rb
  spec/services/account_reset/cancel_request_for_user_spec.rb
  spec/services/account_reset/find_prending_request_for_user_spec.rb
  spec/services/account_reset/notify_user_of_request_cancellation_spec.rb
Labels: status - ready for review

#3814 Deploy RC 111 to production
  Gemfile
  Gemfile.lock
  app/controllers/account_reset/request_controller.rb
  app/controllers/two_factor_authentication/personal_key_verification_controller.rb
  app/controllers/users/delete_controller.rb
  app/controllers/users/personal_keys_controller.rb
  app/models/deleted_user.rb
  app/models/device.rb
  app/models/null_service_provider.rb
  app/models/user.rb
  app/services/account_reset/cancel.rb
  app/services/account_reset/create_request.rb
  app/services/account_reset/delete_account.rb
  app/services/acuant/acuant_base.rb
  app/services/analytics.rb
  app/services/db/deleted_user/create.rb
  app/services/idv/steps/link_sent_step.rb
  app/services/sms_responder.rb
  app/services/user_alerts/alert_user_about_personal_key_sign_in.rb
  app/views/accounts/_email.html.slim
  app/views/accounts/_webauthn.html.erb
  app/views/accounts/_webauthn.html.slim
  app/views/idv/capture_doc/selfie.html.erb
  app/views/idv/session_errors/recovery_warning.html.erb
  config/initializers/telephony.rb
  db/migrate/20200601215509_create_deleted_users.rb
  db/migrate/20200601235647_add_liveness_steps_to_doc_auth_logs.rb
  db/schema.rb
  production.Dockerfile
  spec/controllers/account_reset/cancel_controller_spec.rb
  spec/controllers/account_reset/request_controller_spec.rb
  spec/controllers/idv/scan_id_acuant_controller_spec.rb
  spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb
  spec/controllers/users/personal_keys_controller_spec.rb
  spec/features/account_reset/delete_account_spec.rb
  spec/features/idv/doc_auth/verify_step_spec.rb
  spec/features/idv/doc_capture/selfie_step_spec.rb
  spec/features/idv/recovery/verify_step_spec.rb
  spec/features/reports/doc_auth_funnel_report_spec.rb
  spec/models/null_service_provider_spec.rb
  spec/services/account_reset/cancel_spec.rb
  spec/services/account_reset/create_request_spec.rb
  spec/services/db/deleted_user/create_spec.rb
  spec/services/user_alerts/alert_user_about_personal_key_sign_in_spec.rb
  spec/support/features/doc_capture_helper.rb
Labels: status - promotion

#3812 LG-2579 Add Support for Multi-Region KMS Encryption
  app/services/encryption/kms_client.rb
  app/services/encryption/multi_region_kms_client.rb
  config/application.yml.default
  spec/services/encryption/kms_client_spec.rb
  spec/services/encryption/multi_region_kms_client_spec.rb
  spec/support/aws_kms_client.rb
Labels: status - ready for review

#3804 LG-2740 Upgrade users to be IAL2 NIST conformant
  app/controllers/concerns/idv_session.rb
  app/controllers/concerns/saml_idp_auth_concern.rb
  app/controllers/idv_controller.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/controllers/users/piv_cac_login_controller.rb
  app/forms/openid_connect_authorize_form.rb
  app/models/identity.rb
  app/models/profile.rb
  app/presenters/openid_connect_user_info_presenter.rb
  app/presenters/saml_request_presenter.rb
  app/services/attribute_asserter.rb
  app/services/id_token_builder.rb
  app/services/identity_linker.rb
  app/services/idv/steps/doc_auth_base_step.rb
  app/services/store_sp_metadata_in_session.rb
  app/view_models/sign_up_completions_show.rb
  config/application.yml.default
  config/locales/openid_connect/en.yml
  config/locales/openid_connect/es.yml
  config/locales/openid_connect/fr.yml
  lib/saml_idp_constants.rb
  spec/controllers/openid_connect/authorization_controller_spec.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/features/idv/liveness/upgrade_to_strong_ial2_spec.rb
  spec/services/store_sp_metadata_in_session_spec.rb
  spec/support/features/doc_auth_helper.rb
  spec/support/features/idv_helper.rb
Labels: status - ready for review

#3816 LG-2579 Multi Region KMS fix/reintroduction
  app/services/encryption/kms_client.rb
  app/services/encryption/multi_region_kms_client.rb
  config/application.yml.default
  lib/feature_management.rb
  spec/services/encryption/kms_client_spec.rb
  spec/services/encryption/multi_region_kms_client_spec.rb
Labels: status - ready for review

#3821 Allow user to re-send email confirmation link after expired (LG-3084)
  app/controllers/users/emails_controller.rb
  app/forms/add_user_email_form.rb
  app/validators/form_add_email_validator.rb
  app/views/users/emails/show.html.slim
  spec/features/multiple_emails/add_email_spec.rb
  spec/forms/add_user_email_form_spec.rb
Labels: status - ready for review

#3822 Deploy RC 111.1 to staging
  app/controllers/users/emails_controller.rb
  app/forms/add_user_email_form.rb
  app/validators/form_add_email_validator.rb
  app/views/users/emails/show.html.slim
  spec/features/multiple_emails/add_email_spec.rb
  spec/forms/add_user_email_form_spec.rb
Labels: status - promotion

#3823 Deploy RC 111.1 to production
  app/controllers/users/emails_controller.rb
  app/forms/add_user_email_form.rb
  app/validators/form_add_email_validator.rb
  app/views/users/emails/show.html.slim
  spec/features/multiple_emails/add_email_spec.rb
  spec/forms/add_user_email_form_spec.rb
Labels: status - promotion

#3818 LG-2299 change copy on the re-enter your password to encrypt screen
  app/views/idv/in_person/encrypt.html.slim
  app/views/idv/review/new.html.slim
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
  config/locales/in_person_proofing/en.yml
  config/locales/in_person_proofing/es.yml
  config/locales/in_person_proofing/fr.yml
Labels: status - ready for review

#3820 LG-3082 Add proofing with PIVs and more PIV/CAC error logging
  app/controllers/idv/cac_controller.rb
  app/forms/idv/cac_form.rb
  app/forms/piv_cac_proofing_form.rb
  app/services/flow/base_step.rb
  app/services/idv/steps/cac/enter_info_step.rb
  app/services/piv_cac/extract_cn_from_subject.rb
  app/services/piv_cac/is_full_name_in_cn.rb
  app/services/piv_cac/sanitize_cn.rb
  app/views/idv/cac/enter_info.html.erb
  config/locales/cac_proofing/en.yml
  config/locales/cac_proofing/es.yml
  config/locales/cac_proofing/fr.yml
  spec/features/idv/cac/enter_info_step_spec.rb
  spec/features/idv/cac/present_cac_step_spec.rb
  spec/forms/piv_cac_proofing_form_spec.rb
  spec/services/piv_cac/cn_fields_from_subject_spec.rb
  spec/services/piv_cac/extract_cn_from_subject_spec.rb
  spec/services/piv_cac/is_full_name_in_cn_spec.rb
  spec/services/piv_cac/sanitize_cn_spec.rb
  spec/support/features/cac_proofing_helper.rb
Labels: status - ready for review

#3826 Add a mobile headless chrome driver
  spec/features/users/regenerate_personal_key_spec.rb
  spec/features/visitors/i18n_spec.rb
  spec/support/capybara.rb
Labels: status - ready for review

#3827 Change references from CAC to PIV/CAC in CAC proofing
  config/locales/cac_proofing/en.yml
  config/locales/cac_proofing/es.yml
  config/locales/cac_proofing/fr.yml
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
Labels: status - ready for review

#3828 Fix HTML escaping of info banner (LG-3098)
  app/views/shared/_banner.html.erb
  config/locales/shared/en.yml
  config/locales/shared/es.yml
  config/locales/shared/fr.yml
  spec/views/shared/_banner.html.erb_spec.rb
Labels: status - ready for review

#3831 Update aamva gem to get retries (LG-3051)
  Gemfile
  Gemfile.lock
Labels: status - ready for review

#3836 LG-3091 Fix liveness not loading in hybrid flow
  app/controllers/idv/capture_doc_controller.rb
  spec/controllers/idv/capture_doc_controller_spec.rb
  spec/controllers/idv/doc_auth_controller_spec.rb
Labels: status - ready for review

#3841 Don't output the test profile in parallel mode
  spec/spec_helper.rb
Labels: status - ready for review

#3842 Store last service provider request uuid in runtime
  app/services/service_provider_request_proxy.rb
Labels: status - ready for review

#3839 LG-3060 Enforce SP AAL3 requirements
  app/controllers/concerns/two_factor_authenticatable_methods.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/controllers/two_factor_authentication/webauthn_verification_controller.rb
  app/controllers/users/aal3_rejection_controller.rb
  app/controllers/users/two_factor_authentication_controller.rb
  app/policies/aal3_policy.rb
  app/views/two_factor_authentication/options/no_option.html.erb
  config/locales/titles/en.yml
  config/locales/titles/es.yml
  config/locales/titles/fr.yml
  config/locales/two_factor_authentication/en.yml
  config/locales/two_factor_authentication/es.yml
  config/locales/two_factor_authentication/fr.yml
  config/routes.rb
  spec/controllers/openid_connect/authorization_controller_spec.rb
  spec/controllers/users/aal3_rejection_spec.rb
Labels: status - ready for review

#3852 Deploy RC 112.1 to Staging
  app/models/service_provider_request.rb
  spec/services/service_provider_request_proxy_spec.rb
Labels: status - promotion

#3857 Update redis, silence deprecation warning with note
  Gemfile.lock
  config/initializers/session_store.rb
Labels: status - ready for review

#3858 RSpec: use dot formatter in CI
  spec/spec_helper.rb
Labels: status - ready for review

#3855 IAL context cleanup (LG-3106)
  app/controllers/concerns/saml_idp_auth_concern.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/forms/openid_connect_authorize_form.rb
  app/services/attribute_asserter.rb
  app/services/ial_context.rb
  app/services/store_sp_metadata_in_session.rb
  spec/services/attribute_asserter_spec.rb
  spec/services/ial_context_spec.rb
  spec/services/store_sp_metadata_in_session_spec.rb
Labels: status - ready for review

#3859 Enable voice calls for Jordan
  config/country_dialing_codes.yml
Labels: status - ready for review

#3854 LG-3114 LG-3115 Add app_id to service_providers and SP reports
  app/models/null_service_provider.rb
  app/services/db/identity/sp_active_user_counts.rb
  app/services/db/identity/sp_user_counts.rb
  app/services/db/identity/sp_user_quotas.rb
  app/services/db/monthly_sp_auth_count/total_monthly_auth_counts.rb
  app/services/db/monthly_sp_auth_count/unique_monthly_auth_counts.rb
  app/services/db/monthly_sp_auth_count/unique_yearly_auth_counts.rb
  app/services/db/sp_cost/sp_cost_summary.rb
  app/services/db/sp_return_log/success_rate_by_sp.rb
  db/migrate/20200619121722_add_app_id_to_service_providers.rb
  db/schema.rb
  spec/features/reports/sp_active_users_report_spec.rb
  spec/features/reports/sp_success_rate_report_spec.rb
  spec/models/null_service_provider_spec.rb
  spec/services/db/identity/sp_active_user_counts_spec.rb
  spec/services/db/identity/sp_user_counts_spec.rb
  spec/services/db/identity/sp_user_quotas_spec.rb
  spec/services/db/monthly_auth_count/total_monthly_auth_counts_spec.rb
  spec/services/db/monthly_auth_count/unique_monthly_auth_counts_spec.rb
  spec/services/db/monthly_auth_count/unique_yearly_auth_counts_spec.rb
  spec/services/reports/sp_active_users_over_period_of_performance_report_spec.rb
  spec/services/reports/sp_active_users_report_spec.rb
  spec/services/reports/sp_cost_report_spec.rb
  spec/services/reports/sp_user_counts_report_spec.rb
  spec/services/reports/sp_user_quotas_report_spec.rb
  spec/services/reports/total_monthly_auths_report_spec.rb
  spec/services/reports/unique_monthly_auths_report_spec.rb
  spec/services/reports/unique_yearly_auths_report_spec.rb
Labels: status - ready for review

#3866 Add methods for liveness to the Acuant Client
  app/services/acuant/acuant_client.rb
  app/services/acuant/requests/facial_match_request.rb
  app/services/acuant/requests/get_face_image_request.rb
  app/services/acuant/requests/liveness_request.rb
  app/services/acuant/response.rb
  app/services/acuant/responses/facial_match_response.rb
  app/services/acuant/responses/get_face_image_response.rb
  app/services/acuant/responses/liveness_response.rb
  app/services/acuant_mock/acuant_mock_client.rb
  config/application.yml.default
  spec/fixtures/acuant_responses/facial_match_response_failure.json
  spec/fixtures/acuant_responses/facial_match_response_success.json
  spec/fixtures/acuant_responses/get_face_image_response.jpg
  spec/fixtures/acuant_responses/liveness_response_failure.json
  spec/fixtures/acuant_responses/liveness_response_success.json
  spec/fixtures/doc_auth_images/id-face.jpg
  spec/services/acuant/acuant_client_spec.rb
  spec/services/acuant/requests/create_document_request_spec.rb
  spec/services/acuant/requests/facial_match_request_spec.rb
  spec/services/acuant/requests/get_face_image_request_spec.rb
  spec/services/acuant/requests/get_results_request_spec.rb
  spec/services/acuant/requests/liveness_request_spec.rb
  spec/services/acuant/requests/upload_image_request_spec.rb
  spec/services/acuant/responses/facial_match_response_spec.rb
  spec/services/acuant/responses/get_face_image_response_spec.rb
  spec/services/acuant/responses/liveness_response_spec.rb
  spec/services/acuant_mock/acuant_mock_client_spec.rb
  spec/services/idv/acuant/facial_match_spec.rb
  spec/services/idv/acuant/liveness_spec.rb
  spec/support/acuant_fixtures.rb
  spec/support/doc_auth_image_fixtures.rb
Labels: status - ready for review

#3860 Reword liveness upload button and up rack timeouts for liveness requests
  app/views/idv/capture_doc/selfie.html.erb
  app/views/idv/doc_auth/selfie.html.erb
  config/initializers/rack_timeout.rb
  config/locales/doc_auth/en.yml
  config/locales/doc_auth/es.yml
  config/locales/doc_auth/fr.yml
Labels: status - ready for review

#3869 Integrate the Acuant client into the selfie step
  app/services/acuant/acuant_base.rb
  app/services/acuant/liveness.rb
  app/services/acuant_mock/acuant_mock_client.rb
  app/services/idv/acuant/assure_id.rb
  app/services/idv/acuant/facial_match.rb
  app/services/idv/acuant/fake_assure_id.rb
  app/services/idv/acuant/fake_liveness.rb
  app/services/idv/acuant/http.rb
  app/services/idv/acuant/liveness.rb
  app/services/idv/steps/selfie_step.rb
  spec/features/idv/doc_auth/selfie_step_spec.rb
  spec/features/idv/doc_capture/selfie_step_spec.rb
  spec/features/idv/liveness/upgrade_to_strong_ial2_spec.rb
  spec/services/acuant/liveness_spec.rb
  spec/services/idv/acuant/assure_id_spec.rb
  spec/services/idv/acuant/facial_match_spec.rb
  spec/services/idv/acuant/liveness_spec.rb
  spec/support/features/doc_auth_helper.rb
Labels: status - ready for review

#3871 LG-3021 Replace the acuant client with an adaptable doc auth client
  app/services/doc_auth_mock/doc_auth_mock_client.rb
  app/services/doc_auth_mock/responses/create_document_response.rb
  app/services/doc_auth_mock/responses/get_results_response.rb
  app/services/doc_auth_mock/result_response_builder.rb
  app/services/idv/steps/back_image_step.rb
  app/services/idv/steps/doc_auth_base_step.rb
  app/services/idv/steps/front_image_step.rb
  app/services/idv/steps/link_sent_step.rb
  app/services/idv/steps/mobile_back_image_step.rb
  app/services/idv/steps/mobile_front_image_step.rb
  app/services/idv/steps/selfie_step.rb
  config/application.yml.default
  config/initializers/acuant_simulator_config_validation.rb
  spec/features/idv/doc_auth/back_image_step_spec.rb
  spec/features/idv/doc_auth/front_image_step_spec.rb
  spec/features/idv/doc_auth/mobile_back_image_step_spec.rb
  spec/features/idv/doc_auth/mobile_front_image_step_spec.rb
  spec/features/idv/doc_auth/selfie_step_spec.rb
  spec/features/idv/doc_auth/test_credentials_spec.rb
  spec/features/idv/doc_auth/verify_step_spec.rb
  spec/features/idv/doc_capture/mobile_back_image_step_spec.rb
  spec/features/idv/doc_capture/mobile_front_image_step_spec.rb
  spec/features/idv/doc_capture/selfie_step_spec.rb
  spec/features/idv/recovery/back_image_step_spec.rb
  spec/features/idv/recovery/front_image_step_spec.rb
  spec/features/idv/recovery/recover_fail_step_spec.rb
  spec/features/idv/recovery/verify_step_spec.rb
  spec/rails_helper.rb
  spec/services/acuant_mock/acuant_mock_client_spec.rb
  spec/services/acuant_mock/result_response_builder_spec.rb
  spec/support/features/doc_auth_helper.rb
  spec/support/idv_examples/sp_requested_attributes.rb
Labels: status - ready for review

#3864 LG-3061: configure aal3 if requested
  app/assets/images/icon-lock-alert-important.svg
  app/controllers/application_controller.rb
  app/controllers/concerns/two_factor_authenticatable_methods.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/controllers/users/aal3_controller.rb
  app/controllers/users/two_factor_authentication_controller.rb
  app/controllers/users/two_factor_authentication_setup_controller.rb
  app/policies/aal3_policy.rb
  app/policies/mfa_policy.rb
  app/presenters/two_factor_options_presenter.rb
  app/views/users/two_factor_authentication_setup/index.html.erb
  config/locales/two_factor_authentication/en.yml
  config/locales/two_factor_authentication/es.yml
  config/locales/two_factor_authentication/fr.yml
  config/routes.rb
  spec/controllers/openid_connect/authorization_controller_spec.rb
  spec/controllers/users/aal3_controller_spec.rb
  spec/features/openid_connect/aal3_requested_spec.rb
  spec/support/oidc_auth_helper.rb
Labels: status - do not merge, status - ready for review
