Repository 18F/identity-idp, pull requests merged in 2020-10, with the labels that each got.

#4254 LG-3158 Force people with invalid doc auth configs to upgrade
  config/initializers/acuant_simulator_config_validation.rb
Labels: status - ready for review

#4263 Generate pre-signed S3 upload URLs for doc_auth capture (LG-3415)
  app/helpers/aws_s3_helper.rb
  app/services/doc_auth/image_upload_presigned_url_generator.rb
  app/services/flow/base_flow.rb
  app/services/flow/base_step.rb
  app/services/flow/flow_state_machine.rb
  app/services/idv/steps/document_capture_step.rb
  app/views/idv/capture_doc/document_capture.html.erb
  app/views/idv/doc_auth/document_capture.html.erb
  app/views/idv/shared/_document_capture.html.erb
  spec/controllers/idv/capture_doc_controller_spec.rb
  spec/controllers/idv/doc_auth_controller_spec.rb
  spec/features/idv/doc_auth/document_capture_step_spec.rb
  spec/features/idv/doc_auth/ssn_step_spec.rb
  spec/features/idv/doc_capture/document_capture_step_spec.rb
  spec/helpers/aws_s3_helper_spec.rb
Labels: status - work in progress

#4272 only generate presigned s3 urls if feature flagged in (LG-3415 - not needed for release notes)
  app/services/doc_auth/image_upload_presigned_url_generator.rb
  config/application.yml.default
Labels: status - ready for review

#4274 Fix a NoMethodError that occurred while adding costs in the hybrid flow
  app/controllers/idv/image_uploads_controller.rb
  spec/controllers/idv/image_uploads_controller_spec.rb
Labels: status - ready for review

#4275 Make the document capture step enabled by default
  config/application.yml.default
Labels: status - ready for review

#4288 Update RC 120 in Staging
  app/services/db/proofing_cost/add_user_proofing_cost.rb
  package.json
  spec/services/db/add_document_verification_and_selfie_costs_spec.rb
  yarn.lock
Labels: status - promotion

#4318 LG-3672 Fix overall success rate reporting when doc capture step enabled
  app/controllers/idv/image_uploads_controller.rb
  spec/controllers/idv/image_uploads_controller_spec.rb
Labels: status - ready for review

#4319 LG-3645 Fix authentication costing for SAML
  app/controllers/saml_idp_controller.rb
  spec/controllers/saml_idp_controller_spec.rb
Labels: status - ready for review

#4313 LG-3416 API to verify documents
  app/forms/idv/api_document_verification_form.rb
  app/jobs/vendor_document_verification_job.rb
  app/services/flow/base_flow.rb
  app/services/flow/base_step.rb
  app/services/flow/flow_state_machine.rb
  app/services/idv/actions/verify_document_action.rb
  app/services/idv/actions/verify_document_status_action.rb
  app/services/idv/flows/doc_auth_flow.rb
  app/services/idv/steps/doc_auth_base_step.rb
  spec/controllers/idv/doc_auth_controller_spec.rb
Labels: status - ready for review

#4333 Keep country_dialing_codes.yml normalized
  Makefile
  app/helpers/form_helper.rb
  config/country_dialing_codes.yml
  lib/yaml_normalizer.rb
  spec/config/country_dialing_codes.yml_spec.rb
  spec/spec_helper.rb
Labels: status - ready for review

#4339 LG-3569 Fix LexisNexis costing
  app/controllers/idv/usps_controller.rb
  app/services/idv/steps/cac/verify_wait_step_show.rb
  spec/features/idv/cac/verify_step_spec.rb
Labels: status - ready for review

#4348 LG-3418 Callback for processing images async
  app/controllers/lambda_callback/document_proof_result_controller.rb
  config/application.yml.default
  config/routes.rb
  spec/controllers/lambda_callback/document_proof_result_controller_spec.rb
Labels: status - ready for review

#4355 Update identity-idp-functions calling syntax
  Gemfile.lock
  app/services/lambda_jobs/git_ref.rb
  app/services/lambda_jobs/runner.rb
  spec/services/lambda_jobs/runner_spec.rb
Labels: status - ready for review

#4363 Updated translations for AAL3 and IAL2 (LG-3617)
  .gitignore
  config/locales/account/es.yml
  config/locales/account/fr.yml
  config/locales/doc_auth/en.yml
  config/locales/doc_auth/es.yml
  config/locales/doc_auth/fr.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
  config/locales/headings/es.yml
  config/locales/headings/fr.yml
  config/locales/help_text/es.yml
  config/locales/help_text/fr.yml
  config/locales/idv/es.yml
  config/locales/instructions/en.yml
  config/locales/instructions/es.yml
  config/locales/instructions/fr.yml
  config/locales/two_factor_authentication/en.yml
  config/locales/two_factor_authentication/es.yml
  config/locales/two_factor_authentication/fr.yml
  config/locales/user_authorization_confirmation/es.yml
  config/locales/user_authorization_confirmation/fr.yml
  spec/support/features/session_helper.rb
Labels: status - ready for review
