Repository 18F/identity-idp, pull requests merged in 2021-11, with the labels that each got.

#5578 LG-4870: Drop legacy Acuant SDK relative path support
  config/initializers/secure_headers.rb
  public/en
  public/es
  public/verify/capture-doc
  public/verify/capture_doc
  public/verify/doc_auth
  spec/requests/acuant_sdk_spec.rb
Labels: status - do not merge

#5587 Add `all_emails` support for SAML
  app/presenters/saml_request_presenter.rb
  app/services/attribute_asserter.rb
  spec/features/multiple_emails/sp_sign_in_spec.rb
  spec/services/attribute_asserter_spec.rb
Labels: status - ready for review

#5576 Only allow SSNs in the 900 group to proof with the mock proofer
  app/services/proofing/mock/resolution_mock_client.rb
  config/application.yml.default
  lib/identity_config.rb
  spec/features/idv/doc_auth/verify_step_spec.rb
  spec/features/idv/steps/review_step_spec.rb
  spec/services/idv/agent_spec.rb
  spec/services/proofing/base_spec.rb
  spec/support/features/doc_auth_helper.rb
  spec/support/idv_examples/sp_handoff.rb
  spec/support/idv_examples/sp_requested_attributes.rb
Labels: status - do not merge

#5644 Respect the ForceAuthn attribute in SAML AuthnRequests
  Gemfile
  Gemfile.lock
  app/controllers/concerns/saml_idp_auth_concern.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/support/fake_saml_request.rb
Labels: status - blocked
