Repository 18F/identity-idp, pull requests merged in 2021-03, with the labels that each got.

#4737 LG-4301 Updated the idv_attempts default from 3 to 5
  app/models/throttle.rb
  config/application.yml.default
  spec/controllers/concerns/idv_step_concern_spec.rb
  spec/controllers/idv_controller_spec.rb
  spec/features/idv/steps/phone_step_spec.rb
Labels: status - ready for review

#4715 [LG-4273] Update nameid-format:EmailAddress to match SAML spec
  lib/saml_idp_constants.rb
Labels: status - do not merge

#4628 LG-4135: Upgrade Acuant SDK from v11.4.1 to v11.4.3
  app/javascript/packages/document-capture/components/acuant-capture-canvas.jsx
  app/javascript/packages/document-capture/context/acuant.jsx
  config/application.yml.default
  public/acuant/11.4.1/AcuantImageProcessingService.js.mem
  public/acuant/11.4.1/AcuantImageProcessingWorker.min.js
  public/acuant/11.4.1/AcuantImageProcessingWorker.wasm
  public/acuant/11.4.1/AcuantJavascriptWebSdk.min.js
  public/acuant/11.4.3/AcuantImageProcessingService.js.mem
  public/acuant/11.4.3/AcuantImageProcessingWorker.min.js
  public/acuant/11.4.3/AcuantImageProcessingWorker.wasm
  public/acuant/11.4.3/AcuantJavascriptWebSdk.min.js
  public/verify/capture-doc
  public/verify/capture_doc
  public/verify/doc_auth
  spec/requests/acuant_sdk_spec.rb
Labels: status - blocked

#4738 Make throttle configs required and remove hardcoded defaults
  app/models/throttle.rb
  config/initializers/app_config.rb
Labels: status - ready for review

#4752 [LG-4273 v2] Actually update NameID format for SAML metadata
  Gemfile
  Gemfile.lock
  spec/controllers/saml_idp_controller_spec.rb
  spec/support/saml_response_doc.rb
Labels: status - blocked

#4783 Add the option to use a block to transform app artifacts
  app/forms/openid_connect_logout_form.rb
  app/presenters/openid_connect_certs_presenter.rb
  app/services/id_token_builder.rb
  app/services/push_notification/http_push.rb
  app/services/request_key_manager.rb
  config/initializers/app_artifacts.rb
  lib/app_artifacts.rb
  spec/forms/openid_connect_logout_form_spec.rb
  spec/forms/openid_connect_token_form_spec.rb
  spec/lib/app_artifacts_spec.rb
  spec/presenters/openid_connect_certs_presenter_spec.rb
  spec/services/id_token_builder_spec.rb
  spec/services/push_notification/http_push_spec.rb
  spec/services/request_key_manager_spec.rb
  spec/support/features/push_notifications_helper.rb
Labels: status - ready for review

#4794 Create a `certs` folder when symlinking SP certs
  lib/deploy/activate.rb
Labels: status - ready for review

#4795 LG-4295 12 hour max session timer
  app/controllers/application_controller.rb
  app/services/analytics.rb
  config/application.yml.default
  spec/features/session/timeout_spec.rb
Labels: status - ready for review

#4800 Refactoring ApiImageUploadController (LG-4252)
  app/controllers/idv/image_uploads_controller.rb
  app/forms/idv/api_image_upload_form.rb
  app/forms/idv/doc_pii_form.rb
  app/presenters/image_upload_response_presenter.rb
  app/services/idv/actions/verify_document_action.rb
  app/services/idv/actions/verify_document_status_action.rb
  app/services/idv/doc_auth_form_response.rb
  spec/forms/idv/api_image_upload_form_spec.rb
  spec/presenters/image_upload_response_presenter_spec.rb
Labels: status - ready for review

#4808 make the addition of attempts_remaining more explicit (LG-4252)
  app/forms/idv/api_image_upload_form.rb
  spec/controllers/idv/image_uploads_controller_spec.rb
  spec/forms/idv/api_image_upload_form_spec.rb
Labels: status - ready for review

#4749 LG-4135: Upgrade Acuant SDK from v11.4.1 to v11.4.3
  app/javascript/packages/document-capture/components/acuant-capture-canvas.jsx
  app/javascript/packages/document-capture/context/acuant.jsx
  config/application.yml.default
  public/acuant/11.4.1/AcuantImageProcessingService.js.mem
  public/acuant/11.4.1/AcuantImageProcessingWorker.min.js
  public/acuant/11.4.1/AcuantImageProcessingWorker.wasm
  public/acuant/11.4.1/AcuantJavascriptWebSdk.min.js
  public/acuant/11.4.3/AcuantImageProcessingService.js.mem
  public/acuant/11.4.3/AcuantImageProcessingWorker.min.js
  public/acuant/11.4.3/AcuantImageProcessingWorker.wasm
  public/acuant/11.4.3/AcuantJavascriptWebSdk.min.js
  public/verify/capture-doc
  public/verify/capture_doc
  public/verify/doc_auth
  spec/requests/acuant_sdk_spec.rb
Labels: status - do not merge

#4811 LG-3840 Updated welcome and new agreement pages
  app/services/db/doc_auth_log/drop_off_rates_helper.rb
  app/services/funnel/doc_auth/register_step.rb
  app/services/idv/flows/doc_auth_flow.rb
  app/services/idv/steps/agreement_step.rb
  app/services/idv/steps/welcome_step.rb
  app/views/idv/doc_auth/agreement.html.erb
  app/views/idv/doc_auth/overview.html.erb
  app/views/idv/doc_auth/welcome.html.erb
  config/locales/doc_auth/en.yml
  config/locales/doc_auth/es.yml
  config/locales/doc_auth/fr.yml
  db/migrate/20210316082419_add_agreement_steps_to_doc_auth_logs.rb
  db/schema.rb
  spec/controllers/idv/doc_auth_controller_spec.rb
  spec/features/idv/doc_auth/agreement_step_spec.rb
  spec/features/idv/doc_auth/welcome_step_spec.rb
  spec/features/reports/doc_auth_funnel_report_spec.rb
  spec/support/features/doc_auth_helper.rb
  spec/support/monitor/monitor_idv_steps.rb
Labels: status - ready for review

#4819 LG-4382 Remove PIV/CAC from IAL2 flow as proofing option
  app/controllers/idv/cac_controller.rb
  app/controllers/idv_controller.rb
  app/forms/idv/cac_form.rb
  app/forms/piv_cac_proofing_form.rb
  app/services/analytics.rb
  app/services/idv/flows/cac_flow.rb
  app/services/idv/steps/cac/choose_method_step.rb
  app/services/idv/steps/cac/enter_info_step.rb
  app/services/idv/steps/cac/present_cac_step.rb
  app/services/idv/steps/cac/verify_step.rb
  app/services/idv/steps/cac/verify_wait_step.rb
  app/services/idv/steps/cac/verify_wait_step_show.rb
  app/services/idv/steps/cac/welcome_step.rb
  app/services/piv_cac/extract_cn_from_subject.rb
  app/services/piv_cac/is_full_name_in_cn.rb
  app/services/piv_cac/sanitize_cn.rb
  app/views/idv/cac/_start_over_or_cancel.html.erb
  app/views/idv/cac/choose_method.html.erb
  app/views/idv/cac/enter_info.html.erb
  app/views/idv/cac/present_cac.html.erb
  app/views/idv/cac/verify.html.erb
  app/views/idv/cac/verify_wait.html.erb
  app/views/idv/cac/welcome.html.erb
  app/views/idv/doc_auth/upload.html.erb
  config/locales/cac_proofing/en.yml
  config/locales/cac_proofing/es.yml
  config/locales/cac_proofing/fr.yml
  config/locales/doc_auth/en.yml
  config/locales/doc_auth/es.yml
  config/locales/doc_auth/fr.yml
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
  config/locales/titles/en.yml
  config/locales/titles/es.yml
  config/locales/titles/fr.yml
  config/routes.rb
  spec/controllers/idv/cac_controller_spec.rb
  spec/features/idv/cac/choose_method_step_spec.rb
  spec/features/idv/cac/enter_info_step_spec.rb
  spec/features/idv/cac/present_cac_step_spec.rb
  spec/features/idv/cac/use_cac_step_spec.rb
  spec/features/idv/cac/verify_step_spec.rb
  spec/features/idv/cac/welcome_step_spec.rb
  spec/forms/piv_cac_proofing_form_spec.rb
  spec/services/piv_cac/extract_cn_from_subject_spec.rb
  spec/services/piv_cac/is_full_name_in_cn_spec.rb
  spec/services/piv_cac/sanitize_cn_spec.rb
  spec/support/features/cac_proofing_helper.rb
Labels: status - ready for review

#4848 LG-4359 Cannot redirect to nil! error during signup
  app/controllers/sign_up/completions_controller.rb
  app/controllers/users/authorization_confirmation_controller.rb
  spec/controllers/sign_up/completions_controller_spec.rb
  spec/features/saml/authorization_confirmation_spec.rb
Labels: status - ready for review
