Repository 18F/identity-idp, pull requests merged in 2021-04, with the labels that each got.

#4863 LG-4331 Add coverage for upload step on desktop and mobile devices
  spec/features/idv/doc_auth/upload_step_spec.rb
Labels: status - ready for review

#4833 LG-4312 Remove analytics_user override of default analytics user
  app/controllers/application_controller.rb
  app/controllers/frontend_log_controller.rb
  app/controllers/idv/capture_doc_controller.rb
Labels: status - ready for review

#4893 LG-4457 Log timeout on LexisNexis phone check timeouts
  app/controllers/idv/phone_controller.rb
  spec/controllers/idv/phone_controller_spec.rb
Labels: status - ready for review

#4896 Deploy RC 126.1 to Prod
  .circleci/config.yml
  app/controllers/concerns/saml_idp_auth_concern.rb
  app/controllers/saml_idp_controller.rb
  app/forms/openid_connect_token_form.rb
  app/forms/security_event_form.rb
  app/models/null_service_provider.rb
  app/models/service_provider.rb
  app/services/service_provider_config.rb
  certs.example/sp/saml_test_sp2.crt
  config/initializers/saml_idp.rb
  config/locales/openid_connect/en.yml
  config/locales/openid_connect/es.yml
  config/locales/openid_connect/fr.yml
  config/service_providers.localdev.yml
  keys.example/saml_test_sp2.key
  spec/controllers/saml_idp_controller_spec.rb
  spec/controllers/service_provider_controller_spec.rb
  spec/forms/openid_connect_token_form_spec.rb
  spec/models/null_service_provider_spec.rb
  spec/models/service_provider_spec.rb
  spec/services/service_provider_config_spec.rb
  spec/services/service_provider_seeder_spec.rb
  spec/services/service_provider_updater_spec.rb
  spec/support/fake_saml_logout_request.rb
Labels: status - promotion

#4903 Fix account reset double submit 500 error
  app/services/db/deleted_user/create.rb
  spec/services/db/deleted_user/create_spec.rb
Labels: status - ready for review

#4900 Include flow_path in logged events to distinguish hybrid flow (LG-4399)
  app/javascript/packages/document-capture/context/analytics.jsx
  app/javascript/packs/document-capture.jsx
  app/services/flow/base_flow.rb
  app/services/flow/flow_state_machine.rb
  app/services/idv/flows/capture_doc_flow.rb
  app/views/idv/capture_doc/document_capture.html.erb
  app/views/idv/doc_auth/document_capture.html.erb
  app/views/idv/shared/_document_capture.html.erb
  spec/controllers/idv/capture_doc_controller_spec.rb
  spec/controllers/idv/doc_auth_controller_spec.rb
  spec/controllers/idv/recovery_controller_spec.rb
  spec/features/idv/doc_auth/document_capture_step_spec.rb
  spec/features/idv/doc_capture/document_capture_step_spec.rb
  spec/views/idv/shared/_document_capture.html.erb_spec.rb
Labels: status - ready for review

#4905 Fix IDV address 500 error if no document data in session
  app/controllers/idv/address_controller.rb
  spec/features/idv/doc_auth/address_step_spec.rb
Labels: status - ready for review

#4913 LG-4417 Re-proofing RISC event
  app/models/profile.rb
  app/services/push_notification/reproof_completed_event.rb
  spec/models/profile_spec.rb
  spec/services/push_notification/reproof_completed_event_spec.rb
Labels: status - ready for review

#4935 Fix email changed RISC event
  app/controllers/users/email_confirmations_controller.rb
  app/forms/add_user_email_form.rb
  spec/forms/add_user_email_form_spec.rb
Labels: status - ready for review

#4936 LG-4392: Set Acuant canvas width as HTML attribute
  app/javascript/packages/document-capture/components/acuant-capture-canvas.jsx
Labels: status - do not merge

#4963 Bump CI parallelism to 8
  .circleci/config.yml
  knapsack_rspec_report.json
Labels: status - do not merge

#4992 Remove unused code
  app/controllers/application_controller.rb
  app/controllers/saml_idp_controller.rb
  app/controllers/users/phone_setup_controller.rb
  app/controllers/users/reset_passwords_controller.rb
  app/controllers/users/totp_setup_controller.rb
  app/controllers/users/webauthn_setup_controller.rb
  app/helpers/application_helper.rb
  app/helpers/form_helper.rb
  app/models/null_service_provider.rb
  app/models/service_provider.rb
  app/presenters/confirmation_email_presenter.rb
  app/services/uuid_reporter.rb
  db/migrate/20210427230314_drop_push_account_deletes_table.rb
  db/schema.rb
  lib/job_runner/callback_executor.rb
  spec/helpers/application_helper_spec.rb
  spec/models/null_service_provider_spec.rb
Labels: status - ready for review

#4991 Remove unused routes
  config/routes.rb
  spec/views/accounts/two_factor_authentication/show.html.erb_spec.rb
Labels: status - ready for review
