Repository 18F/identity-idp, pull requests merged in 2021-05, with the labels that each got.

#4969 Drop unused columns in service_providers table
  app/models/service_provider.rb
  db/migrate/20210423221651_drop_unused_service_provider_columns.rb
  db/schema.rb
Labels: status - do not merge

#5060 allow exception notifier to use :expected option to avoid false alerts
  Gemfile
  Gemfile.lock
  app/services/doc_auth_router.rb
  spec/services/doc_auth_router_spec.rb
Labels: status - do not merge

#4968 LG-4448 Implement rules of use for new users
  app/assets/stylesheets/components/_form.scss
  app/controllers/sign_up/registrations_controller.rb
  app/forms/register_user_email_form.rb
  app/javascript/packs/accept-terms-button.js
  app/javascript/packs/form-validation.js
  app/services/marketing_site.rb
  app/services/request_password_reset.rb
  app/views/sign_up/email_resend/new.html.erb
  app/views/sign_up/registrations/new.html.erb
  config/application.yml.default
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
  config/locales/forms/en.yml
  config/locales/forms/es.yml
  config/locales/forms/fr.yml
  config/locales/headings/en.yml
  config/locales/headings/es.yml
  config/locales/headings/fr.yml
  config/locales/notices/en.yml
  config/locales/sign_up/en.yml
  config/locales/sign_up/es.yml
  config/locales/sign_up/fr.yml
  config/locales/titles/en.yml
  config/locales/titles/es.yml
  config/locales/titles/fr.yml
  db/migrate/20210420112113_add_accepted_terms_at_to_users.rb
  db/schema.rb
  lib/identity_config.rb
  spec/controllers/sign_up/registrations_controller_spec.rb
  spec/features/multiple_emails/add_email_spec.rb
  spec/features/users/sign_in_spec.rb
  spec/features/users/sign_up_spec.rb
  spec/features/visitors/password_recovery_spec.rb
  spec/features/visitors/resend_email_confirmation_spec.rb
  spec/forms/register_user_email_form_spec.rb
  spec/services/marketing_site_spec.rb
  spec/support/features/session_helper.rb
  spec/support/monitor/monitor_idp_steps.rb
  spec/views/sign_up/registrations/new.html.erb_spec.rb
Labels: status - do not merge, status - ready for review

#5040 LG-4449 Implement rules of use for existing users
  app/controllers/users/rules_of_use_controller.rb
  app/controllers/users/sessions_controller.rb
  app/forms/rules_of_use_form.rb
  app/models/user.rb
  app/services/analytics.rb
  app/views/users/rules_of_use/new.html.erb
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
  config/locales/users/en.yml
  config/locales/users/es.yml
  config/locales/users/fr.yml
  config/routes.rb
  spec/controllers/users/rules_of_use_controller_spec.rb
  spec/factories/users.rb
  spec/support/features/session_helper.rb
  spec/support/monitor/monitor_idp_steps.rb
Labels: status - do not merge, status - ready for review

#5089 [LG-4634] Downcase agency in Partner API agreements path
  app/services/agreements/reports/agencies_report.rb
  app/services/agreements/reports/agency_iaas_report.rb
  app/services/agreements/reports/agency_partner_accounts_report.rb
  app/services/agreements/reports/base_report.rb
  spec/services/agreements/reports/agencies_report_spec.rb
  spec/services/agreements/reports/agency_iaas_report_spec.rb
  spec/services/agreements/reports/agency_partner_accounts_report_spec.rb
Labels: needs code review
