Repository 18F/identity-idp, pull requests merged in 2022-05, with the labels that each got.

#6286 Remove references to deprecated and renamed session keys
  app/services/reactivate_account_session.rb
  spec/services/reactivate_account_session_spec.rb
Labels: status - do not merge

#5709 Add the SAML remote logout endpoint to the metadata
  Gemfile
  Gemfile.lock
  app/services/saml_endpoint.rb
  config/initializers/saml_idp.rb
  config/routes.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/features/saml/multiple_endpoints_spec.rb
  spec/requests/saml_post_spec.rb
  spec/requests/saml_requests_spec.rb
  spec/services/saml_endpoint_spec.rb
Labels: status - blocked

#5652 Support IALMAX using the Comparison attribute in SAML
  app/controllers/concerns/billable_event_trackable.rb
  app/controllers/concerns/saml_idp_auth_concern.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/controllers/saml_idp_controller.rb
  app/forms/openid_connect_authorize_form.rb
  app/presenters/saml_request_presenter.rb
  app/services/attribute_asserter.rb
  app/services/ial_context.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/features/ialmax/saml_sign_in_spec.rb
  spec/presenters/saml_request_presenter_spec.rb
  spec/services/attribute_asserter_spec.rb
  spec/services/ial_context_spec.rb
  spec/support/saml_auth_helper.rb
  spec/support/shared_examples/sign_in.rb
Labels: status - blocked

#6345 RC 190.1
  config/routes.rb
  spec/requests/saml_requests_spec.rb
Labels: status - promotion
