Repository 18F/identity-idp, pull requests merged in 2022-10, with the labels that each got.

#7063 Support AAL2 phishing-resistant and PIV/CAC authentication contexts
  app/controllers/application_controller.rb
  app/controllers/concerns/two_factor_authenticatable_methods.rb
  app/controllers/two_factor_authentication/options_controller.rb
  app/controllers/users/aal3_controller.rb
  app/controllers/users/mfa_selection_controller.rb
  app/controllers/users/two_factor_authentication_setup_controller.rb
  app/decorators/mfa_context.rb
  app/forms/two_factor_options_form.rb
  app/policies/mfa_policy.rb
  app/policies/service_provider_mfa_policy.rb
  app/presenters/two_factor_auth_code/generic_delivery_presenter.rb
  app/presenters/two_factor_auth_code/piv_cac_authentication_presenter.rb
  app/presenters/two_factor_auth_code/webauthn_authentication_presenter.rb
  app/presenters/two_factor_login_options_presenter.rb
  app/presenters/two_factor_options_presenter.rb
  app/services/store_sp_metadata_in_session.rb
  config/application.yml.default
  config/routes.rb
  knapsack_rspec_report.json
  lib/saml_idp_constants.rb
  spec/controllers/openid_connect/authorization_controller_spec.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/controllers/users/aal3_controller_spec.rb
  spec/controllers/users/mfa_selection_controller_spec.rb
  spec/controllers/users/two_factor_authentication_controller_spec.rb
  spec/controllers/users/two_factor_authentication_setup_controller_spec.rb
  spec/features/openid_connect/aal3_required_spec.rb
  spec/features/openid_connect/phishing_resistant_required_spec.rb
  spec/features/saml/aal3_required_spec.rb
  spec/features/saml/phishing_resistant_required_spec.rb
  spec/features/webauthn/sign_up_spec.rb
  spec/forms/two_factor_options_form_spec.rb
  spec/policies/service_provider_mfa_policy_spec.rb
  spec/presenters/two_factor_auth_code/piv_cac_authentication_presenter_spec.rb
  spec/presenters/two_factor_auth_code/webauthn_authentication_presenter_spec.rb
  spec/presenters/two_factor_login_options_presenter_spec.rb
  spec/presenters/two_factor_options_presenter_spec.rb
  spec/services/store_sp_metadata_in_session_spec.rb
  spec/support/features/session_helper.rb
  spec/support/oidc_auth_helper.rb
  spec/support/saml_auth_helper.rb
  spec/views/two_factor_authentication/options/index.html.erb_spec.rb
Labels: status - work in progress

#7043 LG-7606: generate key pairs and log how long it takes
  app/components/key_pair_generator_component.html.erb
  app/components/key_pair_generator_component.js
  app/components/key_pair_generator_component.rb
  app/views/devise/sessions/new.html.erb
  config/application.yml.default
  config/initializers/ab_tests.rb
  lib/identity_config.rb
  spec/config/initializers/ab_tests_spec.rb
  spec/features/users/key_pair_generation_spec.rb
  spec/services/doc_auth_router_spec.rb
Labels: status - ready for review

#7098 LG-7659 Doc Auth State and Territory Validation
  app/forms/idv/doc_pii_form.rb
  app/services/doc_auth/response.rb
  lib/idp/constants.rb
  spec/fixtures/ial2_test_credential.yml
  spec/forms/idv/doc_pii_form_spec.rb
Labels: status - work in progress, status - do not merge

#7080 [LG-7438] Add logging of whether or not a SAML request was signed
  Gemfile
  Gemfile.lock
  app/controllers/concerns/saml_idp_auth_concern.rb
  app/controllers/saml_idp_controller.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/support/fake_saml_request.rb
Labels: status - do not merge, status - blocked

#7127 LG-7724: set va_inherited_proofing_mock_enabled default value to false for all environments
  config/application.yml.default
Labels: inherited proofing

#7163 Deploy RC 218.1 to Prod
  app/mailers/user_mailer.rb
  spec/mailers/user_mailer_spec.rb
Labels: status - promotion

#7148 LG-7446 Create "Cancel" Links and Supporting Cancellation Code for Identity Proofing Process (3 of n)
  app/views/idv/inherited_proofing/_cancel.html.erb
  app/views/idv/inherited_proofing/agreement.html.erb
  app/views/idv/inherited_proofing/get_started.html.erb
  app/views/idv/inherited_proofing/verify_info.html.erb
  app/views/idv/inherited_proofing_cancellations/new.html.erb
  spec/features/idv/inherited_proofing/agreement_step_spec.rb
  spec/features/idv/inherited_proofing/get_started_step_spec.rb
  spec/views/idv/inherited_proofing/agreement.html.erb_spec.rb
  spec/views/idv/inherited_proofing/get_started.html.erb_spec.rb
Labels: inherited proofing

#7161 LG-7449, Add first error page for inherited proofing when no information is received from API call.
  app/controllers/idv/inherited_proofing_controller.rb
  app/views/idv/inherited_proofing/no_information.html.erb
  app/views/idv/inherited_proofing/phone.html.erb
  config/locales/inherited_proofing/en.yml
  config/locales/inherited_proofing/es.yml
  config/locales/inherited_proofing/fr.yml
  config/locales/step_indicator/en.yml
  config/locales/step_indicator/es.yml
  config/locales/step_indicator/fr.yml
  config/routes.rb
Labels: inherited proofing

#7167 LG-7703: Force a user to re-verify their identity for IRS.
  app/controllers/concerns/idv_session.rb
  app/controllers/concerns/saml_idp_auth_concern.rb
  app/controllers/idv_controller.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/decorators/user_decorator.rb
  spec/factories/service_providers.rb
  spec/features/users/sign_in_irs_spec.rb
  spec/support/features/idv_helper.rb
Labels: status - ready for review

#7181 LG-7255 Refactor inherited proofing concern
  app/controllers/concerns/inherited_proofing_concern.rb
  app/controllers/idv_controller.rb
  app/services/idv/inherited_proofing/service_provider_forms.rb
  app/services/idv/inherited_proofing/service_provider_services.rb
  spec/controllers/concerns/inherited_proofing_concern_spec.rb
  spec/services/idv/inherited_proofing/service_provider_forms_spec.rb
  spec/services/idv/inherited_proofing/service_provider_services_spec.rb
Labels: inherited proofing

#7149 LG 7255 - Add API call to "we are retrieving" page
  app/controllers/concerns/inherited_proofing_concern.rb
  app/jobs/inherited_proofing_job.rb
  app/services/idv/flows/inherited_proofing_flow.rb
  app/services/idv/inherited_proofing/service_providers.rb
  app/services/idv/steps/doc_auth_base_step.rb
  app/services/idv/steps/inherited_proofing/agreement_step.rb
  app/services/idv/steps/inherited_proofing/user_pii_managable.rb
  app/services/idv/steps/inherited_proofing/verify_wait_step.rb
  app/services/idv/steps/inherited_proofing/verify_wait_step_show.rb
  app/views/idv/inherited_proofing/verify_wait.html.erb
  spec/features/idv/inherited_proofing/agreement_step_spec.rb
  spec/features/idv/inherited_proofing/get_started_step_spec.rb
  spec/features/idv/inherited_proofing/verify_info_step_spec.rb
  spec/jobs/inherited_proofing_job_spec.rb
  spec/support/features/doc_auth_helper.rb
  spec/support/features/inherited_proofing_helper.rb
  spec/views/idv/inherited_proofing/retrieval.html.erb_spec.rb
Labels: inherited proofing

#7201 Stop requesting selfies from the frontend
  app/controllers/api/verify/document_capture_controller.rb
  app/controllers/idv/image_uploads_controller.rb
  app/views/idv/shared/_document_capture.html.erb
  spec/controllers/api/verify/document_capture_controller_spec.rb
  spec/features/idv/doc_auth/document_capture_step_spec.rb
  spec/features/idv/doc_capture/document_capture_step_spec.rb
  spec/features/idv/proofing_components_spec.rb
  spec/features/idv/strict_ial2/upgrade_spec.rb
Labels: needs code review

#7210 LG-7255 - Adds proofing session
  app/services/idv/steps/inherited_proofing/agreement_step.rb
Labels: inherited proofing

#7220 Removed IAL2_STRICT constant
  app/controllers/concerns/idv_session.rb
  app/controllers/idv_controller.rb
  app/helpers/application_helper.rb
  app/presenters/openid_connect_user_info_presenter.rb
  app/presenters/saml_request_presenter.rb
  app/services/ial_context.rb
  app/services/id_token_builder.rb
  app/services/idv/steps/doc_auth_base_step.rb
  app/services/idv/steps/send_link_step.rb
  app/services/store_sp_metadata_in_session.rb
  lib/idp/constants.rb
  lib/saml_idp_constants.rb
  spec/controllers/openid_connect/authorization_controller_spec.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/features/reports/authorization_count_spec.rb
  spec/forms/idv/inherited_proofing/base_form_spec.rb
  spec/forms/idv/inherited_proofing/va/form_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/services/ial_context_spec.rb
  spec/services/idv/actions/verify_document_status_action_spec.rb
  spec/services/store_sp_metadata_in_session_spec.rb
  spec/support/features/idv_from_sp_helper.rb
  spec/support/features/idv_helper.rb
  spec/support/oidc_auth_helper.rb
  spec/support/shared_examples/empty_hash_shared_example.rb
Labels: status - work in progress

#7243 Lg 7738 - mock errors for inherited proofing mock proofer
  app/forms/idv/inherited_proofing/base_form.rb
  app/services/idv/inherited_proofing/va/mocks/service.rb
  lib/session_encryptor.rb
  spec/controllers/users/mfa_selection_controller_spec.rb
  spec/services/idv/inherited_proofing/va/mocks/service_spec.rb
Labels: inherited proofing

#7230 LG-7452 Inherited Proofing Error Controller and new error page
  app/controllers/idv/inherited_proofing_controller.rb
  app/controllers/idv/inherited_proofing_errors_controller.rb
  app/views/idv/inherited_proofing_errors/failure.html.erb
  app/views/idv/inherited_proofing_errors/warning.html.erb
  config/locales/inherited_proofing/en.yml
  config/locales/inherited_proofing/es.yml
  config/locales/inherited_proofing/fr.yml
  config/routes.rb
Labels: inherited proofing
