Repository 18F/identity-idp, pull requests merged in 2022-04, with the labels that each got.

#6163 Deploy RC 184.2 to Production
  Gemfile
  Gemfile.lock
  app/controllers/idv/personal_key_controller.rb
  app/javascript/packs/personal-key-page-controller.js
  app/views/shared/_personal_key.html.erb
  config/routes.rb
  spec/views/shared/_personal_key.html.erb_spec.rb
Labels: status - promotion

#6164 Drop unused users columns
  app/models/user.rb
  db/primary_migrate/20220406155240_drop_users_sign_in_at_sign_in_ip_sign_in_count.rb
  db/schema.rb
Labels: status - do not merge

#6211 Add a background job encryptor
  app/jobs/address_proofing_job.rb
  app/jobs/document_proofing_job.rb
  app/jobs/resolution_proofing_job.rb
  app/models/gpo_confirmation.rb
  app/services/encrypted_redis_struct_storage.rb
  app/services/encryption/encryptors/background_proofing_arg_encryptor.rb
  app/services/idv/agent.rb
  spec/features/idv/doc_auth/document_capture_step_spec.rb
  spec/jobs/address_proofing_job_spec.rb
  spec/jobs/document_proofing_job_spec.rb
  spec/jobs/resolution_proofing_job_spec.rb
  spec/lib/identity_job_log_subscriber_spec.rb
  spec/services/encryption/encryptors/background_proofing_arg_encryptor_spec.rb
  spec/services/gpo_confirmation_spec.rb
Labels: needs code review

#6263 Retire the liveness_checking_required flag on service providers
  app/controllers/concerns/saml_idp_auth_concern.rb
  app/forms/openid_connect_authorize_form.rb
  app/models/service_provider.rb
  app/services/ial_context.rb
  spec/features/idv/liveness/upgrade_to_strong_ial2_spec.rb
  spec/services/attribute_asserter_spec.rb
  spec/services/ial_context_spec.rb
Labels: needs code review

#6262 Add a `includes_phone_check?` method to Profile
  app/models/profile.rb
  spec/models/profile_spec.rb
Labels: needs code review
