Repository 18F/identity-idp, pull requests merged in 2022-11, with the labels that each got.

#7228 Pulled out checks for liveness
  app/forms/idv/api_image_upload_form.rb
  app/helpers/application_helper.rb
  app/services/db/add_document_verification_and_selfie_costs.rb
  app/services/doc_auth/acuant/acuant_client.rb
  app/services/doc_auth/mock/doc_auth_mock_client.rb
  app/services/idv/steps/doc_auth_base_step.rb
  app/views/idv/doc_auth/no_camera.html.erb
  app/views/idv/doc_auth/upload.html.erb
  app/views/idv/doc_auth/welcome.html.erb
  app/views/idv/session_errors/throttled.html.erb
  config/application.yml.default
  config/initializers/strong_migrations.rb
  config/locales/doc_auth/en.yml
  config/locales/doc_auth/es.yml
  config/locales/doc_auth/fr.yml
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
  lib/feature_management.rb
  lib/identity_config.rb
  spec/helpers/application_helper_spec.rb
  spec/services/db/add_document_verification_and_selfie_costs_spec.rb
  spec/views/idv/doc_auth/upload.html.erb_spec.rb
  spec/views/idv/doc_auth/welcome.html.erb_spec.rb
  spec/views/idv/session_errors/throttled.html.erb_spec.rb
Labels: status - work in progress

#7176 LG-7446 Create "Cancel" Links and Supporting Cancellation Code for Identity Proofing Process (4 of 4)
  app/controllers/concerns/inherited_proofing_concern.rb
  app/controllers/idv/inherited_proofing_cancellations_controller.rb
  app/controllers/idv/sessions_controller.rb
  app/jobs/inherited_proofing_job.rb
  app/services/idv/steps/inherited_proofing/verify_wait_step_show.rb
  app/views/idv/inherited_proofing/verify_wait.html.erb
  app/views/idv/inherited_proofing_cancellations/new.html.erb
  config/routes.rb
  spec/controllers/idv/sessions_controller_spec.rb
  spec/features/idv/inherited_proofing/inherited_proofing_cancel_spec.rb
  spec/support/features/idv_helper.rb
  spec/views/idv/inherited_proofing/retrieval.html.erb_spec.rb
Labels: inherited proofing

#7307 Microoptimize reproof_for_irs to avoid database query
  app/decorators/user_decorator.rb
Labels: performance

#7326 Lg 7884 analytics for inherited proofing
  app/services/analytics_events.rb
  spec/features/idv/inherited_proofing/analytics_spec.rb
  spec/support/features/inherited_proofing_helper.rb
Labels: inherited proofing

#7284 LG-7450 Implement "Try Again" Button Functionality on the First Error Page
  app/forms/idv/inherited_proofing/base_form.rb
  app/forms/idv/inherited_proofing/va/form.rb
  app/services/analytics_events.rb
  app/services/flow/base_flow.rb
  app/services/flow/base_step.rb
  app/services/flow/failure.rb
  app/services/idv/actions/inherited_proofing/redo_retrieve_user_info_action.rb
  app/services/idv/flows/inherited_proofing_flow.rb
  app/services/idv/inherited_proofing/va/mocks/service.rb
  app/services/idv/inherited_proofing/va/service.rb
  app/services/idv/steps/inherited_proofing/agreement_step.rb
  app/services/idv/steps/inherited_proofing/user_pii_job_initiator.rb
  app/services/idv/steps/inherited_proofing/verify_wait_step_show.rb
  app/services/idv/steps/verify_base_step.rb
  app/services/throttle.rb
  app/views/idv/inherited_proofing_errors/warning.html.erb
  config/application.yml.default
  config/locales/inherited_proofing/en.yml
  config/locales/inherited_proofing/es.yml
  config/locales/inherited_proofing/fr.yml
  lib/identity_config.rb
  spec/features/idv/inherited_proofing/inherited_proofing_cancel_spec.rb
  spec/features/idv/inherited_proofing/verify_wait_step_spec.rb
  spec/forms/idv/inherited_proofing/base_form_spec.rb
  spec/forms/idv/inherited_proofing/va/form_spec.rb
  spec/services/idv/inherited_proofing/va/service_spec.rb
  spec/support/features/idv_helper.rb
  spec/support/features/inherited_proofing_with_service_provider_helper.rb
Labels: inherited proofing

#7394 Lg 7467 log idv step context
  app/controllers/idv/personal_key_controller.rb
  app/controllers/idv/review_controller.rb
  app/services/analytics_events.rb
  spec/features/idv/analytics_spec.rb
Labels: status - work in progress

#7397 Deploy RC 231.1 to Prod
  config/locales/telephony/es.yml
Labels: status - promotion
