Repository 18F/identity-idp, pull requests merged in 2023-11, with the labels that each got.

#9504 Add IconListComponent ViewComponent
  Makefile
  app/assets/stylesheets/_uswds.scss
  app/components/icon_list_component.html.erb
  app/components/icon_list_component.rb
  app/components/icon_list_component.scss
  app/components/icon_list_item_component.html.erb
  app/components/process_list_component.rb
  app/views/partials/multi_factor_authentication/_selected_mfa_option.html.erb
  app/views/users/two_factor_authentication_setup/index.html.erb
  spec/components/icon_list_component_spec.rb
  spec/components/previews/icon_list_component_preview.rb
Labels: performance

#9565 Deploy RC 331 to Production
  app/controllers/idv/unavailable_controller.rb
  app/controllers/users/webauthn_setup_controller.rb
  app/forms/idv/api_image_upload_form.rb
  app/javascript/packages/document-capture/components/document-capture-not-ready.tsx
  app/javascript/packages/document-capture/components/document-capture-review-issues.tsx
  app/javascript/packages/document-capture/components/documents-step.jsx
  app/javascript/packages/document-capture/context/feature-flag.tsx
  app/javascript/packages/document-capture/context/index.ts
  app/javascript/packs/document-capture.tsx
  app/models/disposable_domain.rb
  app/services/analytics_events.rb
  app/services/browser_support.rb
  app/services/outage_status.rb
  app/views/idv/in_person/verify_info/show.html.erb
  app/views/idv/shared/_document_capture.html.erb
  app/views/idv/verify_info/show.html.erb
  config/application.yml.default
  config/application.yml.default.docker
  config/locales/doc_auth/en.yml
  config/locales/doc_auth/es.yml
  config/locales/doc_auth/fr.yml
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
  db/primary_migrate/20231024170146_create_email_data_table.rb
  db/schema.rb
  docs/local-development.md
  lib/identity_config.rb
  lib/tasks/disposable_domains.rake
  spec/controllers/idv/image_uploads_controller_spec.rb
  spec/controllers/idv/unavailable_controller_spec.rb
  spec/controllers/users/webauthn_setup_controller_spec.rb
  spec/features/idv/analytics_spec.rb
  spec/features/idv/doc_auth/document_capture_spec.rb
  spec/features/idv/doc_auth/phone_question_spec.rb
  spec/features/idv/doc_auth/redo_document_capture_spec.rb
  spec/features/idv/doc_auth/verify_info_step_spec.rb
  spec/features/idv/hybrid_mobile/hybrid_mobile_spec.rb
  spec/features/idv/outage_spec.rb
  spec/features/idv/steps/in_person/verify_info_spec.rb
  spec/features/idv/threat_metrix_pending_spec.rb
  spec/forms/idv/api_image_upload_form_spec.rb
  spec/javascript/packages/document-capture/components/document-capture-not-ready-spec.tsx
  spec/javascript/packages/document-capture/components/documents-step-spec.jsx
  spec/services/browser_support_spec.rb
  spec/services/outage_status_spec.rb
  spec/support/features/doc_auth_helper.rb
  spec/support/features/idv_helper.rb
  spec/support/features/in_person_helper.rb
  spec/support/shared_examples/webauthn_setup.rb
  yarn.lock
Labels: status - promotion

#9574 Include TypeScript types in frontend naming conventions
  docs/frontend.md
Labels: documentation

#9583 Deploy RC 332 to Production
  .gitlab-ci.yml
  app/controllers/idv/enter_password_controller.rb
  app/jobs/gpo_expiration_job.rb
  app/models/profile.rb
  app/services/analytics_events.rb
  app/services/idv/analytics_events_enhancer.rb
  app/views/idv/by_mail/enter_code/index.html.erb
  config/application.yml.default
  config/application.yml.default.docker
  config/initializers/content_security_policy.rb
  config/initializers/unused_identity_config_keys.rb
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
  db/primary_migrate/20231102211426_add_gpo_verification_expired_at_to_profiles.rb
  db/schema.rb
  dockerfiles/idp_review_app.Dockerfile
  docs/frontend.md
  lib/cleanup/destroy_unused_providers.rb
  lib/identity_config.rb
  lib/linters/errors_add_linter.rb
  lib/tasks/backfill_gpo_expiration.rake
  lib/tasks/disposable_domains.rake
  scripts/review_app_service_providers.rb
  spec/controllers/idv/enter_password_controller_spec.rb
  spec/factories/gpo_confirmation_codes.rb
  spec/factories/users.rb
  spec/features/idv/analytics_spec.rb
  spec/features/idv/steps/enter_code_step_spec.rb
  spec/jobs/gpo_expiration_job_spec.rb
  spec/lib/identity_config_spec.rb
  spec/lib/linters/errors_add_linter_spec.rb
  spec/models/profile_spec.rb
Labels: status - promotion

#9555 Use Icon List component for requested attributes consent
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_list.scss
  app/components/icon_list_component.rb
  app/components/icon_list_item_component.html.erb
  app/views/sign_up/completions/_requested_attributes.html.erb
  app/views/sign_up/completions/show.html.erb
  app/views/users/authorization_confirmation/new.html.erb
  spec/components/icon_list_component_spec.rb
  spec/features/openid_connect/authorization_confirmation_spec.rb
  spec/features/saml/authorization_confirmation_spec.rb
  spec/features/saml/ial1_sso_spec.rb
  spec/support/idv_examples/sp_requested_attributes.rb
Labels: performance, design system
