Repository 18F/identity-idp, pull requests merged in 2023-01, with the labels that each got.

#7639 Fully remove references to old ThreatMetrix config flags (LG-8512)
  config/application.yml.default
  lib/feature_management.rb
  lib/identity_config.rb
  spec/lib/feature_management_spec.rb
Labels: status - do not merge

#7711 LG-8503: Add commas to example search text
  config/locales/in_person_proofing/en.yml
  config/locales/in_person_proofing/es.yml
  config/locales/in_person_proofing/fr.yml
Labels: status - ready for review

#7723 Deploy RC 248
  app/components/countdown_alert_component.rb
  app/controllers/idv/session_errors_controller.rb
  app/controllers/idv/verify_info_controller.rb
  app/controllers/two_factor_authentication/otp_expired_controller.rb
  app/javascript/packages/countdown/countdown-alert-element.spec.ts
  app/javascript/packages/countdown/countdown-alert-element.ts
  app/javascript/packages/document-capture/components/address-search.tsx
  app/javascript/packages/document-capture/components/document-capture-troubleshooting-options.tsx
  app/javascript/packages/document-capture/components/in-person-call-to-action.spec.tsx
  app/javascript/packages/document-capture/components/in-person-call-to-action.tsx
  app/javascript/packages/document-capture/components/in-person-location-post-office-search-step.spec.tsx
  app/javascript/packages/document-capture/components/review-issues-step.tsx
  app/javascript/packages/document-capture/components/warning.tsx
  app/javascript/packages/document-capture/context/in-person.ts
  app/javascript/packs/document-capture.tsx
  app/services/idv/steps/document_capture_step.rb
  app/services/idv/steps/ssn_step.rb
  app/views/idv/capture_doc/document_capture.html.erb
  app/views/idv/doc_auth/document_capture.html.erb
  app/views/idv/shared/_document_capture.html.erb
  app/views/two_factor_authentication/otp_expired/show.html.erb
  app/views/two_factor_authentication/otp_verification/show.html.erb
  config/application.yml.default
  config/i18n-tasks.yml
  config/initializers/ab_tests.rb
  config/locales/errors/en.yml
  config/locales/errors/es.yml
  config/locales/errors/fr.yml
  config/locales/headings/en.yml
  config/locales/headings/es.yml
  config/locales/headings/fr.yml
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
  config/locales/in_person_proofing/en.yml
  config/locales/in_person_proofing/es.yml
  config/locales/in_person_proofing/fr.yml
  config/locales/links/en.yml
  config/locales/links/es.yml
  config/locales/links/fr.yml
  config/locales/titles/en.yml
  config/locales/titles/es.yml
  config/locales/titles/fr.yml
  config/routes.rb
  lib/ab_test_bucket.rb
  lib/identity_config.rb
  scripts/changelog_check.rb
  spec/controllers/idv/verify_info_controller_spec.rb
  spec/controllers/two_factor_authentication/otp_expired_controller_spec.rb
  spec/fixtures/git_log_changelog.yml
  spec/javascripts/packages/document-capture/components/document-capture-spec.jsx
  spec/services/idv/steps/document_capture_step_spec.rb
  spec/support/controller_helper.rb
  spec/views/idv/shared/_document_capture.html.erb_spec.rb
  spec/views/two_factor_authentication/otp_expired/show.html.erb_spec.rb
Labels: status - promotion
