Repository 18F/identity-idp, pull requests merged in 2023-09, with the labels that each got.

#9160 Deploy RC 312 to Prod
  .gitlab-ci.yml
  app/controllers/idv/personal_key_controller.rb
  app/controllers/idv/review_controller.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/forms/two_factor_options_form.rb
  app/javascript/packages/phone-input/package.json
  app/jobs/reports/monthly_account_reuse_report.rb
  app/models/profile.rb
  app/models/user.rb
  app/services/analytics_events.rb
  bin/oncall/download-piv-certs
  bin/oncall/email-deliveries
  bin/oncall/otp-deliveries
  bin/query-cloudwatch
  lib/reporting/cloudwatch_client.rb
  spec/controllers/idv/personal_key_controller_spec.rb
  spec/controllers/idv/review_controller_spec.rb
  spec/controllers/openid_connect/authorization_controller_spec.rb
  spec/factories/profiles.rb
  spec/features/idv/analytics_spec.rb
  spec/forms/gpo_verify_form_spec.rb
  spec/forms/two_factor_options_form_spec.rb
  spec/jobs/reports/monthly_account_reuse_report_spec.rb
  spec/models/profile_spec.rb
  spec/services/idv/profile_maker_spec.rb
  spec/services/idv/session_spec.rb
  yarn.lock
Labels: status - promotion

#9182 LG-10886 remove ssn from flow session
  app/controllers/concerns/idv/verify_info_concern.rb
  app/controllers/concerns/idv_step_concern.rb
  app/controllers/concerns/rate_limit_concern.rb
  app/controllers/idv/in_person/ssn_controller.rb
  app/controllers/idv/in_person/verify_info_controller.rb
  app/controllers/idv/session_errors_controller.rb
  app/controllers/idv/ssn_controller.rb
  app/controllers/idv/verify_info_controller.rb
  spec/controllers/concerns/rate_limit_concern_spec.rb
  spec/controllers/idv/in_person/ssn_controller_spec.rb
  spec/controllers/idv/in_person/verify_info_controller_spec.rb
  spec/controllers/idv/session_errors_controller_spec.rb
  spec/controllers/idv/ssn_controller_spec.rb
  spec/controllers/idv/verify_info_controller_spec.rb
Labels: status - do not merge

#9217 Fix JavaScript Webpack tree-shaking
  webpack.config.js
Labels: performance

#9218 Remove password toggle click frontend event
  app/controllers/frontend_log_controller.rb
  app/javascript/packages/password-confirmation/password-confirmation-element.spec.ts
  app/javascript/packages/password-confirmation/password-confirmation-element.ts
  app/javascript/packages/password-toggle/password-toggle-element.spec.ts
  app/javascript/packages/password-toggle/password-toggle-element.ts
  app/services/analytics_events.rb
Labels: performance

#9247 LG-10445: bump up the GPO verification code max attempts to 5
  config/application.yml.default
  spec/controllers/idv/by_mail/enter_code_controller_spec.rb
Labels: status - do not merge

#9272 Override Propshaft digesting for shorter file names
  config/initializers/assets.rb
  lib/extensions/propshaft/asset.rb
Labels: performance
