Repository 18F/identity-idp, pull requests merged in 2023-10, with the labels that each got.

#9288 Rename ial2_consent_given (3/3)
  app/controllers/idv/agreement_controller.rb
  app/controllers/idv/getting_started_controller.rb
  app/forms/idv/consent_form.rb
  spec/controllers/idv/agreement_controller_spec.rb
  spec/controllers/idv/getting_started_controller_spec.rb
Labels: status - do not merge

#9335 LG-11101: Support multiple valid MFA to satisfy authentication request (Part 2 of 2)
  app/controllers/application_controller.rb
  app/controllers/concerns/reauthentication_required_concern.rb
  app/controllers/concerns/remember_device_concern.rb
  app/controllers/concerns/two_factor_authenticatable_methods.rb
  app/policies/service_provider_mfa_policy.rb
  app/services/auth_methods_session.rb
  spec/controllers/concerns/reauthentication_required_concern_spec.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb
  spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
  spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb
  spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb
  spec/controllers/two_factor_authentication/totp_verification_controller_spec.rb
  spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb
  spec/controllers/users/piv_cac_authentication_setup_controller_spec.rb
  spec/controllers/users/piv_cac_login_controller_spec.rb
  spec/features/openid_connect/phishing_resistant_required_spec.rb
  spec/features/saml/phishing_resistant_required_spec.rb
  spec/policies/service_provider_mfa_policy_spec.rb
  spec/services/auth_methods_session_spec.rb
  spec/support/controller_helper.rb
  spec/support/features/session_helper.rb
Labels: status - do not merge

#9443 Add feature specs for expected skip link behavior
  spec/features/accessibility/user_pages_spec.rb
  spec/features/accessibility/visitor_pages_spec.rb
  spec/support/matchers/accessibility.rb
Labels: accessibility

#9445 Remove USWDS prose styles from application stylesheet
  Makefile
  app/assets/stylesheets/_uswds.scss
  app/components/accordion_component.html.erb
Labels: performance

#9446 Move File Input component styles to document capture stylesheet
  Makefile
  app/assets/stylesheets/_uswds-form-controls.scss
  app/assets/stylesheets/components/_index.scss
  app/javascript/packages/document-capture/components/_file-input.scss
  app/javascript/packages/document-capture/styles.scss
Labels: performance

#9448 Add JavaScript naming conventions to frontend documentation
  docs/frontend.md
Labels: documentation

#9478 Remove ineffective invalid CSS
  app/assets/stylesheets/components/_btn.scss
  app/assets/stylesheets/components/_list.scss
Labels: performance

#9495 Deploy RC 328.1 to Prod
  app/views/two_factor_authentication/sms_opt_in/new.html.erb
  spec/controllers/two_factor_authentication/sms_opt_in_controller_spec.rb
Labels: status - promotion
