Repository 18F/identity-idp, pull requests merged in 2024-10, with the labels that each got.

#11300 Deploy RC 418 to Production
  app/controllers/concerns/idv/verify_info_concern.rb
  app/forms/register_user_email_form.rb
  app/jobs/socure_shadow_mode_proofing_job.rb
  app/mailers/user_mailer.rb
  app/presenters/idv/account_verified_email_presenter.rb
  app/services/analytics.rb
  app/services/analytics_events.rb
  app/services/idv/analytics_events_enhancer.rb
  app/services/proofing/aamva/proofer.rb
  app/services/proofing/resolution/progressive_proofer.rb
  app/services/proofing/socure/id_plus/proofer.rb
  app/services/user_alerts/alert_user_about_account_verified.rb
  app/views/user_mailer/account_verified.html.erb
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/zh.yml
  spec/controllers/idv/in_person/verify_info_controller_spec.rb
  spec/controllers/idv/verify_info_controller_spec.rb
  spec/features/idv/analytics_spec.rb
  spec/fixtures/proofing/aamva/responses/verification_response.xml
  spec/fixtures/proofing/aamva/responses/verification_response_namespaced_success.xml
  spec/jobs/resolution_proofing_job_spec.rb
  spec/jobs/socure_shadow_mode_proofing_job_spec.rb
  spec/mailers/previews/user_mailer_preview.rb
  spec/mailers/user_mailer_spec.rb
  spec/presenters/idv/account_verified_email_presenter_spec.rb
  spec/services/analytics_spec.rb
  spec/services/proofing/aamva/proofer_spec.rb
  spec/services/proofing/aamva/response/verification_response_spec.rb
  spec/services/proofing/aamva/verification_client_spec.rb
  spec/services/user_alerts/alert_user_about_account_verified_spec.rb
Labels: status - promotion

#11323 Deploy RC 420 to Production
  app/controllers/concerns/idv/threat_metrix_concern.rb
  app/controllers/concerns/threat_metrix_concern.rb
  app/controllers/idv/in_person_controller.rb
  app/controllers/sign_up/registrations_controller.rb
  app/controllers/test/oidc_test_controller.rb
  app/javascript/packages/document-capture/components/_file-input.scss
  app/javascript/packages/document-capture/components/documents-step.tsx
  app/javascript/packages/document-capture/components/file-input.tsx
  app/javascript/packages/document-capture/components/selfie-step.tsx
  app/models/profile.rb
  app/models/user.rb
  app/services/analytics_events.rb
  app/services/idv/steps/threat_metrix_step_helper.rb
  app/services/saml_request_validator.rb
  app/services/threat_metrix_helper.rb
  app/services/vot/supported_component_values.rb
  app/views/accounts/_identity_verification.html.erb
  app/views/idv/how_to_verify/show.html.erb
  app/views/idv/shared/ssn.html.erb
  app/views/shared/_threat_metrix_profiling.html.erb
  app/views/sign_up/registrations/new.html.erb
  app/views/test/oidc_test/index.html.erb
  config/application.yml.default
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/telephony/fr.yml
  config/locales/telephony/zh.yml
  config/locales/zh.yml
  docs/sdk-upgrade.md
  lib/feature_management.rb
  lib/identity_config.rb
  spec/controllers/concerns/threat_metrix_concern_spec.rb
  spec/features/idv/doc_auth/document_capture_spec.rb
  spec/i18n_spec.rb
  spec/javascript/packages/document-capture/components/documents-and-selfie-step-spec.tsx
  spec/lib/reporting/identity_verification_report_spec.rb
  spec/views/accounts/_identity_verification.html.erb_spec.rb
  spec/views/idv/agreement/show.html.erb_spec.rb
  spec/views/idv/how_to_verify/show.html.erb_spec.rb
Labels: status - promotion

#11307 Use a list to log resolved ACRs in events
  app/services/analytics.rb
  lib/saml_idp_constants.rb
  spec/services/analytics_spec.rb
Labels: type - enhancement, status - ready for review, ruby, area - analytics

#11341 Deploy RC 422 to Prod
  .gitlab-ci.yml
  app/controllers/concerns/idv/verify_info_concern.rb
  app/controllers/concerns/idv_session_concern.rb
  app/controllers/idv/in_person/ssn_controller.rb
  app/controllers/idv/ssn_controller.rb
  app/forms/idv/ssn_format_form.rb
  app/javascript/packs/document-capture.tsx
  app/services/analytics_events.rb
  app/services/id_token_builder.rb
  app/services/idv/session.rb
  app/views/idv/shared/_document_capture.html.erb
  config/application.yml.default
  dockerfiles/application.yaml
  lib/reporting/protocols_report.rb
  lib/tasks/backfill_in_person_pending_at.rake
  spec/controllers/idv/in_person/ssn_controller_spec.rb
  spec/controllers/idv/in_person/verify_info_controller_spec.rb
  spec/controllers/idv/ssn_controller_spec.rb
  spec/controllers/idv/verify_info_controller_spec.rb
  spec/features/idv/doc_auth/document_capture_spec.rb
  spec/features/idv/doc_auth/how_to_verify_spec.rb
  spec/features/idv/doc_auth/hybrid_handoff_spec.rb
  spec/features/idv/steps/in_person/state_id_50_50_spec.rb
  spec/features/idv/steps/in_person_opt_in_ipp_spec.rb
  spec/features/openid_connect/openid_connect_spec.rb
  spec/features/reports/authorization_count_spec.rb
  spec/javascript/packages/document-capture/components/document-capture-spec.jsx
  spec/jobs/get_usps_proofing_results_job_spec.rb
  spec/lib/reporting/protocols_report_spec.rb
  spec/services/id_token_builder_spec.rb
  spec/support/features/idv_helper.rb
  spec/support/idv_examples/sp_handoff.rb
  spec/support/oidc_auth_helper.rb
  spec/support/usps_ipp_helper.rb
Labels: status - promotion

#11359 Deploy RC 423 to Prod
  app/controllers/users/emails_controller.rb
  app/views/users/emails/show.html.erb
  config/locales/zh.yml
  spec/controllers/idv/by_mail/resend_letter_controller_spec.rb
  spec/controllers/idv/personal_key_controller_spec.rb
  spec/controllers/idv/verify_info_controller_spec.rb
  spec/controllers/idv_controller_spec.rb
  spec/controllers/users/emails_controller_spec.rb
  spec/controllers/users/piv_cac_login_controller_spec.rb
  spec/policies/pending_profile_policy_spec.rb
  spec/presenters/account_show_presenter_spec.rb
  spec/presenters/saml_requested_attributes_presenter_spec.rb
  spec/services/attribute_asserter_spec.rb
  spec/services/vot/parser_spec.rb
  spec/views/accounts/_identity_verification.html.erb_spec.rb
Labels: status - promotion

#11351 LG-14642: Update design and copy of GPO 'letter on the way' email
  app/assets/images/email/letter-success.png
  app/helpers/locale_helper.rb
  app/mailers/user_mailer.rb
  app/presenters/idv/account_verified_email_presenter.rb
  app/presenters/idv/by_mail/letter_requested_email_presenter.rb
  app/views/user_mailer/verify_by_mail_letter_requested.html.erb
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/zh.yml
  spec/controllers/idv/verify_info_controller_spec.rb
  spec/features/idv/steps/enter_password_step_spec.rb
  spec/helpers/locale_helper_spec.rb
  spec/i18n_spec.rb
  spec/mailers/previews/user_mailer_preview.rb
  spec/mailers/user_mailer_spec.rb
  spec/policies/pending_profile_policy_spec.rb
  spec/presenters/account_show_presenter_spec.rb
  spec/presenters/idv/account_verified_email_presenter_spec.rb
  spec/presenters/idv/by_mail/letter_requested_email_presenter_spec.rb
Labels: type - enhancement, status - do not merge, area - usability, status - accepted

#11408 Update local development documentation for working with PKI
  docs/local-development.md
Labels: documentation

#11413 LG-14623: Track visits from the "You've verified your identity" email
  app/controllers/application_controller.rb
  app/controllers/idv/account_verified_cta_visited_controller.rb
  app/presenters/idv/account_verified_email_presenter.rb
  app/services/analytics_events.rb
  app/services/sp_return_url_resolver.rb
  app/views/pages/bad_request.html
  app/views/user_mailer/account_verified.html.erb
  config/application.yml.default
  config/routes.rb
  lib/identity_config.rb
  spec/controllers/idv/account_verified_cta_visited_controller_spec.rb
  spec/presenters/idv/account_verified_email_presenter_spec.rb
Labels: ruby, area - analytics

#11436 Deploy RC 427 to Production
  Gemfile.lock
  app/controllers/idv/phone_controller.rb
  app/controllers/socure_webhook_controller.rb
  app/jobs/reports/protocols_report.rb
  app/jobs/socure_docv_results_job.rb
  app/services/doc_auth/socure/requests/docv_result_request.rb
  app/services/doc_auth/socure/responses/docv_result_response.rb
  db/primary_migrate/20241029152408_index_socure_doc_v_transaction_token.rb
  db/schema.rb
  docs/local-development.md
  spec/controllers/socure_webhook_controller_spec.rb
  spec/features/idv/steps/in_person/verify_info_spec.rb
  spec/jobs/socure_docv_results_job_spec.rb
  spec/mailers/previews/report_mailer_preview.rb
  spec/support/fake_analytics_spec.rb
  spec/support/have_logged_event_matcher.rb
Labels: status - promotion
