Repository 18F/identity-idp, pull requests merged in 2024-02, with the labels that each got.

#10013 Load error tracking script asynchronously
  app/helpers/script_helper.rb
  app/views/layouts/base.html.erb
  app/views/layouts/component_preview.html.erb
  spec/helpers/script_helper_spec.rb
Labels: performance

#9961 Add sideEffects directive to all package.json
  Makefile
  app/javascript/packages/README.md
  app/javascript/packages/address-search/package.json
  app/javascript/packages/analytics/package.json
  app/javascript/packages/assets/package.json
  app/javascript/packages/build-sass/package.json
  app/javascript/packages/captcha-submit-button/package.json
  app/javascript/packages/clipboard-button/package.json
  app/javascript/packages/components/package.json
  app/javascript/packages/compose-components/package.json
  app/javascript/packages/config/package.json
  app/javascript/packages/countdown/package.json
  app/javascript/packages/device/package.json
  app/javascript/packages/document-capture-polling/package.json
  app/javascript/packages/document-capture/package.json
  app/javascript/packages/eslint-plugin/package.json
  app/javascript/packages/form-steps/package.json
  app/javascript/packages/i18n/package.json
  app/javascript/packages/manageable-authenticator/package.json
  app/javascript/packages/masked-text-toggle/package.json
  app/javascript/packages/memorable-date/package.json
  app/javascript/packages/modal/package.json
  app/javascript/packages/normalize-yaml/package.json
  app/javascript/packages/one-time-code-input/package.json
  app/javascript/packages/password-confirmation/package.json
  app/javascript/packages/password-strength/package.json
  app/javascript/packages/password-toggle/package.json
  app/javascript/packages/phone-input/package.json
  app/javascript/packages/print-button/package.json
  app/javascript/packages/rails-i18n-webpack-plugin/package.json
  app/javascript/packages/react-hooks/package.json
  app/javascript/packages/react-i18n/package.json
  app/javascript/packages/request/package.json
  app/javascript/packages/session/package.json
  app/javascript/packages/spinner-button/package.json
  app/javascript/packages/step-indicator/package.json
  app/javascript/packages/stylelint-config/package.json
  app/javascript/packages/submit-button/package.json
  app/javascript/packages/test-helpers/package.json
  app/javascript/packages/time-element/package.json
  app/javascript/packages/unpolyfill-webpack-plugin/package.json
  app/javascript/packages/url/package.json
  app/javascript/packages/validated-field/package.json
  app/javascript/packages/verify-flow/package.json
  app/javascript/packages/webauthn/package.json
  docs/frontend.md
  scripts/validate-workspaces.mjs
Labels: performance

#9959 Parallelize feature spec build, leverage Make up-to-date for browsers.json
  Makefile
  docs/local-development.md
  package.json
  spec/rails_helper.rb
  yarn.lock
Labels: performance

#10098 Implement language picker expander as icon
  app/assets/stylesheets/components/_language-picker.scss
  app/components/language_picker_component.html.erb
Labels: performance

#10126 Stop writing to `sp_session[:ial]`
  app/services/store_sp_metadata_in_session.rb
  spec/controllers/openid_connect/authorization_controller_spec.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/services/store_sp_metadata_in_session_spec.rb
Labels: status - do not merge

#10128 Stop writing to `sp_session[:ialmax]`
  app/services/store_sp_metadata_in_session.rb
  spec/controllers/openid_connect/authorization_controller_spec.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/services/store_sp_metadata_in_session_spec.rb
Labels: status - do not merge

#10130 Stop writing to `sp_session[:ial2]`
  app/services/store_sp_metadata_in_session.rb
  spec/controllers/openid_connect/authorization_controller_spec.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/services/store_sp_metadata_in_session_spec.rb
Labels: status - do not merge

#10166 Deploy RC 359 to Production
  Gemfile.lock
  app/controllers/accounts/connected_accounts_controller.rb
  app/controllers/accounts/history_controller.rb
  app/controllers/accounts/two_factor_authentication_controller.rb
  app/controllers/accounts_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/fraud_review_concern.rb
  app/controllers/concerns/remember_device_concern.rb
  app/controllers/events_controller.rb
  app/controllers/saml_idp_controller.rb
  app/controllers/users/passwords_controller.rb
  app/controllers/users/piv_cac_login_controller.rb
  app/controllers/users/verify_password_controller.rb
  app/javascript/packages/document-capture/components/acuant-capture.tsx
  app/javascript/packages/document-capture/components/document-side-acuant-capture.tsx
  app/javascript/packages/phone-input/package.json
  app/presenters/account_show_presenter.rb
  app/services/doc_auth/mock/result_response.rb
  app/services/id_token_builder.rb
  app/services/proofing/aamva/request/verification_request.rb
  app/services/store_sp_metadata_in_session.rb
  app/services/vot/legacy_component_values.rb
  app/views/accounts/_personal_key.html.erb
  app/views/accounts/show.html.erb
  app/views/idv/not_verified/show.html.erb
  bin/oncall/email-deliveries
  config/application.yml.default
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
  lib/identity_config.rb
  spec/controllers/accounts_controller_spec.rb
  spec/controllers/idv/please_call_controller_spec.rb
  spec/controllers/openid_connect/authorization_controller_spec.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/controllers/users/passwords_controller_spec.rb
  spec/controllers/users/two_factor_authentication_controller_spec.rb
  spec/controllers/users/verify_password_controller_spec.rb
  spec/features/idv/doc_auth/document_capture_spec.rb
  spec/features/remember_device/cookie_expiration_spec.rb
  spec/features/users/password_recovery_via_recovery_code_spec.rb
  spec/features/users/profile_recovery_for_gpo_verified_spec.rb
  spec/features/users/user_profile_spec.rb
  spec/fixtures/ial2_test_credential_barcode_attention_liveness_fail.yml
  spec/presenters/account_show_presenter_spec.rb
  spec/services/id_token_builder_spec.rb
  spec/services/store_sp_metadata_in_session_spec.rb
  spec/support/shared_examples/sign_in.rb
  spec/views/accounts/connected_accounts/show.html.erb_spec.rb
  spec/views/accounts/history/show.html.erb_spec.rb
  spec/views/accounts/show.html.erb_spec.rb
  spec/views/accounts/two_factor_authentication/show.html.erb_spec.rb
  spec/views/idv/not_verified/show.html.erb_spec.rb
  yarn.lock
Labels: status - promotion
