Repository 18F/identity-idp, pull requests merged in 2024-12, with the labels that each got.

#11611 Expand on form pattern documentation validation, error handling
  docs/backend.md
Labels: documentation

#11648 Update Node.js dependencies for improved LTS support
  Gemfile.lock
  package.json
  scripts/enforce-typescript-files.mjs
  scripts/validate-workspaces.mjs
  spec/features/idv/end_to_end_idv_spec.rb
  spec/features/saml/saml_spec.rb
  spec/features/saml/vtr_spec.rb
  spec/support/features/idv_helper.rb
  tsconfig.json
  typings/clipboard-polyfill/overwrite-globals.d.ts
  webpack.config.js
  yarn.lock
Labels: dependencies

#11588 LG-14064: Make IdV event enhancement opt-out
  app/services/idv/analytics_events_enhancer.rb
  lib/analytics_events_documenter.rb
  spec/features/idv/analytics_spec.rb
  spec/services/idv/analytics_events_enhancer_spec.rb
  spec/support/fake_analytics.rb
Labels: status - ready for review, ruby, area - analytics
