Repository 18F/identity-idp, pull requests merged in 2024-05, with the labels that each got.

#10546 Deploy RC 376 to Production
  .gitlab-ci.yml
  Gemfile.lock
  app/controllers/concerns/billable_event_trackable.rb
  app/controllers/idv/by_mail/request_letter_controller.rb
  app/controllers/idv/enter_password_controller.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/controllers/users/backup_code_setup_controller.rb
  app/forms/idv/api_image_upload_form.rb
  app/forms/openid_connect_authorize_form.rb
  app/javascript/packages/document-capture/components/document-side-acuant-capture.tsx
  app/javascript/packages/form-steps/form-error.ts
  app/javascript/packages/form-steps/form-steps.tsx
  app/mailers/user_mailer.rb
  app/models/sp_return_log.rb
  app/presenters/navigation_presenter.rb
  app/services/analytics_events.rb
  app/services/gpo_reminder_sender.rb
  app/services/store_sp_metadata_in_session.rb
  app/views/accounts/actions/_generate_backup_codes.html.erb
  app/views/user_mailer/verify_by_mail_letter_requested.html.erb
  app/views/user_mailer/verify_by_mail_reminder.html.erb
  app/views/users/backup_code_setup/create.html.erb
  config/locales/doc_auth/en.yml
  config/locales/doc_auth/es.yml
  config/locales/doc_auth/fr.yml
  config/locales/doc_auth/zh.yml
  config/routes.rb
  db/primary_migrate/20240412175415_add_columns_to_sp_return_logs.rb
  db/schema.rb
  lib/pinpoint_supported_countries.rb
  spec/controllers/concerns/billable_event_trackable_spec.rb
  spec/controllers/idv/image_uploads_controller_spec.rb
  spec/controllers/openid_connect/authorization_controller_spec.rb
  spec/features/idv/doc_auth/document_capture_spec.rb
  spec/features/idv/doc_auth/redo_document_capture_spec.rb
  spec/features/idv/hybrid_mobile/hybrid_mobile_spec.rb
  spec/features/openid_connect/authorization_confirmation_spec.rb
  spec/forms/idv/api_image_upload_form_spec.rb
  spec/forms/openid_connect_authorize_form_spec.rb
  spec/javascript/packages/document-capture/components/document-capture-spec.jsx
  spec/mailers/previews/user_mailer_preview.rb
  spec/mailers/user_mailer_spec.rb
  spec/services/store_sp_metadata_in_session_spec.rb
  spec/support/features/idv_helper.rb
  spec/support/features/idv_step_helper.rb
  spec/support/oidc_auth_helper.rb
  spec/views/users/backup_code_setup/create.html.erb_spec.rb
Labels: status - promotion

#10344 LG-11753 Update Enter Code (formerly, Welcome Back) Screen
  app/views/idv/by_mail/enter_code/_enter_code.html.erb
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
  config/locales/idv/zh.yml
  spec/features/idv/confirm_start_over_spec.rb
  spec/features/idv/in_person_spec.rb
  spec/features/idv/steps/enter_code_step_spec.rb
  spec/features/idv/steps/request_letter_step_spec.rb
  spec/support/idv_examples/clearing_and_restarting.rb
  spec/support/idv_examples/verification_code_entry.rb
Labels: status - do not merge

#10357 LG-12064 Update "Didn't get your letter?" screen
  app/views/idv/by_mail/enter_code/_did_not_receive_letter.html.erb
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
  config/locales/idv/zh.yml
  spec/features/idv/steps/enter_code_step_spec.rb
  spec/features/idv/steps/request_letter_step_spec.rb
  spec/views/idv/by_mail/enter_code/index.html.erb_spec.rb
Labels: status - do not merge

#10353 LG-12062: Update step indicator copy for request letter screen
  app/controllers/concerns/idv/step_indicator_concern.rb
  app/controllers/idv/by_mail/request_letter_controller.rb
  app/controllers/idv/confirm_start_over_controller.rb
  app/controllers/idv/enter_password_controller.rb
  app/controllers/idv/personal_key_controller.rb
  app/javascript/packages/verify-flow/verify-flow-step-indicator.spec.tsx
  app/javascript/packages/verify-flow/verify-flow-step-indicator.tsx
  app/services/idv/flows/in_person_flow.rb
  app/views/idv/by_mail/enter_code/index.html.erb
  app/views/idv/by_mail/enter_code_rate_limited/index.html.erb
  app/views/idv/by_mail/letter_enqueued/show.html.erb
  app/views/idv/by_mail/request_letter/index.html.erb
  app/views/idv/otp_verification/show.html.erb
  app/views/idv/personal_key/show.html.erb
  app/views/idv/phone/new.html.erb
  app/views/idv/phone_errors/_warning.html.erb
  app/views/idv/phone_errors/failure.html.erb
  app/views/idv/phone_errors/warning.html.erb
  app/views/idv/please_call/show.html.erb
  config/locales/step_indicator/en.yml
  config/locales/step_indicator/es.yml
  config/locales/step_indicator/fr.yml
  config/locales/step_indicator/zh.yml
  spec/controllers/concerns/idv/step_indicator_concern_spec.rb
  spec/controllers/idv/by_mail/request_letter_controller_spec.rb
  spec/controllers/idv/enter_password_controller_spec.rb
  spec/features/idv/confirm_start_over_spec.rb
  spec/features/idv/end_to_end_idv_spec.rb
  spec/features/idv/in_person_spec.rb
  spec/features/idv/in_person_threatmetrix_spec.rb
  spec/features/idv/steps/enter_code_step_spec.rb
  spec/features/idv/steps/in_person_opt_in_ipp_spec.rb
  spec/features/users/verify_profile_spec.rb
  spec/i18n_spec.rb
  spec/support/features/in_person_helper.rb
  spec/support/idv_examples/verification_code_entry.rb
  spec/views/idv/by_mail/letter_enqueued/show.html.erb_spec.rb
  spec/views/idv/enter_password/new.html.erb_spec.rb
  spec/views/idv/please_call/show.html.erb_spec.rb
  spec/views/idv/shared/_error.html.erb_spec.rb
Labels: status - do not merge

#10612 Optimize preload response headers to prioritize critical assets
  app/helpers/script_helper.rb
  app/helpers/stylesheet_helper.rb
  app/views/devise/sessions/new.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/base.html.erb
  app/views/session_timeout/_expire_session.html.erb
  spec/helpers/script_helper_spec.rb
  spec/helpers/stylesheet_helper_spec.rb
  spec/views/devise/sessions/new.html.erb_spec.rb
Labels: performance

#10638 Deploy RC RC 380 to Prod
  Gemfile.lock
  app/assets/images/idv/mobile-phone-icon.svg
  app/controllers/idv/how_to_verify_controller.rb
  app/jobs/reports/drop_off_report.rb
  app/presenters/idv/how_to_verify_presenter.rb
  app/services/store_sp_metadata_in_session.rb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/event_disavowal/new.html.erb
  app/views/idv/by_mail/enter_code/_form.html.erb
  app/views/idv/how_to_verify/show.html.erb
  app/views/idv/in_person/address/show.html.erb
  app/views/idv/shared/ssn.html.erb
  app/views/sign_up/passwords/new.html.erb
  app/views/sign_up/registrations/new.html.erb
  app/views/two_factor_authentication/backup_code_verification/show.html.erb
  app/views/two_factor_authentication/options/index.html.erb
  app/views/two_factor_authentication/personal_key_verification/show.html.erb
  app/views/users/delete/show.html.erb
  app/views/users/emails/show.html.erb
  app/views/users/passwords/edit.html.erb
  app/views/users/phone_setup/index.html.erb
  app/views/users/rules_of_use/new.html.erb
  app/views/users/verify_password/new.html.erb
  config/application.yml.default
  config/initializers/job_configurations.rb
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/zh.yml
  dockerfiles/idp_ci.Dockerfile
  lib/identity_config.rb
  lib/reporting/authentication_report.rb
  spec/controllers/openid_connect/authorization_controller_spec.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/features/idv/doc_auth/hybrid_handoff_spec.rb
  spec/jobs/reports/authentication_report_spec.rb
  spec/jobs/reports/drop_off_report_spec.rb
  spec/lib/reporting/authentication_report_spec.rb
  spec/services/store_sp_metadata_in_session_spec.rb
  spec/support/features/in_person_helper.rb
  spec/support/features/interaction_helper.rb
  spec/views/idv/how_to_verify/show.html.erb_spec.rb
Labels: status - promotion

#10647 Use SHA256 for JavaScript subresource integrity
  webpack.config.js
Labels: performance

#10427 LG-13005: use TransactionStatus to determine if document passed TrueID
  app/presenters/image_upload_response_presenter.rb
  app/services/doc_auth/error_generator.rb
  app/services/doc_auth/lexis_nexis/responses/true_id_response.rb
  app/services/doc_auth/mock/result_response.rb
  spec/controllers/idv/image_uploads_controller_spec.rb
  spec/fixtures/ial2_test_credential_back_fail_doc_auth_face_match_errors.yml
  spec/fixtures/ial2_test_credential_back_fail_doc_auth_liveness_errors.yml
  spec/fixtures/ial2_test_credential_barcode_attention_liveness_fail.yml
  spec/fixtures/ial2_test_credential_classification_info_no_name.yml
  spec/fixtures/ial2_test_credential_doc_auth_attention_face_match_fail.yml
  spec/fixtures/ial2_test_credential_doc_auth_fail_and_no_liveness.yml
  spec/fixtures/ial2_test_credential_doc_auth_fail_face_match_fail.yml
  spec/fixtures/ial2_test_credential_doc_auth_fail_selfie_pass.yml
  spec/fixtures/ial2_test_credential_doc_auth_selfie_pass_pii_fail.yml
  spec/fixtures/ial2_test_credential_face_match_fail_and_pii_fail.yml
  spec/fixtures/ial2_test_credential_liveness_fail_face_match_fail.yml
  spec/fixtures/ial2_test_credential_no_liveness.yml
  spec/fixtures/ial2_test_credential_poor_quality.yml
  spec/fixtures/ial2_test_portrait_match_success.yml
  spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_attention_barcode.json
  spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_failure_no_liveness.json
  spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_failure_no_liveness_low_dpi.json
  spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_failure_with_all_failures.json
  spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_failure_with_face_match_pass.json
  spec/fixtures/proofing/lexis_nexis/true_id/true_id_response_failure_with_liveness.json
  spec/forms/idv/api_image_upload_form_spec.rb
  spec/presenters/image_upload_response_presenter_spec.rb
  spec/services/doc_auth/error_generator_spec.rb
  spec/services/doc_auth/lexis_nexis/requests/true_id_request_spec.rb
  spec/services/doc_auth/lexis_nexis/responses/true_id_response_spec.rb
  spec/services/doc_auth/mock/doc_auth_mock_client_spec.rb
  spec/services/doc_auth/mock/result_response_spec.rb
Labels: status - do not merge

#10703 Consolidate and simplify account profile card styles
  app/assets/stylesheets/_uswds.scss
  app/assets/stylesheets/application.css.scss
  app/assets/stylesheets/components/_profile-section.scss
  app/assets/stylesheets/variables/_app.scss
  app/views/accounts/history/show.html.erb
Labels: performance

#10702 Deploy RC 383 to Production
  app/assets/stylesheets/_uswds.scss
  app/assets/stylesheets/application.css.scss
  app/assets/stylesheets/components/_profile-section.scss
  app/assets/stylesheets/variables/_app.scss
  app/controllers/concerns/saml_idp_auth_concern.rb
  app/controllers/idv/how_to_verify_controller.rb
  app/controllers/two_factor_authentication/backup_code_verification_controller.rb
  app/controllers/two_factor_authentication/otp_verification_controller.rb
  app/controllers/two_factor_authentication/personal_key_verification_controller.rb
  app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
  app/controllers/two_factor_authentication/totp_verification_controller.rb
  app/controllers/two_factor_authentication/webauthn_verification_controller.rb
  app/controllers/users/backup_code_setup_controller.rb
  app/controllers/users/two_factor_authentication_controller.rb
  app/forms/idv/how_to_verify_form.rb
  app/javascript/packages/phone-input/package.json
  app/models/user.rb
  app/services/analytics.rb
  app/services/analytics_events.rb
  app/services/reporting/total_user_count_report.rb
  app/services/saml_request_validator.rb
  app/services/vot/component_expander.rb
  app/services/vot/parser.rb
  app/services/vot/supported_component_values.rb
  app/views/accounts/history/show.html.erb
  app/views/idv/how_to_verify/show.html.erb
  app/views/users/backup_code_setup/edit.html.erb
  config/application.yml.default
  lib/identity_config.rb
  lib/reporting/proofing_rate_report.rb
  lib/saml_idp_constants.rb
  spec/controllers/idv/how_to_verify_controller_spec.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb
  spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
  spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb
  spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb
  spec/controllers/two_factor_authentication/totp_verification_controller_spec.rb
  spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb
  spec/controllers/users/backup_code_setup_controller_spec.rb
  spec/controllers/users/two_factor_authentication_controller_spec.rb
  spec/features/account/backup_codes_spec.rb
  spec/lib/reporting/proofing_rate_report_spec.rb
  spec/models/user_spec.rb
  spec/services/reporting/total_user_count_report_spec.rb
  spec/services/vot/component_expander_spec.rb
  spec/support/fake_analytics.rb
  spec/views/users/backup_code_setup/edit.html.erb_spec.rb
  yarn.lock
Labels: status - promotion

#10711 Roll back RC 383
  app/assets/stylesheets/_uswds.scss
  app/assets/stylesheets/application.css.scss
  app/assets/stylesheets/components/_profile-section.scss
  app/assets/stylesheets/variables/_app.scss
  app/controllers/concerns/saml_idp_auth_concern.rb
  app/controllers/idv/how_to_verify_controller.rb
  app/controllers/two_factor_authentication/backup_code_verification_controller.rb
  app/controllers/two_factor_authentication/otp_verification_controller.rb
  app/controllers/two_factor_authentication/personal_key_verification_controller.rb
  app/controllers/two_factor_authentication/piv_cac_verification_controller.rb
  app/controllers/two_factor_authentication/totp_verification_controller.rb
  app/controllers/two_factor_authentication/webauthn_verification_controller.rb
  app/controllers/users/backup_code_setup_controller.rb
  app/controllers/users/two_factor_authentication_controller.rb
  app/forms/idv/how_to_verify_form.rb
  app/javascript/packages/phone-input/package.json
  app/models/user.rb
  app/services/analytics.rb
  app/services/analytics_events.rb
  app/services/reporting/total_user_count_report.rb
  app/services/saml_request_validator.rb
  app/services/vot/component_expander.rb
  app/services/vot/parser.rb
  app/services/vot/supported_component_values.rb
  app/views/accounts/history/show.html.erb
  app/views/idv/how_to_verify/show.html.erb
  app/views/users/backup_code_setup/edit.html.erb
  config/application.yml.default
  lib/identity_config.rb
  lib/reporting/proofing_rate_report.rb
  lib/saml_idp_constants.rb
  spec/controllers/idv/how_to_verify_controller_spec.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/controllers/two_factor_authentication/backup_code_verification_controller_spec.rb
  spec/controllers/two_factor_authentication/otp_verification_controller_spec.rb
  spec/controllers/two_factor_authentication/personal_key_verification_controller_spec.rb
  spec/controllers/two_factor_authentication/piv_cac_verification_controller_spec.rb
  spec/controllers/two_factor_authentication/totp_verification_controller_spec.rb
  spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb
  spec/controllers/users/backup_code_setup_controller_spec.rb
  spec/controllers/users/two_factor_authentication_controller_spec.rb
  spec/features/account/backup_codes_spec.rb
  spec/lib/reporting/proofing_rate_report_spec.rb
  spec/models/user_spec.rb
  spec/services/reporting/total_user_count_report_spec.rb
  spec/services/vot/component_expander_spec.rb
  spec/support/fake_analytics.rb
  spec/views/users/backup_code_setup/edit.html.erb_spec.rb
  yarn.lock
Labels: status - promotion

#10723 Deploy RC 385 to Production
  .gitlab-ci.yml
  .rubocop.yml
  app/controllers/frontend_log_controller.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/jobs/resolution_proofing_job.rb
  app/presenters/openid_connect_user_info_presenter.rb
  app/services/analytics_events.rb
  app/services/encryption/user_access_key.rb
  app/services/idv/analytics_events_enhancer.rb
  app/services/marketing_site.rb
  app/services/proofing/aamva/hmac_secret.rb
  app/services/sp_handoff_bounce/add_handoff_time_to_session.rb
  app/services/sp_handoff_bounce/is_bounced.rb
  app/services/sp_handoff_bouncer.rb
  app/services/x509/attribute.rb
  app/views/idv/how_to_verify/show.html.erb
  app/views/idv/welcome/show.html.erb
  config/application.yml.default
  config/initializers/rack_timeout.rb
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/zh.yml
  lib/aws/ses.rb
  lib/identity_config.rb
  lib/reporting/identity_verification_report.rb
  lib/reporting/protocols_report.rb
  spec/controllers/concerns/remember_device_concern_spec.rb
  spec/features/idv/doc_auth/welcome_spec.rb
  spec/i18n_spec.rb
  spec/lib/reporting/identity_verification_report_spec.rb
  spec/lib/reporting/protocols_report_spec.rb
  spec/presenters/openid_connect_user_info_presenter_spec.rb
  spec/support/features/idv_step_helper.rb
  spec/views/idv/welcome/show.html.erb_spec.rb
Labels: status - promotion
