Repository 18F/identity-idp, pull requests merged in 2024-06, with the labels that each got.

#10780 Use Random.hex for base component unique ID
  app/components/base_component.rb
Labels: performance

#10786 LG-13387 Remove SP cost tracking logic from `VerifyInfoConcern`
  app/controllers/concerns/idv/verify_info_concern.rb
  spec/controllers/idv/in_person/verify_info_controller_spec.rb
  spec/controllers/idv/verify_info_controller_spec.rb
Labels: status - do not merge

#10825 Deploy RC 390 to Production
  .gitlab-ci.yml
  Gemfile
  Gemfile.lock
  Makefile
  app/controllers/concerns/idv/verify_info_concern.rb
  app/controllers/idv/address_controller.rb
  app/controllers/idv/in_person/verify_info_controller.rb
  app/controllers/idv/verify_info_controller.rb
  app/controllers/saml_idp_controller.rb
  app/controllers/test/oidc_test_controller.rb
  app/forms/idv/address_form.rb
  app/javascript/packages/document-capture/components/acuant-capture-canvas.jsx
  app/javascript/packages/document-capture/higher-order/observable-property.tsx
  app/jobs/reports/combined_invoice_supplement_report_v2.rb
  app/services/analytics_events.rb
  app/services/db/monthly_sp_auth_count/new_unique_monthly_user_counts_by_partner.rb
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/telephony/zh.yml
  config/locales/zh.yml
  db/schema.rb
  spec/controllers/idv/in_person/verify_info_controller_spec.rb
  spec/controllers/idv/verify_info_controller_spec.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/features/account_email_language_spec.rb
  spec/features/idv/analytics_spec.rb
  spec/i18n_spec.rb
  spec/javascript/packages/document-capture/components/acuant-capture-canvas-spec.jsx
  spec/javascript/packages/document-capture/higher-order/observable-property-spec.tsx
  spec/jobs/reports/combined_invoice_supplement_report_v2_spec.rb
  spec/services/db/monthly_sp_auth_count/new_unique_monthly_user_counts_by_partner_spec.rb
  spec/services/idv/agent_spec.rb
Labels: status - promotion

#10855 Deploy RC 391.1 to Production
  app/jobs/reports/drop_off_report.rb
  lib/identity_config.rb
  spec/jobs/reports/drop_off_report_spec.rb
Labels: status - promotion

#10827 Remove the `should_proof_state_id` argument from the `Idv::Agent` call to the `ResolutionProofingJob`
  app/services/idv/agent.rb
Labels: status - do not merge

#10881 Deploy RC 393 to Production
  app/controllers/analytics_events_controller.rb
  app/controllers/concerns/idv/verify_info_concern.rb
  app/controllers/idv/by_mail/resend_letter_controller.rb
  app/jobs/reports/combined_invoice_supplement_report_v2.rb
  app/models/user.rb
  app/services/analytics_events.rb
  app/services/db/monthly_sp_auth_count/total_monthly_auth_counts_within_iaa_window.rb
  app/services/db/monthly_sp_auth_count/unique_monthly_auth_counts_by_iaa.rb
  app/services/idv/agent.rb
  app/services/idv/gpo_mail.rb
  app/views/idv/by_mail/resend_letter/new.html.erb
  config/application.rb
  config/routes.rb
  lib/reporting/fraud_metrics_lg99_report.rb
  lib/reporting/mfa_report.rb
  lib/reporting/protocols_report.rb
  lib/tasks/backfill_sponsor_id.rake
  spec/bin/oncall/download-piv-certs_spec.rb
  spec/bin/oncall/otp-deliveries_spec.rb
  spec/controllers/analytics_events_controller_spec.rb
  spec/controllers/idv/by_mail/resend_letter_controller_spec.rb
  spec/factories/in_person_enrollments.rb
  spec/features/idv/analytics_spec.rb
  spec/features/new_device_tracking_spec.rb
  spec/jobs/reports/combined_invoice_supplement_report_v2_spec.rb
  spec/lib/reporting/authentication_report_spec.rb
  spec/lib/reporting/cloudwatch_client_spec.rb
  spec/lib/reporting/drop_off_report_spec.rb
  spec/lib/reporting/fraud_metrics_lg99_report_spec.rb
  spec/lib/reporting/identity_verification_report_spec.rb
  spec/lib/reporting/mfa_report_spec.rb
  spec/lib/reporting/protocols_report_spec.rb
  spec/lib/tasks/backfill_sponsor_id_rake_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/requests/api_cors_spec.rb
  spec/services/db/monthly_sp_auth_count/total_monthly_auth_counts_within_iaa_window_spec.rb
  spec/services/db/monthly_sp_auth_count/unique_monthly_auth_counts_by_iaa_spec.rb
  spec/support/aws_cloudwatch_helper.rb
  spec/support/features/session_helper.rb
Labels: status - promotion

#10884 Deploy RC 393.1 to Production
  app/controllers/concerns/idv_step_concern.rb
  app/controllers/concerns/rate_limit_concern.rb
  app/controllers/idv/by_mail/enter_code_controller.rb
  app/controllers/idv/by_mail/request_letter_controller.rb
  app/controllers/idv/by_mail/resend_letter_controller.rb
  app/controllers/idv/phone_controller.rb
  app/controllers/idv/phone_errors_controller.rb
  app/controllers/vendor_outage_controller.rb
  app/forms/gpo_verify_form.rb
  app/policies/idv/gpo_verify_by_mail_policy.rb
  app/services/vot/parser.rb
  app/services/vot/supported_component_values.rb
  app/views/idv/by_mail/enter_code/_did_not_receive_letter.html.erb
  app/views/idv/by_mail/enter_code/_enter_code.html.erb
  spec/controllers/idv/by_mail/request_letter_controller_spec.rb
  spec/features/idv/steps/request_letter_step_spec.rb
  spec/features/saml/ial2_sso_spec.rb
  spec/policies/idv/gpo_verify_by_mail_policy_spec.rb
  spec/policies/service_provider_mfa_policy_spec.rb
  spec/services/analytics_spec.rb
  spec/services/idv/gpo_mail_spec.rb
  spec/services/vot/parser_spec.rb
  spec/views/idv/by_mail/enter_code/index.html.erb_spec.rb
Labels: status - promotion
