Repository 18F/identity-idp, pull requests merged in 2024-08, with the labels that each got.

#11015 WIP changelog: Internal, In-person proofing, make sponser_id on in_person…
  db/primary_migrate/20240801155943_change_in_person_enrollment_sponsor_id_to_non_nullable.rb
  db/primary_migrate/20240801183410_validate_change_in_person_enrollment_sponsor_id_to_non_nullable.rb
  db/schema.rb
  lib/tasks/dev.rake
  spec/lib/tasks/backfill_sponsor_id_rake_spec.rb
  spec/services/usps_in_person_proofing/enrollment_helper_spec.rb
Labels: status - work in progress

#11044 Remove asset tag helper patch assigning empty image alt
  config/initializers/asset_tag_helper_patch.rb
Labels: accessibility

#11036 LG-13809 | Remove inaccurate mention of US territories being able to verify
  app/views/idv/phone/new.html.erb
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/zh.yml
Labels: status - ready for review, needs code review

#11057 Deploy RC 404 to Production
  app/assets/images/email/info.png
  app/assets/images/email/warning.png
  app/assets/stylesheets/email.css.scss
  app/controllers/redirect/policy_controller.rb
  app/forms/idv/api_image_upload_form.rb
  app/javascript/packages/webauthn/enroll-webauthn-device.spec.ts
  app/javascript/packages/webauthn/enroll-webauthn-device.ts
  app/jobs/get_usps_proofing_results_job.rb
  app/models/doc_auth_log.rb
  app/policies/mfa_policy.rb
  app/presenters/two_factor_options_presenter.rb
  app/services/usps_in_person_proofing/mock/fixtures.rb
  app/services/usps_in_person_proofing/mock/proofer.rb
  app/services/usps_in_person_proofing/mock/responses/request_enrollment_code_response.json
  app/services/usps_in_person_proofing/proofer.rb
  app/views/account_reset/pending/confirm.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/idv/agreement/show.html.erb
  app/views/idv/phone/new.html.erb
  app/views/user_mailer/shared/_in_person_ready_to_verify.html.erb
  config/initializers/asset_tag_helper_patch.rb
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/zh.yml
  db/primary_migrate/20240807202012_drop_aamva_from_doc_auth_logs.rb
  db/schema.rb
  spec/controllers/idv/image_uploads_controller_spec.rb
  spec/controllers/redirect/policy_controller_spec.rb
  spec/features/account_reset/pending_request_spec.rb
  spec/features/two_factor_authentication/multiple_mfa_sign_up_spec.rb
  spec/features/users/sign_in_spec.rb
  spec/forms/idv/api_image_upload_form_spec.rb
  spec/policies/mfa_policy_spec.rb
  spec/presenters/two_factor_options_presenter_spec.rb
  spec/services/attribute_asserter_spec.rb
  spec/services/usps_in_person_proofing/proofer_spec.rb
  spec/support/usps_ipp_helper.rb
  spec/views/devise/sessions/new.html.erb_spec.rb
  spec/views/idv/agreement/show.html.erb_spec.rb
Labels: status - promotion

#11048 Disable USWDS default external link screen reader text
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_link.scss
Labels: accessibility

#11066 LG-13869: Update email languages preference copy
  app/views/shared/_email_languages.html.erb
  app/views/users/email_language/show.html.erb
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/zh.yml
Labels: accessibility

#11068 LG-14153 Display EIPP Expiration Date on Ready to Verify View and Email
  app/models/in_person_enrollment.rb
  config/application.yml.default
  lib/identity_config.rb
  spec/models/in_person_enrollment_spec.rb
Labels: status - work in progress

#11077 Use faster default driver for feature tests not requiring JavaScript
  spec/features/openid_connect/vtr_spec.rb
  spec/features/users/profile_recovery_for_gpo_verified_spec.rb
  spec/features/users/sign_up_spec.rb
  spec/features/webauthn/sign_in_spec.rb
Labels: performance

#11076 Document authentication analytics events properties
  app/services/analytics_events.rb
  spec/controllers/account_reset/cancel_controller_spec.rb
  spec/controllers/accounts/personal_keys_controller_spec.rb
  spec/controllers/concerns/mfa_setup_concern_spec.rb
  spec/controllers/openid_connect/token_controller_spec.rb
  spec/controllers/two_factor_authentication/sms_opt_in_controller_spec.rb
  spec/controllers/two_factor_authentication/webauthn_verification_controller_spec.rb
  spec/controllers/users/email_confirmations_controller_spec.rb
  spec/controllers/users/piv_cac_authentication_setup_controller_spec.rb
  spec/controllers/users/two_factor_authentication_controller_spec.rb
  spec/controllers/users/webauthn_setup_controller_spec.rb
  spec/features/account_reset/cancel_request_spec.rb
  spec/features/multi_factor_authentication/mfa_cta_spec.rb
  spec/features/multiple_emails/add_email_spec.rb
  spec/features/multiple_emails/sp_sign_in_spec.rb
  spec/features/openid_connect/openid_connect_spec.rb
  spec/features/openid_connect/phishing_resistant_required_spec.rb
  spec/features/openid_connect/vtr_spec.rb
  spec/features/remember_device/user_opted_preference_spec.rb
  spec/features/remember_device/webauthn_spec.rb
  spec/features/saml/phishing_resistant_required_spec.rb
  spec/features/saml/vtr_spec.rb
  spec/features/sign_in/multiple_vot_spec.rb
  spec/features/sign_in/setup_piv_cac_after_sign_in_spec.rb
  spec/features/sign_in/two_factor_options_spec.rb
  spec/features/two_factor_authentication/multiple_mfa_sign_up_spec.rb
  spec/features/two_factor_authentication/sign_in_spec.rb
  spec/features/users/piv_cac_management_spec.rb
  spec/features/users/regenerate_personal_key_spec.rb
  spec/features/users/sign_up_spec.rb
  spec/features/users/user_profile_spec.rb
  spec/features/webauthn/hidden_spec.rb
  spec/features/webauthn/management_spec.rb
  spec/features/webauthn/sign_in_spec.rb
  spec/features/webauthn/sign_up_spec.rb
  spec/requests/openid_connect_cors_spec.rb
Labels: documentation

#11078 Remove pii_like_keypaths from documented analytics properties
  app/services/analytics_events.rb
Labels: documentation

#11096 Use defer for non-critical scripts
  app/views/devise/sessions/new.html.erb
  app/views/layouts/base.html.erb
  spec/helpers/script_helper_spec.rb
  spec/views/devise/sessions/new.html.erb_spec.rb
Labels: performance

#11108 Remove reference to frontend interest group team in contributing guide
  CONTRIBUTING.md
Labels: documentation

#11086 LG-13947: Update links
  app/views/accounts/_pii.html.erb
  app/views/idv/in_person/ready_to_verify/show.html.erb
  app/views/idv/in_person/state_id.html.erb
  app/views/idv/in_person/state_id/show.html.erb
  app/views/shared/_personal_key.html.erb
  spec/views/idv/in_person/ready_to_verify/show.html.erb_spec.rb
  spec/views/shared/_personal_key.html.erb_spec.rb
Labels: status - work in progress

#11126 Use defer when loading GTM script via patched DAP
  app/javascript/packages/analytics/digital-analytics-program.patch
Labels: performance

#11151 Deploy RC 409 to Production
  .rubocop.yml
  Gemfile.lock
  app/controllers/concerns/idv/verify_info_concern.rb
  app/controllers/idv/in_person/verify_info_controller.rb
  app/controllers/idv/verify_info_controller.rb
  app/controllers/socure_webhook_controller.rb
  app/javascript/packages/document-capture/components/acuant-capture.tsx
  app/javascript/packs/ssn-field.ts
  app/javascript/packs/state-guidance.ts
  app/jobs/reports/monthly_gpo_letter_requests_report.rb
  app/jobs/reports/monthly_key_metrics_report.rb
  app/services/analytics_events.rb
  app/services/doc_auth/lexis_nexis/image_metrics_reader.rb
  app/services/encryption/encryptors/attribute_encryptor.rb
  app/services/event_disavowal/build_disavowed_event_analytics_attributes.rb
  app/services/flow/base_flow.rb
  app/services/proofing/ddp_result.rb
  app/services/reporting/active_users_count_report.rb
  app/views/idv/shared/_document_capture.html.erb
  config/application.yml.default
  config/initializers/job_configurations.rb
  db/primary_migrate/20240822122355_add_selected_email_to_identity.rb
  db/schema.rb
  lib/identity_config.rb
  lib/reporting/drop_off_report.rb
  lib/reporting/mfa_report.rb
  spec/config/initializers/job_configurations_spec.rb
  spec/controllers/event_disavowal_controller_spec.rb
  spec/controllers/idv/in_person/verify_info_controller_spec.rb
  spec/controllers/idv/verify_info_controller_spec.rb
  spec/controllers/socure_webhook_controller_spec.rb
  spec/features/idv/analytics_spec.rb
  spec/features/phone/confirmation_spec.rb
  spec/javascript/packages/document-capture/components/acuant-capture-spec.jsx
  spec/lib/reporting/drop_off_report_spec.rb
  spec/models/user_spec.rb
  spec/services/proofing/aamva/verification_client_spec.rb
  spec/services/proofing/ddp_result_spec.rb
  spec/services/reporting/active_users_count_report_spec.rb
  spec/support/matchers/accessibility.rb
  spec/support/shared_examples_for_email_validation.rb
  spec/views/idv/shared/_document_capture.html.erb_spec.rb
Labels: status - promotion
