Repository 18F/identity-idp, pull requests merged in 2024-01, with the labels that each got.

#9855 Deploy RC 344 to Prod
  .github/pull_request_template.md
  app/components/form_link_component.html.erb
  app/components/form_link_component.rb
  app/components/form_link_component.ts
  app/javascript/packages/components/index.ts
  app/javascript/packages/components/scroll-into-view.spec.tsx
  app/javascript/packages/components/scroll-into-view.tsx
  app/javascript/packages/document-capture/components/document-capture-review-issues.tsx
  app/javascript/packages/document-capture/components/review-issues-step.tsx
  app/javascript/packages/form-link/README.md
  app/javascript/packages/form-link/form-link-element.spec.ts
  app/javascript/packages/form-link/form-link-element.ts
  app/javascript/packages/form-link/package.json
  app/javascript/packages/i18n/index.ts
  app/javascript/packages/rails-i18n-webpack-plugin/rails-i18n-webpack-plugin.js
  app/javascript/packages/rails-i18n-webpack-plugin/rails-i18n-webpack-plugin.spec.js
  app/models/gpo_confirmation.rb
  app/services/gpo_confirmation_maker.rb
  app/services/gpo_confirmation_uploader.rb
  app/services/idv/session.rb
  bin/oncall/email-deliveries
  config/application.yml.default
  lib/identity_config.rb
  spec/bin/oncall/email-deliveries_spec.rb
  spec/components/form_link_component_spec.rb
  spec/controllers/idv/enter_password_controller_spec.rb
  spec/services/gpo_confirmation_maker_spec.rb
  spec/services/gpo_confirmation_spec.rb
  spec/services/gpo_confirmation_uploader_spec.rb
  spec/services/idv/gpo_mail_spec.rb
Labels: status - promotion

#9868 Remove unused USWDS utility classes
  app/assets/stylesheets/_uswds-core.scss
  app/views/users/two_factor_authentication_setup/index.html.erb
Labels: performance

#9889 Deploy RC 345.1 to Prod
  app/jobs/reports/identity_verification_report.rb
  app/jobs/resolution_proofing_job.rb
  app/services/idv/agent.rb
  app/services/proofing/resolution/progressive_proofer.rb
  lib/reporting/identity_verification_report.rb
  spec/controllers/idv/verify_info_controller_spec.rb
  spec/jobs/reports/identity_verification_report_spec.rb
Labels: status - promotion

#9906 Deploy RC 346 to Prod
  .gitlab-ci.yml
  app/controllers/idv/document_capture_controller.rb
  app/controllers/idv/image_uploads_controller.rb
  app/controllers/idv/link_sent_controller.rb
  app/controllers/openid_connect/authorization_controller.rb
  app/decorators/service_provider_session.rb
  app/models/disposable_email_domain.rb
  app/services/doc_auth/lexis_nexis/requests/true_id_request.rb
  app/services/doc_auth_router.rb
  app/services/gpo_reminder_sender.rb
  app/services/idv/profile_maker.rb
  app/services/idv/session.rb
  app/services/reporting/account_reuse_report.rb
  app/views/idv/shared/_document_capture.html.erb
  db/primary_migrate/20240110141229_add_disposable_email_domains_table.rb
  db/schema.rb
  lib/feature_management.rb
  lib/tasks/disposable_domains.rake
  package.json
  spec/controllers/idv/image_uploads_controller_spec.rb
  spec/controllers/openid_connect/authorization_controller_spec.rb
  spec/controllers/sign_up/completions_controller_spec.rb
  spec/decorators/service_provider_session_spec.rb
  spec/features/idv/analytics_spec.rb
  spec/features/idv/doc_auth/document_capture_spec.rb
  spec/features/idv/doc_auth/redo_document_capture_spec.rb
  spec/features/idv/hybrid_mobile/hybrid_mobile_spec.rb
  spec/jobs/gpo_reminder_job_spec.rb
  spec/lib/feature_management_spec.rb
  spec/models/disposable_email_domain_spec.rb
  spec/services/doc_auth/lexis_nexis/requests/true_id_request_spec.rb
  spec/services/doc_auth_router_spec.rb
  spec/services/gpo_reminder_sender_spec.rb
  spec/services/idv/profile_maker_spec.rb
  spec/services/reporting/account_reuse_report_spec.rb
  spec/views/idv/shared/_document_capture.html.erb_spec.rb
  webpack.config.js
  yarn.lock
Labels: status - promotion

#9895 LG-11882 (Step 2): Update code paths referencing DisposableDomain
  app/controllers/sign_up/completions_controller.rb
  spec/controllers/sign_up/completions_controller_spec.rb
Labels: status - do not merge

#9902 LG-11584 Update Welcome template
  app/controllers/idv/welcome_controller.rb
  app/views/idv/welcome/show.html.erb
  config/locales/doc_auth/en.yml
  config/locales/doc_auth/es.yml
  config/locales/doc_auth/fr.yml
  config/locales/idv/en.yml
  config/locales/idv/es.yml
  config/locales/idv/fr.yml
  spec/features/idv/doc_auth/welcome_spec.rb
  spec/features/idv/end_to_end_idv_spec.rb
  spec/features/idv/pending_profile_password_reset_spec.rb
  spec/views/idv/welcome/show.html.erb_spec.rb
Labels: status - blocked by content freeze

#9954 build-sass: Use new Shared Resources API
  app/javascript/packages/build-sass/CHANGELOG.md
  app/javascript/packages/build-sass/README.md
  app/javascript/packages/build-sass/cli.js
  app/javascript/packages/build-sass/index.js
  app/javascript/packages/build-sass/package.json
  yarn.lock
Labels: performance

#9826 Reimplement password strength as ViewComponent, custom element
  app/assets/stylesheets/components/_index.scss
  app/components/password_confirmation_component.html.erb
  app/components/password_confirmation_component.rb
  app/components/password_strength_component.html.erb
  app/components/password_strength_component.rb
  app/components/password_strength_component.scss
  app/components/password_strength_component.ts
  app/components/password_toggle_component.rb
  app/javascript/packages/password-strength/README.md
  app/javascript/packages/password-strength/package.json
  app/javascript/packages/password-strength/password-strength-element.spec.ts
  app/javascript/packages/password-strength/password-strength-element.ts
  app/javascript/packs/pw-strength.js
  app/views/devise/passwords/edit.html.erb
  app/views/devise/shared/_password_strength.html.erb
  app/views/event_disavowal/new.html.erb
  app/views/sign_up/passwords/new.html.erb
  app/views/users/passwords/edit.html.erb
  config/locales/instructions/en.yml
  config/locales/instructions/es.yml
  config/locales/instructions/fr.yml
  package.json
  spec/components/password_confirmation_component_spec.rb
  spec/components/password_strength_component_spec.rb
  spec/components/password_toggle_component_spec.rb
  spec/components/previews/password_strength_component_preview.rb
  spec/features/event_disavowal_spec.rb
  spec/features/users/user_profile_spec.rb
  spec/features/visitors/set_password_spec.rb
  spec/i18n_spec.rb
  spec/javascript/packs/pw-strength-spec.js
  spec/views/devise/shared/_password_strength.html.erb_spec.rb
  tsconfig.json
  yarn.lock
Labels: performance
