Repository 18F/identity-idp, pull requests merged in 2024-11, with the labels that each got.

#11418 Update Facial Match and semantic acr value configurations
  app/forms/openid_connect_authorize_form.rb
  app/models/service_provider.rb
  app/services/authn_context_resolver.rb
  app/services/saml_request_validator.rb
  config/application.yml.default
  lib/feature_management.rb
  lib/identity_config.rb
  lib/saml_idp_constants.rb
  spec/forms/openid_connect_authorize_form_spec.rb
  spec/models/service_provider_spec.rb
  spec/services/attribute_asserter_spec.rb
  spec/services/authn_context_resolver_spec.rb
  spec/services/saml_request_validator_spec.rb
Labels: status - do not merge

#11484 Remove unused email styles
  app/assets/stylesheets/email.css.scss
Labels: performance

#11459 LG-14464: Show warning CTA on ThreatMetrix API exception
  app/controllers/concerns/idv/verify_info_concern.rb
  spec/controllers/idv/verify_info_controller_spec.rb
  spec/features/idv/threat_metrix_pending_spec.rb
Labels: status - ready for review, ruby

#11524 Deploy RC 432 to Prod
  .gitlab-ci.yml
  app/controllers/concerns/idv/step_indicator_concern.rb
  app/controllers/idv/hybrid_mobile/socure/document_capture_controller.rb
  app/controllers/idv/in_person/address_controller.rb
  app/controllers/idv/socure/document_capture_controller.rb
  app/controllers/socure_webhook_controller.rb
  app/javascript/packages/webauthn/enroll-webauthn-device.spec.ts
  app/javascript/packages/webauthn/enroll-webauthn-device.ts
  app/services/proofing/resolution/plugins/instant_verify_residential_address_plugin.rb
  app/services/proofing/resolution/plugins/instant_verify_state_id_address_plugin.rb
  app/validators/idv/form_state_id_validator.rb
  config/application.yml.default
  config/routes.rb
  knapsack_rspec_report.json
  lib/identity_config.rb
  package.json
  spec/controllers/concerns/idv/step_indicator_concern_spec.rb
  spec/controllers/idv/hybrid_mobile/socure/document_capture_controller_spec.rb
  spec/controllers/idv/socure/document_capture_controller_spec.rb
  spec/features/idv/steps/enter_password_step_spec.rb
  spec/forms/idv/in_person/address_form_spec.rb
  spec/forms/idv/state_id_form_spec.rb
  spec/services/proofing/resolution/plugins/instant_verify_residential_address_plugin_spec.rb
  spec/services/proofing/resolution/plugins/instant_verify_state_id_address_plugin_spec.rb
  yarn.lock
Labels: status - promotion

#11499 LG-13761: ProofingComponents to store real vendor used to verify document PII
  app/controllers/concerns/idv/verify_info_concern.rb
  app/controllers/idv/in_person/verify_info_controller.rb
  app/controllers/idv/verify_info_controller.rb
  app/services/idv/proofing_components.rb
  app/services/idv/session.rb
  app/services/proofing/resolution/plugins/aamva_plugin.rb
  lib/idp/constants.rb
  spec/controllers/idv/verify_info_controller_spec.rb
  spec/features/idv/analytics_spec.rb
  spec/features/idv/end_to_end_idv_spec.rb
  spec/features/idv/proofing_components_spec.rb
  spec/services/idv/proofing_components_spec.rb
Labels: status - ready for review, ruby

#11539 Upgrade DAP to v8.4 release
  app/javascript/packages/analytics/Makefile
  app/javascript/packages/analytics/digital-analytics-program.patch
Labels: area - analytics

#11504 Add uncapped preload headers for style, script assets
  app/helpers/script_helper.rb
  app/helpers/stylesheet_helper.rb
  app/services/asset_preload_linker.rb
  spec/helpers/script_helper_spec.rb
  spec/helpers/stylesheet_helper_spec.rb
  spec/services/asset_preload_linker_spec.rb
Labels: performance
