Repository 18F/identity-idp, pull requests merged in 2024-09, with the labels that each got.

#11189 Run all relevant Axe accessibility test groups
  Gemfile.lock
  spec/support/matchers/accessibility.rb
Labels: accessibility

#11188 Deploy RC 411 to Production
  app/controllers/concerns/ab_testing_concern.rb
  app/controllers/idv/enter_password_controller.rb
  app/controllers/idv/welcome_controller.rb
  app/controllers/users/sessions_controller.rb
  app/forms/sign_in_recaptcha_form.rb
  app/forms/webauthn_setup_form.rb
  app/forms/webauthn_verification_form.rb
  app/jobs/reports/fraud_metrics_report.rb
  app/jobs/resolution_proofing_job.rb
  app/jobs/socure_shadow_mode_proofing_job.rb
  app/services/analytics_events.rb
  app/services/encryption/contextless_kms_client.rb
  app/services/encryption/kms_client.rb
  app/services/encryption/kms_logger.rb
  app/services/encryption/password_verifier.rb
  app/services/encryption/user_access_key.rb
  app/services/idv/session.rb
  app/services/proofing/resolution/result.rb
  app/views/users/service_provider_revoke/show.html.erb
  config/application.yml.default
  config/initializers/ab_tests.rb
  lib/ab_test.rb
  lib/identity_config.rb
  lib/reporting/fraud_metrics_lg99_report.rb
  package.json
  spec/config/initializers/ab_tests_spec.rb
  spec/controllers/concerns/ab_testing_concern_spec.rb
  spec/controllers/idv/enter_password_controller_spec.rb
  spec/controllers/idv/welcome_controller_spec.rb
  spec/controllers/users/sessions_controller_spec.rb
  spec/features/account_connected_apps_spec.rb
  spec/features/idv/analytics_spec.rb
  spec/features/users/sign_in_spec.rb
  spec/forms/sign_in_recaptcha_form_spec.rb
  spec/forms/webauthn_setup_form_spec.rb
  spec/forms/webauthn_verification_form_spec.rb
  spec/jobs/reports/fraud_metrics_report_spec.rb
  spec/jobs/resolution_proofing_job_spec.rb
  spec/jobs/socure_shadow_mode_proofing_job_spec.rb
  spec/lib/ab_test_spec.rb
  spec/lib/reporting/fraud_metrics_lg99_report_spec.rb
  spec/services/encryption/contextless_kms_client_spec.rb
  spec/services/encryption/kms_client_spec.rb
  spec/services/encryption/kms_logger_spec.rb
  spec/services/proofing/mock/resolution_mock_client_spec.rb
  spec/support/ab_tests_helper.rb
  spec/support/features/navigation_helper.rb
  spec/support/features/webauthn_helper.rb
  spec/support/have_logged_event_matcher.rb
  yarn.lock
Labels: status - promotion

#11158 LG-14334 | Don't log redacted values
  app/services/proofing/lexis_nexis/ddp/response_redacter.rb
  spec/features/idv/analytics_spec.rb
  spec/fixtures/proofing/lexis_nexis/ddp/successful_redacted_response.json
  spec/services/proofing/ddp_result_spec.rb
  spec/services/proofing/lexis_nexis/ddp/response_redacter_spec.rb
Labels: status - ready for review, needs code review

#11182 Use picture element to avoid unnecessary image load
  app/views/shared/_footer_lite.html.erb
Labels: performance

#11176 Remove wide card styles
  app/assets/stylesheets/components/_card.scss
  app/views/test/telephony/index.html.erb
Labels: performance

#11197 Rearrange conditions to short-circuit before database queries
  app/controllers/application_controller.rb
  app/controllers/concerns/mfa_setup_concern.rb
  app/forms/recaptcha_form.rb
  app/forms/webauthn_visit_form.rb
  app/presenters/two_factor_options_presenter.rb
  app/services/user_event_creator.rb
Labels: performance

#11191 Run automated accessibility tests for account pages, fix issues
  app/views/accounts/_auth_apps.html.erb
  app/views/accounts/_pii.html.erb
  app/views/accounts/_piv_cac.html.erb
  app/views/accounts/_webauthn_platform.html.erb
  app/views/accounts/_webauthn_roaming.html.erb
  spec/features/accessibility/account_pages_spec.rb
  spec/views/accounts/_auth_apps.html.erb_spec.rb
  spec/views/accounts/_piv_cac.html.erb_spec.rb
  spec/views/accounts/_webauthn_platform.html.erb_spec.rb
  spec/views/accounts/_webauthn_roaming.html.erb_spec.rb
Labels: accessibility

#11208 Add new semantic ACR values
  app/forms/openid_connect_authorize_form.rb
  app/models/federated_protocols/oidc.rb
  app/models/federated_protocols/saml.rb
  app/models/service_provider.rb
  app/services/authn_context_resolver.rb
  app/services/saml_request_validator.rb
  app/services/service_provider_request_handler.rb
  app/services/vot/acr_component_values.rb
  app/services/vot/parser.rb
  config/application.yml.default
  lib/feature_management.rb
  lib/identity_config.rb
  lib/saml_idp_constants.rb
  spec/controllers/saml_idp_controller_spec.rb
  spec/models/service_provider_spec.rb
  spec/services/attribute_asserter_spec.rb
  spec/services/authn_context_resolver_spec.rb
  spec/services/saml_request_validator_spec.rb
  spec/services/vot/parser_spec.rb
Labels: type - enhancement, status - do not merge

#11206 Upgrade Faker to latest major version
  Gemfile.lock
  spec/controllers/users/email_confirmations_controller_spec.rb
  spec/controllers/users/emails_controller_spec.rb
  spec/controllers/users/sessions_controller_spec.rb
  spec/factories/email_addresses.rb
  spec/factories/users.rb
  spec/features/users/sign_up_spec.rb
  spec/services/push_notification/email_changed_event_spec.rb
  spec/services/push_notification/http_push_spec.rb
  spec/services/push_notification/identifier_recycled_event_spec.rb
  spec/services/reset_user_password_spec.rb
  spec/services/usps_in_person_proofing/proofer_spec.rb
  spec/support/features/session_helper.rb
Labels: status - ready for review, ruby, area - testing

#11265 Deploy RC 416 to Production
  .mocharc.js
  Gemfile.lock
  app/controllers/idv/agreement_controller.rb
  app/controllers/idv/in_person/state_id_controller.rb
  app/controllers/idv/in_person/verify_info_controller.rb
  app/controllers/idv/verify_info_controller.rb
  app/controllers/saml_idp_controller.rb
  app/controllers/two_factor_authentication/webauthn_verification_controller.rb
  app/controllers/users/two_factor_authentication_controller.rb
  app/javascript/packages/document-capture/components/document-capture-review-issues.spec.tsx
  app/javascript/packages/document-capture/components/document-capture-review-issues.tsx
  app/javascript/packages/webauthn/enroll-webauthn-device.spec.ts
  app/javascript/packages/webauthn/enroll-webauthn-device.ts
  app/javascript/packs/webauthn-setup.ts
  app/jobs/reports/mfa_report.rb
  app/jobs/socure_shadow_mode_proofing_job.rb
  app/services/analytics_events.rb
  app/services/proofing/ddp_result.rb
  app/services/proofing/lexis_nexis/ddp/proofer.rb
  app/services/proofing/mock/ddp_mock_client.rb
  app/services/proofing/socure/id_plus/input.rb
  app/services/proofing/socure/id_plus/request.rb
  config/application.yml.default
  config/initializers/job_configurations.rb
  config/service_providers.localdev.yml
  lib/identity_config.rb
  scripts/enforce-typescript-files.mjs
  spec/controllers/idv/in_person/state_id_controller_spec.rb
  spec/controllers/idv/in_person/verify_info_controller_spec.rb
  spec/controllers/idv/verify_info_controller_spec.rb
  spec/controllers/users/email_confirmations_controller_spec.rb
  spec/controllers/users/emails_controller_spec.rb
  spec/controllers/users/sessions_controller_spec.rb
  spec/controllers/users/two_factor_authentication_controller_spec.rb
  spec/factories/email_addresses.rb
  spec/factories/users.rb
  spec/features/idv/analytics_spec.rb
  spec/features/idv/steps/in_person/state_id_50_50_spec.rb
  spec/features/remember_device/revocation_spec.rb
  spec/features/users/sign_up_spec.rb
  spec/features/webauthn/hidden_spec.rb
  spec/fixtures/proofing/lexis_nexis/ddp/successful_redacted_response.json
  spec/fixtures/proofing/lexis_nexis/ddp/successful_response.json
  spec/jobs/reports/mfa_report_spec.rb
  spec/presenters/two_factor_options_presenter_spec.rb
  spec/services/proofing/lexis_nexis/ddp/proofing_spec.rb
  spec/services/proofing/socure/id_plus/input_spec.rb
  spec/services/proofing/socure/id_plus/request_spec.rb
  spec/services/push_notification/email_changed_event_spec.rb
  spec/services/push_notification/http_push_spec.rb
  spec/services/push_notification/identifier_recycled_event_spec.rb
  spec/services/reset_user_password_spec.rb
  spec/services/usps_in_person_proofing/proofer_spec.rb
  spec/support/features/session_helper.rb
  spec/support/flow_policy_helper.rb
  spec/support/shared_examples/remember_device.rb
Labels: status - promotion

#11279 Deploy RC 416 to Production
  .eslintrc
  Gemfile
  Gemfile.lock
  app/components/phone_input_component.scss
  app/controllers/concerns/idv/verify_info_concern.rb
  app/controllers/idv/in_person/usps_locations_controller.rb
  app/controllers/idv/verify_info_controller.rb
  app/forms/webauthn_setup_form.rb
  app/javascript/packages/address-search/components/full-address-search-input.tsx
  app/javascript/packages/address-search/components/full-address-search.spec.tsx
  app/javascript/packages/address-search/hooks/use-validated-usps-locations.ts
  app/javascript/packages/document-capture/components/document-capture.tsx
  app/javascript/packages/phone-input/index.spec.ts
  app/javascript/packages/phone-input/index.ts
  app/javascript/packages/phone-input/package.json
  app/javascript/packs/idv-phone-alert.ts
  app/jobs/socure_shadow_mode_proofing_job.rb
  app/models/anonymous_user.rb
  app/services/account_reset/delete_account.rb
  app/services/analytics_events.rb
  app/services/idv/session.rb
  app/services/idv/steps/threat_metrix_step_helper.rb
  app/services/proofing/resolution/progressive_proofer.rb
  app/services/proofing/resolution/result_adjudicator.rb
  app/services/usps_in_person_proofing/applicant.rb
  app/views/devise/sessions/new.html.erb
  config/initializers/ab_tests.rb
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/zh.yml
  lib/ab_test.rb
  package.json
  spec/components/previews/phone_input_component_preview.rb
  spec/controllers/account_reset/delete_account_controller_spec.rb
  spec/controllers/idv/enter_password_controller_spec.rb
  spec/controllers/idv/in_person/usps_locations_controller_spec.rb
  spec/controllers/idv/otp_verification_controller_spec.rb
  spec/controllers/idv/phone_errors_controller_spec.rb
  spec/controllers/idv/ssn_controller_spec.rb
  spec/controllers/idv/verify_info_controller_spec.rb
  spec/controllers/idv/welcome_controller_spec.rb
  spec/factories/users.rb
  spec/features/idv/analytics_spec.rb
  spec/features/idv/doc_auth/document_capture_spec.rb
  spec/features/idv/doc_auth/hybrid_handoff_spec.rb
  spec/features/phone/add_phone_spec.rb
  spec/forms/webauthn_setup_form_spec.rb
  spec/jobs/socure_shadow_mode_proofing_job_spec.rb
  spec/services/proofing/resolution/result_adjudicator_spec.rb
  spec/support/flow_policy_helper.rb
  spec/support/matchers/accessibility.rb
  spec/views/devise/sessions/new.html.erb_spec.rb
  yarn.lock
Labels: status - promotion

#11288 Deploy RC 417 to Production
  .gitlab-ci.yml
  app/helpers/ipp_helper.rb
  app/jobs/reports/duplicate_ssn_report.rb
  app/jobs/reports/idv_legacy_conversion_supplement_report.rb
  app/models/profile.rb
  app/models/sp_upgraded_biometric_profile.rb
  app/services/iaa_reporting_helper.rb
  app/services/proofing/aamva/proofer.rb
  app/services/proofing/aamva/response/verification_response.rb
  config/application.yml.default
  config/database.yml
  config/initializers/job_configurations.rb
  db/primary_migrate/20240916202940_create_sp_upgraded_biometric_profiles.rb
  db/schema.rb
  lib/identity_config.rb
  spec/controllers/idv/in_person/usps_locations_controller_spec.rb
  spec/factories/profiles.rb
  spec/factories/sp_upgraded_biometric_profiles.rb
  spec/fixtures/proofing/aamva/responses/verification_response_namespaced_success.xml
  spec/helpers/ipp_helper_spec.rb
  spec/jobs/get_usps_proofing_results_job_spec.rb
  spec/jobs/reports/idv_legacy_conversion_supplement_report_spec.rb
  spec/models/profile_spec.rb
  spec/services/proofing/aamva/request/verification_request_spec.rb
  spec/services/proofing/aamva/response/verification_response_spec.rb
  spec/services/proofing/aamva/verification_client_spec.rb
Labels: status - promotion
